import type { AssessmentQuestion } from './assessment-data';
import { electricalTerms } from './knowledge-graph';
import { standardsChecks } from './standards-checks';

export type AnswerTeaching = { reasoning: string; application: string };
const profiles: Record<string, AnswerTeaching> = {};
const span = (prefix: string, first: number, last: number) => Array.from({length:last-first+1},(_,i)=>`${prefix}${String(first+i).padStart(2,'0')}`);
function teach(ids: string[], reasoning: string, application: string) {
  for (const id of ids) profiles[id] = {reasoning, application};
}

teach(['p01-l01','p01-l02'], 'Protons carry positive charge and electrons carry negative charge. In a metal, mobile electrons move while the atomic nuclei remain in place. The circuit transfers energy without using up these electrons.', 'A copper cable conducts because some electrons can move through its structure. The cable does not need to supply a new batch of electrons whenever an appliance starts.');
teach(['p01-l03','p01-l04'], 'Charge is an amount, measured in coulombs. Current is how quickly charge passes a point, measured in amperes. One ampere means one coulomb passes each second, so both the amount and the time matter.', 'If 6 coulombs pass a point in 2 seconds, the average current is 3 amperes. The same charge taking longer would mean a smaller average current.');
teach(['p01-l05'], 'The source provides a potential difference, and the closed circuit provides a route through the load and back to the source. Opening that route stops continuous current, but does not necessarily remove voltage from every conductor.', 'A lamp can be off while its supply terminal remains live. Operating the light switch and safely isolating the circuit are different actions.');
teach(['p01-l06','p01-l07'], 'Voltage is the potential difference between two points. Resistance opposes current. For a resistive circuit, increasing voltage at the same resistance increases current; increasing resistance at the same voltage reduces current.', 'A 12-volt supply across 6 ohms produces 2 amperes. Increasing the resistance to 12 ohms reduces the current to 1 ampere.');
teach(['p01-l08'], 'A series circuit has one continuous current path, so every component carries the same current. Each resistance contributes a voltage drop, and the drops around the complete loop add up to the source voltage.', 'Two series resistors of 4 ohms and 6 ohms give 10 ohms in total. On a 20-volt supply, both carry 2 amperes; their voltage drops are 8 volts and 12 volts.');
teach(['p01-l09','p01-l10','p01-l11'], 'Parallel branches connect across the same two points, so they share the same voltage. Current divides between the branches according to their resistance and adds together at the source. Adding a conducting branch reduces the equivalent resistance.', 'Across 12 volts, a 6-ohm branch carries 2 amperes and a 12-ohm branch carries 1 ampere. The source supplies their total of 3 amperes.');
teach(['p01-l12','p01-l13','p01-l14'], 'Power is the rate of energy transfer, measured in watts. In a resistor, current produces heat; at constant resistance, doubling current produces four times the heating power. Choose the power relationship that matches the known quantities.', 'A connection with extra resistance can become hot under load. A connection carrying twice the current generates four times its previous resistive heating if its resistance stays unchanged.');
teach(['p01-l15'], 'Power tells you how fast energy is being used; energy tells you how much has been used over time. A kilowatt-hour is energy, not power. At constant power, doubling the operating time doubles the energy used.', 'A 2-kilowatt heater running for 3 hours uses 6 kilowatt-hours. Its power remains 2 kilowatts throughout that period.');
teach(['p01-l16'], 'Electric current can produce heat, magnetic effects or chemical change, depending on the component. The useful effect comes from energy transferred by the supply; charge continues through the circuit rather than being consumed by the load.', 'A heater uses resistive heating, a contactor uses a magnetic field to move contacts, and battery charging involves chemical change.');
teach(['p01-l17'], 'Current produces a magnetic field. A coil combines the fields from many turns, and a suitable core concentrates the flux. Reversing current reverses the magnetic field direction.', 'A contactor coil uses this magnetic effect to pull its contacts into position. The coil supply must match its rating; more voltage is not a safe way to obtain more force.');
teach(['p01-l18','p01-l19'], 'Induced voltage depends on changing magnetic flux linkage. Faster change or more linked turns produces a larger induced voltage. A stationary coil in an unchanging field does not receive a continuous induced voltage from that field.', 'In an AC generator, rotation repeatedly changes the flux linkage and reverses the induced polarity. Mechanical energy supplies the electrical output.');
teach(['p01-l20','p01-l21'], 'A waveform shows how a quantity changes with time. Amplitude is its largest displacement from zero; frequency counts complete cycles per second. Period is the time for one cycle, so a higher frequency means a shorter period.', 'At 50 hertz, one cycle lasts 0.02 seconds. This timing says nothing by itself about whether the voltage amplitude is 12 volts or 230 volts.');
teach(['p01-l22','p01-l23','p01-l24'], 'Resistance dissipates energy as heat. Inductors and capacitors can store energy in fields and return it to the circuit; this behaviour creates reactance in AC circuits. Impedance includes both resistance and reactance, with their phase relationship.', 'A coil can draw different current on AC and DC even when its conductor resistance is unchanged. Its inductance adds frequency-dependent opposition on AC.');
teach(['p01-l25'], 'Capacitance describes stored charge for each volt applied. Parallel capacitors share voltage and their capacitances add. Series capacitors share charge, so the combination has a lower capacitance than any one capacitor in the chain.', 'A capacitor may retain charge after the supply is removed. Equipment discharge instructions matter before a capacitor-containing circuit is handled.');
teach(['p01-transformers'], 'A transformer transfers energy through changing magnetic flux. The turns ratio sets its ideal voltage ratio, while current changes in the opposite proportion at the same power. Separate windings can provide electrical isolation; an autotransformer shares part of a winding.', 'An ideal transformer with ten times as many primary turns as secondary turns reduces 230 volts to 23 volts. This voltage ratio does not establish a safe power rating or every protective requirement.');
teach(['p01-pf-visual','p01-l26','p01-l27','p06-l14'], 'Real power is the net energy transfer per second. Apparent power reflects the RMS voltage and current that the supply must carry. Power factor compares real power with apparent power; a lower value requires more current for the same real power at the same voltage.', 'Improving power factor can reduce cable current and heating. It does not remove the useful energy a motor or other load needs to perform its work.');
teach(['p03-l14','p08-l01'], 'An off switch or stopped load does not establish that conductors are dead. Safe isolation identifies every source, prevents reconnection and verifies absence of voltage. Proving the indicator before and after the check confirms it was functioning throughout.', 'A building may have grid, generator, PV or battery supplies. Each source that can energise the work area must be addressed in the isolation procedure.');
teach(['p01-l28'], 'Voltage is measured between two points, so a voltmeter connects across those points. Its high input impedance limits the current it takes from the circuit. The function, leads, input sockets and measurement category must suit the actual measurement.', 'A high-impedance meter can display a coupled voltage on an open conductor. The reading needs interpretation; its presence alone does not establish the source’s ability to supply current.');
teach(['p01-l29'], 'An ammeter measures current passing through it, so it belongs in the load’s series path. Its current input has low resistance. Connecting that input across a voltage source can create a high-current fault.', 'Before measuring current, select the correct input socket and a suitable range. A meter left in current mode must not be used as though it were a voltmeter.');
teach(['p01-l30'], 'A resistance meter applies its own test signal to a safely isolated circuit. Parallel paths can make the result lower than the resistance of the component being investigated. Lead resistance also affects small readings.', 'A resistor may need to be separated from parallel circuitry for a meaningful measurement. A continuity beep alone does not establish the resistance needed for a protective path.');
teach(['p01-l31','p09-l09','p09-l11'], 'A clamp responds to the combined magnetic effect of the conductors inside its jaws. One conductor gives its current; all live conductors of one circuit give their residual imbalance because equal outgoing and returning currents cancel.', 'Use one conductor when assessing load current. For leakage assessment, the conductor selection, instrument sensitivity and fully closed jaws all affect the result.');
teach(['p02-l01','p04-l11'], 'A cable’s conductor carries current, insulation separates conductive parts, and the sheath protects the assembly. Armour adds mechanical protection and may have a designed protective role. Each layer serves a different purpose.', 'A robust-looking cable is not automatically suitable for a load or location. Current capacity, environment, glands and protective continuity must all match the installation.');
teach(['p02-l02','p10-l02','p10-l06','p07-l06','p07-l07'], 'A distribution assembly combines supply switching, busbars and outgoing protection. Correct device ratings alone are insufficient if the assembly, neutral arrangement or connections are unsuitable. Each outgoing circuit needs identifiable protection and a sound return path.', 'When replacing a board, existing circuit defects still need investigation. A new enclosure cannot repair damaged insulation or a shared neutral on an old circuit.');
teach(['p02-l03',...span('p07-l',1,5),'p06-l13'], 'Line values describe the supply conductors; phase values describe individual load elements. In a balanced star load, line current equals phase current. In delta, each element is connected across two lines. These connections determine which voltage and current belong in a calculation.', 'On a balanced 400-volt star supply, line-to-neutral voltage is about 230 volts. A delta-connected winding sees the full line-to-line voltage.');
teach(['p02-l04','p05-l08'], 'The earthing arrangement determines the route fault current can take back to the source. TN-S keeps neutral and protective functions separate; TN-C-S combines them upstream; TT uses a local installation electrode. Protection must work with the actual arrangement.', 'A familiar supply voltage does not identify the earthing system. Confirm the arrangement at the origin before relying on a fault-loop or protective-device assumption.');
teach(['p02-l05','p05-l09','p05-l10','p08-l03'], 'Protective earthing provides a route for fault current. Bonding limits potential differences between conductive parts that may be touched together. Continuity, conductor size and sound connections are essential because a broken or resistive path weakens the protective arrangement.', 'Parallel metallic paths can make a damaged bonding conductor appear continuous during a test. Inspection and the chosen test arrangement help distinguish the intended conductor from an alternative path.');
teach(['p02-l06','p05-l02','p05-l03','p05-l05','p06-l15'], 'A protective device’s normal current rating, trip characteristic and breaking capacity describe different things. The trip characteristic governs its response to overcurrent; breaking capacity limits the fault current it can safely interrupt.', 'A breaker with the right ampere rating can still be unsuitable if its breaking capacity is too low or its operating curve does not satisfy the circuit’s protection requirements.');
teach(['p02-l07','p02-l08','p05-l04','p05-l15','p08-l13','p08-l14'], 'An RCD compares outgoing and returning current. A difference suggests current is taking another route. Residual-current protection is separate from overload protection; an RCBO combines both functions. RCD operation does not prove every part of the circuit is sound.', 'The test button checks the device’s built-in operating function. It does not measure protective-conductor continuity or replace the installation’s required instrument tests.');
teach(['p02-l09','p05-l06','p05-l07',...span('p05-l',11,13),'p08-l08','p08-l10','p08-l11'], 'An earth fault needs a complete return path to the source. More loop impedance means less fault current at the same voltage. An overcurrent device needs enough current to operate within the required time, so the loop and device must be assessed together.', 'Ze covers the external loop. Adding the circuit’s line and protective-path contribution gives an estimate of Zs at the point; temperature and the actual protective device affect the acceptance check.');
teach(['p07-l13','p07-l14','p07-l15'], 'Different drawings answer different questions. A single-line diagram shows supply and protection paths; a riser shows distribution between levels; a panel schedule identifies individual ways. Consistent circuit references connect the drawings to real equipment.', 'Trace a load from its label to the panel schedule, then back through the single-line diagram. This establishes which feeder and protective devices serve it.');
teach(['p02-l10','p07-l08','p10-l01'], 'A feeder carries the combined demand of downstream circuits. Its cable and protection must suit load current, fault current, route and environment. Isolation and identification make the downstream supply controllable for maintenance.', 'A sub-main to an outbuilding needs more than a cable that physically reaches. Its voltage drop, protection, earthing, entries and support must be designed for the route.');
teach(['p02-l11','p03-l01','p03-l02','p03-l03','p03-l04','p03-l12','p03-l13','p16-l01','p16-l02','p16-l03'], 'A sound termination needs adequate metal contact without damaged strands, trapped insulation or strain. Poor contact adds resistance and can heat under load. The conductor, terminal, preparation method and specified torque must form a compatible connection.', 'A terminal can feel tight while clamping insulation instead of copper. Inspect conductor engagement and use the manufacturer’s preparation and tightening instructions.');
teach(['p03-l05','p03-l06','p03-l07','p10-l04'], 'Permanent line supplies the switch; switched line returns from the switch to the lamp. Neutral completes the load’s return path. Keeping these functions separate allows switching to interrupt line while preserving the correct circuit connections.', 'At a ceiling rose, the permanent-line group is not the lamp’s switched-line connection. Identify each conductor’s function rather than relying on its physical position.');
teach(['p03-l08','p03-l09','p08-l15'], 'A two-way switch connects its common terminal to one of two travellers. An intermediate switch passes those travellers straight through or crosses them. Changing one switch changes continuity through the complete control path.', 'A lamp controlled from three locations normally uses two-way switches at the ends and an intermediate switch between them. Working at every position does not by itself establish protective continuity.');
teach(['p03-l10','p08-l05','p09-l01','p09-l02'], 'A ring final circuit has two intended conductor paths back to the same origin. A broken conductor may leave appliances operating through the remaining path. End-to-end and cross-connected tests examine the ring’s actual continuity and arrangement.', 'Two cables entering a socket do not prove that it belongs to a complete ring. Establish circuit identity and continuity before treating it as the basis for an alteration.');
teach(['p03-l11','p12-v2-l07','p12-v2-l08'], 'A recessed fitting interacts with the ceiling, insulation and surrounding space. Heat, driver access and the ceiling’s tested fire performance remain important even when the light works. A fitting’s claims must match the actual construction.', 'A fire-rated downlight is not automatic approval for every ceiling. The specified ceiling assembly, insulation conditions and installation details must match the supporting evidence.');
teach([...span('p04-l',1,6)], 'Containment must protect the cables without creating sharp edges, tight bends or excessive pulling force. Accurate set-out and compatible fittings preserve the planned route. Metallic systems may also need verified electrical continuity.', 'A neatly bent conduit can still be unsuitable if its bend restricts cable pulling or its cut edge damages insulation. Check the internal path as well as the outside appearance.');
teach(['p04-l07','p04-l08','p04-l09','p04-l10','p04-l18'], 'Space capacity, heat dissipation and mechanical protection are separate checks. A route with enough room for cables can still have excessive grouping, sharp edges or inaccessible joints. Allow for bends, supports and maintenance access.', 'Passing a trunking fill calculation does not prove that grouped loaded cables can carry their tabulated current. The thermal installation conditions still need assessment.');
teach(['p04-l12','p04-l13','p04-l14','p04-l15'], 'Glands and supports transfer mechanical forces without straining terminals or damaging insulation. Where armour forms part of the protective arrangement, its connection must also be electrically reliable. Environmental sealing depends on the complete entry arrangement.', 'A gland can grip a cable firmly yet fail to seal its outer sheath. Mechanical security, ingress protection and protective continuity need their own checks.');
teach(['p04-l16','p04-l17'], 'MICC uses mineral insulation within a metal sheath. Exposed mineral insulation can absorb moisture and lose insulation resistance. Careful preparation, sealing and testing preserve both the insulation and the intended protective connection.', 'After making an MICC termination, a sound-looking seal is not the whole result. Insulation resistance testing helps establish that the prepared end remains dry and electrically sound.');
teach(['p05-l01'], 'An overload follows the intended load path but carries too much current. A short circuit bypasses load impedance between live conductors. An earth fault introduces a path to exposed conductive parts or the protective arrangement; these faults do not all behave alike.', 'A damaged cable touching a metal enclosure is an earth-fault problem. Choosing protection requires understanding the return path and available fault current, not only the normal load.');
teach(['p05-l14','p06-l01','p06-l02','p06-l03','p06-l04','p06-l05','p06-l10','p10-l03'], 'Cable selection links the expected load, protective-device rating and capacity under actual installation conditions. Heat must escape without excessive conductor temperature. Grouping, insulation and ambient temperature can reduce usable capacity.', 'A larger breaker is not a remedy for repeated overload if the cable cannot carry that rating. Reassess demand, cable capacity and the remaining design checks together.');
teach(['p06-l06','p06-l07','p06-l08','p06-l09'], 'A conductor has resistance, so load current produces both heat and voltage drop along the route. Greater length or smaller cross-section increases resistance. A cable that carries current thermally may still deliver insufficient voltage to its load.', 'Lengthening a cable route can require a larger conductor even when the load is unchanged. The voltage available at the equipment must still be acceptable.');
teach(['p06-l11','p06-l12','p07-l16','p10-l09','p10-l10'], 'Connected load is the sum of installed ratings. Maximum demand estimates the greatest load likely to operate together. Diversity reflects real operating patterns, so assumptions must suit the building rather than being copied without context.', 'Several heaters controlled by the same timer may start together. Their demand pattern differs from appliances used at unrelated times, even if total installed power is identical.');
teach(['p07-induction'], 'Three-phase stator currents create a rotating magnetic field. Relative motion between that field and the rotor induces rotor current and produces torque. In normal motoring operation the rotor runs below synchronous speed; that difference is slip.', 'A four-pole motor on 50 hertz has a synchronous field speed of 1,500 rpm. A rated rotor speed below this is expected and is not, by itself, evidence of a fault.');
teach(['p04-l19','p04-l20','p04-l21','p15-v2-l01'], 'The power contacts carry motor current, while the coil circuit carries the control command. A holding contact maintains the coil after Start is released. Stop and overload contacts interrupt that command so the main contacts release.', 'A motor starter needs overload protection as well as a contactor. The contactor switches the load; it does not independently determine a safe overload setting.');
teach(['p07-star-delta'], 'Star starting reduces winding voltage compared with delta on the same line supply, reducing starting current and torque. The motor must be suitable for delta running at that voltage, and the load must accelerate with the reduced starting torque.', 'Electrical and mechanical interlocks prevent star and delta contactors closing together. A timer alone is not evidence that every conflicting state is prevented.');
teach(['p07-vfd'], 'A drive rectifies incoming AC to a DC link, then switches it to produce a controlled motor supply. Output frequency affects field speed. The DC-link capacitors can retain energy after isolation, and the switched output differs from a clean mains sine wave.', 'Stopping a motor through the drive keypad is not safe isolation. Follow the equipment’s isolation and discharge procedure before accessing its power circuits.');
teach(['p07-l09'], 'Loaded conductors produce heat and need both cooling space and mechanical support. Bundling changes heat dissipation, while fault current can impose substantial forces. A tidy route must still satisfy these physical conditions.', 'Tightly bundling several loaded cables can reduce allowable current. Support design also needs to keep expected forces away from the terminations.');
teach(['p08-l02','p08-l04'], 'A measurement is meaningful only when the test function, leads and circuit condition match the quantity being checked. Low-resistance tests include the lead path unless it is compensated. Record the result so later loop and fault assessments have a reliable basis.', 'Test-lead resistance can be significant compared with a short protective conductor. Nulling the leads prevents their resistance being mistaken for resistance in the circuit.');
teach(['p08-l06','p08-l16','p09-l03'], 'Insulation resistance testing looks for unwanted conduction between paths that should be separated. Connected electronics can affect results or be damaged by unsuitable testing. The circuit must be safely isolated and prepared for the chosen test method.', 'A low reading may come from connected equipment, moisture or damaged wiring. Subdividing the circuit helps locate the cause instead of assuming the whole cable route is defective.');
teach(['p08-l07'], 'Voltage magnitude, phase sequence and polarity are different observations. Expected voltages help identify connections, but equal phase voltages do not establish their time order. Test equipment and safe access must suit the observation being made.', 'A three-phase motor may see the expected line voltages but rotate the wrong way. Phase sequence and controlled rotation checks address information that voltage readings alone cannot provide.');
teach(['p08-l09','p08-l17'], 'Prospective fault current is the current that could flow under a specified fault condition. Different conductor pairs and phases can give different values. Protective equipment must safely interrupt the highest applicable fault duty.', 'A normal-load reading cannot establish breaking capacity. The fault-current assessment concerns the source and fault path rather than the current the appliance usually draws.');
teach(['p08-l12'], 'Electrode resistance depends on contact with the surrounding soil and the test arrangement. Auxiliary probes or an appropriate clamp method must measure the intended path. Parallel paths can change what the instrument actually includes.', 'A clamp method needs a suitable complete return loop. Clamping a lone electrode conductor does not automatically create the conditions for a meaningful resistance measurement.');
teach(['p08-periodic','p16-l09'], 'Inspection and testing provide complementary evidence. A report must identify the circuit, condition, limitations and findings. A passing number cannot cancel a visible defect, and an unexplained defect cannot be resolved by documentation alone.', 'After repair, record what changed and repeat the relevant verification. This lets the next inspector distinguish an old observation from the installation’s current condition.');
teach(['p09-l04','p09-l05'], 'A load working does not prove correct polarity or sound connections. High-resistance joints may overheat, and missing conductors can produce misleading indications. Diagnosis combines circuit identity, inspection and suitable measurements.', 'A loose socket termination can work intermittently. Replacing the appliance without investigating the connection leaves the cause and its heating risk in place.');
teach(['p09-l06'], 'An RCD expects a circuit’s outgoing and returning currents to pass through the same sensing arrangement. A borrowed neutral can upset that balance and may remain connected to another supply when one circuit is isolated.', 'Treat an unexpected shared neutral as a circuit-identification problem. Do not assume that switching off one labelled breaker has isolated every connected conductor.');
teach(['p09-l07'], 'Ageing cable materials can migrate and contaminate terminations. Continuity only establishes a conducting path; it does not establish insulation condition or accessory suitability. The affected materials need inspection and electrical assessment.', 'Green contamination at a socket can originate within the cable. Cleaning the visible surface alone does not establish that the underlying deterioration is resolved.');
teach(['p09-l08'], 'A high-impedance meter takes very little current, so it can display voltage coupled from nearby live wiring onto an open conductor. The indication must be distinguished from a source capable of supplying significant current using an appropriate safe test method.', 'A voltage reading on a disconnected conductor should prompt investigation of coupling, connections and test conditions. It must not be dismissed by appearance or treated as proof of safety.');
teach(['p09-l10'], 'A heating circuit may depend on timed supplies, thermostats and thermal protection. No current at one moment does not identify which element is open. Trace the permitted operating sequence before drawing a conclusion.', 'An off-peak heater outside its scheduled supply period may correctly draw no current. That observation alone does not establish a failed element.');
teach(['p10-l05','p10-l07','p10-l08'], 'The final installation must coordinate load, conductor, protection and connections. Functional operation checks one result, while inspection and electrical tests establish conditions hidden from normal use.', 'A cooker heating normally does not prove protective continuity or acceptable fault-loop impedance. Those require their relevant verification before the work is accepted.');
teach(['p16-l04','p16-l05','p11-l01'], 'Detection instruments have limits determined by material, depth, screening and signal paths. Drawings, surveys and repeated scans add context. Intrusive work must account for uncertain indications as well as detected services.', 'A live-wire detector may miss an isolated or screened conductor. A clear indication is not permission to drill without the wider service-location assessment.');

teach(span('p11-v2-l',2,11), 'An accessory must match the load, conductor arrangement and installation environment. Correct terminal engagement, enclosure space and protective continuity matter because normal operation can hide an unsafe connection.', 'Before replacing an accessory, identify the circuit and conductor functions. The new product’s markings and instructions govern its connections, even if it resembles the previous one.');
teach(['p11-v2-l04'], 'A fused connection unit combines distinct functions: its fuse can protect the downstream flex, while its switch controls operation. Supply and load terminals must be distinguished. The selected fuse and conductors must be coordinated.', 'A small appliance flex should not be assumed protected merely because the circuit has a much larger upstream breaker. Assess the protection provided at the connection unit.');
teach(['p11-v2-l05'], 'USB charging sockets contain electronics as well as mains connections. Output power may be shared between ports, and the assembly needs sufficient depth and heat clearance. The mains circuit’s protective requirements still apply.', 'Two connected devices may share the stated total USB output rather than each receiving it. Check the actual power-sharing specification before promising charging performance.');
teach(['p11-v2-l06','p11-v2-l07','p11-v2-l08'], 'Appliance positions and electrical ratings must be planned together. Cable capacity, local isolation, termination space and the actual load remain separate checks. Diversity estimates demand; it does not prove the whole circuit is suitable.', 'A cooker point hidden behind an immovable appliance may be difficult to isolate. Coordinate accessible controls with the final cabinet and appliance arrangement.');
teach(['p11-v2-l09'], 'A shaver supply unit uses an isolating transformer for a limited-purpose output. It is not interchangeable with an ordinary mains socket. The product’s output rating, location restrictions and installation instructions must be respected.', 'Do not assume that a shaver outlet can supply a general high-power appliance merely because a plug fits. Its intended use and transformer rating limit the load.');
teach(['p11-v2-l10','p11-v2-l11'], 'Water, dust and impact protection address different environmental hazards. The complete installed accessory must maintain its protection at entries, seals and mounting points, while its electrical ratings match the connected equipment.', 'An outdoor enclosure can lose its protection through an unsuitable cable entry or damaged gasket. A rating on the lid does not correct those defects.');

teach([...span('p12-v2-l',1,6),'p12-l04',...span('p07-l',10,12)], 'Lighting design starts with the visual task. Lumens describe light output; lux describes light reaching a surface; watts describe electrical power. Distribution, reflectance, glare and maintenance determine how useful that output becomes.', 'Two fittings with the same wattage can produce different useful illumination. Compare light output and distribution at the working plane rather than selecting by watts alone.');
teach(['p07-l10','p07-l11','p07-l12'], 'Utilisation factor accounts for how much source light reaches the working plane. Maintenance factor allows for reduced output over time. Both affect the initial lumens required, while spacing and glare still need separate assessment.', 'A room can meet its average illuminance target yet contain dark areas between fittings. Check distribution and spacing as well as the average calculation.');
teach(['p12-v2-l09','p12-v2-l10','p12-v2-l11','p12-v2-l12','p12-v2-l13'], 'An LED load needs a compatible driver, and any dimmer must work with that combination. Electrical efficiency does not eliminate heat. Incorrect output type, poor cooling or incompatible dimming can reduce life or cause unstable operation.', 'Flicker at low brightness can arise from the driver, dimmer, minimum load or their combination. Replacing the lamp alone may not address the cause.');
teach(['p12-v2-l14','p12-v2-l15','p12-v2-l16','p12-v2-l17'], 'A lighting fitting needs both suitable light distribution and a suitable physical installation. Ingress, impact, temperature, access and mounting conditions affect its performance and service life.', 'Aim outdoor lighting at the intended surfaces and check the result at night. More output can increase glare without improving visibility at the required location.');
teach(['p12-v2-l18','p12-v2-l19','p12-v2-l20','p12-v2-l21','p12-v2-l22'], 'Lighting controls act on power circuits but do not replace their protective arrangements. Commands, groups and scenes need a defined relationship to real loads. Commissioning must establish normal use, overrides and behaviour after a power interruption.', 'A lighting group may be changed in software without moving its mains cable. Keep the control configuration and physical circuit records consistent for maintenance.');
teach(['p12-v2-l23','p12-v2-l24'], 'Emergency lighting must operate when normal lighting fails and remain effective for the specified duration. A brief functional test proves operation at that moment; a duration test checks sustained operation. Test scheduling must allow safe recharge and continued protection.', 'A fitting that illuminates for a few seconds may still have insufficient battery capacity. Record both functional and duration-test results under the maintenance procedure.');

teach(['p13-v2-l01','p13-v2-l02','p13-v2-l03'], 'KNX separates control messages from load power. Device addresses identify equipment, group addresses connect functions, and parameters define behaviour. Correct communication needs compatible data types as well as connected wiring.', 'A successful configuration download does not prove a room behaves correctly. Test the sensor command, actuator response, feedback and manual override as a complete sequence.');
teach(['p13-v2-l04','p13-v2-l05','p13-v2-l06'], 'A cable can have continuity and still fail its required data performance. Certification compares measurements with the selected link specification. Correct adapters, reference conditions and cable identity determine whether the result describes the installed link.', 'A split pair may pass a simple continuity check yet perform poorly at data frequencies. A correctly configured performance test measures what a basic wire map cannot.');
teach(['p13-v2-l07'], 'A surveillance system connects image quality to network and storage capacity. Resolution, frame rate and retention affect the resources needed. Secure commissioning also needs controlled access, correct time and a recoverable configuration.', 'Adding cameras can exceed a recorder’s throughput before its storage disk is full. Assess both incoming data rate and the storage required for the retention period.');
teach(['p13-v2-l08'], 'Access control must coordinate authorised entry with safe exit, fire requirements and power-loss behaviour. The lock, controller, exit input and power supply form one system rather than independent accessories.', 'A lock working during normal entry is only one test. Also establish what happens on denied entry, exit request and loss of power under the design.');
teach(['p13-v2-l09','p13-v2-l10'], 'A powered gate creates crushing, shearing and trapping hazards throughout its travel. Safety devices must address the actual danger zones and respond appropriately to faults. A gate moving correctly is not complete safety verification.', 'A photocell beam and a pressure-sensitive edge detect different conditions. Neither should be assumed to protect every part of the gate’s movement.');
teach(['p13-v2-l11','p13-l10','p13-v2-l13'], 'A fire-warning system needs suitable detection, effective warning and dependable power. Siting, interfaces, supervision and maintenance all affect the response. Equipment selection follows the fire strategy and applicable design requirements.', 'An individual detector sounding does not establish that the warning reaches all intended areas. Test interconnection and the required system response as well.');

teach(['p14-l01','p14-v2-l02','p14-v2-l03','p14-v2-l07'], 'Solar and battery systems can operate with several sources and power-flow directions. Demand, equipment ratings and physical routes must be planned together. A connection that works in one mode may need different protection or switching in another.', 'Map grid supply, PV generation, battery charging and backup loads before connecting equipment. This reveals which conductors and devices can remain energised in each mode.');
teach(['p14-v2-l09'], 'Isolating the AC supply does not stop illuminated PV modules generating DC or remove stored battery energy. Every source and any retained charge must be addressed by the equipment-specific isolation procedure.', 'An inverter display going dark is not proof that all its terminals are dead. Source identification, lock-off, discharge time and proving dead remain separate steps.');
teach(['p14-v2-l04','p14-v2-l05'], 'Battery and inverter locations must allow heat to escape and preserve access for isolation and service. Structural support, environmental exposure and fire consequences influence suitability. Clearances must follow the actual equipment instructions.', 'A compact cupboard may physically fit the equipment yet recirculate hot air or obstruct an escape route. Space alone is not a sufficient location check.');
teach(['p14-v2-l06'], 'PV verification checks both the physical installation and electrical string conditions. Polarity and expected voltage must match the design and environment. Test methods must suit connected electronics and the fact that daylight can maintain DC voltage.', 'An insulation-test method suitable for an isolated conventional circuit is not automatically suitable for connected PV electronics. Select and prepare the system for the approved method.');
teach(['p14-l02','p14-v2-l10','p14-v2-l11','p14-l07'], 'Backup systems need defined normal, transfer and island operating states. The source, neutral arrangement, fault-current capability and load priorities can change between states. A successful changeover does not by itself establish protective performance.', 'An inverter may support a load at normal voltage while providing less fault current than the grid. Protection must be checked for the actual backup mode, not copied from the grid-mode result.');
teach(['p14-v2-l13','p14-v2-l14','p14-l08','p14-v2-l16'], 'EV charging combines a sustained load with supply-capacity, earthing and protective requirements. Load sensing and software settings help control demand but cannot replace sound electrical connections or required protective functions.', 'A reversed current transformer can mislead load management. Check its position, direction and readings against the actual supply before relying on the charger’s displayed values.');

teach(['p15-v2-l02'], 'Pump control links motor protection with level, pressure or demand signals. Each input has a purpose, and sensor failure needs a defined response. Manual operation must remain consistent with the protective design.', 'A pump failing to start may reflect a low-level interlock rather than a failed motor. Trace the control conditions before bypassing or replacing components.');
teach(['p15-v2-l03'], 'Delivered airflow depends on the fan and the resistance of the complete duct path. Long, narrow or sharply bent ducts increase resistance. Control settings cannot compensate for an unsuitable physical airflow route.', 'A fan’s free-air rating is not the installed room airflow. Commission the completed duct and terminal arrangement rather than relying only on the nameplate figure.');
teach(['p05-spd','p15-v2-l04'], 'A surge protective device limits brief overvoltages through a coordinated protective path. Its voltage rating, connections and position matter. It does not replace overload protection, residual-current protection or the rest of the earthing design.', 'A healthy status indicator does not establish short connecting leads or correct backup protection. Assess the installed arrangement as well as the device condition.');
teach(['p16-l06'], 'A thermal image records a surface temperature pattern, not the cause of a fault. Load, emissivity and reflections affect what is displayed. Electrical measurements and inspection connect the pattern to a supported diagnosis.', 'One terminal hotter than comparable terminals under similar load deserves investigation. A reflection from a shiny surface can imitate a hot spot, so confirm the conditions before concluding.');
teach(['p16-l07','p16-l08'], 'An electrical quotation must cover the defined work and the resources needed to complete it. Labour, materials, overheads and profit have different roles. Clear assumptions and variation rules protect the agreed scope when conditions change.', 'A cable price alone omits installation access, supports, terminations, testing and making good. A room-by-room schedule makes these work items visible before pricing.');

const standardReasoning: Record<string, AnswerTeaching> = {
  'bathroom-sockets': { reasoning:'Wet conditions increase the consequences of contact with electricity. Location restrictions, suitable equipment and additional protection work together; fitting an RCD does not make a prohibited socket location acceptable.', application:'Identify the zone boundary first, then assess the specific accessory. An ordinary mains socket and an isolating shaver supply are different equipment categories.' },
  'kitchen-placement': { reasoning:'A socket needs protection from likely splash and heat, and its position should not draw appliance leads across hazards. A guidance distance must be understood with its measurement point and scope.', application:'Measure from the sink edge when applying the stated guidance, then consider the actual tap, draining area, hob and appliance lead routes.' },
  'accessory-height': { reasoning:'Mounting height affects reach and usability. Accessibility guidance has a defined scope; it must not be presented as a universal BS 7671 height for every building and accessory.', application:'Establish the building requirements and finished floor level before setting out boxes. An exact number without its scope can produce the wrong installation decision.' },
};
for (const [id, lessonId] of Object.entries({ 'fault-protection':'p05-l06', residual:'p05-l04', 'cable-design':'p06-l04', 'safe-testing':'p08-l01', verification:'p08-periodic', 'multiple-sources':'p14-l02', 'termination-quality':'p03-l03', 'ring-final-alteration':'p03-l10', 'outdoor-sockets':'p11-v2-l10', 'bath-shower-equipment':'p11-v2-l08', 'swa-support':'p04-l14' })) standardReasoning[id] = profiles[lessonId];

export function teachingForQuestion(question: AssessmentQuestion): AnswerTeaching {
  const standard = question.kind === 'Standards check' ? Object.entries(standardsChecks).find(([, check]) => check.prompt.trim() === question.prompt.trim())?.[0] : undefined;
  if (standard && standardReasoning[standard]) return standardReasoning[standard];
  const profile = profiles[question.lessonId];
  if (!profile) throw new Error(`Missing answer teaching for ${question.lessonId}`);
  if (question.id.includes('-q-term-')) {
    const definition = question.options[question.answer];
    const term = electricalTerms.find(item => item.definition.replace(/[“”"]/g,'') === definition);
    if (term?.contrast) return { reasoning: term.contrast, application: profile.application };
  }
  return profile;
}
