import bookAssets from './book-assets.json';
export type BookId = 'installation-designs' | 'modern-wiring' | 'iet-wiring-guide' | 'on-site-guide';
export type BookChapter = { title: string; printed: string; pdf: number };
export type CourseBook = { id: BookId; title: string; shortTitle: string; authors: string; edition: string; year: number; pages: number; description: string; chapters: BookChapter[] };

const chapter = (title: string, printed: string, pdf: number): BookChapter => ({ title, printed, pdf });
export const courseBooks: CourseBook[] = [
  { id: 'installation-designs', title: 'Electrical Installation Designs', shortTitle: 'Installation Designs', authors: 'Bill Atkinson · Roger Lovegrove · Gary Gundry', edition: 'Fourth edition', year: 2013, pages: 264, description: 'Design decisions, worked examples and complete building projects.', chapters: [
    chapter('Introduction', '1', 23), chapter('Three Bedroom House', '8', 30), chapter('Retirement Flatlets', '21', 43), chapter('Overcurrent Protection', '35', 57), chapter('An Architect’s Office', '44', 66), chapter('A High Street Shop', '62', 84), chapter('Earthing and Bonding', '75', 97), chapter('Car Service Workshop', '90', 112), chapter('Circuits', '111', 133), chapter('Farming and Horticulture', '123', 145), chapter('Isolation and Switching', '138', 160), chapter('A Village Sports Centre', '145', 167), chapter('An Indoor Swimming Pool', '160', 182), chapter('Cables and Wiring Systems', '174', 196), chapter('Inspection, Testing and Certification', '186', 208), chapter('A Caravan Park', '208', 230), chapter('Residual Current Devices', '213', 235), chapter('Flood Lighting Project', '224', 246), chapter('Circuit Design Calculations', '231', 253), chapter('Index', '239', 260),
  ] },
  { id: 'modern-wiring', title: 'Modern Wiring Practice', shortTitle: 'Wiring Practice', authors: 'W. E. Steward · R. A. Beck · edited by T. A. Stubbs', edition: 'Fourteenth edition', year: 2010, pages: 352, description: 'Installation methods, design fundamentals and practical photographs.', chapters: [
    chapter('Regulations Governing Installations', '3', 18), chapter('Fundamental Principles', '25', 40), chapter('The Design Process', '47', 62), chapter('Installation Design', '57', 72), chapter('Distribution of Supplies in Buildings', '101', 116), chapter('Worked Example', '139', 154), chapter('Special Types of Installation', '181', 196), chapter('A Survey of Installation Methods', '197', 212), chapter('Conduit Systems', '215', 230), chapter('Trunking Systems', '241', 256), chapter('Busbar and Modular Wiring Systems', '255', 270), chapter('Power Cable Systems', '261', 276), chapter('Insulated and Sheathed Cable Systems', '273', 288), chapter('Mineral Insulated Cables', '281', 296), chapter('Luminaires, Switches, Socket Outlets and Data', '291', 306), chapter('Inspection and Testing', '301', 316), chapter('Appendix A: Historical IEE Tables', '319', 334), chapter('Glossary', '327', 342), chapter('Index', '329', 344),
  ] },
  { id: 'iet-wiring-guide', title: 'Guide to the IET Wiring Regulations', shortTitle: 'IET Wiring Guide', authors: 'Electrical Contractors’ Association', edition: '17th Edition regulations · Amendment 1:2011', year: 2012, pages: 290, description: 'Historical BS 7671:2008+A1:2011 guidance on circuit design, equipment, earthing and verification. Scanned with an OCR text layer.', chapters: [
    chapter('Introduction and Overview', '1', 19), chapter('Legal Relationship and General Requirements', '11', 29), chapter('Circuitry and Related Requirements', '21', 39), chapter('Selection and Erection — Equipment', '79', 97), chapter('Earthing and Bonding', '133', 151), chapter('Inspection, Testing and Certification', '161', 179), chapter('Special Locations', '201', 219), chapter('References', '240', 258), chapter('Appendices', '243', 261), chapter('Standards and Bibliography', '244', 262), chapter('Popular Cables: Current Rating Tables', '249', 267), chapter('Limiting Earth Fault Loop Impedance', '252', 270), chapter('Cable Resistance, Impedance and R1 + R2', '254', 272), chapter('Fuse I²t Characteristics', '258', 276), chapter('Index', '259', 277),
  ] },
  { id: 'on-site-guide', title: 'On-Site Guide', shortTitle: 'On-Site Guide', authors: 'The Institution of Engineering and Technology', edition: 'Ninth edition · BS 7671:2018+A4:2026', year: 2026, pages: 258, description: 'The 2026 IET guide to supplies, protection, installation and verification, with cable and design appendices. Image scan: use Page view and chapter search.', chapters: [
    chapter('Preface', '9', 11), chapter('Introduction', '13', 15), chapter('The Electrical Supply', '19', 21), chapter('Protection', '33', 35), chapter('Earthing and Bonding', '61', 63), chapter('Isolation and Switching', '69', 71), chapter('Identification and Notices', '73', 75), chapter('Final Circuits', '83', 85), chapter('Locations Containing a Bath or Shower', '117', 119), chapter('Inspection for Initial Verification', '121', 123), chapter('Guidance on Initial Testing of Installations', '123', 125), chapter('Operation of RCDs', '141', 143), chapter('Prosumer’s Electrical Installations', '145', 147), chapter('Appendix A: Maximum Demand and Diversity', '149', 151), chapter('Appendix B: Measured Earth Fault Loop Impedance', '153', 155), chapter('Appendix C: Cable Types and External Influences', '163', 165), chapter('Appendix D: Supports for Cables and Wiring Systems', '169', 171), chapter('Appendix E: Conduit and Trunking Capacities', '177', 179), chapter('Appendix F: Current Capacity and Voltage Drop', '183', 185), chapter('Appendix G: Certification and Reporting', '195', 197), chapter('Appendix H: Standard Circuit Arrangements', '217', 219), chapter('Appendix I: Conductor Resistance', '225', 227), chapter('Appendix J: Devices for Isolation and Switching', '229', 231), chapter('Appendix K: Conductor Identification', '233', 235), chapter('Appendix L: IP Code', '241', 243), chapter('Appendix M: Safe Working Practices', '243', 245), chapter('Index', '247', 249),
  ] },
];
export const getBook = (id: string) => courseBooks.find(book => book.id === id);
export const bookByteLengths = Object.fromEntries(courseBooks.map(book => [book.id, bookAssets[book.id].reader.size])) as Record<BookId, number>;
export function printedPage(book: CourseBook, pdf: number) {
  if (book.id === 'installation-designs') return pdf >= 260 ? `p. ${pdf - 21}` : pdf >= 23 ? `p. ${pdf - 22}` : 'Front matter';
  if (book.id === 'iet-wiring-guide') return pdf >= 19 && pdf <= 283 ? `p. ${pdf - 18}` : 'Front matter / end matter';
  if (book.id === 'on-site-guide') return pdf >= 5 && pdf <= 256 ? `p. ${pdf - 2}` : 'Front matter / end matter';
  return pdf >= 16 ? `p. ${pdf - 15}` : 'Front matter';
}
