type ConnectionCheck = { id: string; prompt: string; correct: string; distractors: [string, string, string]; explanation: string };
export const connectionChecks: Record<string, ConnectionCheck[]> = {
  'p01-transformers': [{ id: 'turns', prompt: 'An ideal 230 V transformer has 1,000 primary turns and 100 secondary turns. What is its secondary voltage?', correct: '23 V', distractors: ['2.3 V', '230 V', '2,300 V'], explanation: 'V₂ = V₁ × N₂/N₁ = 230 × 100/1,000 = 23 V. This is the ideal winding-voltage ratio.' }],
  'p01-l26': [{ id: 'compensation', prompt: 'A sinusoidal 5 kW load improves from PF 0.75 to 0.95 lagging. Approximately what capacitor compensation is needed?', correct: '2.77 kVAr', distractors: ['1.00 kVAr', '5.00 kW', '4.41 kVAr'], explanation: 'Qc = 5 × [tan(acos 0.75) − tan(acos 0.95)] ≈ 2.77 kVAr. The original reactive demand is 4.41 kVAr; only the reduction is supplied by the capacitor.' }],
  'p06-l13': [{ id: 'three-phase-power', prompt: 'A balanced sinusoidal 400 V three-phase load draws 20 A at PF 0.80. What is its total real power?', correct: '11.09 kW', distractors: ['6.40 kW', '13.86 kW', '33.26 kW'], explanation: 'P = √3 × 400 × 20 × 0.80 / 1,000 = 11.09 kW. Line quantities already account for the complete three-phase system.' }],
  'p07-induction': [
    { id: 'slip', prompt: 'A four-pole, 50 Hz induction motor runs at 1,450 rpm. What is its slip?', correct: '3.33%', distractors: ['50%', '96.67%', '1.67%'], explanation: 'Synchronous speed is 120 × 50 / 4 = 1,500 rpm. Slip = (1,500 − 1,450)/1,500 = 3.33%; it is not efficiency.' },
    { id: 'motor-input', prompt: 'A 7.5 kW shaft-output motor has efficiency 0.90 and PF 0.82 on 400 V three-phase. Approximately what line current does it draw?', correct: '14.67 A', distractors: ['10.82 A', '13.20 A', '25.41 A'], explanation: 'I = 7,500/(√3 × 400 × 0.90 × 0.82) ≈ 14.67 A. Account for efficiency because the stated kW is shaft output.' },
  ],
  'p07-star-delta': [{ id: 'nameplate', prompt: 'Which nameplate winding rating can suit star–delta starting on a 400 V line supply, subject to the motor and load requirements?', correct: '400/690 V Δ/Y', distractors: ['230/400 V Δ/Y', 'Any six-terminal motor', 'Any motor with a 400 V star rating'], explanation: 'The motor must run in delta at the line voltage. A 230/400 V Δ/Y motor would expose 230 V windings to 400 V when switched to delta.' }],
  'p06-l15': [{ id: 'selectivity', prompt: 'What establishes selectivity between an upstream MCCB and a downstream breaker?', correct: 'Verified coordination data for the exact pair, settings, voltage and fault level', distractors: ['A larger upstream ampere rating by itself', 'Matching enclosure colours and brands', 'A downstream breaking capacity higher than the load current'], explanation: 'Selectivity concerns which device operates for a fault. Ampere ratings alone do not prove it; use the actual manufacturer coordination data.' }],
  'p08-l07': [{ id: 'sequence', prompt: 'Do correct line-to-line voltage readings establish the phase sequence?', correct: 'No; use a suitable phase-sequence instrument and the commissioning procedure', distractors: ['Yes, if all three RMS readings are equal', 'Yes, if every phase is the same colour', 'Yes, if a single-phase load works'], explanation: 'Equal voltage magnitudes do not identify the time order of the phases. Sequence and actual equipment rotation need their respective checks.' }],
};
