export type CourseBridgeNote={
  title:string;lead:string;rows:[string,string][];example:string;
  prompt:string;answer:string;formula?:string;flow?:string[];caution?:string;
  sources:{title:string;url:string}[];
};
const guide='https://www.electrical-installation.org/enwiki/';
export const courseBridges:Record<string,CourseBridgeNote>={
  'p06-l11':{
    title:'Connected load, demand and utilization',
    lead:'Use consistent units and a defined time period. A factor is meaningful only when its numerator and denominator are stated.',
    rows:[
      ['Connected load','Sum of the installed equipment ratings on a consistent input-power basis.'],
      ['Maximum demand','The greatest simultaneous demand over the stated assessment period. It is not automatically the sum of all ratings.'],
      ['Demand factor','Maximum demand divided by connected load, on the same basis.'],
      ['Utilization factor ku','For an individual load, its assessed operating demand relative to nominal rating.'],
      ['Coincidence factor ks','Group simultaneous maximum divided by the sum of individual maxima: at most one.'],
      ['Diversity factor','In the reciprocal convention, 1/ks: at least one. Some guides call ks “diversity”; always declare the convention.'],
    ],
    example:'Course example: two workshops each have 10 kW connected input load and each peaks at 8 kW. The measured group peak is 12 kW. Group demand factor = 12/20 = 0.60; coincidence = 12/16 = 0.75; reciprocal diversity = 16/12 ≈ 1.33. These are example results, not default design factors.',
    formula:'k_s=\\frac{D_{\\mathrm{group}}}{\\sum D_i},\\qquad F_{\\mathrm{div}}=\\frac{1}{k_s}',
    prompt:'Why must the group peak be divided by 16 kW, not 20 kW, when calculating coincidence in this example?',
    answer:'Coincidence compares the simultaneous group maximum with individual maxima. The 20 kW connected total belongs to the demand-factor calculation.',
    caution:'Use site evidence and applicable rules. Do not apply an assumed reduction twice or copy a factor from an unrelated building.',
    sources:[{title:'Schneider: utilization and coincidence definitions',url:guide+'Estimation_of_actual_maximum_kVA_demand'}],
  },
  'p02-l01':{
    title:'Conductor identification: the Kenyan evidence check',
    lead:'Identify function from verified drawings, markings and appropriate tests—not colour alone. Existing installations may contain mixed eras, repairs or incorrect markings.',
    rows:[
      ['Before selecting cable','Obtain the adopted Kenyan standard and project specification, including edition and conductor-identification table.'],
      ['Before touching conductors','Identify all sources and follow safe isolation. A familiar colour does not prove that a conductor is safe.'],
      ['Before alteration','Record the existing system, trace and verify conductor functions, and agree compliant identification for new work.'],
      ['At handover','Update circuit labels and drawings; record any unresolved identification issue rather than concealing it.'],
    ],
    example:'An apprentice finds two colour schemes in one board. The correct response is to establish the applicable identification requirements and verify the circuits, not relabel every conductor from a remembered UK video.',
    prompt:'Does a colour match establish both conductor function and absence of voltage?',
    answer:'No. Markings communicate intended identification; verified circuit evidence establishes function, and the safe-isolation procedure establishes the conditions for work.',
    caution:'Evidence gap: the accessible DKS 662-5:2026 document is a public-review draft. This course does not present its table as an adopted Kenyan requirement. Obtain the applicable adopted edition from KEBS before using a mandatory colour table.',
    sources:[{title:'KEBS public-review draft — not an adopted rule',url:'https://www.kebs.org/wp-content/uploads/2026/03/DKS-662-5-2026-PRD.pdf'},{title:'KEBS: verify applicable standards',url:'https://www.kebs.org/'}],
  },
  'p08-l02':{
    title:'Choose the instrument by the question',
    lead:'One instrument may offer several modes, but each mode has its own connection, safety conditions and interpretation. This map introduces the demonstrations; it is not a field test procedure.',
    rows:[
      ['Two-pole voltage indicator','Voltage presence/absence within a safe-isolation method, with the required instrument proving checks.'],
      ['Low-resistance ohmmeter','Continuity on an appropriately isolated circuit; account for lead resistance and parallel paths.'],
      ['Insulation-resistance tester','Insulation under a selected test voltage; isolate, protect connected equipment and follow discharge requirements.'],
      ['Loop tester','Earth-fault-loop impedance, with the specified controlled test method and appropriate live-test precautions.'],
      ['RCD tester','Residual-current operation: select the correct waveform, current and test mode.'],
      ['Earth-resistance tester','Electrode/system resistance using a method suited to the installation and parallel paths.'],
      ['Clamp meter','Current around the intended conductor or conductor group; clamping line and neutral together is not a normal load-current reading.'],
      ['Multimeter','Voltage, resistance or current only with suitable mode, terminals, ratings and method; it is not a universal substitute for installation tests.'],
      ['Phase-sequence meter','Three-phase order; not proof of isolation.'],
      ['Multifunction tester (MFT)','Combines specified functions, not every instrument or every method. Read the actual model’s capabilities.'],
    ],
    example:'A continuous protective conductor and sound insulation answer different questions. A low resistance along the conductor can be desirable; low resistance through insulation can indicate a defect. Record what was measured before interpreting the number.',
    prompt:'Why is a resistance number meaningless without the test points and selected function?',
    answer:'The same numerical scale can describe different paths and purposes. State the instrument mode, points, safe condition, units and expected interpretation.',
    caution:'Live tests require competence and controls. Never change to resistance or insulation testing on an energised circuit.',
    sources:[{title:'Megger: multifunction installation tester functions',url:'https://www.megger.com/en/type/low-voltage-installation-testing/multifunction-installation-testers'}],
  },
  'course-TqdQRgf3uGs':{
    title:'Reading an MCCB specification',
    lead:'Read the frame, trip unit and fault duties separately. No single ampere label establishes a complete feeder specification.',
    rows:[
      ['In / frame / Ir','Rated current, frame family and overload setting are related but distinct. Verify the actual fitted trip unit.'],
      ['Ue and poles','Operating voltage and pole arrangement must match the system and switching requirements.'],
      ['Icu','Ultimate short-circuit breaking capacity at stated conditions.'],
      ['Ics','Service short-circuit breaking capacity under the applicable standard.'],
      ['Icw','Short-time withstand current for a stated duration, where specified; relevant to intentional delay.'],
      ['L / S / I / G','Long-time, short-time, instantaneous and ground-fault functions, where the trip unit provides them.'],
    ],
    example:'Course example: a suitable load-current rating does not approve a 15 kA device where prospective fault current is 22 kA. A higher-rated device or a specifically verified backup combination is needed; a convenient delay setting does not raise breaking capacity.',
    prompt:'Why must an intentional short-time delay be checked against withstand as well as selectivity?',
    answer:'The upstream equipment carries fault current during the delay. Its specified current-and-time withstand must support that exposure.',
    caution:'Never raise pickups or delays simply to stop upstream operation. Cable protection, disconnection, withstand and exact coordination data must remain satisfactory.',
    sources:[{title:'Schneider: fundamental breaker ratings',url:guide+'Fundamental_characteristics_of_a_circuit-breaker'},{title:'Schneider: Ics and short-time withstand',url:guide+'Other_characteristics_of_a_circuit-breaker'},{title:'Schneider: breaker selection and backup conditions',url:guide+'Selection_of_a_circuit-breaker'}],
  },
  'p05-l14':{
    title:'Basic selectivity before a coordination study',
    lead:'Start with the fault location and the supplies that should remain available. The device nearest upstream should clear the relevant fault within the verified selective arrangement.',
    flow:['Main MCCB','Floor distribution board','Final-circuit MCB','Faulted load'],
    rows:[
      ['Current discrimination','Different operating-current characteristics can separate responses over a defined range.'],
      ['Time discrimination','An upstream delay may allow downstream clearing, only where protection and withstand permit.'],
      ['Manufacturer evidence','Use exact device combinations, settings and stated selectivity limits; ampere ratios alone are insufficient.'],
    ],
    example:'A fault in one office socket circuit should not unnecessarily black out the entire floor. Trace every upstream device on that path, then establish whether selectivity holds up to the available fault level.',
    prompt:'If selectivity is verified only up to a stated current, what must the designer compare it with?',
    answer:'The prospective fault conditions at the relevant location; record where the selectivity claim ends.',
    caution:'Backup protection and selectivity are not synonyms. A combination that safely interrupts a fault does not automatically preserve all healthy circuits.',
    sources:[{title:'Schneider: coordination between circuit breakers',url:guide+'Coordination_between_circuit-breakers'}],
  },
  'p06-l14':{
    title:'Inside an automatic power-factor panel',
    lead:'Separate the sensing/control path from the capacitor power branches. The CT does not carry the capacitor bank’s load current through the controller.',
    flow:['CT and voltage sensing','PF controller','Step commands','Capacitor-duty switching','Parallel capacitor steps'],
    rows:[
      ['Power path','Supply → suitable protection → switching for each step → capacitor branches, in parallel with the load.'],
      ['Control path','Correctly located CT and voltage inputs let the controller assess the compensated installation and command steps.'],
      ['Fixed versus stepped','Fixed correction suits an assessed stable duty; automatic steps adapt compensation as demand changes.'],
      ['Reactors where required','Detuned arrangements address particular harmonic/resonance conditions; they require an engineered product selection.'],
    ],
    example:'A workshop that alternates between one and several motors may need different kvar through the day. A stepped bank can add or remove sections; its step sizes, control range and switching duty must suit those changes.',
    prompt:'Why should the controller’s sensing include the loads and the effect of the capacitor bank?',
    answer:'It needs to observe the corrected supply condition to decide whether another step is required or a step should be removed.',
    caution:'Concept diagram only—not terminal wiring. Capacitors retain energy. Follow discharge/verification instructions, and never open-circuit an energised CT secondary. Use the exact panel documentation.',
    sources:[{title:'Schneider: fixed and automatic compensation',url:guide+'Equipment_to_improve_power_factor'},{title:'PowerLogic: CT position',url:'https://productinfo.se.com/powerlogic_pfc_capacitor_bank_iom/powerlogictm_pfc-capacitor-bank_iom_manual/English/DOCA0495EN_PowerLogic%E2%84%A2_PFC%20Capacitor%20Bank_IOM_Manual_DD00827046.XML.xml/%24/PFC_NAM_CurrentTransformerPosition_TPC_DD01148766.XML'},{title:'Schneider: detuned capacitor banks',url:'https://www.se.com/us/en/product-range/60270-varset-detuned-capacitor-banks'}],
  },
  'p07-vfd':{
    title:'What actually protects the motor?',
    lead:'Assign a function to each component. A contactor inside a starter is not, by itself, the motor’s overload protection.',
    rows:[
      ['Short circuit','Appropriately selected fuse, breaker or motor-protection device, coordinated with the equipment.'],
      ['Sustained overload','An overload relay or documented motor-protection function with suitable settings and duty.'],
      ['Phase loss / imbalance','A documented motor/phase protective function appropriate to the risk; do not assume it from an acronym.'],
      ['Switching','The contactor carries and switches the load within its rating, often responding to a separate protective control contact.'],
      ['Speed and process control','A VFD provides controlled motor operation, with only the protective functions actually specified by its manufacturer.'],
    ],
    example:'A stopped motor and an open contactor do not identify the cause. Trace whether the stop command, overload, phase monitor or drive caused release, then investigate that evidence under a safe procedure.',
    prompt:'Why is replacing an overload relay with an ordinary contactor not equivalent protection?',
    answer:'The contactor switches when commanded; it does not inherently sense and time sustained motor overload.',
    caution:'Do not bypass protective contacts to keep production running. Establish cause, repair and verify before returning equipment to service.',
    sources:[{title:'eFIXX DOL lesson — supplied transcript',url:'https://www.youtube.com/watch?v=HFkTPmY7N7w'},{title:'MPCB lesson — supplied transcript',url:'https://www.youtube.com/watch?v=wQwGZMcDGXk'}],
  },
  'course-igi8F6UAvh0':{
    title:'Phase sequence before the meter demonstration',
    lead:'Three phase voltages reach corresponding points in their cycles in a defined order. For a given connection, reversing that order reverses the motor’s rotating field.',
    flow:['L1 → L2 → L3 sequence','Rotating magnetic field','Motor/load direction','Verify against the required direction'],
    rows:[
      ['Concept','Interchanging any two phases reverses the sequence; cyclic relabelling of all three is not the same operation.'],
      ['Measurement','The indicator reports sequence for its connected lead order. Record the lead reference and measurement point.'],
      ['Correction','Any wiring change requires safe isolation and proving dead; controlled verification follows.'],
    ],
    example:'After supply repairs, unchanged motor terminals do not guarantee unchanged supply sequence. A pump’s required direction must be checked in the commissioning plan, without treating trial operation as permission for unsafe access.',
    prompt:'Can a rotation meter verify protective-conductor continuity or absence of voltage?',
    answer:'No. Those are different verification tasks; use their specified instruments and safe methods.',
    caution:'This concept lesson precedes a live-measurement demonstration. It does not authorise unsupervised live testing.',
    sources:[{title:'Fluke 9040 manufacturer manual',url:'https://assets.fluke.com/manuals/9040____umeng0100.pdf'}],
  },
};
