import type {Revision} from './question-revisions';

// Individually written distinctions for repeated core stems identified in the
// course-integrity audit. IDs, answer positions and associated card IDs survive.
export const courseEditorialRevisions:Record<string,Revision>={
  'p12-v2-l01-q-concept-3':{
    prompt:'You are replacing an incandescent lamp with an LED. The cap fits, but you still need similar light output and a suitable appearance. Which information should guide that comparison?',
    correct:'Compare lumen output and colour temperature, then check the supply and fitting compatibility.',
    wrong:['Match the old wattage; different lamp technologies produce the same light per watt.','Match the cap alone; it determines both light output and colour.','Choose the highest wattage that fits, without checking the fitting rating.'],
    errors:['Watts describe input power, not a fixed light output across different technologies.','The cap identifies the connection, not the light quantity or colour.','Physical fit does not establish thermal or electrical suitability.'],
    why:'A lamp converts electrical input into light with a technology-dependent efficacy. Lumens describe light output; colour temperature describes its warm or cool appearance. Neither replaces the electrical and thermal compatibility checks.',
    distinction:'Input watts, light output and physical compatibility answer different questions.',
    practice:'Read the replacement lamp and luminaire information together before recommending a substitution.',
    followUp:{prompt:'Two lamps have equal lumen ratings but different wattages. What can you compare from those figures?',answer:'Their luminous efficacy in lumens per watt.',why:'For equal light output, the lower input power gives more lumens per watt; this alone does not establish colour quality or suitability.'},
  },
  'p01-pf-visual-q-concept-2':{
    prompt:'In the power-factor animation, part of the energy moves into a field and later returns to the source. Which quantity describes this exchange rather than net energy converted to work or heat?',
    correct:'Reactive power, Q, measured in var.',
    wrong:['True (real) power, P, measured in watts.','Apparent power, S, measured in volt-amperes.','Power factor, measured in watts per second.'],
    errors:['Real power describes net energy transfer, not the back-and-forth exchange alone.','Apparent power describes the RMS voltage–current demand, not just its reactive component.','Power factor is a ratio without units, not a rate of change of power.'],
    why:'The field can store energy during one part of the cycle and return it during another. Reactive power describes that exchange. It can contribute to supply current even though it is not net energy converted by an ideal reactive element.',
    distinction:'Reactive exchange is not the same as power dissipated as heat.',
    practice:'Use the animation to explain why current loading and useful output are not interchangeable ratings.',
    followUp:{prompt:'Does zero average power in an ideal inductor mean zero current?',answer:'No.',why:'Current can exchange energy with the magnetic field while the average net energy transfer over a cycle is zero.'},
  },
  'p06-l14-q-concept-2':{
    prompt:'You are drawing a sinusoidal-load power triangle to scale. True power is 3 kW and apparent power is 5 kVA. What reactive-power magnitude completes the triangle?',
    correct:'4 kvar.',
    wrong:['2 kvar.','8 kvar.','5.83 kvar.'],
    errors:['Subtracting the side lengths treats perpendicular components as collinear.','Adding the two given magnitudes does not give the perpendicular side.','This treats apparent power as a perpendicular component rather than the hypotenuse.'],
    why:'Apparent power S is the hypotenuse. True (real) power P and reactive power Q are perpendicular components, so Q = √(S² − P²) = √(25 − 9) = 4 kvar.',
    distinction:'Use the right-angle relationship, not ordinary addition of P and Q.',
    practice:'Label kW, kvar and kVA separately even when one drawing scale is used for their magnitudes.',
    workingTex:'Q=\\sqrt{S^2-P^2}=\\sqrt{5^2-3^2}=4\\,\\mathrm{kvar}',
    followUp:{prompt:'What is the power factor of this 3 kW, 5 kVA load?',answer:'0.6.',why:'Power factor is P/S = 3/5; for these sinusoidal conditions it is also the cosine of the phase angle.'},
  },
  'p03-l12-q-concept-3':{
    prompt:'An MCB fits onto the consumer-unit rail. Before accepting it for the circuit, what further selection evidence is needed?',
    correct:'Its compatibility with the assembly, its circuit protection characteristics and its suitability for the prospective fault duty.',
    wrong:['Its physical fit is enough to establish electrical compatibility.','Only its colour and position need to match the neighbouring devices.','The largest available current rating is always the safest choice.'],
    errors:['Mechanical fit does not establish the approved assembly or protection performance.','Appearance does not demonstrate protective characteristics.','An excessive rating can leave the conductor inadequately protected.'],
    why:'The consumer unit is an assembly, not just a rail of interchangeable-looking devices. Device selection must suit both the assembly and the designed circuit, including the fault duty it may have to interrupt.',
    distinction:'A device that fits is not necessarily a device that protects correctly.',
    practice:'Use the design and manufacturer documentation when checking an unconnected training assembly.',
    followUp:{prompt:'Does a correct device rating establish correct terminal tightening?',answer:'No.',why:'Selection and workmanship are separate checks; terminal tightening follows the manufacturer’s specified method and torque.'},
  },
  'p10-l02-q-concept-2':{
    prompt:'During planning for a consumer-unit change, why is the prospective fault current relevant to the replacement protective devices?',
    correct:'They must be suitable for the fault current that could occur, not merely the normal load current.',
    wrong:['It is the normal current that every circuit will continuously draw.','It replaces the need to assess existing circuit condition.','It proves any device with the same ampere rating is interchangeable.'],
    errors:['Prospective fault current concerns fault conditions, not ordinary demand.','A fault-level assessment does not reveal all defects in the existing circuits.','Equal current ratings do not establish breaking capacity or assembly compatibility.'],
    why:'Normal circuit current and prospective fault current describe different operating conditions. The replacement protection and assembly need evidence of suitability for the actual fault duty as well as the circuit load.',
    distinction:'Rated current and fault-interrupting capability are not the same rating.',
    practice:'Keep fault-level information and device details together in the changeover assessment; this is not a live-testing instruction.',
    followUp:{prompt:'Can a new consumer unit cure damaged insulation in an existing circuit?',answer:'No.',why:'Changing the central protection does not repair defects elsewhere; those circuits still need assessment and appropriate verification.'},
  },
  'p10-l08-q-concept-4':{
    prompt:'A three-phase installation looks untidy, but you need evidence for a repair or rewire decision. Which protection finding deserves investigation beyond appearance?',
    correct:'Whether device characteristics coordinate with the conductors and the available fault current.',
    wrong:['Whether every protective device has the same current rating.','Whether the enclosure looks newer than the cables.','Whether all connected equipment happens to run during the visit.'],
    errors:['Different circuits can legitimately require different ratings.','Age and appearance alone do not establish coordination.','Normal operation does not demonstrate adequate protection during a fault.'],
    why:'Protection is judged against circuit characteristics and fault conditions. A tidy enclosure or a working load cannot prove that conductors are adequately protected or that devices can deal with the available fault duty.',
    distinction:'Normal function is evidence of operation, not complete evidence of safety.',
    practice:'Record the identified defect and its supporting evidence before deciding the scope of corrective work.',
    followUp:{prompt:'Must every untidy installation automatically receive a full rewire?',answer:'No.',why:'The decision should follow the extent and seriousness of verified defects, not untidiness alone.'},
  },
  'p06-l11-q-concept-2':{
    prompt:'In the house example, adding all circuit ratings gives a larger figure than the proposed demand after diversity. What is the demand estimate trying to represent?',
    correct:'The greatest credible load operating at the same time under the stated assumptions.',
    wrong:['The total energy used over a full year.','A guarantee that the supply current can never exceed the estimate.','The smallest load that can operate overnight.'],
    errors:['Energy over time and coincident demand are different quantities.','An estimate depends on operating assumptions and is not an absolute guarantee.','Maximum demand concerns the credible peak, not the minimum.'],
    why:'Diversity recognises that not all loads run at full rating together. The estimate is useful only when its assumptions fit the installation; the video’s example method is not a universal allowance for every building.',
    distinction:'Connected ratings describe installed capacity; maximum demand describes expected coincidence.',
    practice:'Write down the operating assumptions alongside the calculation so they can be checked when the use changes.',
    followUp:{prompt:'If the heating arrangement changes, should the old diversity assumptions be reused without review?',answer:'No.',why:'A different operating pattern can change which loads coincide and therefore the credible demand.'},
  },
  'p10-l09-q-concept-2':{
    prompt:'A project equipment list gives installed ratings, but the designer also asks when the equipment runs. Why is that operating information needed for load estimation?',
    correct:'It helps establish the likely coincident demand rather than assuming every nameplate load runs together.',
    wrong:['It allows all short-duration loads to be ignored.','It makes power factor irrelevant to supply capacity.','It means the smallest device rating can represent the entire project.'],
    errors:['Short-duration or starting loads may still affect the design.','Supply current and kVA can depend on power factor as well as kW.','One small device cannot represent the simultaneous project load.'],
    why:'Load estimation connects the equipment schedule to the way the project will operate. Coincidence, load characteristics and justified growth assumptions help turn installed ratings into a credible design demand.',
    distinction:'An equipment inventory is an input to demand estimation, not its finished result.',
    practice:'Keep occupancy and operating schedules with the load schedule so later design changes can be traced.',
    followUp:{prompt:'Would two buildings with identical equipment lists necessarily have the same maximum demand?',answer:'No.',why:'Different operating schedules can produce different simultaneous loads.'},
  },
  'p08-l03-q-concept-3':{
    prompt:'A low-resistance reading is obtained between the main earthing terminal and bonded pipework. Why does that reading alone not prove the intended bonding conductor is sound?',
    correct:'Other connected metalwork may provide a parallel path for the test current.',
    wrong:['Every low-resistance reading proves the exact conductor route.','Pipework always prevents a continuity tester from passing current.','A continuity measurement also proves the installation’s insulation resistance.'],
    errors:['The instrument measures the available path, not the identity of the intended conductor.','Conductive pipework can form a path rather than block one.','Continuity and insulation resistance are different tests.'],
    why:'Current can reach the test point through more than one metallic route. A satisfactory-looking combined reading can therefore conceal a poor intended connection. The result needs the approved test method and inspection context.',
    distinction:'A path exists is a weaker conclusion than the intended bonding conductor is continuous.',
    practice:'Interpret the measurement alongside the conductor route and terminations; do not alter safety connections without the required safe procedure.',
    followUp:{prompt:'Why compensate a long wandering lead before judging a low-resistance result?',answer:'Its own resistance contributes to the displayed reading.',why:'Lead resistance can be significant compared with the low resistance being assessed.'},
  },
  'p05-l09-q-concept-3':{
    prompt:'In the fault-finding demonstration, two bonding routes connect through pipework. One intended conductor is defective, yet a test still gives continuity. What explains the misleading result?',
    correct:'The test current reaches the point through the other conductor and interconnected metalwork.',
    wrong:['A continuity tester automatically repairs an open conductor.','The pipework proves both individual conductors are sound.','Any continuity result proves the bonding conductor has the required size.'],
    errors:['A measuring instrument does not restore a broken connection.','A combined route cannot prove each individual route.','Continuity alone does not establish conductor size or full suitability.'],
    why:'The demonstration separates the conductor being investigated from an alternative route. The parallel route can mask its defect, which is why fault finding must establish which path the measurement actually represents.',
    distinction:'Proving a network connection is not the same as proving each conductor in it.',
    practice:'Study the demonstration on an isolated training arrangement under supervision; it is not permission to disconnect bonding on a working installation.',
    followUp:{prompt:'What question should you ask before accepting an unexpectedly low continuity reading?',answer:'Which paths could the test current have taken?',why:'Understanding the circuit of the test helps distinguish the intended conductor from parallel routes.'},
  },
  'p08-l08-q-concept-2':{
    prompt:'The Ze demonstration distinguishes the supply-side earth loop from other metallic routes. If those parallel routes influence a reading, what can happen to the result?',
    correct:'It can appear lower than the impedance of the external supply loop being assessed.',
    wrong:['It must become the final-circuit conductor resistance R1 + R2.','It automatically proves the supply earthing connection is satisfactory.','It becomes a measurement of insulation resistance.'],
    errors:['Parallel influence does not turn a loop measurement into an isolated conductor-resistance measurement.','An alternative route can mask a problem in the intended supply path.','Loop impedance and insulation resistance measure different properties.'],
    why:'Parallel conductive routes can lower the combined impedance seen by an instrument. Ze is intended to describe the external earth-fault loop, so the identity of the measured path matters, not just whether the number is small.',
    distinction:'A low combined reading does not necessarily establish the external path on its own.',
    practice:'This is interpretation only. Live loop testing and any handling of safety connections require a competent person and the applicable safe method.',
    followUp:{prompt:'Does Ze include the final circuit’s R1 + R2?',answer:'No.',why:'Ze describes the external loop; final-circuit conductor resistance contributes when considering the complete circuit loop Zs.'},
  },
};
