import type {Revision} from './question-revisions';

// Nine separately authored replacements for two repeated glossary families.
// The concept changes with the demonstrated lesson, not just its title.
export const foundationVocabularyRevisions:Record<string,Revision>={
 'p01-l01-q-term-1':{
  prompt:'In the atom model, an electron and a proton are compared. Which statement correctly relates their electrical charges?',
  correct:'Their charges have equal magnitude but opposite signs.',
  wrong:['The proton has the larger charge because it has much greater mass.','Both charges are negative, but the nucleus makes the proton appear positive.','An electron is uncharged until it begins moving through a conductor.'],
  errors:['Mass and electric charge are different properties; larger mass does not imply greater charge.','A proton carries positive charge; its location does not change that sign.','Motion is not required for an electron to possess its negative charge.'],
  why:'A proton carries positive elementary charge and an electron carries an equal magnitude of negative charge. Their different masses do not change this equality, which explains how equal numbers can give a neutral atom.',
  distinction:'Charge magnitude, charge sign and particle mass are separate properties.',
  practice:'Use the particle model to explain electrical neutrality before considering charge transfer between materials.',
  followUp:{prompt:'Why can an atom with charged particles have zero net charge?',answer:'Its positive and negative charges can balance.',why:'Neutrality concerns the net total, not an absence of charged particles.'},
 },
 'p01-l02-q-term-1':{
  prompt:'The copper lesson draws attention to the outer-shell electron. Why is this important to the conductor model?',
  correct:'It helps explain mobile electrons moving through the metal without the nuclei travelling with them.',
  wrong:['It explains why voltage must first create a new electron inside each copper atom.','It shows that whole copper atoms must move from one terminal to the other.','It means each electron must stay permanently attached to the copper atom that originally held it.'],
  errors:['Mobile charge carriers are already present; the source need not manufacture electrons.','Charge transport in solid copper is not a flow of whole copper atoms.','The conducting model depends on mobile electrons not remaining confined to one parent atom.'],
  why:'The instructor’s outer-shell model introduces why some electrons are mobile in copper. In the solid, these conduction electrons can move through the metallic structure while its positive ion cores remain essentially in place.',
  distinction:'Movement of charge through copper does not require movement of the copper structure.',
  practice:'This is the model behind a mechanically fixed conductor carrying current.',
  followUp:{prompt:'What remains essentially in place when conduction electrons drift in copper?',answer:'The positive ion cores of the metallic structure.',why:'The conductor remains a solid while mobile electrons transport charge.'},
 },
 'p01-l02-q-term-2':{
  prompt:'The copper drawing contains 29 protons and 29 electrons. What does that tell you about its net electrical charge?',
  correct:'It is neutral because the positive and negative charges balance.',
  wrong:['It is positive because the massive nucleus outweighs the electrons.','It is negative because the outer electron is the easiest particle to move.','It has no electrical charges because a neutral atom contains only uncharged particles.'],
  errors:['Neutrality depends on charge, not a comparison of particle masses.','Mobility does not change the balance of total positive and negative charge.','A neutral atom contains charged particles whose contributions cancel.'],
  why:'Each proton contributes positive charge and each electron an equal magnitude of negative charge. With equal counts, their net contribution is zero. The outer electron’s mobility is a separate property.',
  distinction:'Neutral does not mean unable to conduct; it means zero net charge.',
  practice:'Keep the explanation of copper’s neutrality separate from the explanation of its conductivity.',
  followUp:{prompt:'Does the ability of a material to conduct prove it has a net negative charge?',answer:'No.',why:'Mobile charges can exist in material whose total positive and negative charges balance.'},
 },
 'p01-l03-q-term-1':{
  prompt:'The instructor introduces the coulomb to avoid counting enormous numbers of individual electrons. What does a quantity stated in coulombs describe?',
  correct:'An amount of electric charge, without by itself stating the transfer time.',
  wrong:['The rate of charge transfer, without needing a separate time interval.','The energy transferred by each unit of charge between two points.','The rate of energy conversion by the load while charge moves.'],
  errors:['Charge per unit time is current; coulombs alone specify an amount.','Energy per unit charge is potential difference, measured in volts.','Energy per unit time is power, measured in watts.'],
  why:'The coulomb gives a practical unit for an amount of electric charge. A time interval is additionally needed to calculate the average current associated with a transfer of that charge.',
  distinction:'Charge is an amount; current is a rate.',
  practice:'When reading a charge-transfer example, keep the coulomb value and the elapsed time as separate inputs.',
  followUp:{prompt:'Can 6 C alone tell you the average current?',answer:'No; the transfer time is also needed.',why:'The same amount of charge can pass quickly or slowly, producing different average currents.'},
 },
 'p01-l04-q-term-1':{
  prompt:'A steady current transfers 12 C through a point in 4 s. The same current continues for another 4 s. How much charge has passed in the full 8 s?',
  correct:'24 C: the unchanged rate transfers another 12 C in the second interval.',
  wrong:['12 C: a constant current keeps the total transferred charge unchanged.','6 C: spreading the transfer over twice the time halves the charge.','3 C: dividing charge by time gives the accumulated charge.'],
  errors:['A constant rate continues adding transferred charge as time passes.','This incorrectly holds the total transfer fixed while the stated current continues.','12 C divided by 4 s gives 3 A, a current rather than accumulated charge.'],
  why:'The current is 12/4 = 3 A. At this unchanged rate, 8 s transfers 3 × 8 = 24 C. A fixed current does not mean a fixed total charge over increasingly long intervals.',
  distinction:'Rate stays constant while the accumulated amount increases.',
  practice:'Use elapsed time with the measured current when estimating transferred charge.',
  workingTex:String.raw`I=\frac{12}{4}=3\,\mathrm{A},\qquad Q=3\times8=24\,\mathrm{C}`,
  followUp:{prompt:'At the same 3 A, how much charge passes in 1 s?',answer:'3 C.',why:'One ampere is one coulomb per second.'},
 },
 'p01-l05-q-term-1':{
  prompt:'In the basic circuit demonstration, which component is intended to interrupt the current during ordinary operation?',
  correct:'The control switch, which opens or closes the conducting path.',
  wrong:['The load, which opens the path whenever it converts energy.','The protective device, which should trip each time normal control is wanted.','The connecting conductor, which limits operation by consuming the supplied charge.'],
  errors:['A normally operating load transfers energy without repeatedly opening the circuit.','Overcurrent protection is a different purpose from ordinary switching.','A conductor provides a path; charge consumption is not its operating mechanism.'],
  why:'The instructor distinguishes the source, protection, control, load and connecting conductors. A switch provides ordinary control by changing whether the current path is complete.',
  distinction:'Control of normal operation and response to overcurrent are different functions.',
  practice:'Identify the component’s role before explaining why a lamp turns on or off.',
  followUp:{prompt:'Does an open control switch mean the source has lost its voltage?',answer:'No.',why:'Interrupting load current does not remove the source’s potential difference.'},
 },
 'p01-l06-q-term-1':{
  prompt:'The demonstration increases the supply voltage while keeping the resistance unchanged. The ammeter reading rises. What does that larger reading mean?',
  correct:'More charge passes the measurement point each second.',
  wrong:['Each electron has acquired a greater magnitude of electric charge.','The same amount of charge now takes longer to pass the point.','The conductor now consumes more charge each second than the source supplies.'],
  errors:['The elementary charge does not increase when supply voltage is raised.','A greater current means a faster, not slower, charge-transfer rate.','Charge is not consumed in the conductor; current describes its transfer.'],
  why:'An ammeter measures current, the rate of charge transfer. In this fixed-resistance example, increasing voltage increases that rate; it does not increase the charge carried by an individual electron.',
  distinction:'A larger current changes the rate of transfer, not the elementary charge.',
  practice:'Interpret the meter reading physically before using the voltage–current relationship in calculations.',
  followUp:{prompt:'At fixed voltage, what does an increased resistance do to charge passing per second?',answer:'It reduces the charge-transfer rate.',why:'For the stated resistive model, current is inversely related to resistance.'},
 },
 'p01-l12-q-term-1':{
  prompt:'For the resistive heating load, voltage stays constant while current doubles. Which prediction follows from the power relationship developed in the lesson?',
  correct:'Power doubles because twice the charge passes per second at the same energy per unit charge.',
  wrong:['Power stays constant because voltage alone determines energy transferred per second.','Power quadruples because doubling current always produces a fourfold power increase.','Power halves because each unit of charge now has less time to transfer energy.'],
  errors:['Power depends on current as well as voltage.','The fourfold I²R result requires resistance to stay constant; here voltage is held constant.','At fixed voltage the energy per unit charge does not halve when current rises.'],
  why:'For the DC or purely resistive case, P = VI. Holding V constant and doubling I doubles P. The physical link is energy per charge multiplied by charge per second.',
  distinction:'State which quantity is fixed before using a proportional power rule.',
  practice:'Connect the heater’s voltage and current readings to its electrical input power.',
  workingTex:String.raw`P_2=V(2I_1)=2P_1`,
  followUp:{prompt:'Why is the same simple P = VI interpretation qualified for later AC loads?',answer:'Voltage and current may no longer be in phase.',why:'The lesson explicitly limits this form for real power to DC or purely resistive AC examples.'},
 },
 'p01-l25-q-term-1':{
  prompt:'The capacitor demonstration starts with two conducting plates separated by a dielectric. Why must the plates remain separated?',
  correct:'The dielectric separates the conductors so they can sustain a potential difference rather than form a direct connection.',
  wrong:['The dielectric must conduct between the plates to make the device act as a capacitor.','The plates must touch so equal charge can flow continuously between them.','The separation makes the capacitor behave exactly like a resistor of the same numerical value.'],
  errors:['A normal dielectric is insulating; direct conduction is not the intended capacitor action.','Touching plates provide a direct connection, losing the intended separated-plate arrangement.','Capacitance and resistance describe different properties and use different units.'],
  why:'The instructor’s plate-and-dielectric model distinguishes a capacitor from a direct conducting link. Separated conductors can support opposite charges and an electric field between them.',
  distinction:'Capacitance is not an alternative name or unit for resistance.',
  practice:'Keep capacitor construction in mind before comparing series and parallel capacitance readings.',
  followUp:{prompt:'In the demonstration, does adding a capacitor in parallel increase or decrease total capacitance?',answer:'It increases total capacitance.',why:'Parallel capacitances add, unlike the reciprocal relationship for parallel resistances.'},
 },
};
