import { Q, type SuppliedTeaching } from './supplied-content-types';

export const applicationsTeaching:Record<string,SuppliedTeaching> = {
  '8Z255dd78H4':{
    model:'Cable selection is a connected design process. Establish the load current, protective-device rating and installed cable capacity, then check voltage drop and fault protection. A cable can satisfy its current-carrying requirement and still fail a voltage-drop check.',
    ideas:[
      'For the video’s resistive 4.6 kW load at 230 V, design current is 20 A. Coordinate design current Ib, protective rating In and installed capacity Iz. Installation method, insulation and applicable correction factors affect Iz. Do not confuse tabulated capacity with the capacity in the actual route.',
      'In the source example, a 55 m run with an 11 mV/A/m coefficient at 20 A gives 12.1 V drop. That exceeds the example’s 11.5 V allowance even though a thermal-capacity choice may have appeared satisfactory. Length matters independently of the normal current check.',
      'Using the example’s 7.3 mV/A/m coefficient gives 8.03 V over the same route. Alternatively, the original coefficient reaches 11.5 V at about 52.3 m. A redesign must recheck the whole circuit: do not shorten a number on paper or increase cable size without checking the other conditions.',
    ],
    practice:'Prepare a circuit worksheet with load assumptions, installation method, correction factors, protective device, cable capacity, route length, voltage drop and fault checks. Each number should have an identified source rather than an unexplained table-page reference.',
    retrieval:{prompt:'A cable passes its installed current-capacity check. What additional effect can make a long route unacceptable?',answer:'Voltage drop can exceed the applicable design limit even at an acceptable load current.',why:'Thermal capacity and voltage at the load are separate constraints.',workingTex:'\\Delta U = \\frac{m\\,I_b\\,L}{1000}'},
    note:'The UK On-Site Guide edition, installation examples and 5% allowance are source-specific, not Kenyan requirements. Selecting the next breaker size above Ib is not an unconditional rule.',
    questions:[
      Q('In the video’s example, the coefficient is 11 mV/A/m, current is 20 A and length is 55 m. Against the stated 11.5 V allowance, what does the result show?','12.1 V: the example exceeds its voltage-drop allowance|1.21 V: the example has a large margin|11.5 V: the allowance fixes the actual drop|121 V: millivolts need no conversion','This places the decimal one position too far left.|An allowance is a limit, not the calculated circuit drop.|Convert millivolts to volts by dividing by 1000.','11 × 20 × 55 / 1000 = 12.1 V. Compare the calculated result with the stated allowance, not with the cable’s ampere rating.','How is a mV/A/m cable coefficient converted into voltage drop?','Multiply by design current and route length, then divide by 1000 to obtain volts.'),
      Q('The same 55 m example uses a larger cable with a 7.3 mV/A/m coefficient. What should the designer conclude?','The calculated drop becomes 8.03 V, but the other design checks still apply|The protective device may now be increased without checking the load|All fault and installation checks disappear once drop is below the allowance|The load current automatically falls from 20 A to 7.3 A','A cable change does not independently justify a protective-rating change.|Passing one criterion does not prove the entire design.|The coefficient is not a new load current.','7.3 × 20 × 55 / 1000 = 8.03 V. The voltage-drop calculation passes the example limit, but coordination and fault checks remain necessary.','Why is increasing cable size not the last line of a design worksheet?','The final circuit still needs verified protection, installation conditions, fault performance and other applicable checks.'),
      Q('An apprentice selects a cable from a free-air capacity table, but much of the route is surrounded by insulation. What needs correction?','Use the actual installation method and relevant capacity corrections|Keep the free-air value because conductor material is unchanged|Use the voltage-drop coefficient as its current rating|Treat the breaker rating as proof of cable capacity','The surroundings change heat dissipation despite unchanged material.|Voltage-drop coefficients and current capacity have different units and purposes.|A fitted breaker does not establish how much current the installed cable can carry.','Installed capacity depends on heat removal and route conditions. Select from the applicable method and corrections before checking Ib, In and Iz.','What distinguishes tabulated cable capacity from installed capacity Iz?','Installed capacity accounts for the actual installation method and applicable correction factors.'),
    ],
  },
  NIrKOVZrqnU:{
    model:'Power factor links useful real power to the apparent power drawn from the supply. Inductive loads require reactive power as well as real power. Parallel capacitors can offset some inductive reactive demand, reducing supply current without claiming that the useful mechanical work has disappeared.',
    ideas:[
      'For the sinusoidal single-phase model, apparent power S = VI, real power P = S cos(phi), and reactive power Q = S sin(phi). The power triangle gives S² = P² + Q². Motor shaft output is not electrical input: efficiency must be considered before using the nameplate’s mechanical power in an input-power calculation.',
      'Inductive reactive demand is lagging; capacitive reactive power has the opposite sign. A shunt capacitor reduces the reactive power supplied from upstream while the load still needs real power. Lower current can reduce cable losses and release capacity; it does not imply the same percentage reduction in useful-energy consumption.',
      'For target correction, Qc = P(tan(phi1) − tan(phi2)). For a single-phase capacitor at voltage V and frequency f, C = Qc/(2 pi f V²). Select a real product and recalculate the resulting power factor; connection, duty, harmonic conditions and ratings matter. Three-phase bank connections require their appropriate equations.',
    ],
    practice:'For a motor installation, distinguish shaft kW, input kW, kvar and kVA before estimating correction. Document voltage, frequency, existing power factor and target power factor, then check actual bank steps and operating conditions.',
    retrieval:{prompt:'Why does adding a parallel capacitor not remove the real power required to drive a loaded motor?',answer:'It offsets reactive exchange with the supply; useful mechanical output and motor losses still require real input power.',why:'Real and reactive power are different components, not two interchangeable descriptions of wasted energy.',workingTex:'Q_c=P(\\tan\\phi_1-\\tan\\phi_2)'},
    note:'The transcript has caption errors, including an angle that should be 90 degrees rather than 9. Do not calculate reactive power as S minus P, or apply a single-phase capacitance formula blindly to a three-phase bank.',
    questions:[
      Q('A sinusoidal load takes 10 kVA at 0.8 power factor. What real input power should enter the power triangle?','8 kW|10 kW|12.5 kW|2 kW','Apparent power equals real power only at unity power factor.|Dividing by power factor reverses the required relationship.|S minus P is neither the requested real power nor the correct reactive-power calculation.','P = S × power factor = 10 × 0.8 = 8 kW. In this case Q = 6 kvar, from the right triangle, not 2 kvar.','For an 8 kW, 10 kVA sinusoidal load, what is the reactive power?','6 kvar: the square root of 10² minus 8².'),
      Q('A motor continues driving the same load after shunt correction, but supply current falls. Which explanation is sound?','The capacitor supplies part of the reactive demand locally|The motor no longer needs real input power|The capacitor has raised the motor’s shaft output automatically|The reduced current proves the electricity bill falls by the same percentage','Useful output and losses still require real power.|Correction does not by itself command a higher mechanical output.|Billing and real-energy use are not proportional to current alone.','Reactive current supplied upstream can fall while useful real power remains. Distinguish capacity and loss benefits from claims about energy charges.','What is the primary electrical quantity a shunt PFC capacitor offsets?','Inductive reactive power demand seen by the upstream supply.'),
      Q('A calculated single-phase correction capacitor is replaced by the nearest available standard size. What should happen before approval?','Recalculate the achieved power factor and verify duty, voltage and frequency ratings|Assume every larger value is always better|Use the same capacitance unchanged for any three-phase connection|Ignore harmonics because the original formula used frequency','Excess correction can create an unsuitable leading condition.|Connection changes voltage across elements and the required calculation.|A fundamental-frequency formula is not a harmonic suitability assessment.','The calculation proposes a value; the selected product must be checked in the actual system. Avoid treating a theoretical capacitance as a finished panel design.','Why must capacitor-bank connection be stated in a sizing calculation?','The voltage across each capacitor and its reactive output depend on the connection.'),
    ],
  },
  XbL0R_9KLD4:{
    model:'A motor nameplate links a particular supply and connection to rated mechanical performance. Read voltage, star/delta connection, frequency, current and speed together rather than selecting one attractive number independently.',
    ideas:[
      'The rated kW is shaft output, while efficiency relates output to electrical input. Power factor relates real input to apparent input. A design calculation that treats output kW as input understates the electrical demand.',
      'Use the connection paired with the actual supply voltage and frequency. Rated current belongs to those conditions. For the demonstrated two-pole 50 Hz motor, 2935 r/min is below the 3000 r/min synchronous field speed: that difference is slip, not necessarily a defect.',
      'IP rating, insulation class, frame and mounting code answer different mechanical/environmental questions. Insulation class F is not permission for a 155°C ambient. Bearing and lubrication instructions belong to the exact motor. Service factor is conditional data, not unrestricted permission to overload.',
    ],
    practice:'Before connecting a replacement motor, compare the nameplate with the supply, terminal diagram, starter settings, driven load and mounting. Include maintenance data in the handover rather than recording only kW.',
    retrieval:{prompt:'A nameplate gives shaft output, efficiency and power factor. Which is used first to obtain real electrical input?',answer:'Divide shaft output by efficiency; use power factor separately when relating real input to apparent power/current.',why:'Efficiency and power factor describe different relationships.'},
    note:'Nameplate examples belong to the demonstrated machine. Do not generalise its voltage connection, bearing grease, current or service factor to another motor.',
    questions:[
      Q('A replacement motor is rated at 22 kW shaft output and 90% efficiency. Approximately what real electrical input is implied at that operating point?','24.4 kW|19.8 kW|22 kW exactly|2.2 kW','Multiplying output by efficiency calculates in the wrong direction.|Input must also cover losses when efficiency is below 100%.|The loss fraction is not the total input.','Input = output / efficiency = 22 / 0.90. Power factor is a separate quantity when calculating apparent power or current.','Why is motor output kW not the whole electrical input?','The electrical supply must provide mechanical output plus motor losses.'),
      Q('A 50 Hz, two-pole induction motor nameplate gives 2935 r/min. How should the speed be interpreted?','It runs below the 3000 r/min synchronous field speed because of slip|It proves the supply is necessarily below 50 Hz|It must be reconnected until the shaft runs exactly at 3000 r/min under load|It indicates an insulation-class temperature','Slip explains the difference without proving a frequency fault.|Loaded induction operation needs slip; exact synchronism is not the target correction.|Speed and insulation thermal classification are unrelated markings.','The rotating field’s speed is set by frequency and pole count. The induction rotor follows slightly slower under load.','What is slip comparing?','The difference between synchronous rotating-field speed and rotor speed, often expressed as a fraction of synchronous speed.'),
      Q('A motor carries an insulation-class F marking. What should the installer avoid inferring from that alone?','That the motor is approved for a 155°C ambient|That the nameplate contains thermal information|That the manufacturer has specified an insulation system|That temperature limits matter in application','The marking does convey thermal-class information.|It does identify the insulation system’s thermal class.|Temperature limits remain important; that is not the mistaken inference.','An insulation thermal class is not the permitted ambient temperature. Use the motor’s actual operating and environmental ratings.','Why must IP rating and mounting code be read separately?','IP describes enclosure ingress protection; the mounting code describes the mechanical arrangement.'),
    ],
  },
  HFkTPmY7N7w:{
    model:'A direct-on-line starter connects the motor to full supply voltage through a contactor. The control circuit operates the coil; the power contacts carry motor current. An overload relay can interrupt the coil circuit so the contactor releases, but the contactor alone is not overload protection.',
    ideas:[
      'Energising the coil produces magnetic force that closes the contactor. Removing coil power lets the return spring open it. The specified coil voltage may differ from the motor supply, so identify both circuits before wiring.',
      'DOL starting does not intentionally reduce starting voltage. A motor can draw substantial inrush while accelerating. Suitability depends on the supply, motor and driven load—not a universal kW cut-off.',
      'The overload relay monitors motor loading and its control contact releases the contactor when it operates. Choose the appropriate relay range, setting and trip class from motor and manufacturer data. Short-circuit protection remains a separate coordinated function.',
    ],
    practice:'Trace a starter drawing in two passes: supply through protective devices and main contacts to the motor; then control supply through stop/start, holding contacts and overload contact to the coil. Identify what opens when each protective function operates.',
    retrieval:{prompt:'Why can a small overload-relay control contact stop a motor carrying a much larger current?',answer:'It opens the contactor coil circuit; the contactor’s main poles then interrupt the motor supply.',why:'Control and power circuits have different duties.'},
    note:'Do not adopt “just above full-load current” as a universal overload setting or a fixed motor-kW limit for DOL. Follow the exact starter/motor specification and site design.',
    questions:[
      Q('A DOL starter’s overload contact opens in the coil circuit. What normally stops power reaching the motor?','The contactor releases and its main contacts open|The small overload contact carries and interrupts every motor phase directly|The motor voltage becomes equal to the coil voltage|The main fuse rating automatically decreases','The control contact commands the contactor; it is not the main power path described.|The two voltage ratings do not merge when the coil opens.|A relay operation does not change a fuse’s rating.','Opening the coil circuit removes the force holding the main contacts closed. Distinguish the initiating protective signal from the device interrupting load current.','What is the contactor’s role in a DOL starter?','Electrically controlled switching of the motor power circuit.'),
      Q('A contactor for a 400 V motor has a 24 V coil. Which supply belongs at its coil terminals?','The specified 24 V control supply|The 400 V motor supply because the contactor switches it|Any voltage below the motor’s starting current number|The neutral conductor alone without a control supply','Main-pole voltage and coil voltage are different specifications.|Current is not a voltage-selection criterion.|A coil requires its specified complete control circuit.','A contactor can switch a high-voltage power circuit while its coil operates from a lower-voltage control circuit. Follow the coil label and drawing.','Which two electrical ratings must not be confused when selecting a contactor?','Main-contact load/voltage duty and coil operating voltage.'),
      Q('A pump started DOL causes an unacceptable supply dip. What design fact should be reviewed?','Full-voltage starting current and its effect on the supply and load|Whether DOL automatically ramps voltage slowly|Whether the contactor is itself a variable-frequency drive|Whether every motor below one fixed kW limit is exempt from inrush','DOL applies full voltage rather than providing an intentional ramp.|A contactor is a switch, not a frequency converter.|A blanket size rule does not replace the actual system assessment.','Review starting duty, acceleration and supply strength before choosing an alternative starter. The presence of a contactor does not reduce inrush by itself.','Does a DOL starter intentionally reduce motor starting voltage?','No. It connects the motor directly to the full supply voltage.'),
    ],
  },
  wQwGZMcDGXk:{
    model:'A motor-protection circuit breaker combines protective functions suited to a motor circuit, within the capabilities of the particular product. Its adjustable current range is used with the motor specification; it is not a dial for making faults disappear.',
    ideas:[
      'The demonstrated adjustable range, 4–6.3 A, allows matching a specified motor duty within that range. A device set too high can fail to provide the intended overload protection. Do not choose solely by enclosure size.',
      'Short-circuit and sustained-overload responses serve different hazards. Phase-loss sensitivity may be provided, but the exact mechanism and limitations must be verified. Do not assume every MPCB detects every supply-voltage problem.',
      'Auxiliary contacts can report device state through NO/NC control contacts. A mechanical test verifies a mechanism action, not the complete current-time calibration. A starter still needs a defined control and switching arrangement.',
    ],
    practice:'For a motor replacement, compare rated current and duty with the MPCB range and manufacturer settings. Check coordinated contactor and short-circuit data, and verify any required phase-loss or imbalance protection explicitly.',
    retrieval:{prompt:'What must be checked before relying on an MPCB for phase-loss protection?',answer:'The exact product’s documented protective functions and limitations, and whether they satisfy the motor application.',why:'A family name does not guarantee every type of fault detection.'},
    note:'The source’s phase-failure claims are product-dependent. Do not assume a generic MPCB provides comprehensive phase-voltage monitoring or that its test button proves calibrated protection.',
    questions:[
      Q('A motor’s specified setting is 5.2 A and the selected MPCB range is 4–6.3 A. What is the appropriate use of the range?','Set it according to the motor and device instructions, not automatically at 6.3 A|Always select 6.3 A to minimise trips|Treat 4–6.3 A as the control-coil voltage|Assume any motor current is acceptable because the device is adjustable','The highest setting can undermine the intended overload protection.|The range is current, not coil voltage.|Adjustment remains bounded by the device and motor specification.','An adjustable range permits correct matching; it does not justify maximising the setting. Confirm the required setting and the application conditions.','What should determine a motor-protection current setting?','Motor rating/duty and the protection manufacturer’s instructions, within the device’s valid range.'),
      Q('A technician operates an MPCB’s mechanical test and sees it open. What remains unproven by that action alone?','Its complete protective current-time performance|That the mechanism moved during the test|That the handle can indicate an operated state|That the technician used the mechanical test','Movement was directly observed.|The observed indication can be recorded without claiming full calibration.|That action is known; the missing evidence concerns protective performance.','A mechanical test and a calibrated protective-response test answer different questions. Do not convert an observed mechanical action into a complete commissioning claim.','What does an MPCB auxiliary contact usually serve?','A separate status or control circuit, within the contact’s rating.'),
      Q('A pump must be protected against harmful supply imbalance. Is the label “MPCB” enough to confirm this requirement is met?','No; verify the particular protection’s documented capabilities|Yes; every MPCB measures all three phase voltages|Yes; a current-range dial measures voltage balance|No; motor circuits can never be protected against imbalance','The label does not guarantee universal voltage monitoring.|A current adjustment is not a three-phase voltage measurement.|Appropriate motor/phase protection can be specified.','Select functions against the fault requirement. Some motor devices respond to phase loss through current behaviour; a particular application may require additional monitoring.','Why map motor protection by hazard rather than product acronym alone?','It reveals whether short circuit, overload, phase problems and switching duties are actually covered.'),
    ],
  },
  At7AnMV7Xd0:{
    model:'A radial circuit begins at its protective device and extends to its final outlets without returning as a ring to the origin. It can branch. The outlets remain electrically parallel: “radial” describes wiring topology, not appliances connected in series.',
    ideas:[
      'Trace line, neutral and circuit protective conductor together from the board to the outlets. A branch does not automatically turn a radial into a ring. The load current is shared between branches according to what is connected, while common upstream sections carry their combined current.',
      'Each accessory must accept the conductor arrangement in its rated terminals. Connection capacity, conductor size and mechanical condition come from the product specification, not a universal maximum number of wires.',
      'Opening one protective switch does not establish safe isolation. For an RCBO circuit, line and neutral must follow the intended protected path; mixed neutrals can cause incorrect operation and hazards. Verify the whole circuit rather than inferring correctness from working sockets.',
    ],
    practice:'Before adding an outlet, sketch the existing route and identify the supplying device, cable sizes, installation conditions and terminal capacities. Confirm the circuit topology and design capacity before installation, then complete the appropriate inspection and tests.',
    retrieval:{prompt:'Why does a branched radial still have outlets at the same supply voltage rather than dividing voltage between appliances?',answer:'The outlets are connected across line and neutral in parallel; branching the cable route does not put appliances in series.',why:'Physical route and electrical load connection are different descriptions.'},
    note:'John Ward’s UK sizes and protective arrangements are examples, not Kenyan design rules. Follow current local requirements and exact accessory ratings.',
    questions:[
      Q('A socket circuit leaves the board, splits into two branches and neither branch returns to the origin. What topology is shown?','A branched radial|A ring final circuit|Appliances connected in series|Two supplies operating in parallel','A ring requires a return path to the same origin.|Branching wiring does not put the socket loads in series.|Two branches from one circuit are not two independent supplies.','The presence or absence of a return path defines the distinction here. Outlets on the radial are still parallel loads.','Does adding a branch automatically make a radial into a ring?','No. A ring returns to its origin; a radial may branch without that return.'),
      Q('Two branch loads draw 4 A and 6 A simultaneously on the same single-phase radial. What current does their common upstream section carry, neglecting other loads?','10 A|6 A only|4 A only|2 A','The common section supplies both branches, not only the larger one.|The common section also supplies the second branch.|The branch currents add rather than subtract in this stated load arrangement.','The common conductor carries the combined load current before it divides. This is why adding outlets requires assessment of upstream capacity.','Which part of a branched radial carries the combined branch load?','The common upstream section before the branches divide.'),
      Q('An extra socket would require another conductor in an existing terminal. What must be checked before accepting the connection?','The accessory’s permitted conductor combination and terminal capacity|A universal rule that every socket accepts three conductors|Only whether the faceplate can still close|Whether the new socket works briefly when energised','Terminal ratings differ by product and conductor combination.|Closing the faceplate does not establish a sound electrical connection.|Temporary operation is not evidence of correct termination or design.','Use the actual manufacturer limits for number, size and type of conductors, together with sound installation and verification.','Why is a working socket not proof of correct circuit construction?','It does not establish protective-conductor continuity, polarity, capacity or sound terminations.'),
    ],
  },
  hZN6hiGLtrE:{
    model:'A ring final circuit returns its line, neutral and protective conductor to the same origin. Its two paths can share current, but not necessarily equally. Continuity of the intended ring is therefore a design and verification concern, not something established because the sockets work.',
    ideas:[
      'Current division depends on the resistances of the two paths and where loads are connected. Near one end, the shorter path can carry more current. Do not assume each leg carries exactly half of every load.',
      'A broken ring can leave outlets energised through the remaining route. That apparent operation can hide a loss of the assumptions supporting the circuit design. Verify line, neutral and protective-conductor continuity with the appropriate safe test method.',
      'A spur is a branch from the ring, not a continuation completing the ring. Extending a ring, adding a spur and supplying a separate circuit are different alterations. Load distribution, cable conditions and accessory ratings must be considered; outlet count alone does not prove capacity.',
    ],
    practice:'Before altering a supposed ring, establish its topology and existing test evidence. After work, inspect and perform the appropriate end-to-end and cross-connection checks under safe conditions. Investigate unexpected readings rather than assuming a powered outlet confirms the return path.',
    retrieval:{prompt:'Why can an open ring be more difficult to notice than a completely open radial?',answer:'The other route can still supply outlets, masking the break while changing the circuit’s current-sharing assumptions.',why:'Loss of intended topology does not always produce immediate loss of supply.'},
    note:'UK ring-final cable sizes, floor-area guidance and protective ratings are jurisdiction-specific examples. The instructor’s preferences about topology are opinions, not universal requirements.',
    questions:[
      Q('All sockets work, but continuity testing identifies a break in one ring conductor. Which conclusion is justified?','Supply continuity does not prove that the intended ring is intact|The test must be wrong because every socket works|The remaining route proves the original design is unchanged|The break automatically creates a second protective conductor','A remaining route can conceal a break.|The break changes current paths and can invalidate the design assumptions.|A break removes continuity; it does not create an extra conductor.','The ring can keep supplying loads through one path. Investigate and rectify the fault, then verify the intended circuit rather than relying on operation alone.','What can mask an open ring during ordinary use?','The unbroken route may still energise the outlets.'),
      Q('A large load is connected close to one end of a ring. Must each leg carry exactly half its current?','No; current division depends on the resistance of each path|Yes; the ring name guarantees equal sharing|Yes; outlet position has no effect on route resistance|No; one leg always carries all current even with an intact ring','Topology alone does not guarantee equal path resistance.|Different path lengths and connections affect resistance.|An intact ring can share current through both paths, though unequally.','The two routes act as parallel paths with their actual resistances. Equal sharing is a special case, not a safe universal assumption.','What determines how an intact ring shares a particular load current?','The resistances of the two routes from the supply to that load.'),
      Q('A single cable leaves an existing ring socket to feed an additional outlet and does not return. How should that addition be described?','A spur requiring its own suitability assessment|A complete new ring because it starts at a ring socket|Proof that the existing protective rating may be increased|A series connection of the two appliances','Starting from a ring does not provide a return path.|The addition does not independently justify a rating increase.|Socket loads remain parallel, not series.','Describe the actual topology before applying design rules. A spur and an extension of both legs of a ring are not the same alteration.','Which conductors require verification of the intended ring continuity?','Line, neutral and the circuit protective conductor, using the appropriate safe verification method.'),
    ],
  },
  _tGyaE78WTA:{
    model:'A soft starter controls the voltage applied while a motor starts, reducing starting stress where suitable for the load. It fills the gap between direct switching and a variable-frequency drive, but it is not normally a running-speed controller.',
    ideas:[
      'Controlled semiconductor devices (SCRs/thyristors) progressively apply voltage. This can reduce starting current and mechanical shock compared with abrupt full-voltage starting. The motor must still develop enough torque to accelerate its particular load.',
      'After acceleration, a bypass arrangement can carry the normal running current instead of continuous semiconductor conduction, reducing losses. This does not create a separate variable-speed operating mode.',
      'Soft stopping can moderate deceleration effects such as water hammer in a suitable pump system. It is not an emergency brake. A VFD controls voltage and frequency for speed control; choose by the process requirement, not by assuming all electronic starters do the same job.',
    ],
    practice:'For a conveyor or pump, separate the requirement for gentler starting from the requirement for adjustable running speed. Check load torque, starting frequency, supply conditions, bypass arrangement and protective coordination with the manufacturer.',
    retrieval:{prompt:'A process needs a motor to run at several commanded speeds throughout the day. Why is a conventional soft starter not the direct solution?',answer:'It manages starting/stopping voltage rather than providing normal running frequency-based speed control; assess a suitable drive instead.',why:'Starting stress and continuous speed regulation are different requirements.'},
    note:'Soft stop is not safety-rated emergency stopping or a mechanical brake. Actual torque, starting duty and protection requirements are product- and load-specific.',
    questions:[
      Q('A pump should reach normal speed with less starting shock, but does not need variable running speed. Which feature explains the soft-starter option?','A controlled voltage ramp during starting|Continuous adjustment of running frequency as its basic function|Removal of every motor protective device|An instant reverse torque pulse on every start','Frequency-based running-speed control describes a drive, not the basic soft-start function.|Starting control does not eliminate protective requirements.|Reversing torque is not the voltage-ramp principle described.','A soft starter moderates application of voltage during acceleration. Confirm that reduced starting torque can still accelerate the load.','Which semiconductor devices are described in soft starting?','SCRs (thyristors), controlling the applied voltage during the ramp.'),
      Q('A bypass contactor closes after a soft-started motor reaches running conditions. What is its purpose?','Carry running current around the semiconductor path to reduce losses|Turn the starter into a VFD|Disconnect all motor power while the pump keeps running normally|Make overload protection unnecessary','Bypass does not introduce frequency conversion.|A normal bypass provides another conduction path, not complete disconnection.|Running operation still needs appropriate protection.','The bypass reduces the continuous losses associated with the semiconductor path. It does not change the basic distinction between starter and variable-speed drive.','Does bypass operation provide variable running speed?','No. It provides a normal running current path after starting.'),
      Q('A client requests soft stopping to reduce pump water hammer. What limitation should the designer explain?','It must suit the hydraulic system and is not an emergency brake|It guarantees immediate mechanical standstill|It works identically for every driven load|It replaces safe isolation during maintenance','A soft stop is a controlled process transition, not guaranteed instant stopping.|Load behaviour and product capability determine the outcome.|Control functions do not establish safe electrical isolation.','Soft stopping can improve a suitable process but must not be confused with safety stopping or maintenance isolation.','What distinction matters between soft stop and emergency braking?','Soft stop moderates an operating transition; it is not inherently a safety-rated or immediate braking function.'),
    ],
  },
  igi8F6UAvh0:{
    model:'Phase sequence describes the order of the three alternating phases. That order determines the direction of the rotating magnetic field for a given motor connection. A phase-rotation meter provides evidence of sequence at its connected points; it does not prove that equipment is isolated.',
    ideas:[
      'The practical demonstration checks sequence after supply work, before relying on motor direction. Connect the meter leads to their identified reference phases according to its instructions. A clockwise or counter-clockwise indication has meaning only with that lead arrangement recorded.',
      'Changing any two phase connections reverses sequence. Any corrective wiring requires safe isolation, proving dead and the appropriate controlled work procedure—not swapping live leads or conductors while investigating.',
      'Meter selection includes the instrument and leads’ voltage and measurement-category ratings, condition and permitted environment. A maximum voltage marking alone is not the whole safety specification. Live measurements require competence and appropriate controls; a phase meter is not a substitute for an approved safe-isolation process.',
    ],
    practice:'During pump commissioning, compare supply sequence and the driven equipment’s required direction under a controlled plan. Record where and how sequence was measured. After any isolated correction, repeat the appropriate verification before return to service.',
    retrieval:{prompt:'Why must the lead-to-phase relationship be recorded with a rotation-meter reading?',answer:'The indicated direction refers to that ordering of the connected leads; interchanging two leads reverses the indicated sequence.',why:'A direction symbol without the connection reference is incomplete evidence.'},
    note:'Observe the demonstration as controlled live testing, not permission for unsupervised work. Use the Fluke 9040 manual for the exact instrument; sequence indication does not establish absence of voltage.',
    questions:[
      Q('After transformer work, a pump may rotate the wrong way. Which measurement addresses the supply-order question before the planned functional check?','Phase sequence at the relevant supply points|Insulation resistance as a substitute for phase order|Only the resistance of the protective conductor|Only the circuit’s normal load current','Insulation resistance assesses insulation, not sequence.|Protective-conductor resistance does not identify phase order.|Current magnitude alone does not reveal the cyclic order.','Sequence is a separate three-phase property. The demonstration shows why supply work can require it to be reverified before assuming motor direction.','What physical motor effect is associated with reversed phase sequence?','The rotating field, and hence the direction for the same motor connection, reverses.'),
      Q('A sequence correction requires exchanging two phase conductors. What must precede that wiring change?','Safe isolation and proving dead under the controlled work procedure|Keeping the supply live so the meter can show the change immediately|Removing only the neutral conductor|Holding the contactor closed by hand','A live indication does not justify live conductor alteration.|Removing neutral does not isolate phase conductors.|Forcing a contactor is neither isolation nor a safe correction method.','Although the concept is “exchange two phases,” physical alteration must be done safely isolated. Reverification follows the completed change.','How many phases are interchanged to reverse a three-phase sequence?','Any two—only as part of a properly isolated and controlled wiring change.'),
      Q('A phase meter has a suitable maximum voltage marking. What else is needed before its use at a distribution board?','Suitable measurement-category ratings, leads, condition and a controlled test method|Only confirmation that the display lights up|Only a match between lead colour and the board paint|No further checks because maximum voltage covers every transient environment','A working display does not prove measurement safety.|Cosmetic similarity is not a safety specification.|Voltage rating alone does not describe transient-category suitability.','Match both the instrument and its leads to the measurement environment and manufacturer instructions. Competence and safe access remain necessary.','Can a phase-sequence indication serve as proof that a circuit is dead?','No. Phase-sequence measurement and proving dead are different tasks and require their appropriate methods.'),
    ],
  },
};
