import { Q, type SuppliedTeaching } from './supplied-content-types';

export const protectionTeaching:Record<string,SuppliedTeaching> = {
  '8VhgQ9Q9ixA':{
    model:'Choose protection by the condition it detects, not by the similarity of device names. Overcurrent, residual current and transient overvoltage are different phenomena. Trace each protective function from the fault it senses to the circuit it disconnects.',
    ideas:[
      'MCBs and MCCBs provide overcurrent protection according to their ratings and trip characteristics. An isolating device provides a means of separation when suitably rated; a switch handle alone does not prove automatic fault protection or safe isolation.',
      'RCD is the umbrella term for residual-current devices. An RCCB responds to residual current but has no integral overcurrent protection; an RCBO combines residual-current and overcurrent functions. Coordinate an RCCB with suitable overcurrent protection rather than treating it as an RCBO.',
      'A motor-protection circuit breaker has motor-oriented protective features that depend on its specification. Historical voltage-operated ELCBs differ from modern current-operated RCDs. Read the product standard, wiring diagram and manufacturer data: acronyms are a starting point, not a complete specification.',
    ],
    practice:'When reviewing a small distribution board, label the isolator, each overcurrent function and each residual-current function on the single-line diagram. Check their protected boundaries and compatibility before deciding that a circuit is adequately protected.',
    retrieval:{prompt:'Why is “an RCD is fitted” an incomplete description of a final circuit’s protection?',answer:'It does not identify whether overcurrent protection is included, the residual-current type and rating, or which conductors and part of the circuit are protected.',why:'The name of one function does not describe the whole protective arrangement.'},
    note:'Correction: an RCD does not prevent every shock or make touching live parts safe. Do not treat the video’s current limits for device families as universal product limits.',
    questions:[
      Q('A board schedule lists an RCCB supplying several final circuits. What must the designer still establish?','Suitable overcurrent protection for the RCCB and outgoing circuits|That the RCCB current rating is also its earth-leakage setting|That no MCBs are needed because residual current includes overload|That an isolator will trip automatically for every short circuit','Rated load current and residual operating current describe different properties.|Balanced overload can occur without residual current.|An isolator is not automatically an overcurrent protective device.','An RCCB detects imbalance but does not incorporate the overcurrent function of an RCBO. The complete arrangement must provide both where required.','Which protective function is absent from an RCCB but included in an RCBO?','Integral overcurrent protection; an RCBO combines it with residual-current protection.'),
      Q('An installer wants one final-circuit device combining overload, short-circuit and residual-current protection. Which device category matches that description?','RCBO|RCCB alone|Switch-disconnector alone|Voltage-operated ELCB alone','An RCCB does not include overcurrent protection.|A switch-disconnector provides switching/isolation, not those automatic fault responses.|The historical earth-leakage device is not the combined modern function described.','The RCBO combines the two protection families; its actual ratings, residual-current type and compatibility still need checking.','What does combining functions in an RCBO not remove from design?','The need to verify current rating, breaking capacity, residual-current type, wiring and coordination.'),
      Q('A replacement device has a familiar acronym but no matching technical data. Which evidence should decide whether it can replace the original?','Its specified protective functions, ratings, standard and manufacturer compatibility|The fact that its enclosure fits the same space|The fact that both device names contain “CB”|The colour and direction of its handle','Physical fit does not establish electrical compatibility.|Similar acronyms do not prove identical protection.|Handle appearance is not a protective specification.','Replacement is an engineering decision about functions and ratings, not appearance. The circuit diagram helps locate what each device actually protects.','Why should protection be marked by function on a board drawing?','It shows which device responds to each fault and exposes gaps hidden by abbreviated device names.'),
    ],
  },
  kx35WN3uLis:{
    model:'A fuse is a calibrated protective component, not simply a thin wire that fits a holder. Its current rating, time-current characteristic, voltage rating and breaking capacity describe different requirements. A suitable replacement must satisfy the equipment specification and the available fault conditions.',
    ideas:[
      'Rated current is not an exact instantaneous melting threshold. A time-delay fuse may tolerate legitimate starting inrush that a fast fuse cannot. Repeated operation calls for fault investigation and verification of the specified characteristic—not a larger fuse or a bypass.',
      'Breaking capacity describes interruption of fault current under specified conditions. High-rupturing-capacity designs use construction such as arc-quenching filler. An automotive voltage rating is not suitable for a mains circuit merely because the ampere rating matches. Appearance alone cannot establish breaking capacity or authenticity.',
      'Fast, time-delay and semiconductor fuses serve different duties. A resettable PTC limits current by increasing resistance and may still pass current: it is not an isolator. The high-voltage demonstration illustrates specialist arc management, not a procedure to repeat on site.',
    ],
    practice:'For a failed equipment fuse, isolate safely, investigate why it operated and obtain the exact specified replacement. Record the current, voltage, characteristic, dimensions and interruption rating; never fit foil, wire or an unverified substitute to restore service.',
    retrieval:{prompt:'Two fuses have the same ampere rating. Why might only one be suitable for a mains appliance?',answer:'Their voltage ratings, time-current characteristics and breaking capacities may differ, even if the physical size matches.',why:'Carrying normal current and safely interrupting a fault are separate duties.'},
    note:'Do not copy temporary wrong-rating replacements or destructive inspection from demonstrations. Use the manufacturer specification; a ceramic body alone is not proof of an HRC fuse.',
    questions:[
      Q('An appliance requires a time-delay fuse. A fast fuse of the same current rating repeatedly opens at switch-on. What should the technician investigate first?','The specified fuse characteristic and whether starting current or a fault explains operation|Whether doubling the current rating stops the inconvenience|Whether a short wire can carry the starting current|Whether a lower voltage rating makes the fuse more tolerant','Upsizing can defeat protection instead of correcting the cause.|A wire bypass removes the calibrated protective function.|Voltage rating concerns safe interruption, not a solution to starting inrush.','Check both the actual appliance condition and the intended time-current response. A correct time-delay replacement is justified by specification, not by trial and error.','What does a time-delay fuse accommodate that a fast fuse may not?','A permitted short starting-current surge, within its specified time-current characteristic.'),
      Q('A 32 V automotive fuse matches the ampere rating of a failed 230 V equipment fuse. Why is that not a suitable basis for substitution?','It may not safely interrupt an arc at the equipment voltage|Its current rating automatically becomes zero above 32 V|It must always open before any mains current flows|A matching holder converts its voltage rating to 230 V','A rating is a suitability limit, not an automatic zero-current mechanism.|The fuse may carry current yet fail dangerously when required to interrupt.|The holder cannot upgrade the fuse’s interruption capability.','The fuse must extinguish the arc under the specified voltage and fault current. A matching ampere rating does not prove this capability.','What additional fault-related rating matters alongside fuse voltage and current?','Breaking capacity: the fault current the fuse can interrupt under its specified conditions.'),
      Q('A resettable PTC has tripped and the equipment appears off. What should a maintenance worker conclude?','Current may be limited, but safe isolation has not been established|The PTC has created the same separation as a locked isolator|All stored energy has necessarily discharged|Touching internal parts is safe while the supply remains connected','High resistance is not verified electrical separation.|A protective response does not prove discharge of capacitors or other stored energy.|Apparent inactivity is not proof of a dead circuit.','A PTC changes resistance; it does not provide the isolation needed before access. Use the equipment’s safe-isolation and stored-energy procedure.','Why is a resettable current limiter not an isolator?','It can remain electrically connected and pass residual current despite limiting the load.'),
    ],
  },
  gqEu9t8HwW0:{
    model:'A thermal-magnetic MCB has two responses: a thermal element responds to sustained overload and a magnetic mechanism responds rapidly to sufficiently high overcurrent. Neither response makes a normal circuit breaker a personal shock detector.',
    ideas:[
      'The bimetal element heats and bends over time, releasing the mechanism during overload. Greater overcurrent generally shortens operating time. Cable heating rises with current squared for unchanged resistance, so moderate overload is still important even when it does not cause an immediate trip.',
      'A solenoid releases the latch rapidly at the magnetic operating range. Contacts separate and the arc is managed by the arc chute. The trip-free mechanism allows protective opening even if someone holds the handle in the on position.',
      'Read a time-current band rather than assuming operation at one exact current and time. Starting inrush and prospective fault current must be considered together when selecting a characteristic. Do not upsize a breaker simply to stop trips; first establish load, cable capacity and the cause.',
    ],
    practice:'If a motor circuit trips at starting, compare measured or specified inrush with the correct manufacturer curve and check the protective design. If a cable overheats, do not take the absence of an immediate trip as evidence that the loading is acceptable.',
    retrieval:{prompt:'Why can a modest overload take longer to trip than a short circuit?',answer:'The thermal mechanism needs heating time, whereas sufficiently high fault current operates the magnetic mechanism rapidly.',why:'The two mechanisms deliberately respond to different current-time conditions.'},
    note:'The video title concerns direct shock protection. Overcurrent devices can still contribute to automatic disconnection for earth faults in a correctly designed earthing/protection system. A rated-current marking is not an instantaneous trip threshold.',
    questions:[
      Q('A workshop circuit carries a sustained overload but its MCB does not open instantly. Which mechanism explains the intended delayed response?','Heating and bending of the bimetal element|The handle waiting for a person to release it|Residual-current cancellation in a sensing toroid|The arc chute measuring the room temperature','A trip-free mechanism does not depend on releasing the handle.|Residual-current sensing describes an RCD, not this overload response.|The arc chute manages interruption; it is not the thermal sensor described.','The bimetal’s heating response gives inverse-time overload protection. The exact time must be read from the specified characteristic.','Which MCB element responds to sustained overload?','The thermal bimetal element; heating causes it to release the trip mechanism.'),
      Q('A fault produces enough current to enter an MCB’s magnetic operating range. What causes rapid release?','The solenoid acts on the trip mechanism|The cable insulation has to melt first|The neutral conductor must leak current to earth|The user must move the handle halfway off','Protection must not depend on insulation destruction.|A line-neutral short circuit can operate overcurrent protection without earth leakage.|Automatic tripping does not require a user operation.','High current energises the magnetic mechanism sufficiently to release the latch. This is different from waiting for the thermal element.','What is the purpose of the arc chute after breaker contacts separate?','It helps manage and extinguish the arc during interruption; it does not detect the original overload.'),
      Q('Someone holds an MCB handle on while a trip condition exists. What feature is intended to prevent that from defeating protective opening?','A trip-free mechanism|A larger handle current rating|A second neutral label|A higher room-temperature setting','Handle size is not the protective release principle.|Terminal labels do not provide mechanical release.|Changing temperature assumptions does not provide trip-free operation.','The internal mechanism can open under a trip condition independently of someone holding the operating handle. Never use this as a reason to force repeated reclosing into a fault.','Does holding a breaker on provide a legitimate way to keep a faulty circuit running?','No. A trip-free mechanism is designed to open anyway; investigate the fault before restoration.'),
    ],
  },
  Me_adh09CdY:{
    model:'A marking such as C10 combines a characteristic letter with a rated current. The letter concerns the operating curve; 10 A is not the breaking capacity and does not mean an immediate trip at any current just above ten amperes.',
    ideas:[
      'For common MCB characteristics, the magnetic bands are typically B: 3–5 times rated current, C: 5–10 times and D: 10–20 times. These are bands, not promises of one exact trip point. Confirm the applicable standard and manufacturer curve.',
      'K and Z characteristics are product-specific choices and must be read from the actual data. A higher magnetic threshold can tolerate inrush, but it also changes the fault current needed for rapid disconnection. Load suitability and fault-loop performance must both be checked.',
      'Keep the markings separate: rated current, curve, voltage, short-circuit breaking capacity and any energy-limiting class. An energy-limiting class number is not a time in seconds. Select and document the entire specification, not just the letter.',
    ],
    practice:'For a proposed B-to-C replacement on a motor circuit, ask why the existing device operates, whether the cable remains protected and whether minimum fault current still achieves the required disconnection. Do not use a curve change as an unexamined nuisance-trip fix.',
    retrieval:{prompt:'What two independent meanings are contained in C10?',answer:'C identifies the time-current characteristic; 10 A identifies rated current. Breaking capacity is a separate marking.',why:'Separating the markings avoids confusing normal load duty with fault interruption.'},
    note:'The video’s K/Z ranges and trip-time examples must not be universalised. Use exact manufacturer data; the number “3” on an energy-limiting-class marking does not mean three seconds.',
    questions:[
      Q('A typical C10 MCB is being considered for a control circuit. Which current range corresponds to the usual C magnetic band?','50–100 A|5–10 A|10–20 A|100–200 A','That treats the multiplier as an absolute current.|That is only one to two times this rated current.|That corresponds to the typical D band for a 10 A device.','Multiply rated current by the typical C band of five to ten. This identifies a magnetic range; suitability still depends on the actual device and circuit.','For a typical B16 MCB, how is its magnetic band estimated?','Multiply 16 A by 3 and by 5: approximately 48–80 A, subject to the specified characteristic.'),
      Q('A replacement MCB is marked C16 and 6 kA. Which statement reads the markings correctly?','16 A is rated current; 6 kA is short-circuit breaking capacity|6 kA is the continuous load current|C means it trips whenever current reaches 6 kA|16 A is the maximum earth-leakage current','Breaking capacity is a fault-interruption rating, not normal load duty.|The C characteristic is expressed relative to rated current, not the breaking-capacity marking.|This is an overcurrent marking, not residual-current sensitivity.','Rated current and interruption capacity answer different design questions: normal circuit duty and the fault current the device can safely interrupt.','Why must the kA marking be checked even when the ampere rating is correct?','Available fault current may exceed the device’s interruption capacity.'),
      Q('A circuit’s B-curve breaker is proposed to become D-curve solely to tolerate starting. What additional concern must be assessed?','Whether available fault current still produces the required disconnection|Whether the D letter reduces the cable’s resistance|Whether the new letter automatically provides RCD protection|Whether every D device has the same settings as every B device','A characteristic change does not alter conductor resistance.|An MCB curve change does not add residual-current sensing.|The point of different curves is different operating behaviour.','A higher instantaneous threshold may tolerate inrush while making rapid fault disconnection harder to achieve. Check the complete design and manufacturer data.','Why are inrush tolerance and fault clearance considered together?','A curve that tolerates a larger starting surge also requires sufficient fault current for its fast operating region.'),
    ],
  },
  'TUno2IT-KZY':{
    model:'An RCD compares the currents in the live conductors passing through its sensing core. When their vector sum is not zero, some current is returning by another path. That imbalance can operate the device, but it is not a universal detector of every electric shock.',
    ideas:[
      'In a healthy single-phase load, line and neutral currents balance. Leakage returning outside the monitored conductors produces residual current. A person connected between line and neutral can carry a dangerous balanced current that does not provide the residual signal expected by the RCD.',
      'Type AC, A, F and B refer to residual-current waveforms the device is designed to detect. Electronic equipment can create pulsating or smooth DC and mixed frequencies. Select the required type from equipment instructions and the installation requirements; these letters are unrelated to an MCB’s B/C/D trip curve.',
      'An RCCB needs coordinated overcurrent protection; an RCBO combines functions. The test button checks an internal operating path, not the complete installation. Instrument tests must use the correct device type and settings: trip-time tests measure time, while ramp tests investigate operating-current threshold.',
    ],
    practice:'For a new electronic load, identify the expected residual waveform and the required protective arrangement before choosing an RCD. During verification, record the device type, rated residual current, test configuration and results rather than recording only “button works”.',
    retrieval:{prompt:'Why can an RCD remain closed during a dangerous line-to-neutral contact?',answer:'If the current leaving through line returns through the monitored neutral, it may remain balanced at the sensing core despite passing through a person.',why:'Residual-current protection responds to imbalance, not directly to whether current is flowing through a body.'},
    note:'Never test protection by touching live conductors. RCDs reduce some risks but do not make contact safe or protect wiring upstream of them. Source-era UK test limits are not automatic Kenyan acceptance criteria.',
    questions:[
      Q('An apprentice says an RCCB makes touching line and neutral safe because it detects any current through a person. Which explanation corrects this?','Balanced line-to-neutral current may not create a residual signal|The RCCB detects a person only above its load-current rating|An RCCB always measures body resistance before switching|Earth conductors carry every possible shock current','Load-current rating is not a body-current detector.|The device compares conductor currents; it does not identify a person.|A shock path can be between line and neutral without earth being the return.','Current balance, not the identity of the load, drives residual sensing. Safe isolation and avoidance of live contact remain essential.','Which boundary limits an RCD’s protection upstream?','Current paths before its monitored and switched circuit are outside that device’s downstream protective boundary.'),
      Q('A machine’s manufacturer specifies protection suitable for smooth DC residual current. What should the designer compare?','The required residual-current waveform capability and the approved protective arrangement|Only whether the MCB has a B or C overcurrent curve|Only the enclosure colour of the existing RCCB|Whether the normal load current is below 30 mA','MCB curve letters describe a different phenomenon.|Appearance does not establish residual waveform capability.|Rated residual current is not the machine’s permitted normal load current.','Electronic loads can affect residual-current sensing. Check the equipment’s specified arrangement, including any built-in detection, rather than applying a blanket rule to every electronic load.','Why is Type B RCD not the same description as B-curve MCB?','The RCD type identifies residual waveform capability; the MCB curve describes overcurrent operating behaviour.'),
      Q('The RCD test button opens the device. What may the verifier legitimately record from that action alone?','The internal test function operated; full installation verification is still required|All earth-loop and bonding measurements are acceptable|The ramp-test threshold has been measured|Every downstream circuit has correct polarity','The button does not measure loop impedance or bonding continuity.|A ramp test requires controlled increasing test current and a measured threshold.|Correct circuit polarity is not established by this button action.','A successful button operation is useful but limited evidence. It does not substitute for the relevant inspections and instrument tests.','How does a ramp test differ from a trip-time test?','A ramp test varies residual current to investigate the operating threshold; a trip-time test measures operation time at a selected test current.'),
    ],
  },
  TqdQRgf3uGs:{
    model:'MCB and MCCB describe device families, not a universal dividing line at one current rating. MCCBs commonly offer a wider selection of frame sizes, trip units and accessories. Select the actual product for load, fault interruption, adjustment and coordination requirements.',
    ideas:[
      'A frame size describes the physical/rating family; the fitted trip unit and its settings determine the protective behaviour. Some devices are fixed and others adjustable. Read the exact model rather than assuming every MCCB has every adjustment.',
      'Rated operating voltage and breaking capacities must suit the installation. Icu is ultimate short-circuit breaking capacity and Ics is service short-circuit breaking capacity under the relevant standard. These are not interchangeable with continuous rated current.',
      'A shunt trip allows an external command to release the breaker; it is not itself a sensor of every fault. Auxiliary contacts signal state to a control or indication circuit; they are not the main load path. A mechanical trip button does not calibrate the complete protective characteristic.',
    ],
    practice:'For a feeder replacement, collect the single-line diagram, prospective fault current, required settings and manufacturer compatibility data. Confirm the accessories’ control voltage and function separately from the main circuit’s voltage and current.',
    retrieval:{prompt:'Why is “same frame size” insufficient when replacing an MCCB?',answer:'Trip unit, settings, voltage rating, breaking capacities, poles and coordination may differ within the same frame family.',why:'The enclosure does not specify all the protective behaviour.'},
    note:'Do not adopt the video’s family-wide current/pole limits or accessory claims as universal. Actual manufacturers offer different MCB and MCCB ranges.',
    questions:[
      Q('Two MCCBs fit the same mounting space, but their trip units differ. Which check is essential before substitution?','Compare the actual protective settings and coordination requirements|Assume the frame makes their trip curves identical|Use the auxiliary contact rating as the feeder rating|Choose whichever has the easier operating handle','A frame family can accept different trip units.|Auxiliary contacts belong to signalling circuits, not the main feeder path.|Operating convenience does not establish protective suitability.','The fitted trip unit determines the response within the device’s limits. Match the complete electrical specification, not only the frame.','What is the distinction between frame size and trip setting?','Frame size identifies a device family/capacity; the trip unit and adjustment establish its operating protection settings.'),
      Q('A remote emergency command must open a suitably designed breaker arrangement. What is the role of a specified shunt-trip accessory?','Release the breaker when its control circuit receives the required command|Measure all feeder faults without another sensing function|Carry the full feeder load through the control switch|Increase the breaker’s short-circuit breaking capacity','A commanded release is not a universal fault sensor.|The command circuit and main load path have different duties.|An accessory release does not increase the certified fault-interruption rating.','The shunt trip converts an external electrical command into opening. The system still needs the correct detection, control supply and protective design.','What should auxiliary contacts normally communicate?','Device state to a control or indication circuit, within their own ratings.'),
      Q('A proposed MCCB has adequate rated load current, but its interruption rating at the operating voltage is below the prospective fault current. What is the design issue?','It lacks demonstrated fault-interruption capability for that location|Its handle cannot indicate on and off|Its load rating guarantees all fault duties anyway|Its auxiliary contact can absorb the excess fault current','The issue is electrical fault duty, not indication.|Load carrying and fault interruption are distinct ratings.|An auxiliary contact cannot take over main-circuit fault interruption.','Choose adequate breaking capacity or an explicitly verified manufacturer-supported backup arrangement. Do not assume normal load suitability guarantees fault suitability.','What does Ics describe, compared with Icu?','Service short-circuit breaking capacity, as distinct from ultimate short-circuit breaking capacity under the relevant standard.'),
    ],
  },
  CNiLNvBLopI:{
    model:'A Type 2 surge protective device addresses transient overvoltages that can damage electronic equipment. Such transients can arise from atmospheric events or switching inductive loads. This is a different protective task from interrupting an overload or detecting residual current.',
    ideas:[
      'Electronic equipment can be vulnerable to brief voltage disturbances even when its normal current is within the circuit rating. A transient is a short-duration event, not automatically a sustained overload.',
      'Nearby atmospheric activity and switching motors or other inductive loads can produce surges. The short video explains why this risk can exist without a direct lightning strike on the building.',
      'Type 2 protection belongs within a coordinated surge-protection design. The video is a motivation for protection, not a complete SPD selection or wiring specification. Device type, location, earthing, connections and manufacturer requirements still matter.',
    ],
    practice:'When specifying a board serving controls and electronics, consider surge risk as a separate design question. Do not present an MCB, an RCD or one SPD as a guarantee against every cause of equipment damage.',
    retrieval:{prompt:'Why might a workshop need surge assessment even when its machines never overload the circuit?',answer:'Switching and atmospheric transients concern brief overvoltage, not just sustained load current.',why:'Different electrical disturbances require different protective functions.'},
    note:'This 51-second source explains purpose, not installation detail. It does not establish direct-lightning protection or a universal regulatory requirement to fit a particular SPD.',
    questions:[
      Q('Electronic controls fail after an inductive load is switched, although normal circuit current is acceptable. Which disturbance does this lesson ask the designer to consider?','A transient overvoltage|A guaranteed sustained cable overload|A necessary loss of every neutral conductor|A change in the MCB’s rated current','Acceptable normal current does not rule out a transient; overload is a different claim.|The described event does not establish a neutral failure.|A switching event does not rewrite a breaker’s marked rating.','Inductive switching is one possible surge source identified in the video. Investigate evidence rather than diagnosing every failure from the symptom alone.','Name a non-lightning source of a voltage surge discussed in this video.','Switching an inductive load, such as a motor.'),
      Q('A client asks why an SPD is considered when MCBs are already fitted. Which distinction is useful?','The SPD addresses transient voltage; MCBs address overcurrent|An SPD is just a larger-current MCB|The SPD replaces every downstream fuse|An MCB detects every brief overvoltage','The devices have different functions, not merely different sizes.|Surge protection does not replace required overcurrent protection.|An MCB is not a universal transient-voltage detector.','Explain the disturbance first, then the device that addresses it. This prevents one protective function being mistaken for complete protection.','Which two quantities distinguish the SPD and MCB roles here?','Transient voltage for surge protection; excessive current for overcurrent protection.'),
      Q('After watching this short Type 2 SPD video, what information is still needed to install a specific device?','The complete design and the manufacturer’s selection and connection requirements|Only the fact that the equipment contains electronics|Only the nearest empty space in the board|Only confirmation that no direct lightning strike has occurred','Equipment vulnerability explains purpose, not correct installation.|Available space does not establish compatibility or correct connections.|Past absence of a strike does not specify a protective arrangement.','A short purpose video is not a wiring instruction. Use the exact product documentation and applicable installation requirements.','Does a Type 2 SPD by itself prove protection from every lightning effect?','No. Lightning and surge protection require an appropriate coordinated design.'),
    ],
  },
  lIit5k8QVj8:{
    model:'An arc-fault detection device looks for electrical signatures associated with hazardous arcing. The demonstration shows why a damaged conductor can create a fire risk without producing the high current of a conventional short circuit.',
    ideas:[
      'A series arc can restrict current through a damaged connection or conductor. The resulting current may remain below an overcurrent device’s fast operating region while concentrated heating creates a hazard.',
      'If current still returns through the expected live conductors, residual-current protection may not see sufficient imbalance. AFDD technology examines waveform behaviour and distinguishes unwanted arcing from normal switching signatures.',
      'Arc-fault protection complements, rather than excuses omission of, other protective measures. Correct terminals, cable protection, inspection and compatible protective devices remain necessary. The laboratory demonstration is not a safe experiment to reproduce on an installation.',
    ],
    practice:'A scorched connection requires isolation, investigation and repair—not just a device upgrade. Consider the required arc-fault protective arrangement alongside workmanship, circuit condition and manufacturer guidance.',
    retrieval:{prompt:'Why can a damaging series arc fail to operate either an MCB or an RCD promptly?',answer:'The arc may limit current below the MCB’s relevant response and still carry balanced outgoing and returning current.',why:'Arc signatures, overcurrent and residual imbalance are different detection inputs.'},
    note:'A controlled manufacturer demonstration is not an invitation to create arcs. AFDD suitability and regulatory application require the exact product and current local requirements.',
    questions:[
      Q('A damaged series connection arcs while load current stays modest. Why might the MCB not clear it promptly?','The arc does not necessarily produce enough overcurrent for prompt operation|The MCB has to detect visible flames first|Every arc makes current exactly zero|A series arc always bypasses the entire circuit','The breaker senses electrical current, not visible flames.|An arc can sustain current and heating.|A series fault remains in the load path rather than automatically bypassing it.','A dangerous local heating condition need not resemble a high-current short circuit. Arc-fault detection addresses a different signature.','What makes series arcing different from a bolted short circuit?','It can limit rather than greatly increase current while producing dangerous local heating.'),
      Q('An AFDD is added to a circuit with a known loose, heat-damaged termination. What must still happen?','Isolate, investigate and repair the damaged connection before return to service|Leave the termination because the AFDD now replaces workmanship|Increase the circuit rating until the arc disappears|Treat a successful switch-on as proof of repair','A protective device does not restore a damaged connection.|Increasing rating can worsen the risk and does not repair the cause.|Operation alone does not establish soundness or safe verification.','Protection reduces risk; it does not justify leaving known defects. Repair and verify the installation itself.','Does fitting an AFDD remove the need for inspection and sound terminations?','No. It complements good installation and other protection; it does not repair defects.'),
      Q('Why might a series arc carrying balanced line and neutral current fail to operate an RCD?','The expected residual-current imbalance may be absent|The RCD responds only to room temperature|All arcs occur upstream of every RCD|A neutral conductor cannot carry arc current','An RCD compares monitored currents, not ambient temperature alone.|Arcs can occur downstream too; location is not the stated explanation.|Neutral can carry the returning load current.','Balanced current can still contain an arc signature. Residual-current sensing and arc detection are not interchangeable.','What additional signal does an AFDD analyse?','Electrical waveform patterns associated with hazardous arcing, rather than only current magnitude or residual imbalance.'),
    ],
  },
  V6WR_TBf1AU:{
    model:'Selective coordination aims to clear a fault with the appropriate device nearest upstream while maintaining unaffected supplies. The webinar moves from time-current curves to tested device combinations and shows why a coordination claim needs more evidence than two different ampere ratings.',
    ideas:[
      'Study the whole single-line path and all relevant fault conditions. Overload, short-circuit and ground-fault elements can operate differently. A downstream branch device must coordinate with the upstream devices that can interrupt its supply; an overlooked ground-fault element can defeat an apparently satisfactory phase-overcurrent study.',
      'Time-current curves are useful in their applicable regions, but instantaneous and current-limiting behaviour may require manufacturer test tables. Match frame, sensor, trip unit, settings, voltage and every table note. Overlapping plotted curves do not alone settle coordination when the manufacturer supplies applicable tested data.',
      'Transformer impedance and current transformation affect the comparison across primary and secondary sides, but do not guarantee coordination. Check inrush, damage protection, fault levels and operating settings. Specify the required scope and evidence before equipment purchase rather than expecting software to fix incompatible hardware.',
    ],
    practice:'For a main board feeding floor boards, mark a final-circuit fault on the drawing, identify every device able to disconnect it and request coordination evidence for the exact combination. Record any limit of selectivity and the consequences for unaffected occupants.',
    retrieval:{prompt:'Why is “upstream breaker is twice the amperes” not sufficient proof of selectivity?',answer:'Device mechanisms, trip settings, fault level and tested pairing determine operation; a simple current-rating ratio does not establish the result.',why:'Coordination is a relationship between specified devices under specified conditions.'},
    note:'This webinar discusses North American NEC contexts and manufacturer examples. Those legal scopes and time thresholds are not Kenyan rules. Do not delay protection or raise pickups without a complete safety and withstand review.',
    questions:[
      Q('A final-circuit fault shuts down both its breaker and the building main. Which design objective was not achieved for that event?','Selective clearing that preserves unaffected supplies|Making every protective device operate together|Eliminating all impedance in the feeder|Keeping the faulty circuit energised for diagnosis','Simultaneous upstream operation is what selectivity aims to avoid where achievable.|Impedance is not something the coordination objective eliminates.|The faulty circuit must be disconnected safely, not maintained live.','The intended downstream device should clear the relevant fault without unnecessarily losing healthy circuits, within the established selectivity range.','What does partial selectivity mean for the design record?','Selectivity is established only up to a stated limit, not for every possible fault current.'),
      Q('Two instantaneous regions overlap on a software plot, but a manufacturer table claims selectivity for a tested pair. What should the reviewer do?','Verify exact device identities, settings, fault level and table conditions|Reject all manufacturer data because lines overlap|Accept the table for any devices with the same ampere labels|Erase the instantaneous regions from the study','A curve plot may not capture the tested high-current interaction.|The claim applies to specified combinations and conditions, not generic labels.|Removing inconvenient evidence does not resolve the engineering question.','Use the correct evidence for the operating region. Manufacturer tests can describe interactions not resolved by a simplified plot, provided every condition matches.','What details must accompany a manufacturer coordination-table claim?','The exact device/frame and trip combination, settings, voltage, fault-current limit and relevant notes.'),
      Q('A phase-overcurrent study appears selective, yet an upstream ground-fault element trips first. What was omitted?','Coordination of all enabled protective elements along the fault path|Only the colour of the outgoing cable|Proof that both breakers have equal handles|A rule that all ground-fault protection must be disabled','Cable colour does not resolve the omitted protective operating curve.|Mechanical appearance is irrelevant to the separate trip function.|Disabling protection without design justification is not a remedy.','An independent ground-fault element can determine actual operation even when phase curves look satisfactory. Include it in the protective study.','Why must ground-fault elements appear in a coordination review?','They can operate independently of the phase-overcurrent elements and disconnect an upstream supply first.'),
    ],
  },
};
