import { Q, type SuppliedTeaching } from './supplied-content-types';

// Individually written from the two supplied St John Ambulance transcripts.
export const safetyTeaching: Record<string,SuppliedTeaching> = {
  TsJ49Np3HS0: {
    model:'CPR is the immediate response when an adult is unresponsive and is not breathing normally. At an electrical incident, first make the scene safe: do not touch a casualty who may still be in contact with electricity. Once safe to approach, assess responsiveness and breathing, summon emergency help and begin CPR when indicated.',
    ideas:[
      'Recognise the emergency, not just movement. Occasional gasps are not normal breathing. Check breathing briefly (no more than ten seconds); call for emergency assistance, use speakerphone and follow the dispatcher. Send another person for an AED while you remain with the casualty.',
      'Effective adult compressions use the centre of the chest, straight arms, 100–120 compressions per minute and a depth of 5–6 cm. Release pressure between compressions so the chest recoils; minimise interruptions. These are skills to practise with an accredited trainer, not on a healthy person.',
      'If trained and willing, use 30 compressions followed by two rescue breaths, each sufficient to produce visible chest rise. Otherwise give compression-only CPR and follow emergency guidance. Continue until help takes over, normal breathing returns, an AED requests a pause, or you cannot continue. Reassess and monitor a casualty who recovers; responsiveness alone does not establish normal breathing.',
    ],
    practice:'Include electrical isolation, access for emergency responders, emergency contacts, first-aid training and AED location in the site emergency plan. In Kenya, emergency numbers include 999 and 112. Do not turn a rescue into a second electrical casualty.',
    retrieval:{prompt:'Why should a workmate fetch the AED while the first aider stays with an adult receiving CPR?',answer:'It brings defibrillation to the casualty without abandoning compressions and ongoing assessment.',why:'The tasks can run in parallel; avoidable interruptions reduce the benefit of CPR.'},
    note:'Electrical safety comes before contact. This is adult first-aid revision, not certification. Follow current emergency dispatcher guidance. Sources: supplied St John Ambulance transcript; sja.org.uk/first-aid-advice/cpr/; resus.org.uk 2025 adult basic life support guidance.',
    questions:[
      Q('After the electrical danger has been made safe, an adult worker is unresponsive and only gasps occasionally. What should the first aider do?','Call emergency help and begin CPR, following dispatcher instructions|Wait for the gasps to become regular before calling|Place the worker in the recovery position and leave to find help|Give rescue breaths alone until the worker speaks','Occasional gasps are not normal breathing; waiting delays resuscitation.|Recovery positioning is not a substitute for CPR when normal breathing is absent.|Breaths alone omit the circulation support provided by compressions.','Unresponsiveness with abnormal breathing calls for emergency help and CPR, not watchful waiting. Electrical danger must first be controlled.','What breathing pattern must not be mistaken for normal breathing after collapse?','Occasional gasping. An unresponsive adult who is not breathing normally needs emergency help and CPR.'),
      Q('During a training exercise, an apprentice keeps weight on the chest between compressions. Which correction matters?','Release pressure between compressions while keeping hand position|Move the hands to a new position after every compression|Pause for several breaths after each compression|Press more shallowly so recoil is unnecessary','Repeated hand movement interrupts delivery and loses position.|Long pauses interrupt circulation support.|Shallow compressions do not replace adequate depth and full recoil.','Full recoil allows the chest to return between compressions. Combine recoil with the taught adult depth and rate, without leaning continuously.','What three features define good adult chest compressions?','A depth of 5–6 cm, a rate of 100–120 per minute and full chest recoil, with minimal interruptions.'),
      Q('A bystander is willing to help but cannot give rescue breaths. The dispatcher confirms CPR is needed. What is the appropriate response?','Give continuous chest compressions and follow the dispatcher|Withhold CPR until someone able to give breaths arrives|Give one compression every time the casualty gasps|Search for a pulse repeatedly before starting','Inability to provide breaths should not prevent compression-only CPR.|Gasping is not a reliable pacing signal for compressions.|Repeated pulse searching delays the instructed response.','Compression-only CPR is the appropriate alternative when breaths cannot be given; emergency guidance supports the bystander while help is coming.','If rescue breaths cannot be provided, what CPR action remains available?','Compression-only CPR while following emergency dispatcher instructions.'),
    ],
  },
  UFvL7wTFzl0:{
    model:'An automated external defibrillator (AED) analyses the heart rhythm and guides the rescuer. It delivers or advises a shock only when indicated; it does not shock every collapsed person. CPR, emergency help and AED use are complementary parts of resuscitation.',
    ideas:[
      'Switch on the AED and follow its spoken or pictured instructions. Expose the chest and apply pads in the positions shown on that device. If there are two rescuers, one can continue CPR while the other prepares the AED, keeping interruptions short.',
      'Nobody should touch the casualty during rhythm analysis or shock delivery. Clearly announce the pause and check that everyone is clear. Follow the particular AED prompts; some devices deliver automatically and others ask the rescuer to press a shock button.',
      'After a shock—or a no-shock instruction—resume CPR when prompted if the casualty remains unresponsive and is not breathing normally. No shock advised does not mean no emergency. Keep pads attached for further analysis and handover; continue reassessment until professional help takes over.',
    ],
    practice:'On a worksite, establish who calls emergency services, who brings the AED and who maintains CPR. AED access should be quick and known before an incident. Never approach an electrically unsafe casualty merely because an AED has arrived.',
    retrieval:{prompt:'An AED says “no shock advised.” Why might CPR still be necessary?',answer:'The detected rhythm may not be shockable even though the casualty remains in cardiac arrest. Follow the AED and dispatcher and resume CPR as directed.',why:'The shock decision concerns rhythm suitability, not confirmation of recovery.'},
    note:'The 2016 video remains a device demonstration, not the current local emergency protocol. Follow current AED/dispatcher guidance. Electrical danger must be controlled before touching the casualty.',
    questions:[
      Q('An AED arrives while two colleagues are helping an unresponsive adult who is not breathing normally. How should they share the work?','One prepares the AED while the other continues CPR until a pause is requested|Both stop CPR and study the AED case before opening it|One removes the pads after each analysis while the other waits|Both hold the casualty still throughout analysis','Stopping both tasks creates avoidable interruption.|Pads should remain attached for repeated analysis and treatment.|Touching during analysis can interfere with assessment and is unsafe during shock delivery.','Preparation can overlap with CPR. Pause when the AED requires everyone clear, then promptly resume as directed.','When can AED preparation and CPR happen together?','With two rescuers, one can prepare and attach the AED while the other continues CPR, pausing for analysis or shock as directed.'),
      Q('The AED announces that it is analysing. A helper is still touching the casualty’s shoulder. What should the rescuer do?','Tell everyone to stand clear and check that nobody is touching|Allow contact because no shock has yet been announced|Disconnect one pad until the helper moves|Hold the helper away while maintaining contact with the casualty','Analysis also requires nobody touching the casualty, not just the shock.|Disconnecting pads interrupts the device’s assessment.|Remaining in contact defeats the clear instruction.','Everyone must be clear for reliable analysis and safe shock delivery. Communicate the pause explicitly rather than assuming others heard the device.','What does “stand clear” require during AED analysis?','Nobody touches the casualty; the rescuer announces and checks this before analysis or shock.'),
      Q('After a shock, the AED instructs the team to resume CPR. The casualty remains unresponsive and is not breathing normally. What now?','Resume CPR promptly with the pads left attached|Remove the pads because the shock has finished treatment|Wait for the next analysis without compressions|Give another shock by pressing the button repeatedly','A shock does not establish recovery; the AED may need further analyses.|Waiting needlessly interrupts circulation support.|The AED, not repeated button presses, determines whether another shock is indicated.','A shock is one intervention within continuing resuscitation. Resume CPR as directed and leave the AED connected for subsequent prompts.','Does a delivered AED shock prove that the casualty has recovered?','No. Reassess and follow prompts; continue CPR if unresponsive and not breathing normally.'),
    ],
  },
};
