import {Q, type AuthoredItem} from './supplied-content-types';

// Longer explanations need additional retrieval of their distinct ideas.
// Short purpose demonstrations are not padded to an arbitrary question count.
export const deeperQuestions:Record<string,AuthoredItem[]>={
  kx35WN3uLis:[
    Q('A supplier offers an unverified ceramic fuse as an HRC replacement. What evidence is missing?','Verified ratings and provenance for the specified fuse|Evidence that the fuse body is a different colour|A continuity reading alone with no rating information|Permission to reuse the fuse after its element has opened','Colour does not establish the fuse’s interruption performance.|Continuity can show an intact element but cannot establish breaking capacity.|An operated non-resettable fuse requires the specified replacement.','The construction and certified ratings matter. A ceramic enclosure is not proof that an unknown product can safely clear the available fault current.','Can a continuity check certify a fuse’s breaking capacity?','No. It checks the conductive path; interruption ratings come from the verified product specification.'),
    Q('A semiconductor power unit specifies a particular fast protective fuse. Why should a technician not replace it with a generic time-delay fuse of equal amperes?','Its current-time and let-through behaviour may not protect the semiconductor|Time-delay means it always opens faster for every condition|Equal amperes guarantee equal protection energy|Any fuse with the right dimensions is electrically equivalent','Time-delay behaviour is not universally faster.|Rated current alone does not define the energy passed before interruption.|Physical dimensions do not establish protective equivalence.','Sensitive devices can require a specific protective characteristic and energy limitation. Follow the equipment’s specified fuse rather than matching only current and size.','What fuse properties matter for a sensitive electronic power stage?','The specified operating characteristic and fault/energy-limiting duty, as well as current, voltage and breaking capacity.'),
  ],
  gqEu9t8HwW0:[
    Q('On a manufacturer’s time-current chart, a given overload crosses a shaded operating band rather than one line. What should the reviewer report?','An operating-time range under the stated conditions|One exact time chosen from the centre as a guarantee|No possible trip because the band is shaded|The cable temperature without any thermal information','A midpoint does not remove permitted operating variation.|The band represents possible operation, not its absence.|A trip curve alone does not provide the complete cable temperature.','The band represents the characteristic’s operating range. Use its relevant limits and assumptions when checking a protective requirement.','Why is an MCB time-current band not one guaranteed operating instant?','Device tolerances and specified conditions create a range; the required design check must respect the applicable limits.'),
    Q('For an unchanged conductor resistance, current rises from 10 A to 20 A. What happens to resistive heating power?','It becomes four times as large|It merely doubles|It stays unchanged until the breaker opens|It halves because current flows faster','Heating follows current squared, not current alone.|Heating occurs while current flows, whether or not the breaker has opened.|Increasing current does not reduce resistive heating at fixed resistance.','P = I²R, so doubling current multiplies heating by four at the stated constant resistance. This explains why sustained overload cannot be dismissed.','At fixed resistance, how does current relate to heating power?','Heating power is proportional to current squared.'),
  ],
  'TUno2IT-KZY':[
    Q('A verifier selects a five-times test on a 30 mA RCD. What nominal test-current magnitude does that represent?','150 mA|35 mA|6 mA|150 A','Five times means multiplication, not adding five milliamperes.|Dividing reverses the selected multiplier.|The unit remains milliamperes; 150 A is a thousand times larger.','5 × 30 mA = 150 mA. The correct test mode, waveform and acceptance criteria must still come from the applicable procedure; this arithmetic is not a universal instruction to perform that test.','Which is different: RCD rated residual current or selected test-current multiplier?','Rated residual current is the device’s sensitivity marking; the multiplier sets a test current relative to it.'),
    Q('Several circuits share an RCCB and one develops residual leakage sufficient to operate it. Why might healthy circuits also lose supply?','They lie within the same RCCB’s switched supply group|Every healthy circuit must have developed the identical leak|An RCCB always isolates the entire utility network|Each MCB has acquired the RCCB’s sensing core','A shared upstream device can disconnect healthy loads without identical faults.|Its boundary is the connected downstream group, not the whole network.|The MCBs do not become residual-current sensors merely by being downstream.','A group RCCB can interrupt all its supplied circuits. Individual RCBO arrangements change the grouping, but require a complete compatible design.','What practical consequence follows from grouping circuits behind one RCCB?','One residual-current operation can interrupt every circuit supplied through that device.'),
  ],
  V6WR_TBf1AU:[
    Q('A coordination reviewer compares primary and secondary breaker currents across a transformer using the same raw ampere scale. What must be accounted for?','The transformer ratio and fault conditions on the respective sides|Only the downstream breaker’s physical width|An assumption that transformer impedance guarantees selectivity|The total number of breakers regardless of connection','Physical width is not a current-reference conversion.|Impedance affects fault current but is not an automatic guarantee.|The electrical path and operating characteristics matter, not just device count.','Currents on different voltage sides must be referred consistently. Include transformer inrush, damage protection and fault levels in the review.','Why does a transformer not automatically solve coordination?','Its ratio and impedance change the comparison, but the actual device responses and transformer protection still require checking.'),
    Q('A project orders breakers before defining the required selective-coordination scope. Why can the later study become difficult?','The purchased combinations may not meet the required operating relationship|Software can always make incompatible trip units selective|A study only needs the building’s total connected kW|Coordination applies only after a fault has already occurred','Software evaluates data; it cannot create unavailable hardware characteristics.|Connected load alone does not determine all fault interactions.|Coordination is a design requirement to establish before service.','Define the protected paths, continuity needs and evidence early. Hardware selection and available trip functions constrain the final study.','What should a coordination specification establish before procurement?','The circuits and fault conditions covered, required selectivity, device/settings evidence and any permitted limits.'),
  ],
  NIrKOVZrqnU:[
    Q('A 10 kW sinusoidal load improves from 0.8 to 0.95 power factor. Using Qc = P(tan(phi1) − tan(phi2)), approximately how much correction is needed?','4.21 kvar|1.50 kvar|7.50 kvar|10.53 kvar','Subtracting power-factor numbers and multiplying by kW is not the tangent relationship.|7.50 kvar is the original reactive demand, not the amount removed to reach 0.95.|10.53 kVA is the target apparent power, not correction kvar.','tan(acos 0.8) = 0.75 and tan(acos 0.95) ≈ 0.3287. Their difference times 10 gives about 4.21 kvar, before selecting real equipment.','Why is correction to 0.95 smaller than correction to unity power factor?','Some reactive demand remains at 0.95; unity correction would offset the whole idealised reactive component.'),
    Q('A 230 V, 50 Hz single-phase capacitor must provide 1 kvar in the ideal model. Which approximate capacitance follows from C = Qc/(2 pi f V²)?','60 microfarads|60 farads|3.0 microfarads|120 millifarads','The numerical result is about 0.000060 F, not 60 F.|That value provides much less reactive power at the stated conditions.|This is far above the required capacitance; maintain the unit conversion.','Use Qc = 1000 var: 1000/(2 pi × 50 × 230²) ≈ 0.0000602 F = 60.2 microfarads. This is a calculation exercise, not an installation specification.','What voltage belongs in the single-phase capacitor reactive-power formula?','The RMS voltage actually across that capacitor, with consistent units and frequency.'),
  ],
  '8Z255dd78H4':[
    Q('The example keeps 20 A and 11 mV/A/m but limits drop to 11.5 V. Approximately what maximum route length follows?','52.3 m|63.3 m|5.23 m|55 m regardless of the allowance','This is not the result of dividing the voltage allowance by drop per metre.|A factor-of-ten error arises from the unit conversion.|The existing route must be checked; it does not fix the allowable length.','L = 11.5 × 1000 /(11 × 20) ≈ 52.3 m. A real route must be surveyed and all design checks repeated if changed.','Which factors set voltage drop when a cable’s mV/A/m coefficient is given?','The design current and actual route length, multiplied by the coefficient with conversion to volts.'),
    Q('For the video’s resistive heater rated 4.6 kW at 230 V, what design current follows before other circuit-selection checks?','20 A|4.6 A|230 A|1058 A','Kilowatts are not amperes; convert power to watts before dividing by voltage.|The voltage magnitude is not the load current.|Multiplication of the stated numbers is not I = P/V.','4600 W / 230 V = 20 A for the stated resistive load. Motor and other non-unity-power-factor input calculations need the relevant additional data.','When is I = P/V directly applicable to the single-phase load example?','For the stated resistive load using its real electrical input power and voltage.'),
  ],
  XbL0R_9KLD4:[
    Q('A motor plate pairs one voltage with delta and another with star. Which evidence determines the terminal links for the actual supply?','The pairing on that motor’s plate and terminal diagram|A rule that every 400 V motor must be linked the same way|The colour of the terminal box cover|The protective device’s manufacturer alone','Motor winding voltage ratings differ, so a universal connection rule is unsafe.|A cover colour is not an electrical connection specification.|The motor’s winding and terminal data determine the connection requirement.','Read the voltage/connection pair for the exact machine. A familiar supply voltage alone does not establish how its windings should be connected.','Why must voltage and star/delta symbols be read together?','They identify the supply conditions for the intended winding connection.'),
    Q('A maintenance plan copies bearing grease intervals from another motor of equal kW. What should be checked?','The exact bearing, speed, operating conditions and manufacturer lubrication instructions|Only whether both motors have the same shaft output|Only whether both terminal boxes have six studs|Whether either motor ever reaches synchronous speed','Equal output does not prove identical bearings or lubrication duty.|Terminal count does not specify bearing maintenance.|Synchronous speed is not a substitute for the actual maintenance instructions.','Mechanical construction and operating conditions affect lubrication. The nameplate and manual link the maintenance plan to the actual motor.','What nameplate-related information helps mechanical maintenance beyond kW?','Frame/mounting, bearing details and the manufacturer’s lubrication requirements for the actual machine.'),
  ],
  Me_adh09CdY:[
    Q('A supplier proposes a K-characteristic breaker using a curve from another manufacturer. What should the designer request?','The proposed model’s own curve and application data|Assurance that K has one universal magnetic band everywhere|Only the curve from the existing B device|A claim that all K devices include phase-loss protection','The source’s K example must not be treated as universal.|The old B curve does not describe the new product.|An overcurrent characteristic letter does not establish motor phase monitoring.','K and Z product characteristics must be verified for the actual model and standard. Use those data for inrush and fault-disconnection checks.','Which source should settle the K or Z characteristic of a proposed device?','The exact manufacturer/model technical data and applicable standard.'),
    Q('An MCB bears an energy-limiting class number 3. What does that number not specify?','A guaranteed three-second disconnection time|A classification associated with limiting fault energy|A characteristic distinct from rated current|Information to interpret with the product standard','The marking does concern energy limitation; that is not the incorrect inference.|It is separate from rated current; that distinction is valid.|Its standard context matters; that is also valid.','Do not turn a class number into a time value. Use the time-current characteristic for timing and the relevant data for energy let-through.','Where should breaker operating time be obtained?','From the applicable time-current characteristic and conditions, not an energy-class number.'),
  ],
  TqdQRgf3uGs:[
    Q('A device has a service breaking capacity lower than its ultimate breaking capacity. Why should both be recorded?','They describe different standardised fault-interruption duties|Their difference is the normal load-current rating|The lower figure is necessarily a printing error|The higher figure is the only relevant voltage rating','Subtracting the capacities does not give load current.|Different Ics and Icu values can be intentional specifications.|Both figures are current capacities, not a replacement for operating voltage.','The required interruption and service-performance duties must be checked at the operating voltage. Do not collapse distinct ratings into one unlabeled kA number.','What unit is commonly used for MCCB short-circuit breaking capacities?','kA, at specified voltage and standardised test conditions.'),
    Q('A remote panel must indicate whether a breaker is open. Which component is normally chosen for that signalling task?','A suitably rated auxiliary contact|The main load terminal used as an unprotected signal wire|The frame-size marking without a sensing connection|The shunt-trip coil treated as a position contact','A main power terminal is not a suitable substitute for a designed indication circuit.|A printed rating cannot transmit state.|A shunt-trip coil is an operating accessory, not inherently a position contact.','Use the specified indication accessory and its contact arrangement. State indication and a command to open are different control functions.','How do an auxiliary contact and a shunt trip differ?','The auxiliary contact signals state; the shunt trip commands opening when energised as specified.'),
  ],
};
