import course from './course-curriculum';
import { lessonGuides } from './lesson-guides';
import { glossary } from './learning-data';

export type KnowledgeTerm = { term: string; aliases: string[]; definition: string; category: string; contrast?: string; unit?: string; formula?: string };
const term = (name: string, aliases: string[], definition: string, category: string, contrast?: string, unit?: string, formula?: string): KnowledgeTerm => ({ term: name, aliases, definition, category, contrast, unit, formula });
export const electricalTerms: KnowledgeTerm[] = [
  term('Zs', ['earth fault loop impedance','earth-fault loop','total loop'], 'The impedance of the complete path from the source, along line to an earth fault, and back through the protective arrangement to the source.', 'Testing', 'Ze covers the external portion; Zs also includes the circuit. Earth is part of a return path, not a sink that consumes current.', 'Ω', 'Zs ≈ Ze + (R1 + R2), when circuit reactance is negligible; allow for temperature.'),
  term('Ze', ['external earth fault','external loop'], 'The external part of earth-fault loop impedance, at the installation origin.', 'Testing', 'Do not use Ze alone as the loop impedance at the end of a final circuit.', 'Ω'),
  term('R1 + R2', ['r1','r2','protective conductor resistance'], 'The combined resistance of the circuit line conductor and circuit protective conductor.', 'Testing', 'A continuity measurement is a resistance measurement. It does not by itself determine the external supply impedance.', 'Ω'),
  term('CPC', ['circuit protective conductor','protective conductor'], 'A circuit protective conductor connects exposed conductive parts into the protective arrangement.', 'Protection', 'Neutral carries normal load current; a CPC is not a substitute neutral.'),
  term('ADS', ['automatic disconnection','fault protection'], 'Automatic disconnection of supply limits how long a fault can create a hazardous condition.', 'Protection', 'A low loop impedance is useful only when coordinated with the actual protective device and required disconnection conditions.'),
  term('RCD', ['residual current','residual-current'], 'A family of devices that detect imbalance in the currents through their sensing core.', 'Protection', 'An RCCB provides residual-current protection without integral overcurrent protection; an RCBO combines both.'),
  term('RCCB', ['residual current circuit breaker'], 'A residual-current circuit-breaker without integral overcurrent protection.', 'Protection', 'An RCCB does not replace correctly coordinated overload and short-circuit protection.'),
  term('RCBO', ['combined residual'], 'A residual-current operated circuit-breaker with integral overcurrent protection.', 'Protection', 'It combines functions that an RCCB alone does not provide.'),
  term('MCB', ['miniature circuit breaker','miniature circuit-breaker'], 'A miniature circuit-breaker designed for overcurrent protection within its ratings.', 'Protection', 'An MCB does not provide the same residual-current sensing as an RCD.'),
  term('MCCB', ['moulded case','molded case'], 'A moulded-case circuit-breaker; ratings, trip settings and breaking capacity depend on the product.', 'Protection', 'The housing name alone does not specify its settings or coordination.'),
  term('TN-S', ['tn s'], 'An earthing arrangement with separate neutral and protective conductors throughout the system.', 'Protection', 'TN-C-S combines protective and neutral functions in part of the supply; TT uses a local electrode for the installation protective system.'),
  term('TN-C-S', ['tn c s','pme'], 'An arrangement with combined protective and neutral functions upstream and separate conductors in the installation.', 'Protection', 'An open upstream PEN can create hazards. Do not assume an arrangement from cable appearance alone.'),
  term('TT', ['tt system','earth electrode'], 'An arrangement in which exposed conductive parts connect to an installation earth electrode electrically independent of the source electrode.', 'Protection', 'The earth-electrode path differs from the metallic supply return path of TN systems.'),
  term('MET', ['main earthing terminal'], 'The main earthing terminal connects the relevant protective and earthing conductors.', 'Protection'),
  term('PEN', ['combined protective','open pen'], 'A conductor combining protective earthing and neutral functions.', 'Protection', 'Loss of a PEN can affect exposed conductive parts even when appliances appear to operate.'),
  term('PFC', ['prospective fault current','fault current'], 'Prospective fault current is the current that would flow under a stated fault condition at a specified point.', 'Protection', 'PSCC concerns a short circuit; PEFC concerns an earth fault.', 'A or kA'),
  term('PSCC', ['prospective short circuit'], 'Prospective short-circuit current at a stated point and fault configuration.', 'Protection', 'Compare relevant prospective currents with equipment breaking capacity.', 'A or kA'),
  term('PEFC', ['prospective earth fault'], 'Prospective earth-fault current at a stated point.', 'Protection', 'Do not silently substitute line-to-line voltage into a line-to-earth fault calculation.', 'A or kA'),
  term('Insulation resistance', ['insulation test','insulation-resistance'], 'Resistance offered by insulation between conductors or between conductors and earth under specified test conditions.', 'Testing', 'Continuity looks for a connected conducting path; insulation resistance looks for unwanted conduction through insulation.', 'MΩ'),
  term('Continuity', ['continuity','r1+r2'], 'Evidence that an intended conducting path is continuous; assess resistance and test conditions as well as the existence of a path.', 'Testing', 'A continuity buzzer alone is not proof of acceptable protective-conductor resistance.', 'Ω'),
  term('Polarity', ['polarity'], 'Correct conductor connections so functions such as single-pole switching and protection act in the intended conductor.', 'Testing', 'Equipment operating normally does not prove correct polarity.'),
  term('Safe isolation', ['safe isolation','prove dead','lock off'], 'A controlled process to identify and isolate all relevant energy sources, secure against reconnection and verify absence of voltage using suitable proven equipment.', 'Safety', 'A stopped motor, an open control switch or a non-contact detector alone does not establish safe isolation.'),
  term('Ib', ['design current'], 'The current the circuit is designed to carry under its intended operating conditions.', 'Design', 'In is the protective-device rating or setting; Iz is cable capacity under the relevant installation conditions.', 'A', 'Ib ≤ In ≤ Iz is one overload coordination check, not a complete design.'),
  term('In', ['rated current','device rating'], 'The rated current or selected setting of a protective device.', 'Design', 'Increasing the breaker rating can leave a cable inadequately protected.', 'A'),
  term('Iz', ['current-carrying capacity','current carrying capacity','cable size','cable capacity'], 'The continuous current a conductor can carry under its actual installation conditions without exceeding the relevant temperature limit.', 'Design', 'Cable cross-section alone does not determine Iz.', 'A'),
  term('Voltage drop', ['voltage drop','volt drop'], 'The change in voltage along a circuit due to current flowing through its impedance.', 'Design', 'A cable can pass a capacity check and still fail another design check.', 'V or %'),
  term('Line and phase values', ['line voltage','phase voltage','star','delta','three-phase','three phase'], 'Line values refer to supply conductors; phase values refer to a winding or load phase. Their relationship depends on the connection.', 'Science', 'In balanced star, VL = √3 Vphase. In delta, VL = Vphase. Do not interchange line and winding values.'),
  term('Power factor', ['power factor','cos φ','cos phi'], 'Real power divided by apparent power. For sinusoidal voltage and current it is cos φ.', 'Science', 'Better power factor can reduce current for a fixed real load; it does not automatically reduce that load’s useful energy requirement.', 'dimensionless', 'P = √3 VL IL PF for a balanced three-phase load.'),
  term('Slip', ['slip','induction motor','rotor'], 'The difference between synchronous field speed and rotor speed, expressed relative to synchronous speed.', 'Motors', 'A normally motoring induction rotor runs below synchronous speed; an ordinary contactor does not control frequency.', '%', 'ns = 120 f / poles; slip = (ns − nr) / ns.'),
  term('Contactor', ['contactor','dol','holding contact'], 'An electrically operated switch used to control a power circuit.', 'Motors', 'A holding contact sustains the control command. It is not an isolator or overload-protection device.'),
  term('Interlock', ['interlock','star–delta','star-delta'], 'A means of preventing incompatible operating states, such as simultaneous star and delta contactor operation.', 'Motors', 'A timer alone must not be assumed to provide every necessary interlocking function.'),
  term('SWA', ['steel wire armoured','steel-wire armoured','swa'], 'Steel-wire-armoured cable; armour, glands and terminations need selection for the actual installation.', 'Installation'),
  term('Conduit', ['conduit'], 'A protective routing system for insulated conductors or cables.', 'Installation', 'Mechanical containment does not remove requirements for cable capacity, bend radius or electrical continuity where applicable.'),
  term('Lux', ['illuminance','lux','lighting design'], 'Illuminance: luminous flux incident per unit area.', 'Lighting', 'Lumens describe luminous flux; watts describe electrical power.', 'lm/m²'),
  term('PV', ['solar','photovoltaic','pv'], 'Photovoltaic devices convert incident light into electrical energy.', 'Energy systems', 'Opening an AC isolator does not remove all DC generation from illuminated modules.'),
  term('Inverter', ['inverter','ups'], 'Equipment that converts DC to AC with specified control and protection capabilities.', 'Energy systems', 'Grid-connected and island operation can have different fault-current and earthing conditions.'),
  term('SPD', ['surge','spd'], 'A surge protective device limits transient overvoltages within its specified application and coordination.', 'Protection', 'It does not replace overcurrent, residual-current or lightning-protection design.'),
  term('Electron', ['electron','atomic','atom'], 'A negatively charged particle. Mobile electrons carry charge through metals.', 'Science', 'A simplified atom drawing is a model; electrons do not travel around a real atom like planets.'),
  term('Charge', ['charge','coulomb'], 'An electrical property whose movement constitutes current.', 'Science', 'Charge is not the same quantity as current; current is charge transfer per unit time.', 'C', 'Q = I t for constant current.'),
  term('Termination', ['termination','ferrule','ferrules','strip flexible cable'], 'A connection between a conductor and a terminal, prepared and secured for the actual conductor and terminal design.', 'Installation', 'A ferrule is not universally required or universally suitable. Use the terminal and conductor manufacturer’s instructions.'),
  term('Cable tray', ['cable tray'], 'A support system carrying cables along a planned route.', 'Installation', 'A mechanically neat route must also meet cable bend-radius, support, environmental and electrical design requirements.'),
  term('Ring final circuit', ['ring circuit','ring final'], 'A final circuit whose conductors form a ring connected to the same origin.', 'Installation', 'An appliance working does not prove that each ring conductor remains continuous.'),
  term('Concealed services', ['pipe and cable detector','chasing','masonry','flush boxes'], 'Cables, pipes and other services hidden within a building surface or structure.', 'Installation', 'Detector indications have limits. Review drawings, construction and all relevant hazards before intrusive work.'),
  term('Consumer unit', ['consumer unit','consumer units'], 'An assembly distributing a supply to final circuits with the specified switching and protective devices.', 'Installation', 'The assembly’s appearance does not establish its ratings, protective functions or suitability.'),
  term('LED', ['led','leds','downlight','downlights','lamp technologies','garden lighting'], 'A light-emitting diode produces light when operated with a suitable electrical supply and control arrangement.', 'Lighting', 'Lamp, driver and dimmer compatibility matters. The same wattage does not guarantee the same light output or dimming behaviour.'),
  term('IP and IK ratings', ['ip','ik','ingress protection'], 'IP classifies enclosure protection against access and ingress; IK classifies resistance to specified external mechanical impacts.', 'Installation', 'A rating describes specified test conditions. It does not by itself establish suitability for every outdoor or wet location.'),
  term('Emergency lighting', ['emergency lighting','high-bay'], 'Lighting provided for specified needs when the normal lighting supply fails.', 'Lighting', 'Ordinary illumination, emergency coverage, duration, controls and testing are separate design questions.'),
  term('PIR', ['pir','passive infrared','manual override'], 'A passive infrared sensor responds to changes in received infrared radiation to provide a control signal.', 'Lighting', 'A motion-control command is not safe isolation. An override must be understood in every intended operating mode.'),
  term('KNX and ETS', ['knx','ets5','ets6'], 'KNX is a building-control system; ETS is the software used to configure and commission KNX projects.', 'Building systems', 'Physical addressing, group communication and device parameters have different roles. A successful download alone does not verify the whole sequence.'),
  term('Cabling certification', ['dsx','certifiber','structured cabling'], 'Testing an installed communications link against a selected specification using suitable configured equipment.', 'Building systems', 'A connectivity check is different from certification. DSX copper measurements and CertiFiber optical-loss measurements address different media.'),
  term('Smoke alarm', ['smoke alarm','smoke alarms'], 'A device that detects smoke and provides an alarm for its specified application.', 'Building systems', 'Detector type, siting, interconnection, power supply and maintenance must suit the actual fire-safety design and applicable requirements.'),
  term('Sine wave', ['sine wave','periodic time','frequency'], 'A smooth repeating waveform. Its frequency counts cycles per second; its period is the time for one cycle.', 'Science', 'Frequency and period are reciprocals, not interchangeable quantities.', 'Hz and s', 'f = 1 / T'),
  term('Ceiling rose', ['ceiling rose','3 plate'], 'A ceiling connection point that can join circuit conductors and supply a pendant lamp.', 'Installation', 'Permanent line, switched line and neutral have different functions; position alone does not identify a conductor.'),
  term('Two-way switching', ['2 way','two-way','intermediate lighting'], 'A switching arrangement that allows a light to be controlled from more than one position.', 'Installation', 'Switch position alone does not establish whether the circuit is isolated.'),
  term('Trunking', ['trunking'], 'An enclosure used to route and protect conductors or cables.', 'Installation', 'Space, bend conditions, heat dissipation and access are separate selection checks.'),
  term('MICC', ['micc','pyro'], 'Mineral-insulated copper-sheathed cable, with conductors separated by mineral insulation inside a copper sheath.', 'Installation', 'Preparation and sealing must suit this cable construction and its termination system.'),
  term('Field-terminated data link', ['mptl','field-terminated'], 'A communications link with a connector installed on site for the specified equipment and cable.', 'Building systems', 'The selected connector, cable and test arrangement must match the intended link specification.'),
  term('Fire detection and alarm system', ['fire detection','bs 5839'], 'A coordinated system that detects a fire condition and provides the specified warning or control response.', 'Building systems', 'Detection coverage, alarm audibility, power, circuit integrity and maintenance are separate design considerations.'),
  ...glossary.filter(item => !['Ze / Zs','Earth fault loop impedance','RCD','RCBO','MCB','Power factor','Voltage drop','Circuit protective conductor (CPC)'].includes(item.term)).map(item => term(item.term, [item.term.toLowerCase()], item.definition, item.category)),
];
const normalize = (value: string) => value.toLowerCase().replace(/[–—−]/g, '-');
function containsTerm(text: string, value: string) {
  // The protective-device symbol In must not match the ordinary word “in”.
  if (value === 'In') return /(^|[^a-zA-Z0-9])In([^a-zA-Z0-9]|$)/.test(text);
  const escaped = normalize(value).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, 'i').test(normalize(text));
}
export const lessons = course.modules.flatMap(module => module.lessons);
export const lessonById = new Map(lessons.map(lesson => [lesson.id, lesson]));
export const lessonKnowledge = Object.fromEntries(lessons.map(lesson => {
  const guide = lessonGuides[lesson.id];
  const content = `${lesson.title} ${guide.summary} ${guide.keyConcepts.join(' ')}`;
  const terms = electricalTerms.filter(item => [item.term,...item.aliases].some(alias => containsTerm(content, alias)));
  const prerequisites = [...new Set((lesson.prerequisite.match(/p\d{2}-(?:v\d+-l\d{2}|l\d{2}|[a-z]+(?:-[a-z]+)*)/gi) ?? []).map(id => id.toLowerCase()))].filter(id => id !== lesson.id && lessonById.has(id));
  return [lesson.id, { terms, prerequisites, concepts: guide.keyConcepts.map((statement, index) => ({ id: `${lesson.id}-concept-${index + 1}`, statement })), source: 'Existing lesson guide' }];
}));
export const lessonsForTerm = (name: string) => lessons.filter(lesson => lessonKnowledge[lesson.id].terms.some(item => item.term === name));
export function matchingTerms(query: string) {
  const value = normalize(query).trim();
  return electricalTerms.filter(item => normalize(`${item.term} ${item.aliases.join(' ')} ${item.definition}`).includes(value))
    .sort((a,b) => Number(normalize(b.term) === value) - Number(normalize(a.term) === value));
}
