import type { Revision } from './question-revisions';

export const moduleTwoRevisions: Record<string, Revision> = {
  'p02-l01-q-concept-1': {
    prompt: 'A cable is chosen for a damp external route that may be struck or pulled during installation. What is the correct way to think about its layers?',
    correct: 'Each layer must provide the electrical, mechanical or environmental protection required by that route.',
    wrong: [
      'The conductor cross-sectional area alone decides whether the complete cable is suitable.',
      'Any outer covering gives the same protection once the cable has been clipped in place.',
      'A cable is suitable whenever its copper conductors can carry the expected load current.',
    ],
    errors: [
      'Conductor size deals with current capacity, but it does not establish insulation, impact protection or suitability for the environment.',
      'Outer coverings have different mechanical, moisture, UV and chemical capabilities; one covering cannot be assumed equivalent to another.',
      'Current capacity is only one part of cable selection. The installation route and termination method can require a different cable construction.',
    ],
    why: 'A cable is an assembly, not only a copper size. Its conductors carry current, insulation separates live parts, and the sheath or armour protects the assembly against conditions on the route. Selection must satisfy every duty the route creates.',
    distinction: 'Cable capacity answers a thermal question; cable construction answers protection and installation questions.',
    practice: 'Before choosing a cable for an exposed route, identify load current, mechanical risk, moisture, sunlight, containment, entries and the type of termination required.',
    followUp: { prompt: 'A cable has adequate current capacity but its sheath is not suitable for the exposed route. Is the cable selection complete?', answer: 'No. The cable still has to provide the environmental and mechanical protection required by the route.', why: 'A cable can pass its thermal calculation while failing the route or environmental part of selection.' },
  },
  'p02-l01-q-concept-2': {
    prompt: 'What is the key difference between conductor insulation and a cable outer sheath?',
    correct: 'Insulation separates conductors electrically, while the outer sheath protects the cable assembly.',
    wrong: [
      'Insulation is the outer layer that protects the cable from pulling and impact, while the sheath separates line and neutral.',
      'Both layers serve the same purpose, so damage to either layer has the same electrical consequence.',
      'The sheath carries fault current while insulation carries normal load current.',
    ],
    errors: [
      'This swaps the functions. Insulation is the electrical barrier around a conductor; the sheath surrounds and protects the assembled cable.',
      'Both layers are important, but they protect against different hazards. Damage to insulation can expose conductive parts electrically, while sheath damage can expose the assembly to the environment.',
      'Neither layer is intended to carry normal or fault current. Current-carrying and protective functions belong to the conductors and designed protective paths.',
    ],
    why: 'Each insulated conductor needs an electrical barrier from other conductive parts. The sheath sits outside the insulated conductors and protects the complete cable against handling and environmental conditions. A cable can need both layers even though they have different jobs.',
    distinction: 'Insulation controls electrical separation; the sheath protects the assembled cable.',
    practice: 'When stripping a cable, remove only the amount of sheath needed and avoid nicking the insulation beneath it, because a hidden insulation defect can later create a fault.',
    followUp: { prompt: 'A cable sheath is cut but the conductor insulation appears intact. Which protective function may already be reduced?', answer: 'Protection of the cable assembly against its installation environment and mechanical handling.', why: 'The sheath is the cable’s outer protective layer even when the inner electrical insulation has not yet been damaged.' },
  },
  'p02-l01-q-concept-3': {
    prompt: 'Why can armour be important in an electrical cable installation?',
    correct: 'It provides mechanical protection and, where designed for it, can contribute to protective continuity.',
    wrong: [
      'It replaces the need for conductor insulation because steel cannot carry normal load current.',
      'It exists only to make a cable heavier so that it remains in place without supports.',
      'It makes the cable suitable for every location without checking entries, glands or protective connections.',
    ],
    errors: [
      'Armour does not replace insulation. Conductors still need insulation to remain electrically separated from each other and from the metal armour.',
      'Armour has a protective construction role; cable support still has to resist the route’s weight, movement and environmental conditions.',
      'Armour must be terminated correctly and the complete installation still needs suitable glands, sealing, support and a verified protective path where applicable.',
    ],
    why: 'Armour helps resist mechanical damage to the cable. In a cable and termination system designed for it, the armour can also form part of the protective arrangement. Both uses depend on the cable construction and the quality of its termination.',
    distinction: 'Mechanical protection and protective continuity are separate functions; one does not prove the other automatically.',
    practice: 'An armoured cable entry must be prepared with the correct gland and bonding arrangement. A tight gland alone does not establish a reliable electrical protective connection.',
    followUp: { prompt: 'Can an armoured cable be assumed to provide sound protective continuity merely because the armour is visible?', answer: 'No. The armour and its terminations must be designed, connected and verified as part of the protective arrangement.', why: 'A visible metal layer does not prove a low-resistance, continuous protective path.' },
  },
  'p02-l01-q-concept-4': {
    prompt: 'What must a cable selection match before it can be accepted for an installation?',
    correct: 'The load, route, environment and termination method together.',
    wrong: [
      'Only the expected load current, because all correctly sized cables have the same route suitability.',
      'Only the route appearance, because conductor size can be increased later if the load changes.',
      'Only the terminal size, because a cable that fits the terminals is suitable for the circuit.',
    ],
    errors: [
      'Load current matters, but cables with the same current capacity can differ greatly in their environmental and mechanical suitability.',
      'The route is important, but the cable must be selected for the actual load and protection before work begins; later upsizing may not solve other design problems.',
      'A cable can physically fit a terminal while having the wrong capacity, insulation, construction or environmental rating for the installation.',
    ],
    why: 'Cable selection combines electrical duty with the actual route and method of installation. The cable must carry the intended load safely, withstand its environment and arrive at a termination that is designed for its construction and size.',
    distinction: 'A cable fitting physically is not the same as a cable being electrically and environmentally suitable.',
    practice: 'Record the installation method before using cable data: clipping, containment, insulation, grouping, external exposure and the termination system all influence the decision.',
    followUp: { prompt: 'A cable fits its terminals and has adequate conductor area, but will be exposed to sunlight and movement. What else must be checked?', answer: 'Its construction and outer protection must be suitable for the exposed route and movement.', why: 'The thermal conductor calculation does not establish environmental or mechanical suitability.' },
  },
  'p02-l02-q-concept-1': {
    prompt: 'What is the main switch intended to provide in a consumer unit?',
    correct: 'A common means of controlling or isolating the installation supply within its intended scope.',
    wrong: [
      'Individual overload protection for every final circuit connected to the board.',
      'A test of protective-conductor continuity whenever it is switched off.',
      'Automatic proof that all possible sources feeding the work area are isolated.',
    ],
    errors: [
      'Outgoing protective devices perform individual circuit protection. The main switch controls the board supply rather than setting each circuit’s overcurrent response.',
      'Switching a device does not measure continuity. Protective continuity needs its relevant inspection and test method.',
      'A main switch may not address alternative supplies or every upstream source. Safe isolation starts by identifying every source that can energise the work area.',
    ],
    why: 'The main switch provides a common control point for the consumer unit supply. It does not replace the protective devices for outgoing circuits or the safe-isolation process required before work.',
    distinction: 'Operating a main switch controls a supply path; safe isolation establishes that every relevant source has been identified, secured and proven dead.',
    practice: 'When planning work, trace the circuit and identify grid, generator, PV or battery sources before relying on a single switch position.',
    followUp: { prompt: 'A consumer-unit main switch is off. What must still be established before electrical work begins?', answer: 'That every source capable of energising the work area has been identified, isolated as required and the conductors have been proven dead.', why: 'An off switch is not evidence that no alternative or upstream source remains connected.' },
  },
  'p02-l02-q-concept-2': {
    prompt: 'What is the protective role of an outgoing device in a consumer unit?',
    correct: 'It limits fault or overload conditions affecting the final circuit assigned to it.',
    wrong: [
      'It protects every circuit in the building equally once the consumer-unit door is closed.',
      'It provides a permanent connection between line and neutral so the circuit can operate.',
      'It identifies the circuit automatically without a schedule or circuit label.',
    ],
    errors: [
      'An outgoing device protects its assigned circuit under its specified conditions. Other circuits have their own devices and may have different ratings or characteristics.',
      'A protective device is connected in the circuit path; it does not intentionally join line and neutral together.',
      'Device position alone does not tell a future worker what it serves. Identification must connect the device to the actual circuit and load.',
    ],
    why: 'Each outgoing way is protected for the circuit it serves. Its rating, characteristic and breaking capacity must suit that circuit’s load, conductor and fault conditions.',
    distinction: 'Board-level control and final-circuit protection are different functions carried out by different parts of the assembly.',
    practice: 'A circuit schedule should identify each way, its protective device and the load or area it serves so isolation and fault finding can be planned safely.',
    followUp: { prompt: 'Can a circuit breaker’s ampere marking alone prove it is suitable for its final circuit?', answer: 'No. Its characteristic, breaking capacity and coordination with the circuit conductors and fault conditions also matter.', why: 'The current rating is only one part of protective-device selection.' },
  },
  'p02-l02-q-concept-3': {
    prompt: 'Why are neutral and protective conductors terminated on functionally distinct bars in a consumer unit?',
    correct: 'Their normal-current and protective functions are different and must remain correctly arranged for the system and protective devices.',
    wrong: [
      'They are interchangeable conductors, so separating them only makes the board look tidy.',
      'They must be joined together at every outgoing circuit to improve continuity.',
      'The neutral bar carries only fault current while the protective bar carries the normal return current.',
    ],
    errors: [
      'Neutral and protective conductors have different functions. A neat layout is useful, but the separation is part of the electrical arrangement rather than decoration.',
      'Joining them downstream can create incorrect return paths and interfere with protective arrangements, including residual-current protection.',
      'This reverses their roles. Neutral is a current-carrying return conductor in normal operation; the protective conductor is intended for protective fault conditions, not normal load current.',
    ],
    why: 'Neutral provides the intended return path for normal circuit current. The protective conductor connects exposed conductive parts into the protective arrangement. Their termination arrangement must match the earthing system and the protective devices in use.',
    distinction: 'Neutral is a normal current-carrying conductor; a circuit protective conductor is not intended to carry normal load current.',
    practice: 'A borrowed neutral or an incorrect neutral-bar connection can make an RCD trip unexpectedly and can leave conductors energised when a single circuit is isolated.',
    followUp: { prompt: 'Why can an incorrect neutral connection cause a residual-current device to trip?', answer: 'The outgoing and returning current may no longer pass through the same sensing arrangement, creating an imbalance.', why: 'An RCD compares the current leaving on line with the current returning through its associated neutral path.' },
  },
  'p02-l02-q-concept-4': {
    prompt: 'Why must a consumer-unit circuit schedule agree with the actual protective devices and connected loads?',
    correct: 'It connects physical devices to the circuits they protect so work, isolation and fault finding can be carried out safely.',
    wrong: [
      'A schedule is only for estimating electricity bills and has no effect on safe work.',
      'The device colour and ampere marking make a circuit schedule unnecessary.',
      'Once a circuit works, the schedule can remain inaccurate without affecting future work.',
    ],
    errors: [
      'A schedule is an operational safety record. It helps identify what a device controls and supports planning, isolation and future alterations.',
      'A marking may describe a device, but it does not identify the route, load or area supplied by that way.',
      'Normal operation does not correct misleading identification. An inaccurate schedule can lead someone to isolate the wrong circuit.',
    ],
    why: 'Circuit identification links drawings, board ways and real loads. This prevents work being planned from an assumption and helps an electrician trace a circuit through the installation.',
    distinction: 'A device marking describes the device; a circuit schedule identifies what that device actually serves.',
    practice: 'After alteration, update labels and records only after the circuit has been identified and verified, so the next person can follow the actual supply path.',
    followUp: { prompt: 'A breaker is labelled Lighting but controls socket-outlets after an alteration. What should be done?', answer: 'Correct the identification after establishing and verifying the circuit, rather than relying on the old label.', why: 'A label is useful only when it matches the circuit that is actually connected.' },
  },
  'p02-l03-q-concept-1': {
    prompt: 'How are the corresponding points of three balanced phase waveforms spaced?',
    correct: 'They are displaced by 120 electrical degrees.',
    wrong: [
      'They reach corresponding points together, like three copies of one single-phase waveform.',
      'They are displaced by 90 degrees because three-phase supplies have four conductors.',
      'They are spaced by 180 degrees, so one phase always cancels the other two.',
    ],
    errors: [
      'Balanced three-phase waveforms are deliberately staggered; they do not rise and fall together.',
      'Ninety degrees belongs to a quarter cycle, not the phase separation of a balanced three-phase supply.',
      'At 180 degrees two quantities oppose each other. Three balanced phases are separated evenly by one third of a cycle.',
    ],
    why: 'A balanced three-phase supply has three sinusoidal quantities separated by 120 electrical degrees. This even spacing allows their combined power transfer to be smoother than a single-phase supply.',
    distinction: 'Three-phase separation is 120 degrees; 180 degrees describes two quantities in opposition.',
    practice: 'The phase relationship is used when interpreting phasors, calculating balanced systems and checking motor rotation.',
    followUp: { prompt: 'A complete AC cycle is 360 degrees. What fraction of a cycle separates adjacent balanced phases?', answer: 'One third of a cycle, which is 120 electrical degrees.', why: 'Three equal phase positions divide the full cycle into three equal angular intervals.' },
  },
  'p02-l03-q-concept-2': {
    prompt: 'In a star-connected three-phase system, why must line-to-line voltage be distinguished from line-to-neutral voltage?',
    correct: 'They are measured between different points and therefore have different magnitudes in a balanced star system.',
    wrong: [
      'They are always identical because both readings come from the same supply.',
      'Line-to-neutral voltage is found by adding all three line voltages together.',
      'The distinction matters only for conductor colour identification, not for load connection or calculation.',
    ],
    errors: [
      'Both are supply measurements, but they are taken between different conductors and represent different voltage relationships.',
      'Three-phase voltages have phase angles and cannot be treated as simple quantities to add in this way.',
      'The connection determines which voltage reaches a load element, so the distinction directly affects equipment selection and calculation.',
    ],
    why: 'Line-to-line voltage is measured between two line conductors. Line-to-neutral voltage is measured between one line conductor and neutral. In a balanced star system they have a defined relationship, but they are not interchangeable measurements.',
    distinction: 'Line values describe supply conductors; phase or line-to-neutral values describe the voltage applied to an individual star load element.',
    practice: 'A three-phase motor winding connected in star must be checked against the voltage across each winding, not only the supply’s line-to-line value.',
    followUp: { prompt: 'A balanced star supply is 400 V line-to-line. Is each line-to-neutral voltage also 400 V?', answer: 'No. The line-to-neutral voltage is lower, approximately 230 V in that system.', why: 'The two measurements are between different points and are related by the balanced star phasor relationship.' },
  },
  'p02-l03-q-concept-3': {
    prompt: 'What happens to neutral current when three linear phase loads are equal and balanced?',
    correct: 'Their phase currents have a zero vector sum, so the fundamental neutral current is approximately zero.',
    wrong: [
      'The neutral carries the sum of all three phase currents because every current must return through it.',
      'The neutral carries the largest phase current because it is the common conductor.',
      'No neutral current proves that every circuit component is electrically safe.',
    ],
    errors: [
      'The phase currents are separated in angle, so their vector sum can cancel. They must not be added as three currents at the same instant and direction.',
      'Neutral current depends on the vector combination of phase currents, not on selecting the largest individual phase current.',
      'A balanced-current observation is limited evidence about load balance. It does not prove insulation, protective continuity, terminations or every other safety condition.',
    ],
    why: 'For equal linear three-phase loads, the three currents are equal in magnitude and spaced by 120 degrees. Their vector sum at the neutral point is zero, so the fundamental neutral current cancels.',
    distinction: 'Neutral-current assessment uses vector addition, not ordinary arithmetic addition of phase magnitudes.',
    practice: 'A substantial neutral current can reveal unbalanced single-phase loading or harmonic effects. It should be interpreted with the load type and measurement method in mind.',
    followUp: { prompt: 'Can three equal phase-current magnitudes still produce neutral current if their phase angles are not balanced as expected?', answer: 'Yes. Neutral current depends on the vector sum, so both magnitude and phase angle matter.', why: 'Equal numerical magnitudes alone do not guarantee cancellation.' },
  },
  'p02-l03-q-concept-4': {
    prompt: 'Why does phase sequence matter when connecting a three-phase motor?',
    correct: 'Changing the order of two phases reverses the rotating magnetic field and can reverse the motor’s rotation.',
    wrong: [
      'Phase sequence changes only the supply voltage magnitude, not the motor field direction.',
      'A motor always turns the same way because its shaft and bearings determine the direction.',
      'Phase sequence can be changed freely while a machine is running because only the motor speed is affected.',
    ],
    errors: [
      'The line voltage magnitude can remain normal while the phase order changes. The sequence changes the direction of the rotating field.',
      'Mechanical parts follow the electromagnetic torque direction; they do not set phase rotation independently of the supply sequence.',
      'Unexpected reversal can create a serious hazard. Rotation must be checked under controlled conditions using the proper procedure for the equipment.',
    ],
    why: 'A three-phase motor develops a rotating magnetic field from the ordered phase currents. Interchanging two phase conductors changes that order, reversing the field and therefore the possible direction of rotation.',
    distinction: 'Voltage magnitude and phase sequence are different properties of a three-phase supply.',
    practice: 'After installation or reconnection, motor rotation is checked with access controlled and the driven equipment considered before allowing normal operation.',
    followUp: { prompt: 'Two phase conductors are interchanged on an isolated motor circuit before recommissioning. What effect must be anticipated?', answer: 'The motor may rotate in the opposite direction when energised.', why: 'Interchanging two phases reverses the phase sequence and the rotating magnetic field direction.' },
  },
  'p02-l04-q-concept-1': {
    prompt: 'What defines a TN-S earthing arrangement?',
    correct: 'Neutral and protective functions remain separate throughout the supply path.',
    wrong: [
      'Neutral and protective functions are combined upstream and separated only at the installation origin.',
      'The installation relies on its own local electrode as the main earth connection.',
      'The neutral conductor is used as the circuit protective conductor on final circuits.',
    ],
    errors: [
      'This describes the upstream combined-and-separated arrangement of TN-C-S, not TN-S.',
      'This describes the local electrode feature of a TT arrangement, not TN-S.',
      'A circuit protective conductor has a protective function and is distinct from the neutral return path in a TN-S installation.',
    ],
    why: 'In TN-S, the source provides separate neutral and protective paths all the way to the installation. That arrangement determines the route earth-fault current is intended to take back to the source.',
    distinction: 'TN-S keeps the two functions separate throughout; TN-C-S combines them upstream before they are separated at the origin.',
    practice: 'Before relying on a loop-impedance or protective-device assumption, establish the actual earthing arrangement at the installation origin.',
    followUp: { prompt: 'Does a familiar supply voltage identify the earthing arrangement by itself?', answer: 'No. TN-S, TN-C-S and TT can have similar supply voltages but different protective fault paths.', why: 'Earthing arrangement is identified from the supply and protective-conductor arrangement, not from the nominal voltage alone.' },
  },
  'p02-l04-q-concept-2': {
    prompt: 'What is the defining sequence in a TN-C-S earthing arrangement?',
    correct: 'Neutral and protective functions are combined upstream and separated at the installation origin.',
    wrong: [
      'They remain separate throughout the entire supply path from source to final circuit.',
      'They are combined only within each final circuit after the protective device.',
      'They are replaced by a local earth electrode at the installation origin.',
    ],
    errors: [
      'Separate functions throughout describes TN-S rather than the combined upstream feature of TN-C-S.',
      'Combining neutral and protective functions within a final circuit would create an incorrect downstream arrangement, not TN-C-S supply configuration.',
      'A local electrode is the defining earth connection for TT; it does not describe the combined upstream conductor in TN-C-S.',
    ],
    why: 'TN-C-S has a combined neutral-and-protective function in part of the supply network. At the installation origin the functions are separated into neutral and protective arrangements for the installation.',
    distinction: 'The point of separation matters. Upstream supply arrangements cannot be inferred from a downstream conductor simply looking separate.',
    practice: 'Supply characteristics and conductor arrangements must be confirmed at the origin before designing bonding, protective conductors or fault-loop verification.',
    followUp: { prompt: 'Why must neutral and protective functions not be casually reconnected together downstream of the origin in a TN-C-S installation?', answer: 'It can create unintended current paths and interfere with the designed protective and residual-current arrangements.', why: 'The supply separation establishes distinct normal-current and protective functions within the installation.' },
  },
  'p02-l04-q-concept-3': {
    prompt: 'What provides the installation earth connection in a TT arrangement?',
    correct: 'A local earth electrode connected as part of the installation protective arrangement.',
    wrong: [
      'A distributor-provided protective conductor that returns every fault directly to the transformer.',
      'The neutral bar in the consumer unit, used in place of an earth electrode.',
      'The armour of any cable entering the building, regardless of its design and termination.',
    ],
    errors: [
      'A distributor-provided protective path characterises TN arrangements. TT relies on the installation’s local electrode for its earth connection.',
      'Neutral is not a substitute for an earth electrode or circuit protective arrangement.',
      'Cable armour can have a protective role only where the cable and termination are designed for it. It does not automatically provide the TT earth connection.',
    ],
    why: 'A TT installation uses a local electrode as the installation earth connection. The fault path and protective measures must be assessed for that actual arrangement rather than assumed to behave like a TN supply.',
    distinction: 'An electrode connection is an earthing feature; it does not by itself prove that the required protective disconnection conditions are satisfied.',
    practice: 'TT design and verification consider the electrode arrangement, protective devices and the actual fault conditions together. Do not borrow a TN conclusion without checking the system.',
    followUp: { prompt: 'Can the presence of an earth electrode alone prove acceptable fault protection in a TT installation?', answer: 'No. The electrode, protective device and complete protective arrangement must be assessed together.', why: 'A physical electrode is only one part of the fault-protection decision.' },
  },
  'p02-l04-q-concept-4': {
    prompt: 'Why must the earthing arrangement be established before protection is designed or verified?',
    correct: 'It determines the intended fault-current path and therefore affects protective measures and verification.',
    wrong: [
      'It changes only the colour used for the protective conductor and not the fault path.',
      'It matters only after a fault has occurred, because normal operation is identical in every arrangement.',
      'It allows protective-device ratings to be selected without considering the actual source and circuit conditions.',
    ],
    errors: [
      'Conductor identification matters, but earthing arrangement is fundamentally about the electrical route available during a fault.',
      'Normal operation can hide the protective arrangement. Protection must be designed before a fault, not inferred from an appliance working normally.',
      'Protective-device selection depends on the actual fault current and loop conditions; earthing arrangement is one reason those conditions differ.',
    ],
    why: 'Earthing arrangement sets the intended return route for an earth fault. That route influences fault current, disconnection behaviour, bonding and the tests needed to establish that protective measures are effective.',
    distinction: 'Earthing system is not a label. It is part of the physical fault path on which protection depends.',
    practice: 'When investigating or altering an installation, establish the earthing arrangement first, then decide which loop, electrode, bonding and protective-device checks are relevant.',
    followUp: { prompt: 'A circuit operates normally. Does that observation establish that its earthing arrangement and fault protection are correct?', answer: 'No. Normal operation does not test the fault-current path or protective disconnection behaviour.', why: 'Fault protection requires its own inspection, design assessment and testing evidence.' },
  },
  'p02-l05-q-concept-1': {
    prompt: 'What is the protective purpose of earthing an exposed conductive part?',
    correct: 'It connects the part into the intended protective fault-current return path.',
    wrong: [
      'It carries the circuit’s normal return current instead of the neutral conductor.',
      'It prevents any earth-fault current from flowing through the protective arrangement.',
      'It makes every metal part safe without a sound connection back through the protective path.',
    ],
    errors: [
      'The neutral carries normal return current. A protective conductor is not intended to carry normal load current.',
      'Earthing provides a route for fault current so protective measures can operate; it does not prevent the fault current from having a return path.',
      'A protective path must be continuous and suitably connected. A loose or high-resistance connection weakens its protective function.',
    ],
    why: 'Protective earthing connects exposed conductive parts to the protective arrangement. If a fault makes a metal enclosure live, the path supports fault current and the operation of the relevant protective measure.',
    distinction: 'Earthing provides the fault path; it does not replace the neutral or guarantee protection without continuity and coordinated devices.',
    practice: 'When an appliance enclosure is earthed, inspect and test the protective conductor connection rather than assuming the visible green-and-yellow insulation proves a sound path.',
    followUp: { prompt: 'Why is an open circuit protective conductor dangerous if a line conductor contacts a metal enclosure?', answer: 'The intended fault-current return path may be interrupted, so the enclosure can remain at a hazardous voltage without the protective device operating as intended.', why: 'The protective conductor must be continuous for the fault path to work.' },
  },
  'p02-l05-q-concept-2': {
    prompt: 'What is the protective purpose of bonding conductive parts that could be touched together?',
    correct: 'It limits dangerous differences in touch potential between those parts during a fault condition.',
    wrong: [
      'It replaces the circuit protective conductor connected to an appliance enclosure.',
      'It carries all normal load current away from the neutral conductor.',
      'It guarantees that a protective device will operate without considering the fault path.',
    ],
    errors: [
      'Bonding and the circuit protective conductor have different roles. A bonded pipe is not a substitute for an appliance’s protective conductor.',
      'Bonding is not a normal current-carrying return path. It is part of limiting potential differences between conductive parts.',
      'Bonding can reduce touch-voltage differences, but protective-device operation still depends on the complete fault path and coordinated protective measures.',
    ],
    why: 'Bonding connects conductive parts that may be touched together so that a fault is less likely to create a dangerous voltage difference between them. It works alongside, rather than in place of, earthing and circuit protective conductors.',
    distinction: 'Earthing provides a fault-current path; bonding limits potential difference between touchable conductive parts.',
    practice: 'Trace bonding separately from circuit protective conductors on a schematic. Asking which parts may be touched together helps explain why the connection is needed.',
    followUp: { prompt: 'Why is a bonded metal pipe not a substitute for the circuit protective conductor of an appliance?', answer: 'Bonding limits potential difference between conductive parts, while the appliance protective conductor provides its intended fault-current path.', why: 'The two measures support safety in different ways and neither replaces the other.' },
  },
  'p02-l05-q-concept-3': {
    prompt: 'Why does bonding not remove the need for a reliable circuit protective conductor?',
    correct: 'Bonding limits touch-voltage differences, but the circuit protective conductor provides the appliance fault-current return path.',
    wrong: [
      'Bonding carries a larger normal current than a circuit protective conductor and therefore makes it unnecessary.',
      'Bonding turns every conductive part into an insulating barrier against a fault.',
      'Bonding is only a label for the same conductor used as the circuit protective conductor.',
    ],
    errors: [
      'Neither bonding nor a circuit protective conductor is intended as a normal load-current path. Their purpose is protective, but their connections and functions differ.',
      'Bonding connects conductive parts; it does not insulate them or prevent a fault from energising an enclosure.',
      'The conductors can be physically distinct and serve different protective functions. Treating them as the same loses the reason each is assessed.',
    ],
    why: 'A circuit protective conductor connects an appliance’s exposed conductive parts into the protective fault path. Bonding reduces potential difference between other conductive parts that may be touched together. Both need sound connections because they solve different parts of the fault problem.',
    distinction: 'Reducing touch potential is not the same as providing a complete return path to operate protection.',
    practice: 'A continuity result through an unintended parallel metal path can hide a damaged bonding or protective conductor. Use inspection and a suitable method to confirm the intended path.',
    followUp: { prompt: 'A metal service pipe is bonded, but an appliance protective conductor is disconnected. What protective issue remains?', answer: 'The appliance may lack its intended fault-current return path, even though the pipe bonding is present.', why: 'Bonding does not replace the appliance circuit protective conductor.' },
  },
  'p02-l05-q-concept-4': {
    prompt: 'How do earthing and bonding work together in fault protection?',
    correct: 'Earthing supports the fault-current path, while bonding reduces potential differences between conductive parts that may be touched together.',
    wrong: [
      'Earthing and bonding are interchangeable names for one connection with exactly the same purpose.',
      'Earthing reduces touch potential, while bonding carries fault current back to the source.',
      'Either measure alone makes conductor continuity and protective-device selection unnecessary.',
    ],
    errors: [
      'They are related protective measures, but each addresses a different part of the fault problem.',
      'This reverses their main roles. Earthing connects into the protective fault path; bonding limits differences between touchable conductive parts.',
      'Both measures rely on suitable conductors, connections and protective arrangements. Neither makes the wider design and verification unnecessary.',
    ],
    why: 'Earthing and bonding are coordinated protective measures. Earthing connects exposed conductive parts to the intended protective arrangement, while bonding helps keep simultaneously touchable conductive parts closer in potential under fault conditions.',
    distinction: 'Both support safety, but the question each answers is different: fault-current path versus touch-voltage difference.',
    practice: 'When reviewing a building, identify the appliance protective conductor and the main bonding connections separately before deciding what inspection or continuity evidence is needed.',
    followUp: { prompt: 'Which measure primarily addresses a dangerous voltage difference between a metal pipe and another touchable conductive part?', answer: 'Bonding.', why: 'Bonding is used to limit potential difference between conductive parts that may be contacted together.' },
  },
  'p02-l06-q-concept-1': {
    prompt: 'What causes a conventional fuse to operate on excessive current?',
    correct: 'Its calibrated element heats and melts when the current-time condition exceeds its design limit.',
    wrong: [
      'It detects the cable insulation colour and opens when the colour indicates a fault.',
      'It measures earth continuity and opens whenever a protective conductor is present.',
      'It opens at exactly the same time for every current above its rated current.',
    ],
    errors: [
      'A fuse responds to heating caused by current, not to the visible colour of the connected cable.',
      'Protective continuity is a different condition. A fuse is an overcurrent protective device, not an earth-continuity tester.',
      'Fuse operation depends on the magnitude and duration of overcurrent. Larger faults usually produce a different operating time from smaller overloads.',
    ],
    why: 'Current produces heating in a fuse element. The element and surrounding construction are designed so that excessive current for a sufficient time melts the element and interrupts the circuit.',
    distinction: 'A fuse responds to current and time; it does not inspect conductor appearance or prove an earthing arrangement.',
    practice: 'When a fuse has operated, do not replace it repeatedly without investigating whether the circuit has overload, fault current or an unsuitable device selection.',
    followUp: { prompt: 'Why can a modest overload and a large short circuit operate the same fuse in different times?', answer: 'They produce different heating conditions in the fuse element, so the time-current characteristic gives different operating times.', why: 'Protective operation is related to both current magnitude and duration.' },
  },
  'p02-l06-q-concept-2': {
    prompt: 'What distinguishes a circuit breaker from a fuse in normal service?',
    correct: 'A circuit breaker uses resettable operating mechanisms with specified protective characteristics.',
    wrong: [
      'A circuit breaker has no time-current characteristic because it can be reset after a trip.',
      'A circuit breaker is suitable whenever its ampere rating matches the load, regardless of fault level.',
      'A circuit breaker protects a circuit by permanently joining line and neutral during an overload.',
    ],
    errors: [
      'Resettable operation does not remove the need for a defined response to overload and short-circuit conditions.',
      'Current rating is only one property. Breaking capacity and operating characteristic must also suit the circuit and available fault current.',
      'A protective device interrupts the circuit when it operates. Joining line and neutral would create a fault rather than protect against one.',
    ],
    why: 'Circuit breakers are resettable devices, but they still have defined trip characteristics and breaking capacities. The device selected has to coordinate with its conductors, load and prospective fault conditions.',
    distinction: 'Resettable does not mean universally suitable; a breaker still has a specified operating and interrupting duty.',
    practice: 'Before replacing a breaker, confirm the actual circuit, conductor capacity, fault level and required protective behaviour instead of copying a familiar ampere rating.',
    followUp: { prompt: 'Can a resettable breaker be assumed to have the correct breaking capacity for every installation?', answer: 'No. Its breaking capacity must be adequate for the prospective fault current at its location.', why: 'Resettable operation and safe interruption of a high fault current are separate characteristics.' },
  },
  'p02-l06-q-concept-3': {
    prompt: 'Why does a protective-device ampere rating alone not establish a suitable selection?',
    correct: 'The device must also have suitable operating characteristics and breaking capacity for the circuit fault conditions.',
    wrong: [
      'The ampere rating is the only value that matters because it always equals the available fault current.',
      'Breaking capacity describes the normal load current the circuit is expected to carry.',
      'A device with a larger ampere marking always provides faster and more complete protection.',
    ],
    errors: [
      'Normal circuit current and prospective fault current are different quantities. The ampere rating does not automatically equal fault duty.',
      'Breaking capacity is the fault current a device can interrupt safely under stated conditions, not its normal load-current rating.',
      'A larger rating can be unsuitable for the conductors and protective requirements. More amperes is not automatically more protection.',
    ],
    why: 'A protective device needs coordinated current rating, operating curve and breaking capacity. The device must protect the circuit in normal overload conditions and be able to interrupt the fault current that could occur at its installation point.',
    distinction: 'Rated current describes intended continuous duty; breaking capacity describes safe interruption of prospective fault current.',
    practice: 'A breaker can carry the expected load without being suitable to interrupt the highest fault current available at a board near the supply origin.',
    followUp: { prompt: 'A breaker has the correct nominal current for a cable. What fault-related value must still be checked?', answer: 'Its breaking capacity against the prospective fault current at that point.', why: 'Cable coordination does not by itself establish the device can interrupt the available fault duty.' },
  },
  'p02-l06-q-concept-4': {
    prompt: 'What does a protective device time-current characteristic tell the designer?',
    correct: 'How the device’s operating time changes with the magnitude and type of overcurrent.',
    wrong: [
      'The physical distance that a fault current travels through the installation.',
      'The maximum cable length that can be installed without any other design check.',
      'The normal energy use of the connected appliance over time.',
    ],
    errors: [
      'A time-current curve describes device response, not the physical route of current through conductors.',
      'Cable length affects several design conditions, but a time-current curve alone cannot approve a cable route.',
      'Energy consumption concerns power and operating time. The protective characteristic concerns abnormal current response.',
    ],
    why: 'Protective devices respond differently to overload and high fault current. Their time-current characteristic shows the relationship between overcurrent magnitude and the time in which the device is expected to operate.',
    distinction: 'Time-current behaviour is protective response, not a cable route measurement or an appliance energy calculation.',
    practice: 'When assessing fault protection, use the actual device characteristic with the available fault current and the required disconnection condition.',
    followUp: { prompt: 'Why might two overcurrents not cause a fuse or breaker to operate in the same time?', answer: 'Their magnitudes differ, and the device time-current characteristic gives a different response at each current level.', why: 'The curve links the severity of overcurrent to the expected operating time.' },
  },
  'p02-l07-q-concept-1': {
    prompt: 'What current balance should an RCD normally see in a healthy single-phase circuit?',
    correct: 'The current leaving on line is matched by the current returning through its associated neutral path.',
    wrong: [
      'The line current is expected to be greater because the appliance uses up current.',
      'The neutral must carry no current because it is connected to earth at the supply.',
      'The RCD compares the normal current with the circuit breaker ampere rating.',
    ],
    errors: [
      'A load transfers energy but does not use up charge. In a healthy circuit the outgoing current has a corresponding return path.',
      'Neutral is a normal current-carrying return conductor. Its supply connection does not mean normal load current disappears from it.',
      'An RCD compares the currents passing through its sensing arrangement; device ampere rating is a separate protective characteristic.',
    ],
    why: 'An RCD senses the combined magnetic effect of the line and neutral currents passing through its core. Equal outgoing and returning currents largely cancel, producing a near-zero residual balance.',
    distinction: 'RCD sensing compares current balance, not load size or protective-conductor continuity.',
    practice: 'A borrowed neutral can cause an RCD to trip because the line current of one circuit and its expected neutral return no longer pass through the same sensing device.',
    followUp: { prompt: 'A circuit draws 5 A on line and 5 A returns through its associated neutral. What residual balance should the RCD see?', answer: 'Approximately zero residual imbalance.', why: 'The opposing magnetic effects of equal line and neutral currents cancel in the sensing core.' },
  },
  'p02-l07-q-concept-2': {
    prompt: 'What does an RCD imbalance indicate?',
    correct: 'Some outgoing current is returning by a path other than the associated neutral through the sensing core.',
    wrong: [
      'The appliance has used up part of the current while performing useful work.',
      'The circuit breaker ampere rating is too large for the connected load.',
      'The protective conductor has become the intended normal return conductor.',
    ],
    errors: [
      'Useful work transfers energy; it does not consume charge so that less current returns.',
      'An overload may require its own protection, but RCD imbalance is about a difference between outgoing and returning currents.',
      'A protective conductor is not the intended normal return path. Current taking another path can create the imbalance the RCD detects.',
    ],
    why: 'If line and neutral current through the RCD do not balance, some current has taken another route. The device is designed to respond when that residual current and duration meet its operating characteristic.',
    distinction: 'Residual current is missing return current, not ordinary appliance current or a measure of energy use.',
    practice: 'Leakage to earth, a borrowed neutral or an incorrect connection can produce imbalance. Diagnose the actual return path rather than simply resetting the device.',
    followUp: { prompt: 'Does an RCD trip prove that one specific appliance is faulty?', answer: 'No. It proves an imbalance has been detected; the circuit, connections and connected equipment still need investigation.', why: 'Several fault or connection conditions can produce residual imbalance.' },
  },
  'p02-l07-q-concept-3': {
    prompt: 'When does an RCD trip mechanism operate?',
    correct: 'When residual imbalance satisfies the device’s specified operating characteristic.',
    wrong: [
      'Whenever the circuit reaches its normal design current.',
      'Only after the connected cable insulation has visibly melted.',
      'Whenever line-to-neutral voltage falls slightly below nominal.',
    ],
    errors: [
      'Normal load current can be equal on line and neutral, giving little residual imbalance. Load rating and residual operation are different conditions.',
      'The RCD is intended to respond to residual imbalance, not wait for visible insulation damage.',
      'Voltage magnitude is not the quantity the RCD sensing core compares. It detects current difference.',
    ],
    why: 'An RCD has a specified residual-current sensitivity and operating behaviour. It trips when the measured imbalance reaches the conditions for which that device is designed to operate.',
    distinction: 'An RCD responds to imbalance; an overcurrent device responds to excessive circuit current.',
    practice: 'Use the correct instrument method and device data when testing RCD operation. The built-in test button checks a limited device function and does not replace installation verification.',
    followUp: { prompt: 'Can a healthy circuit draw a large normal current without causing an RCD imbalance?', answer: 'Yes, if the same current returns through the associated neutral path and the device is within its normal rating.', why: 'RCD sensing compares line and neutral current balance rather than simply the size of load current.' },
  },
  'p02-l07-q-concept-4': {
    prompt: 'Why does an RCD not necessarily provide complete overcurrent protection?',
    correct: 'It detects residual-current imbalance; overload and short-circuit protection may require a separate coordinated device.',
    wrong: [
      'Residual-current sensing automatically measures every overload in the line conductor.',
      'An RCD has a circuit protective conductor built into it, so no other protection is required.',
      'Any device with a test button combines all protective functions in one unit.',
    ],
    errors: [
      'A balanced overload can have equal line and neutral current, leaving no residual imbalance for the RCD to detect.',
      'A protective conductor is part of the installation arrangement, not a replacement for correctly selected overcurrent protection.',
      'A test button demonstrates a particular device test function; it does not identify every protective function included in the device.',
    ],
    why: 'An RCD is designed to respond to current imbalance. A separate fuse, MCB or combined device may be needed to deal with overload and short-circuit conditions according to the circuit design.',
    distinction: 'Residual-current protection and overcurrent protection are different protective jobs.',
    practice: 'Read device markings and the distribution arrangement before assuming what protection a circuit has. An RCBO combines residual-current and overcurrent functions; an RCD alone may not.',
    followUp: { prompt: 'A circuit has a balanced overload with equal line and neutral current. Why might an RCD alone not disconnect it?', answer: 'There may be no residual imbalance, so separate overcurrent protection is needed for the overload condition.', why: 'Equal outgoing and returning current can leave RCD sensing near zero even when circuit current is excessive.' },
  },
  'p02-l08-q-concept-1': {
    prompt: 'What protection does an RCD provide by itself?',
    correct: 'Residual-current protection by detecting an imbalance between outgoing and returning current.',
    wrong: [
      'Complete overload and short-circuit protection for every circuit connected downstream.',
      'A direct test of protective-conductor continuity whenever its test button is pressed.',
      'Automatic identification of which appliance is drawing the largest load current.',
    ],
    errors: [
      'An RCD may need separate overcurrent protection. Its sensing principle is residual imbalance, not complete overcurrent protection.',
      'The test button checks a built-in device function. It does not measure the protective conductor through the installation.',
      'RCD sensing compares line and neutral current balance; it does not identify or rank appliance load current.',
    ],
    why: 'An RCD detects current that does not return through the expected neutral path in its sensing core. That residual-current function is separate from the overload and short-circuit protection a circuit may also need.',
    distinction: 'Residual-current protection responds to imbalance; overcurrent protection responds to excessive circuit current.',
    practice: 'When reviewing a board, identify whether an RCD is protected by an upstream device or whether a combined device is being used for the final circuit.',
    followUp: { prompt: 'Does an RCD test-button operation prove that an appliance circuit has overload protection?', answer: 'No. It proves only the RCD built-in test function has operated; overcurrent protection must be identified separately.', why: 'A test result must be limited to the function actually tested.' },
  },
  'p02-l08-q-concept-2': {
    prompt: 'What additional protective function does an RCBO combine with residual-current detection?',
    correct: 'Overload and short-circuit protection for its assigned circuit.',
    wrong: [
      'A permanent substitute for the circuit protective conductor.',
      'The ability to combine the neutral conductors of several circuits without consequence.',
      'A guarantee that every circuit at the board will remain energised after any fault.',
    ],
    errors: [
      'An RCBO is a protective device, not a replacement for the installation protective-conductor path.',
      'Each RCBO sensing arrangement requires its circuit’s return current to be routed correctly. Combining neutrals can cause incorrect residual sensing and other hazards.',
      'Individual RCBOs can limit how many circuits disconnect for one fault, but they do not guarantee uninterrupted supply in every condition.',
    ],
    why: 'An RCBO combines residual-current protection with overcurrent protection in one device for its assigned circuit. Its selected rating and characteristics still have to match the circuit conductors, load and fault conditions.',
    distinction: 'An RCBO combines two protective functions; it does not remove the need for correct neutral, protective-conductor and circuit design.',
    practice: 'A board using individual RCBOs can reduce unnecessary loss of other circuits after a fault, but each circuit must retain its correct neutral connection and identification.',
    followUp: { prompt: 'Why can a borrowed neutral cause trouble on a circuit protected by an RCBO?', answer: 'The circuit’s line and associated neutral currents may no longer pass through the same sensing arrangement, creating an imbalance.', why: 'Residual-current devices depend on the correct pairing of outgoing and return current paths.' },
  },
  'p02-l08-q-concept-3': {
    prompt: 'Why can individual RCBOs reduce the number of circuits lost after one fault?',
    correct: 'Each assigned circuit has its own residual-current and overcurrent protective device.',
    wrong: [
      'An RCBO prevents faults from occurring on the circuit it protects.',
      'All circuits share one RCBO, so it can distinguish every appliance automatically.',
      'The device makes the circuit independent of the incoming supply and main switch.',
    ],
    errors: [
      'Protection limits fault consequences; it does not prevent every fault or defect from occurring.',
      'A shared device can disconnect several circuits together. Individual RCBO arrangements separate protection by assigned circuit.',
      'An RCBO remains part of the distribution system and does not create an independent source or remove the role of the main switch.',
    ],
    why: 'With individual RCBOs, a residual or overcurrent fault on one assigned final circuit can operate that circuit’s device without necessarily disconnecting other independently protected circuits.',
    distinction: 'Selective loss of supply is a benefit of circuit separation, not proof that the fault has been repaired or that other circuits need no verification.',
    practice: 'After an RCBO operation, identify the affected circuit, investigate the cause and complete the necessary verification before restoring supply.',
    followUp: { prompt: 'An RCBO trips on one final circuit while adjacent RCBO-protected circuits remain on. What does this show?', answer: 'The protection arrangement has isolated the affected assigned circuit separately; it does not by itself identify the fault cause.', why: 'Circuit separation limits supply loss, while diagnosis still requires investigation.' },
  },
  'p02-l08-q-concept-4': {
    prompt: 'Why must RCBO markings match the intended circuit?',
    correct: 'Its residual-current type, current rating and protective characteristics must suit the circuit, load and conditions.',
    wrong: [
      'Any RCBO is interchangeable provided it physically fits the consumer unit.',
      'The highest available ampere rating is always the safest replacement choice.',
      'The marking matters only for recording the circuit after installation is complete.',
    ],
    errors: [
      'Physical fit does not establish electrical compatibility, current coordination, residual-current type or fault-interrupting suitability.',
      'A larger rating can leave conductors inadequately protected or be unsuitable for the required device characteristic.',
      'Markings are selection data used before installation and verification, not only a label for later records.',
    ],
    why: 'RCBO markings identify key characteristics that must be coordinated with the actual circuit. The chosen device must provide the required residual response, overcurrent protection and fault duty for the conductor, load and installation conditions.',
    distinction: 'A device fitting the enclosure is a mechanical fact; suitability is an electrical design and verification decision.',
    practice: 'Before replacement, identify the circuit conductor size, installation conditions, load, existing protective design and the manufacturer-approved device range for the board.',
    followUp: { prompt: 'A replacement RCBO fits physically in a board but has a different characteristic from the design. Is physical fit enough to approve it?', answer: 'No. Its protective characteristics must be checked against the circuit design and conditions.', why: 'Mechanical compatibility does not prove protection coordination.' },
  },
  'p07-l13-q-concept-1': {
    prompt: 'What does one line normally represent on a three-phase single-line diagram?',
    correct: 'The complete three-phase circuit path represented symbolically rather than every separate conductor.',
    wrong: [
      'Only one phase conductor, with the other phases omitted because they are not relevant.',
      'A neutral conductor that carries all of the building load current.',
      'A physical cable route drawn to scale through the building.',
    ],
    errors: [
      'A single-line diagram simplifies all phases of a three-phase path. It does not imply that only one phase exists in the installation.',
      'The line is a diagram convention for a circuit path, not a depiction of a particular neutral conductor.',
      'A single-line diagram shows functional distribution and protection. A route drawing or layout is needed to show physical cable paths.',
    ],
    why: 'A single-line diagram uses one symbolic line to communicate a complete multi-conductor supply path. It keeps the source, switching, protection and downstream distribution readable without drawing every phase separately.',
    distinction: 'Single-line is a functional electrical representation, not a scaled route drawing or a one-phase-only circuit.',
    practice: 'Trace a feeder from the source through its protective device to a downstream board, then use schedules and layout information to identify the actual cables and loads.',
    followUp: { prompt: 'Why can a three-phase feeder appear as one line on a single-line diagram?', answer: 'The line is a symbolic representation of the complete three-phase circuit path.', why: 'The diagram compresses repeated conductor detail so that the distribution and protection path can be read clearly.' },
  },
  'p07-l13-q-concept-2': {
    prompt: 'What information do device ratings add to a single-line diagram?',
    correct: 'They identify the switching and protective duty at each level of the distribution system.',
    wrong: [
      'They show the exact physical location and height of every electrical accessory.',
      'They prove that the connected conductors are correctly terminated without inspection.',
      'They replace the need to assess prospective fault current and installation conditions.',
    ],
    errors: [
      'Physical locations belong on layouts or installation drawings. Device ratings describe electrical duty.',
      'A diagram rating cannot prove workmanship. Terminations need their own inspection and verification evidence.',
      'Ratings are design information. Suitability still depends on the actual circuit, fault level, conductor and installation conditions.',
    ],
    why: 'Ratings on a single-line diagram help the reader understand which devices switch, protect and isolate at each point in the supply path. They support design review but do not replace inspection or calculations.',
    distinction: 'A rated value describes intended device capability; it is not proof that the installed circuit has been verified.',
    practice: 'Use the diagram to identify a feeder device, then compare its rating and characteristics with the panel schedule, cable data and fault assessment.',
    followUp: { prompt: 'Can a breaker rating printed on a diagram prove that its installed terminals are sound?', answer: 'No. Ratings describe the device duty; connection quality requires inspection and relevant testing.', why: 'Design information and installation evidence answer different questions.' },
  },
  'p07-l13-q-concept-3': {
    prompt: 'Why are feeder labels important on a single-line diagram?',
    correct: 'They connect the symbolic feeder path to cable, schedule and equipment information.',
    wrong: [
      'They are decorative names that can be changed without checking any other record.',
      'They identify the phase sequence without the need for terminal markings or tests.',
      'They replace circuit protective-conductor identification at equipment terminals.',
    ],
    errors: [
      'Feeder labels create traceable references between documents and equipment. Changing them without coordination creates ambiguity.',
      'A feeder label identifies a circuit reference; phase sequence needs its own identification and controlled verification.',
      'A drawing reference does not replace conductor identification or the protective connection at the equipment.',
    ],
    why: 'A feeder identifier ties together the diagram, panel schedule, cable information and the physical equipment. Consistent identifiers let a worker trace the real supply path instead of relying on memory or appearance.',
    distinction: 'A drawing reference identifies a circuit; conductor markings identify functions within that circuit.',
    practice: 'Before isolating a feeder, trace its label through the single-line diagram and panel schedule, then verify the actual equipment and circuit identity on site.',
    followUp: { prompt: 'What risk is created when the feeder label on a diagram does not match the panel schedule?', answer: 'The supply path can be misidentified, leading to incorrect planning, isolation or alteration work.', why: 'Cross-referenced records are useful only when their identifiers agree.' },
  },
  'p07-l13-q-concept-4': {
    prompt: 'Why must an earthing arrangement be clear on a single-line diagram?',
    correct: 'It provides information needed to understand protective fault paths and safety decisions.',
    wrong: [
      'Earthing affects only the drawing colour scheme and not the electrical protective arrangement.',
      'The normal supply voltage makes the earthing arrangement irrelevant to fault protection.',
      'A diagram can assume an earthing arrangement because all buildings use the same fault return path.',
    ],
    errors: [
      'Earthing is a physical protective arrangement, not a drawing decoration. It affects the path available during an earth fault.',
      'Similar normal supply voltage can exist with different earthing and fault-current arrangements.',
      'Earthing systems and source arrangements differ. A protection decision must follow the actual arrangement, not an assumption.',
    ],
    why: 'The earthing arrangement affects the intended earth-fault path, protective measures and verification required for the distribution system. Making it clear on the diagram supports safe design, alteration and investigation.',
    distinction: 'Normal operation can look similar across systems; fault protection depends on the actual source and earthing arrangement.',
    practice: 'Use the diagram as a starting point, then confirm the earthing arrangement and supply characteristics at the installation origin before relying on a protective conclusion.',
    followUp: { prompt: 'Why is a supply voltage reading alone not enough to identify an earthing arrangement?', answer: 'Different earthing systems can have the same nominal voltage but different protective fault paths and measures.', why: 'Earthing arrangement is determined by conductor and source relationships, not nominal voltage alone.' },
  },
  'p07-l14-q-concept-1': {
    prompt: 'Which drawing is most useful for tracing electrical paths, switching and protection through a distribution system?',
    correct: 'A single-line diagram.',
    wrong: [
      'A riser diagram, because it is intended primarily to show vertical distribution between levels.',
      'A block diagram, because it omits the protective and switching detail needed to trace the electrical path.',
      'A reflected ceiling plan, because it shows the physical locations of fittings rather than the complete supply path.',
    ],
    errors: [
      'A riser diagram is valuable for vertical distribution, but a single-line diagram is the view that emphasises the electrical path, switching and protection.',
      'A block diagram simplifies functional relationships. It may not contain the circuit and protective detail needed for electrical tracing.',
      'A ceiling plan assists physical coordination; it does not normally show the complete upstream electrical distribution and protective path.',
    ],
    why: 'A single-line diagram represents the supply and distribution path through switching and protection devices. It gives the reader a compact view of how power reaches downstream boards and loads.',
    distinction: 'Single-line diagrams explain electrical paths; riser diagrams explain vertical distribution; block diagrams explain functional relationships.',
    practice: 'Before working on a downstream board, use the single-line diagram with schedules and site identification to trace the feeder and upstream isolation path.',
    followUp: { prompt: 'A question concerns which upstream protective device supplies a distribution board. Which drawing should you consult first?', answer: 'The single-line diagram.', why: 'It is designed to show electrical paths, switching and protection through the distribution system.' },
  },
  'p07-l14-q-concept-2': {
    prompt: 'What does a riser diagram show that a single-line diagram may not make as clear?',
    correct: 'How distribution boards and feeders are arranged between floors or vertical zones of a building.',
    wrong: [
      'The detailed internal terminal wiring of every accessory on each floor.',
      'The precise time-current curve of every protective device.',
      'The physical movement of electrons through every conductor in the building.',
    ],
    errors: [
      'A riser diagram is not a detailed terminal wiring drawing. It is a distribution view between levels or zones.',
      'Protective device curves require device data. A riser diagram shows system distribution, not detailed protective performance.',
      'Electrical drawings represent circuits and equipment, not the physical path of individual charge carriers.',
    ],
    why: 'A riser diagram focuses on how supplies move vertically through a building, for example from a main distribution point to boards serving different floors. It helps coordinate the distribution arrangement across the building structure.',
    distinction: 'A riser is a vertical distribution view, not a complete wiring detail or protection-characteristic record.',
    practice: 'Use a riser diagram when coordinating feeders through risers, service shafts and floor distribution areas, then use the single-line and schedule for electrical detail.',
    followUp: { prompt: 'Which drawing would best show the relationship between a ground-floor main board and distribution boards on several upper floors?', answer: 'A riser diagram.', why: 'It is designed to show vertical distribution between floors or zones.' },
  },
  'p07-l14-q-concept-3': {
    prompt: 'What is the purpose of a block diagram in an electrical project?',
    correct: 'To show simplified functional relationships between parts of the system.',
    wrong: [
      'To replace all conductor, terminal and protective-device information needed for installation work.',
      'To provide a measured route drawing for cable containment and building penetrations.',
      'To prove that the connected equipment has passed electrical verification.',
    ],
    errors: [
      'Block diagrams deliberately simplify detail. Installation work still needs the drawings, schedules, instructions and verification evidence appropriate to the task.',
      'Physical routes and coordination need layout or route information. A block diagram normally shows system function rather than measured building geometry.',
      'A functional diagram describes intended relationships; verification requires inspection and test evidence from the installed work.',
    ],
    why: 'A block diagram reduces a system to its main functional parts and the relationships between them. It helps a learner or project team understand what communicates, controls or supplies what before working with detailed circuit information.',
    distinction: 'A block diagram explains function; it does not replace installation detail, route information or test evidence.',
    practice: 'Use a block diagram to explain a control system to a client or to establish interfaces, then move to detailed drawings and equipment data before installation.',
    followUp: { prompt: 'Can a block diagram alone be used as the final instruction for terminating conductors at equipment?', answer: 'No. It shows functional relationships; detailed wiring, terminal and product information are still required.', why: 'Simplified functional representation is not a termination schedule.' },
  },
  'p07-l14-q-concept-4': {
    prompt: 'Why do electrical projects need shared equipment tags across different drawings?',
    correct: 'They let the reader cross-reference the same real equipment and circuit between separate drawing views.',
    wrong: [
      'They allow each drawing discipline to give the same equipment a different name without coordination.',
      'They replace the need to identify the actual equipment and conductors on site.',
      'They make protective-device ratings identical throughout the building.',
    ],
    errors: [
      'Different names for the same equipment create ambiguity. Shared tags are used to keep records coordinated.',
      'Drawing references guide identification, but actual equipment and conductor identity must still be confirmed before work.',
      'A tag is an identifier, not a rating or a statement that every device has the same protective duty.',
    ],
    why: 'The same board, feeder or item of equipment can appear on a single-line, riser, schedule and layout. A consistent tag links those views so that information from one document can be checked against the others.',
    distinction: 'A shared tag identifies the same asset across records; it does not replace on-site verification or describe every electrical characteristic.',
    practice: 'When a drawing and a schedule disagree, stop and resolve the reference before planning isolation, ordering equipment or making an alteration.',
    followUp: { prompt: 'What should be checked when a feeder has one name on the single-line diagram and another name on the panel schedule?', answer: 'Resolve the identification discrepancy before relying on either record for work or isolation planning.', why: 'Conflicting references can cause a real supply path to be misidentified.' },
  },
  'p07-l15-q-concept-1': {
    prompt: 'What does a single-line diagram reveal that a panel schedule does not show as clearly?',
    correct: 'The upstream and downstream distribution relationship between supplies, boards, feeders and protection.',
    wrong: [
      'The purpose and rating of every individual final-circuit way within one board.',
      'The physical condition of conductor terminations inside the board.',
      'The exact number of appliances presently operating on each circuit.',
    ],
    errors: [
      'That detailed way-by-way information belongs primarily in a panel schedule. A single-line diagram follows the wider distribution relationship.',
      'A drawing describes intended system arrangement. It does not prove the installed termination condition without inspection.',
      'Operating load can change. A single-line diagram shows the designed supply relationship, not a live count of connected appliances.',
    ],
    why: 'A single-line diagram gives a system-level view of how supplies and distribution boards are connected through feeders, switching and protection. It helps trace where power comes from and where it goes next.',
    distinction: 'The single-line diagram shows the distribution path; the panel schedule describes the individual ways within a particular board.',
    practice: 'Trace a load from its panel schedule way to the board, then use the single-line diagram to find the feeder and upstream protective devices serving that board.',
    followUp: { prompt: 'Which document should you use first to find the upstream feeder that supplies a particular distribution board?', answer: 'The single-line diagram.', why: 'It shows the upstream and downstream distribution relationship between boards and feeders.' },
  },
  'p07-l15-q-concept-2': {
    prompt: 'What information does a panel schedule provide for a particular distribution board?',
    correct: 'The individual circuit ways, their identifiers, protective devices, ratings and assigned loads or areas.',
    wrong: [
      'Only the complete vertical route of every feeder between floors.',
      'A simplified diagram of all system functions without individual circuit detail.',
      'Proof that every listed circuit has passed inspection and testing.',
    ],
    errors: [
      'Vertical distribution between levels is the focus of a riser diagram. A panel schedule focuses on ways within a board.',
      'A block diagram may simplify functional relationships, but the schedule identifies the specific circuit ways and their protective information.',
      'A schedule records design and circuit identification. Verification needs separate inspection and test evidence.',
    ],
    why: 'A panel schedule is the detailed record for one distribution board. It identifies individual circuit ways and the information needed to understand what each way supplies and how it is protected.',
    distinction: 'A schedule identifies the board’s individual circuits; it does not replace the wider distribution drawing or completed verification records.',
    practice: 'Use the panel schedule when investigating a specific final circuit, then cross-check the circuit identifier at the board and at the relevant equipment.',
    followUp: { prompt: 'Where should you expect to find the protective-device rating for a specific final circuit at one board?', answer: 'In that board’s panel schedule.', why: 'The schedule is the detailed way-by-way record for the distribution board.' },
  },
  'p07-l15-q-concept-3': {
    prompt: 'Why must circuit identifiers match between drawings, schedules and equipment?',
    correct: 'They prevent ambiguity when tracing, isolating, altering or verifying the same real circuit.',
    wrong: [
      'They make conductor colours unnecessary because the identifier replaces every conductor function.',
      'They allow a circuit to be isolated safely without confirming its actual identity on site.',
      'They prove that the circuit has enough capacity for any future additional load.',
    ],
    errors: [
      'Circuit references and conductor identification are different forms of information. Each supports a separate part of safe work.',
      'Records guide identification, but the actual circuit must still be confirmed before relying on isolation.',
      'An identifier tells the reader which circuit is being discussed. Capacity requires load, conductor, protection and installation assessment.',
    ],
    why: 'Consistent identifiers create a traceable chain from a diagram to a schedule, board label and physical circuit. This reduces the risk of acting on an assumed circuit when planning work or isolation.',
    distinction: 'A circuit identifier supports tracing; it is not proof of conductor function, isolation or circuit capacity.',
    practice: 'When an alteration changes a circuit, update its records only after the actual circuit identity and completed work have been established and verified.',
    followUp: { prompt: 'A schedule says Way 6 is a lighting circuit, but the board label says Way 6 supplies sockets. What should happen before work proceeds?', answer: 'The discrepancy must be resolved by tracing and confirming the actual circuit.', why: 'Conflicting records create unsafe ambiguity about the supply path.' },
  },
  'p07-l15-q-concept-4': {
    prompt: 'Why are phase columns useful on a three-phase panel schedule?',
    correct: 'They help the designer review how single-phase circuit loads are allocated across the three phases.',
    wrong: [
      'They prove that every circuit connected to the board is a balanced three-phase load.',
      'They replace measurements of actual phase currents after the installation is in service.',
      'They make a neutral conductor unnecessary for all single-phase circuits.',
    ],
    errors: [
      'A three-phase board often serves single-phase circuits. Phase columns help distribute those loads; they do not make every individual load three-phase.',
      'Design allocation supports planning, but operating loads and user behaviour can change. Actual current measurement can still be needed.',
      'Single-phase circuits commonly require their intended neutral return path. Phase allocation does not remove that circuit function.',
    ],
    why: 'Phase columns show the intended allocation of circuit ways across the three phases. They help avoid concentrating many single-phase loads on one phase and support a more balanced distribution design.',
    distinction: 'Planned phase allocation is a design aid; it is not proof that operating currents will remain perfectly balanced.',
    practice: 'Review the panel schedule before adding a substantial single-phase load, then assess the actual board capacity and measured or credible phase loading.',
    followUp: { prompt: 'Why might an electrician review phase columns before adding a large single-phase load to a three-phase board?', answer: 'To avoid unnecessarily concentrating load on one phase and worsening phase imbalance.', why: 'The panel schedule helps distribute planned single-phase circuit demand across the available phases.' },
  },
  'p02-l10-q-concept-1': {
    prompt: 'Why may meter tails need protective measures appropriate to their route and fault conditions?',
    correct: 'They can be exposed to high fault energy, so their route, protection and installation conditions must be coordinated.',
    wrong: [
      'They never need protection because they are always shorter than final-circuit conductors.',
      'Their conductor colour alone establishes that any route is safe.',
      'They carry only meter signals and cannot carry supply fault current.',
    ],
    errors: [
      'Length alone does not establish protection. The actual route, construction, source conditions and local requirements determine the protective arrangement needed.',
      'Conductor identification does not establish fault protection, route suitability or coordination with the supply equipment.',
      'Meter tails carry the supply to the installation and can be subject to significant fault conditions depending on the arrangement.',
    ],
    why: 'Meter tails are supply conductors between metering and the installation equipment. Their route and potential fault energy need suitable protective boundaries and coordination with the supply and downstream protective arrangements.',
    distinction: 'A familiar tail length is not a universal approval. Protection follows the actual route, construction and supply conditions.',
    practice: 'Map the supply path from meter to consumer unit or switch-fuse, identify the protection boundary and confirm who controls or approves each section before alteration.',
    followUp: { prompt: 'Can a familiar meter-tail length by itself prove that no additional protection is required?', answer: 'No. The route, construction, source conditions and applicable requirements must be considered together.', why: 'Length is only one possible factor in the protection decision.' },
  },
  'p02-l10-q-concept-2': {
    prompt: 'What function can a switch-fuse provide in a supply arrangement?',
    correct: 'It can combine a means of isolation with upstream overcurrent protection.',
    wrong: [
      'It replaces the need for every downstream protective device on final circuits.',
      'It proves that the meter tails are correctly installed without inspection.',
      'It is only a manually operated switch and has no overcurrent protective function.',
    ],
    errors: [
      'Upstream protection does not remove the need for coordinated protection of downstream circuits and their conductors.',
      'A device function does not prove route, termination, conductor condition or installation workmanship.',
      'A switch-fuse includes a fuse protective function as well as switching or isolation capability in the intended arrangement.',
    ],
    why: 'A switch-fuse can create a protection boundary near the supply while also providing a means of switching or isolation. Its selection must still coordinate with the tails, supply equipment and downstream distribution.',
    distinction: 'A switch-fuse can have both control and protective functions; neither function proves the rest of the installation is correct.',
    practice: 'When identifying an upstream switch-fuse, check its fuse data, rating, location, accessibility and the conductors it is intended to protect.',
    followUp: { prompt: 'Does a switch-fuse upstream of a consumer unit make all final-circuit protective devices unnecessary?', answer: 'No. Final circuits still need protection coordinated with their own conductors and fault conditions.', why: 'One upstream device cannot automatically provide every final-circuit protective function.' },
  },
  'p02-l10-q-concept-3': {
    prompt: 'Why must protection of meter tails coordinate with distributor equipment and downstream devices?',
    correct: 'The complete supply path must have suitable protective boundaries without defeating the intended duties of other equipment.',
    wrong: [
      'Only the downstream circuit breaker matters because the distributor equipment is outside the installation.',
      'Only the distributor equipment matters because downstream devices cannot affect fault conditions.',
      'Coordination means selecting identical fuse ratings for every device in the supply path.',
    ],
    errors: [
      'The supply path is connected. Downstream equipment and conductor conditions still need assessment even where another party controls upstream equipment.',
      'Downstream protection and installation design influence the complete arrangement and cannot be ignored.',
      'Coordination is not making every rating identical. Devices have different duties and must operate safely within the intended arrangement.',
    ],
    why: 'Meter-tail protection sits between supply equipment and downstream distribution. It has to be considered as part of the complete path so that conductors are protected and the installed devices perform their intended duties safely.',
    distinction: 'Coordination means compatible protective roles through the complete path, not a collection of matching numbers.',
    practice: 'Mark each protective device, cable section and ownership boundary on a supply sketch before deciding whether a proposed change needs a switch-fuse or other protective measure.',
    followUp: { prompt: 'Why is copying a familiar fuse rating without tracing the supply path unsafe?', answer: 'The rating may not suit the actual tail conductors, source fault conditions or downstream protective arrangement.', why: 'Protection must be coordinated with the real installation rather than with a remembered example.' },
  },
  'p02-l10-q-concept-4': {
    prompt: 'Why should a familiar meter-tail distance guidance not be treated as a universal design rule?',
    correct: 'Permitted arrangements depend on the local rules, cable construction, route and supply or utility agreement.',
    wrong: [
      'Distance never matters because meter tails cannot be damaged or overloaded.',
      'Every installation uses the same distributor equipment and fault level.',
      'Once a tail has been installed, its route and construction no longer affect protection.',
    ],
    errors: [
      'Meter tails can be subject to mechanical damage and fault conditions. Their installation is not exempt from protection assessment.',
      'Supply arrangements, available fault current and equipment conditions can differ between locations and installations.',
      'Protection depends on the installed arrangement. Route and construction remain relevant throughout the life of the installation.',
    ],
    why: 'Distance guidance has a context. Meter-tail decisions must consider local requirements, the actual cable construction and route, fault conditions and the supply arrangements or approvals that apply to the installation.',
    distinction: 'A remembered number is not a design method. The conditions attached to the guidance determine whether it applies.',
    practice: 'When tail work is proposed, establish ownership, supply conditions, routing and approved equipment before ordering parts or moving the meter connection.',
    followUp: { prompt: 'What should an electrician do when a familiar meter-tail distance is exceeded or the route is unusual?', answer: 'Assess the actual protection arrangement and applicable local or utility requirements instead of assuming the familiar guidance applies.', why: 'Unusual conditions can require a different protection boundary or approved arrangement.' },
  },
  'p02-l11-q-concept-1': {
    prompt: 'Why must the phase terminals of a three-phase plug be identified in their defined sequence?',
    correct: 'They carry ordered alternating waveforms, and their sequence can determine connected equipment behaviour such as motor rotation.',
    wrong: [
      'All phase terminals are electrically identical in use, so their order has no effect on connected equipment.',
      'The phase terminals carry protective current only when the neutral is disconnected.',
      'Phase sequence is determined by the plug body colour rather than by conductor identification and testing.',
    ],
    errors: [
      'Phase conductors have the same nominal system role but their order matters to three-phase loads such as motors.',
      'Phase conductors carry normal supply current. Protective current belongs to the protective arrangement during fault conditions, not the phase terminals.',
      'Appearance cannot establish electrical phase sequence. Use correct identification and the appropriate controlled verification method.',
    ],
    why: 'A three-phase supply has three alternating waveforms in a defined order. Interchanging two phases reverses that sequence, which can reverse a motor’s rotating field and direction of rotation.',
    distinction: 'Phase voltage magnitude and phase sequence are separate properties of the supply.',
    practice: 'Before supervised commissioning of a three-phase motor, confirm terminal functions and control access to the driven equipment before checking rotation.',
    followUp: { prompt: 'What can happen if two phase conductors are interchanged at a motor connection?', answer: 'The motor can rotate in the opposite direction.', why: 'Interchanging two phases reverses the phase sequence and rotating magnetic field direction.' },
  },
  'p02-l11-q-concept-2': {
    prompt: 'What must be true of the protective conductor in a three-phase plug and socket connection?',
    correct: 'It must remain correctly identified, reliably connected and continuous as part of the protective arrangement.',
    wrong: [
      'It may be used as a normal load-current return when a neutral conductor is unavailable.',
      'It is optional when the plug has a strong mechanical strain-relief clamp.',
      'Its connection can be checked only by looking at the terminal colour.',
    ],
    errors: [
      'The protective conductor is not an intended normal current return path. A missing neutral is a system-design issue, not a reason to misuse the protective conductor.',
      'Mechanical strain relief and protective continuity are separate requirements. One does not replace the other.',
      'Identification assists work, but protective continuity and terminal quality need inspection and relevant verification evidence.',
    ],
    why: 'The protective conductor connects exposed conductive parts into the protective arrangement. It must be reliably terminated and remain continuous so that an earth fault has the intended path for protective measures to operate.',
    distinction: 'Strain relief protects the cable mechanically; the protective conductor provides an electrical protective path.',
    practice: 'Inspect conductor engagement and strain relief separately. A cable can be mechanically clamped while its protective conductor is loose, damaged or incorrectly terminated.',
    followUp: { prompt: 'Does a secure cable clamp prove that a three-phase plug protective conductor is electrically sound?', answer: 'No. Mechanical strain relief and protective-conductor continuity must each be checked.', why: 'They are different parts of a sound connection.' },
  },
  'p02-l11-q-concept-3': {
    prompt: 'When is a neutral terminal needed in a three-phase plug and socket system?',
    correct: 'When the connected system or load requires a neutral conductor for its intended connection or supply.',
    wrong: [
      'In every three-phase connection because a neutral is needed to create the three phases.',
      'Never in a three-phase connection because all three-phase loads are always delta connected.',
      'Only when the protective conductor is too small to carry the normal return current.',
    ],
    errors: [
      'Three phases are generated and related independently of whether a particular load connection needs a neutral.',
      'Three-phase loads can use different connection arrangements, and some systems also serve line-to-neutral loads that require neutral.',
      'A protective conductor must not be used as a normal return conductor. Neutral need follows the designed system and load requirement.',
    ],
    why: 'A neutral is present where the supply arrangement and connected loads require it. Some three-phase loads operate between phases only, while other systems include line-to-neutral loads or star-connected requirements.',
    distinction: 'Three-phase supply does not automatically mean neutral is either always present or always absent.',
    practice: 'Identify the actual load terminals, supply arrangement and equipment instructions before selecting or terminating a plug and socket configuration.',
    followUp: { prompt: 'Can a three-phase motor connected only between phases require a neutral for that motor winding connection?', answer: 'Not necessarily. A phase-to-phase motor connection can operate without a neutral, subject to its actual design and supply arrangement.', why: 'Neutral requirement follows the connected system and load, not the phrase three-phase alone.' },
  },
  'p02-l11-q-concept-4': {
    prompt: 'Why are secure terminations and strain relief both required in a three-phase plug connection?',
    correct: 'They prevent conductor movement or pull from damaging the electrical connections while maintaining sound conductor contact.',
    wrong: [
      'A tight strain-relief clamp makes the individual terminal connections unimportant.',
      'Terminal screws alone protect the cable from pulling forces outside the plug.',
      'Strain relief is used only to improve the appearance of the finished plug.',
    ],
    errors: [
      'A clamp can secure the cable sheath while a conductor is still poorly engaged at its terminal. Both checks are needed.',
      'Terminal screws are not intended to take repeated cable pulling forces. Movement can loosen or damage the electrical connection.',
      'Strain relief has a mechanical safety function: it keeps cable movement from transferring force to the conductor terminations.',
    ],
    why: 'Terminations need adequate conductor contact, while strain relief holds the cable so pulling or movement is not transferred to individual conductor terminals. Together they reduce loose connections, damaged strands and heating risk.',
    distinction: 'Terminal contact carries the electrical duty; strain relief manages mechanical force on the cable.',
    practice: 'After terminating a plug, inspect conductor engagement, exposed copper, terminal torque as specified and the cable clamp gripping the sheath rather than individual insulated conductors.',
    followUp: { prompt: 'A plug cable clamp grips the sheath securely, but one phase conductor is loose in its terminal. Is the connection acceptable?', answer: 'No. Strain relief does not correct a poor electrical terminal connection.', why: 'Mechanical retention and conductor contact are separate requirements.' },
  },
};
