import type { Revision } from './question-revisions';

export const moduleTwoRevisions: Record<string, Revision> = {
  'p02-l01-q-concept-1': {
    prompt: 'A cable is chosen for a damp external route that may be struck or pulled during installation. What is the correct way to think about its layers?',
    correct: 'Each layer must provide the electrical, mechanical or environmental protection required by that route.',
    wrong: [
      'The conductor cross-sectional area alone decides whether the complete cable is suitable.',
      'Any outer covering gives the same protection once the cable has been clipped in place.',
      'A cable is suitable whenever its copper conductors can carry the expected load current.',
    ],
    errors: [
      'Conductor size deals with current capacity, but it does not establish insulation, impact protection or suitability for the environment.',
      'Outer coverings have different mechanical, moisture, UV and chemical capabilities; one covering cannot be assumed equivalent to another.',
      'Current capacity is only one part of cable selection. The installation route and termination method can require a different cable construction.',
    ],
    why: 'A cable is an assembly, not only a copper size. Its conductors carry current, insulation separates live parts, and the sheath or armour protects the assembly against conditions on the route. Selection must satisfy every duty the route creates.',
    distinction: 'Cable capacity answers a thermal question; cable construction answers protection and installation questions.',
    practice: 'Before choosing a cable for an exposed route, identify load current, mechanical risk, moisture, sunlight, containment, entries and the type of termination required.',
    followUp: { prompt: 'A cable has adequate current capacity but its sheath is not suitable for the exposed route. Is the cable selection complete?', answer: 'No. The cable still has to provide the environmental and mechanical protection required by the route.', why: 'A cable can pass its thermal calculation while failing the route or environmental part of selection.' },
  },
  'p02-l01-q-concept-2': {
    prompt: 'What is the key difference between conductor insulation and a cable outer sheath?',
    correct: 'Insulation separates conductors electrically, while the outer sheath protects the cable assembly.',
    wrong: [
      'Insulation is the outer layer that protects the cable from pulling and impact, while the sheath separates line and neutral.',
      'Both layers serve the same purpose, so damage to either layer has the same electrical consequence.',
      'The sheath carries fault current while insulation carries normal load current.',
    ],
    errors: [
      'This swaps the functions. Insulation is the electrical barrier around a conductor; the sheath surrounds and protects the assembled cable.',
      'Both layers are important, but they protect against different hazards. Damage to insulation can expose conductive parts electrically, while sheath damage can expose the assembly to the environment.',
      'Neither layer is intended to carry normal or fault current. Current-carrying and protective functions belong to the conductors and designed protective paths.',
    ],
    why: 'Each insulated conductor needs an electrical barrier from other conductive parts. The sheath sits outside the insulated conductors and protects the complete cable against handling and environmental conditions. A cable can need both layers even though they have different jobs.',
    distinction: 'Insulation controls electrical separation; the sheath protects the assembled cable.',
    practice: 'When stripping a cable, remove only the amount of sheath needed and avoid nicking the insulation beneath it, because a hidden insulation defect can later create a fault.',
    followUp: { prompt: 'A cable sheath is cut but the conductor insulation appears intact. Which protective function may already be reduced?', answer: 'Protection of the cable assembly against its installation environment and mechanical handling.', why: 'The sheath is the cable’s outer protective layer even when the inner electrical insulation has not yet been damaged.' },
  },
  'p02-l01-q-concept-3': {
    prompt: 'Why can armour be important in an electrical cable installation?',
    correct: 'It provides mechanical protection and, where designed for it, can contribute to protective continuity.',
    wrong: [
      'It replaces the need for conductor insulation because steel cannot carry normal load current.',
      'It exists only to make a cable heavier so that it remains in place without supports.',
      'It makes the cable suitable for every location without checking entries, glands or protective connections.',
    ],
    errors: [
      'Armour does not replace insulation. Conductors still need insulation to remain electrically separated from each other and from the metal armour.',
      'Armour has a protective construction role; cable support still has to resist the route’s weight, movement and environmental conditions.',
      'Armour must be terminated correctly and the complete installation still needs suitable glands, sealing, support and a verified protective path where applicable.',
    ],
    why: 'Armour helps resist mechanical damage to the cable. In a cable and termination system designed for it, the armour can also form part of the protective arrangement. Both uses depend on the cable construction and the quality of its termination.',
    distinction: 'Mechanical protection and protective continuity are separate functions; one does not prove the other automatically.',
    practice: 'An armoured cable entry must be prepared with the correct gland and bonding arrangement. A tight gland alone does not establish a reliable electrical protective connection.',
    followUp: { prompt: 'Can an armoured cable be assumed to provide sound protective continuity merely because the armour is visible?', answer: 'No. The armour and its terminations must be designed, connected and verified as part of the protective arrangement.', why: 'A visible metal layer does not prove a low-resistance, continuous protective path.' },
  },
  'p02-l01-q-concept-4': {
    prompt: 'What must a cable selection match before it can be accepted for an installation?',
    correct: 'The load, route, environment and termination method together.',
    wrong: [
      'Only the expected load current, because all correctly sized cables have the same route suitability.',
      'Only the route appearance, because conductor size can be increased later if the load changes.',
      'Only the terminal size, because a cable that fits the terminals is suitable for the circuit.',
    ],
    errors: [
      'Load current matters, but cables with the same current capacity can differ greatly in their environmental and mechanical suitability.',
      'The route is important, but the cable must be selected for the actual load and protection before work begins; later upsizing may not solve other design problems.',
      'A cable can physically fit a terminal while having the wrong capacity, insulation, construction or environmental rating for the installation.',
    ],
    why: 'Cable selection combines electrical duty with the actual route and method of installation. The cable must carry the intended load safely, withstand its environment and arrive at a termination that is designed for its construction and size.',
    distinction: 'A cable fitting physically is not the same as a cable being electrically and environmentally suitable.',
    practice: 'Record the installation method before using cable data: clipping, containment, insulation, grouping, external exposure and the termination system all influence the decision.',
    followUp: { prompt: 'A cable fits its terminals and has adequate conductor area, but will be exposed to sunlight and movement. What else must be checked?', answer: 'Its construction and outer protection must be suitable for the exposed route and movement.', why: 'The thermal conductor calculation does not establish environmental or mechanical suitability.' },
  },
  'p02-l02-q-concept-1': {
    prompt: 'What is the main switch intended to provide in a consumer unit?',
    correct: 'A common means of controlling or isolating the installation supply within its intended scope.',
    wrong: [
      'Individual overload protection for every final circuit connected to the board.',
      'A test of protective-conductor continuity whenever it is switched off.',
      'Automatic proof that all possible sources feeding the work area are isolated.',
    ],
    errors: [
      'Outgoing protective devices perform individual circuit protection. The main switch controls the board supply rather than setting each circuit’s overcurrent response.',
      'Switching a device does not measure continuity. Protective continuity needs its relevant inspection and test method.',
      'A main switch may not address alternative supplies or every upstream source. Safe isolation starts by identifying every source that can energise the work area.',
    ],
    why: 'The main switch provides a common control point for the consumer unit supply. It does not replace the protective devices for outgoing circuits or the safe-isolation process required before work.',
    distinction: 'Operating a main switch controls a supply path; safe isolation establishes that every relevant source has been identified, secured and proven dead.',
    practice: 'When planning work, trace the circuit and identify grid, generator, PV or battery sources before relying on a single switch position.',
    followUp: { prompt: 'A consumer-unit main switch is off. What must still be established before electrical work begins?', answer: 'That every source capable of energising the work area has been identified, isolated as required and the conductors have been proven dead.', why: 'An off switch is not evidence that no alternative or upstream source remains connected.' },
  },
  'p02-l02-q-concept-2': {
    prompt: 'What is the protective role of an outgoing device in a consumer unit?',
    correct: 'It limits fault or overload conditions affecting the final circuit assigned to it.',
    wrong: [
      'It protects every circuit in the building equally once the consumer-unit door is closed.',
      'It provides a permanent connection between line and neutral so the circuit can operate.',
      'It identifies the circuit automatically without a schedule or circuit label.',
    ],
    errors: [
      'An outgoing device protects its assigned circuit under its specified conditions. Other circuits have their own devices and may have different ratings or characteristics.',
      'A protective device is connected in the circuit path; it does not intentionally join line and neutral together.',
      'Device position alone does not tell a future worker what it serves. Identification must connect the device to the actual circuit and load.',
    ],
    why: 'Each outgoing way is protected for the circuit it serves. Its rating, characteristic and breaking capacity must suit that circuit’s load, conductor and fault conditions.',
    distinction: 'Board-level control and final-circuit protection are different functions carried out by different parts of the assembly.',
    practice: 'A circuit schedule should identify each way, its protective device and the load or area it serves so isolation and fault finding can be planned safely.',
    followUp: { prompt: 'Can a circuit breaker’s ampere marking alone prove it is suitable for its final circuit?', answer: 'No. Its characteristic, breaking capacity and coordination with the circuit conductors and fault conditions also matter.', why: 'The current rating is only one part of protective-device selection.' },
  },
  'p02-l02-q-concept-3': {
    prompt: 'Why are neutral and protective conductors terminated on functionally distinct bars in a consumer unit?',
    correct: 'Their normal-current and protective functions are different and must remain correctly arranged for the system and protective devices.',
    wrong: [
      'They are interchangeable conductors, so separating them only makes the board look tidy.',
      'They must be joined together at every outgoing circuit to improve continuity.',
      'The neutral bar carries only fault current while the protective bar carries the normal return current.',
    ],
    errors: [
      'Neutral and protective conductors have different functions. A neat layout is useful, but the separation is part of the electrical arrangement rather than decoration.',
      'Joining them downstream can create incorrect return paths and interfere with protective arrangements, including residual-current protection.',
      'This reverses their roles. Neutral is a current-carrying return conductor in normal operation; the protective conductor is intended for protective fault conditions, not normal load current.',
    ],
    why: 'Neutral provides the intended return path for normal circuit current. The protective conductor connects exposed conductive parts into the protective arrangement. Their termination arrangement must match the earthing system and the protective devices in use.',
    distinction: 'Neutral is a normal current-carrying conductor; a circuit protective conductor is not intended to carry normal load current.',
    practice: 'A borrowed neutral or an incorrect neutral-bar connection can make an RCD trip unexpectedly and can leave conductors energised when a single circuit is isolated.',
    followUp: { prompt: 'Why can an incorrect neutral connection cause a residual-current device to trip?', answer: 'The outgoing and returning current may no longer pass through the same sensing arrangement, creating an imbalance.', why: 'An RCD compares the current leaving on line with the current returning through its associated neutral path.' },
  },
  'p02-l02-q-concept-4': {
    prompt: 'Why must a consumer-unit circuit schedule agree with the actual protective devices and connected loads?',
    correct: 'It connects physical devices to the circuits they protect so work, isolation and fault finding can be carried out safely.',
    wrong: [
      'A schedule is only for estimating electricity bills and has no effect on safe work.',
      'The device colour and ampere marking make a circuit schedule unnecessary.',
      'Once a circuit works, the schedule can remain inaccurate without affecting future work.',
    ],
    errors: [
      'A schedule is an operational safety record. It helps identify what a device controls and supports planning, isolation and future alterations.',
      'A marking may describe a device, but it does not identify the route, load or area supplied by that way.',
      'Normal operation does not correct misleading identification. An inaccurate schedule can lead someone to isolate the wrong circuit.',
    ],
    why: 'Circuit identification links drawings, board ways and real loads. This prevents work being planned from an assumption and helps an electrician trace a circuit through the installation.',
    distinction: 'A device marking describes the device; a circuit schedule identifies what that device actually serves.',
    practice: 'After alteration, update labels and records only after the circuit has been identified and verified, so the next person can follow the actual supply path.',
    followUp: { prompt: 'A breaker is labelled Lighting but controls socket-outlets after an alteration. What should be done?', answer: 'Correct the identification after establishing and verifying the circuit, rather than relying on the old label.', why: 'A label is useful only when it matches the circuit that is actually connected.' },
  },
  'p02-l03-q-concept-1': {
    prompt: 'How are the corresponding points of three balanced phase waveforms spaced?',
    correct: 'They are displaced by 120 electrical degrees.',
    wrong: [
      'They reach corresponding points together, like three copies of one single-phase waveform.',
      'They are displaced by 90 degrees because three-phase supplies have four conductors.',
      'They are spaced by 180 degrees, so one phase always cancels the other two.',
    ],
    errors: [
      'Balanced three-phase waveforms are deliberately staggered; they do not rise and fall together.',
      'Ninety degrees belongs to a quarter cycle, not the phase separation of a balanced three-phase supply.',
      'At 180 degrees two quantities oppose each other. Three balanced phases are separated evenly by one third of a cycle.',
    ],
    why: 'A balanced three-phase supply has three sinusoidal quantities separated by 120 electrical degrees. This even spacing allows their combined power transfer to be smoother than a single-phase supply.',
    distinction: 'Three-phase separation is 120 degrees; 180 degrees describes two quantities in opposition.',
    practice: 'The phase relationship is used when interpreting phasors, calculating balanced systems and checking motor rotation.',
    followUp: { prompt: 'A complete AC cycle is 360 degrees. What fraction of a cycle separates adjacent balanced phases?', answer: 'One third of a cycle, which is 120 electrical degrees.', why: 'Three equal phase positions divide the full cycle into three equal angular intervals.' },
  },
  'p02-l03-q-concept-2': {
    prompt: 'In a star-connected three-phase system, why must line-to-line voltage be distinguished from line-to-neutral voltage?',
    correct: 'They are measured between different points and therefore have different magnitudes in a balanced star system.',
    wrong: [
      'They are always identical because both readings come from the same supply.',
      'Line-to-neutral voltage is found by adding all three line voltages together.',
      'The distinction matters only for conductor colour identification, not for load connection or calculation.',
    ],
    errors: [
      'Both are supply measurements, but they are taken between different conductors and represent different voltage relationships.',
      'Three-phase voltages have phase angles and cannot be treated as simple quantities to add in this way.',
      'The connection determines which voltage reaches a load element, so the distinction directly affects equipment selection and calculation.',
    ],
    why: 'Line-to-line voltage is measured between two line conductors. Line-to-neutral voltage is measured between one line conductor and neutral. In a balanced star system they have a defined relationship, but they are not interchangeable measurements.',
    distinction: 'Line values describe supply conductors; phase or line-to-neutral values describe the voltage applied to an individual star load element.',
    practice: 'A three-phase motor winding connected in star must be checked against the voltage across each winding, not only the supply’s line-to-line value.',
    followUp: { prompt: 'A balanced star supply is 400 V line-to-line. Is each line-to-neutral voltage also 400 V?', answer: 'No. The line-to-neutral voltage is lower, approximately 230 V in that system.', why: 'The two measurements are between different points and are related by the balanced star phasor relationship.' },
  },
  'p02-l03-q-concept-3': {
    prompt: 'What happens to neutral current when three linear phase loads are equal and balanced?',
    correct: 'Their phase currents have a zero vector sum, so the fundamental neutral current is approximately zero.',
    wrong: [
      'The neutral carries the sum of all three phase currents because every current must return through it.',
      'The neutral carries the largest phase current because it is the common conductor.',
      'No neutral current proves that every circuit component is electrically safe.',
    ],
    errors: [
      'The phase currents are separated in angle, so their vector sum can cancel. They must not be added as three currents at the same instant and direction.',
      'Neutral current depends on the vector combination of phase currents, not on selecting the largest individual phase current.',
      'A balanced-current observation is limited evidence about load balance. It does not prove insulation, protective continuity, terminations or every other safety condition.',
    ],
    why: 'For equal linear three-phase loads, the three currents are equal in magnitude and spaced by 120 degrees. Their vector sum at the neutral point is zero, so the fundamental neutral current cancels.',
    distinction: 'Neutral-current assessment uses vector addition, not ordinary arithmetic addition of phase magnitudes.',
    practice: 'A substantial neutral current can reveal unbalanced single-phase loading or harmonic effects. It should be interpreted with the load type and measurement method in mind.',
    followUp: { prompt: 'Can three equal phase-current magnitudes still produce neutral current if their phase angles are not balanced as expected?', answer: 'Yes. Neutral current depends on the vector sum, so both magnitude and phase angle matter.', why: 'Equal numerical magnitudes alone do not guarantee cancellation.' },
  },
  'p02-l03-q-concept-4': {
    prompt: 'Why does phase sequence matter when connecting a three-phase motor?',
    correct: 'Changing the order of two phases reverses the rotating magnetic field and can reverse the motor’s rotation.',
    wrong: [
      'Phase sequence changes only the supply voltage magnitude, not the motor field direction.',
      'A motor always turns the same way because its shaft and bearings determine the direction.',
      'Phase sequence can be changed freely while a machine is running because only the motor speed is affected.',
    ],
    errors: [
      'The line voltage magnitude can remain normal while the phase order changes. The sequence changes the direction of the rotating field.',
      'Mechanical parts follow the electromagnetic torque direction; they do not set phase rotation independently of the supply sequence.',
      'Unexpected reversal can create a serious hazard. Rotation must be checked under controlled conditions using the proper procedure for the equipment.',
    ],
    why: 'A three-phase motor develops a rotating magnetic field from the ordered phase currents. Interchanging two phase conductors changes that order, reversing the field and therefore the possible direction of rotation.',
    distinction: 'Voltage magnitude and phase sequence are different properties of a three-phase supply.',
    practice: 'After installation or reconnection, motor rotation is checked with access controlled and the driven equipment considered before allowing normal operation.',
    followUp: { prompt: 'Two phase conductors are interchanged on an isolated motor circuit before recommissioning. What effect must be anticipated?', answer: 'The motor may rotate in the opposite direction when energised.', why: 'Interchanging two phases reverses the phase sequence and the rotating magnetic field direction.' },
  },
  'p02-l04-q-concept-1': {
    prompt: 'What defines a TN-S earthing arrangement?',
    correct: 'Neutral and protective functions remain separate throughout the supply path.',
    wrong: [
      'Neutral and protective functions are combined upstream and separated only at the installation origin.',
      'The installation relies on its own local electrode as the main earth connection.',
      'The neutral conductor is used as the circuit protective conductor on final circuits.',
    ],
    errors: [
      'This describes the upstream combined-and-separated arrangement of TN-C-S, not TN-S.',
      'This describes the local electrode feature of a TT arrangement, not TN-S.',
      'A circuit protective conductor has a protective function and is distinct from the neutral return path in a TN-S installation.',
    ],
    why: 'In TN-S, the source provides separate neutral and protective paths all the way to the installation. That arrangement determines the route earth-fault current is intended to take back to the source.',
    distinction: 'TN-S keeps the two functions separate throughout; TN-C-S combines them upstream before they are separated at the origin.',
    practice: 'Before relying on a loop-impedance or protective-device assumption, establish the actual earthing arrangement at the installation origin.',
    followUp: { prompt: 'Does a familiar supply voltage identify the earthing arrangement by itself?', answer: 'No. TN-S, TN-C-S and TT can have similar supply voltages but different protective fault paths.', why: 'Earthing arrangement is identified from the supply and protective-conductor arrangement, not from the nominal voltage alone.' },
  },
  'p02-l04-q-concept-2': {
    prompt: 'What is the defining sequence in a TN-C-S earthing arrangement?',
    correct: 'Neutral and protective functions are combined upstream and separated at the installation origin.',
    wrong: [
      'They remain separate throughout the entire supply path from source to final circuit.',
      'They are combined only within each final circuit after the protective device.',
      'They are replaced by a local earth electrode at the installation origin.',
    ],
    errors: [
      'Separate functions throughout describes TN-S rather than the combined upstream feature of TN-C-S.',
      'Combining neutral and protective functions within a final circuit would create an incorrect downstream arrangement, not TN-C-S supply configuration.',
      'A local electrode is the defining earth connection for TT; it does not describe the combined upstream conductor in TN-C-S.',
    ],
    why: 'TN-C-S has a combined neutral-and-protective function in part of the supply network. At the installation origin the functions are separated into neutral and protective arrangements for the installation.',
    distinction: 'The point of separation matters. Upstream supply arrangements cannot be inferred from a downstream conductor simply looking separate.',
    practice: 'Supply characteristics and conductor arrangements must be confirmed at the origin before designing bonding, protective conductors or fault-loop verification.',
    followUp: { prompt: 'Why must neutral and protective functions not be casually reconnected together downstream of the origin in a TN-C-S installation?', answer: 'It can create unintended current paths and interfere with the designed protective and residual-current arrangements.', why: 'The supply separation establishes distinct normal-current and protective functions within the installation.' },
  },
  'p02-l04-q-concept-3': {
    prompt: 'What provides the installation earth connection in a TT arrangement?',
    correct: 'A local earth electrode connected as part of the installation protective arrangement.',
    wrong: [
      'A distributor-provided protective conductor that returns every fault directly to the transformer.',
      'The neutral bar in the consumer unit, used in place of an earth electrode.',
      'The armour of any cable entering the building, regardless of its design and termination.',
    ],
    errors: [
      'A distributor-provided protective path characterises TN arrangements. TT relies on the installation’s local electrode for its earth connection.',
      'Neutral is not a substitute for an earth electrode or circuit protective arrangement.',
      'Cable armour can have a protective role only where the cable and termination are designed for it. It does not automatically provide the TT earth connection.',
    ],
    why: 'A TT installation uses a local electrode as the installation earth connection. The fault path and protective measures must be assessed for that actual arrangement rather than assumed to behave like a TN supply.',
    distinction: 'An electrode connection is an earthing feature; it does not by itself prove that the required protective disconnection conditions are satisfied.',
    practice: 'TT design and verification consider the electrode arrangement, protective devices and the actual fault conditions together. Do not borrow a TN conclusion without checking the system.',
    followUp: { prompt: 'Can the presence of an earth electrode alone prove acceptable fault protection in a TT installation?', answer: 'No. The electrode, protective device and complete protective arrangement must be assessed together.', why: 'A physical electrode is only one part of the fault-protection decision.' },
  },
  'p02-l04-q-concept-4': {
    prompt: 'Why must the earthing arrangement be established before protection is designed or verified?',
    correct: 'It determines the intended fault-current path and therefore affects protective measures and verification.',
    wrong: [
      'It changes only the colour used for the protective conductor and not the fault path.',
      'It matters only after a fault has occurred, because normal operation is identical in every arrangement.',
      'It allows protective-device ratings to be selected without considering the actual source and circuit conditions.',
    ],
    errors: [
      'Conductor identification matters, but earthing arrangement is fundamentally about the electrical route available during a fault.',
      'Normal operation can hide the protective arrangement. Protection must be designed before a fault, not inferred from an appliance working normally.',
      'Protective-device selection depends on the actual fault current and loop conditions; earthing arrangement is one reason those conditions differ.',
    ],
    why: 'Earthing arrangement sets the intended return route for an earth fault. That route influences fault current, disconnection behaviour, bonding and the tests needed to establish that protective measures are effective.',
    distinction: 'Earthing system is not a label. It is part of the physical fault path on which protection depends.',
    practice: 'When investigating or altering an installation, establish the earthing arrangement first, then decide which loop, electrode, bonding and protective-device checks are relevant.',
    followUp: { prompt: 'A circuit operates normally. Does that observation establish that its earthing arrangement and fault protection are correct?', answer: 'No. Normal operation does not test the fault-current path or protective disconnection behaviour.', why: 'Fault protection requires its own inspection, design assessment and testing evidence.' },
  },
  'p02-l05-q-concept-1': {
    prompt: 'What is the protective purpose of earthing an exposed conductive part?',
    correct: 'It connects the part into the intended protective fault-current return path.',
    wrong: [
      'It carries the circuit’s normal return current instead of the neutral conductor.',
      'It prevents any earth-fault current from flowing through the protective arrangement.',
      'It makes every metal part safe without a sound connection back through the protective path.',
    ],
    errors: [
      'The neutral carries normal return current. A protective conductor is not intended to carry normal load current.',
      'Earthing provides a route for fault current so protective measures can operate; it does not prevent the fault current from having a return path.',
      'A protective path must be continuous and suitably connected. A loose or high-resistance connection weakens its protective function.',
    ],
    why: 'Protective earthing connects exposed conductive parts to the protective arrangement. If a fault makes a metal enclosure live, the path supports fault current and the operation of the relevant protective measure.',
    distinction: 'Earthing provides the fault path; it does not replace the neutral or guarantee protection without continuity and coordinated devices.',
    practice: 'When an appliance enclosure is earthed, inspect and test the protective conductor connection rather than assuming the visible green-and-yellow insulation proves a sound path.',
    followUp: { prompt: 'Why is an open circuit protective conductor dangerous if a line conductor contacts a metal enclosure?', answer: 'The intended fault-current return path may be interrupted, so the enclosure can remain at a hazardous voltage without the protective device operating as intended.', why: 'The protective conductor must be continuous for the fault path to work.' },
  },
  'p02-l05-q-concept-2': {
    prompt: 'What is the protective purpose of bonding conductive parts that could be touched together?',
    correct: 'It limits dangerous differences in touch potential between those parts during a fault condition.',
    wrong: [
      'It replaces the circuit protective conductor connected to an appliance enclosure.',
      'It carries all normal load current away from the neutral conductor.',
      'It guarantees that a protective device will operate without considering the fault path.',
    ],
    errors: [
      'Bonding and the circuit protective conductor have different roles. A bonded pipe is not a substitute for an appliance’s protective conductor.',
      'Bonding is not a normal current-carrying return path. It is part of limiting potential differences between conductive parts.',
      'Bonding can reduce touch-voltage differences, but protective-device operation still depends on the complete fault path and coordinated protective measures.',
    ],
    why: 'Bonding connects conductive parts that may be touched together so that a fault is less likely to create a dangerous voltage difference between them. It works alongside, rather than in place of, earthing and circuit protective conductors.',
    distinction: 'Earthing provides a fault-current path; bonding limits potential difference between touchable conductive parts.',
    practice: 'Trace bonding separately from circuit protective conductors on a schematic. Asking which parts may be touched together helps explain why the connection is needed.',
    followUp: { prompt: 'Why is a bonded metal pipe not a substitute for the circuit protective conductor of an appliance?', answer: 'Bonding limits potential difference between conductive parts, while the appliance protective conductor provides its intended fault-current path.', why: 'The two measures support safety in different ways and neither replaces the other.' },
  },
  'p02-l05-q-concept-3': {
    prompt: 'Why does bonding not remove the need for a reliable circuit protective conductor?',
    correct: 'Bonding limits touch-voltage differences, but the circuit protective conductor provides the appliance fault-current return path.',
    wrong: [
      'Bonding carries a larger normal current than a circuit protective conductor and therefore makes it unnecessary.',
      'Bonding turns every conductive part into an insulating barrier against a fault.',
      'Bonding is only a label for the same conductor used as the circuit protective conductor.',
    ],
    errors: [
      'Neither bonding nor a circuit protective conductor is intended as a normal load-current path. Their purpose is protective, but their connections and functions differ.',
      'Bonding connects conductive parts; it does not insulate them or prevent a fault from energising an enclosure.',
      'The conductors can be physically distinct and serve different protective functions. Treating them as the same loses the reason each is assessed.',
    ],
    why: 'A circuit protective conductor connects an appliance’s exposed conductive parts into the protective fault path. Bonding reduces potential difference between other conductive parts that may be touched together. Both need sound connections because they solve different parts of the fault problem.',
    distinction: 'Reducing touch potential is not the same as providing a complete return path to operate protection.',
    practice: 'A continuity result through an unintended parallel metal path can hide a damaged bonding or protective conductor. Use inspection and a suitable method to confirm the intended path.',
    followUp: { prompt: 'A metal service pipe is bonded, but an appliance protective conductor is disconnected. What protective issue remains?', answer: 'The appliance may lack its intended fault-current return path, even though the pipe bonding is present.', why: 'Bonding does not replace the appliance circuit protective conductor.' },
  },
  'p02-l05-q-concept-4': {
    prompt: 'How do earthing and bonding work together in fault protection?',
    correct: 'Earthing supports the fault-current path, while bonding reduces potential differences between conductive parts that may be touched together.',
    wrong: [
      'Earthing and bonding are interchangeable names for one connection with exactly the same purpose.',
      'Earthing reduces touch potential, while bonding carries fault current back to the source.',
      'Either measure alone makes conductor continuity and protective-device selection unnecessary.',
    ],
    errors: [
      'They are related protective measures, but each addresses a different part of the fault problem.',
      'This reverses their main roles. Earthing connects into the protective fault path; bonding limits differences between touchable conductive parts.',
      'Both measures rely on suitable conductors, connections and protective arrangements. Neither makes the wider design and verification unnecessary.',
    ],
    why: 'Earthing and bonding are coordinated protective measures. Earthing connects exposed conductive parts to the intended protective arrangement, while bonding helps keep simultaneously touchable conductive parts closer in potential under fault conditions.',
    distinction: 'Both support safety, but the question each answers is different: fault-current path versus touch-voltage difference.',
    practice: 'When reviewing a building, identify the appliance protective conductor and the main bonding connections separately before deciding what inspection or continuity evidence is needed.',
    followUp: { prompt: 'Which measure primarily addresses a dangerous voltage difference between a metal pipe and another touchable conductive part?', answer: 'Bonding.', why: 'Bonding is used to limit potential difference between conductive parts that may be contacted together.' },
  },
  'p02-l06-q-concept-1': {
    prompt: 'What causes a conventional fuse to operate on excessive current?',
    correct: 'Its calibrated element heats and melts when the current-time condition exceeds its design limit.',
    wrong: [
      'It detects the cable insulation colour and opens when the colour indicates a fault.',
      'It measures earth continuity and opens whenever a protective conductor is present.',
      'It opens at exactly the same time for every current above its rated current.',
    ],
    errors: [
      'A fuse responds to heating caused by current, not to the visible colour of the connected cable.',
      'Protective continuity is a different condition. A fuse is an overcurrent protective device, not an earth-continuity tester.',
      'Fuse operation depends on the magnitude and duration of overcurrent. Larger faults usually produce a different operating time from smaller overloads.',
    ],
    why: 'Current produces heating in a fuse element. The element and surrounding construction are designed so that excessive current for a sufficient time melts the element and interrupts the circuit.',
    distinction: 'A fuse responds to current and time; it does not inspect conductor appearance or prove an earthing arrangement.',
    practice: 'When a fuse has operated, do not replace it repeatedly without investigating whether the circuit has overload, fault current or an unsuitable device selection.',
    followUp: { prompt: 'Why can a modest overload and a large short circuit operate the same fuse in different times?', answer: 'They produce different heating conditions in the fuse element, so the time-current characteristic gives different operating times.', why: 'Protective operation is related to both current magnitude and duration.' },
  },
  'p02-l06-q-concept-2': {
    prompt: 'What distinguishes a circuit breaker from a fuse in normal service?',
    correct: 'A circuit breaker uses resettable operating mechanisms with specified protective characteristics.',
    wrong: [
      'A circuit breaker has no time-current characteristic because it can be reset after a trip.',
      'A circuit breaker is suitable whenever its ampere rating matches the load, regardless of fault level.',
      'A circuit breaker protects a circuit by permanently joining line and neutral during an overload.',
    ],
    errors: [
      'Resettable operation does not remove the need for a defined response to overload and short-circuit conditions.',
      'Current rating is only one property. Breaking capacity and operating characteristic must also suit the circuit and available fault current.',
      'A protective device interrupts the circuit when it operates. Joining line and neutral would create a fault rather than protect against one.',
    ],
    why: 'Circuit breakers are resettable devices, but they still have defined trip characteristics and breaking capacities. The device selected has to coordinate with its conductors, load and prospective fault conditions.',
    distinction: 'Resettable does not mean universally suitable; a breaker still has a specified operating and interrupting duty.',
    practice: 'Before replacing a breaker, confirm the actual circuit, conductor capacity, fault level and required protective behaviour instead of copying a familiar ampere rating.',
    followUp: { prompt: 'Can a resettable breaker be assumed to have the correct breaking capacity for every installation?', answer: 'No. Its breaking capacity must be adequate for the prospective fault current at its location.', why: 'Resettable operation and safe interruption of a high fault current are separate characteristics.' },
  },
  'p02-l06-q-concept-3': {
    prompt: 'Why does a protective-device ampere rating alone not establish a suitable selection?',
    correct: 'The device must also have suitable operating characteristics and breaking capacity for the circuit fault conditions.',
    wrong: [
      'The ampere rating is the only value that matters because it always equals the available fault current.',
      'Breaking capacity describes the normal load current the circuit is expected to carry.',
      'A device with a larger ampere marking always provides faster and more complete protection.',
    ],
    errors: [
      'Normal circuit current and prospective fault current are different quantities. The ampere rating does not automatically equal fault duty.',
      'Breaking capacity is the fault current a device can interrupt safely under stated conditions, not its normal load-current rating.',
      'A larger rating can be unsuitable for the conductors and protective requirements. More amperes is not automatically more protection.',
    ],
    why: 'A protective device needs coordinated current rating, operating curve and breaking capacity. The device must protect the circuit in normal overload conditions and be able to interrupt the fault current that could occur at its installation point.',
    distinction: 'Rated current describes intended continuous duty; breaking capacity describes safe interruption of prospective fault current.',
    practice: 'A breaker can carry the expected load without being suitable to interrupt the highest fault current available at a board near the supply origin.',
    followUp: { prompt: 'A breaker has the correct nominal current for a cable. What fault-related value must still be checked?', answer: 'Its breaking capacity against the prospective fault current at that point.', why: 'Cable coordination does not by itself establish the device can interrupt the available fault duty.' },
  },
  'p02-l06-q-concept-4': {
    prompt: 'What does a protective device time-current characteristic tell the designer?',
    correct: 'How the device’s operating time changes with the magnitude and type of overcurrent.',
    wrong: [
      'The physical distance that a fault current travels through the installation.',
      'The maximum cable length that can be installed without any other design check.',
      'The normal energy use of the connected appliance over time.',
    ],
    errors: [
      'A time-current curve describes device response, not the physical route of current through conductors.',
      'Cable length affects several design conditions, but a time-current curve alone cannot approve a cable route.',
      'Energy consumption concerns power and operating time. The protective characteristic concerns abnormal current response.',
    ],
    why: 'Protective devices respond differently to overload and high fault current. Their time-current characteristic shows the relationship between overcurrent magnitude and the time in which the device is expected to operate.',
    distinction: 'Time-current behaviour is protective response, not a cable route measurement or an appliance energy calculation.',
    practice: 'When assessing fault protection, use the actual device characteristic with the available fault current and the required disconnection condition.',
    followUp: { prompt: 'Why might two overcurrents not cause a fuse or breaker to operate in the same time?', answer: 'Their magnitudes differ, and the device time-current characteristic gives a different response at each current level.', why: 'The curve links the severity of overcurrent to the expected operating time.' },
  },
};
