export type CalculationKind = 'ohm' | 'charge' | 'power' | 'energy' | 'series' | 'parallel' | 'loop' | 'drop' | 'three-phase' | 'motor' | 'transformer' | 'lighting' | 'battery';
export type Calculation = { id: CalculationKind; title: string; match: RegExp; concept: string; source: string; assumption: string };
export const calculations: Calculation[] = [
  { id:'loop', title:'Build the complete fault loop', match:/loop impedance|\bzs\b|\bze\b/i, concept:'Zs', source:'IET: minimizing unnecessary live testing, May 2025', assumption:'Simplified resistive circuit model at one stated temperature, with negligible reactance. Values are fictional. It does not decide compliance or predict device trip time.' },
  { id:'three-phase', title:'Separate line values from phase values', match:/three.phase.*(?:power|calcul|theory)|3.phase.*power|line.*phase|star.*delta/i, concept:'Line and phase values', source:'Electrical Installation Designs, chapter 19; existing three-phase toolkit', assumption:'Balanced three-phase load with sinusoidal voltage and current. Use line-to-line voltage and line current. No motor efficiency is included.' },
  { id:'motor', title:'Predict the rotor speed', match:/induction|slip|motor speed|rotating field/i, concept:'Slip', source:'Existing induction-motor lesson connection and manufacturer reference', assumption:'Normal motoring operation of a four-pole induction motor. The result is an idealised nameplate reasoning exercise.' },
  { id:'transformer', title:'Use the turns ratio', match:/transformer/i, concept:'Voltage', source:'Existing transformer lesson connection', assumption:'Ideal single-phase transformer; winding voltages, neglecting losses and regulation.' },
  { id:'parallel', title:'Follow current into parallel branches', match:/resistors.*parallel|parallel circuit|resistance.*parallel/i, concept:'Resistance', source:'Existing circuit-theory guides and toolkit', assumption:'Two ideal resistors in parallel at constant temperature.' },
  { id:'series', title:'Reconstruct a series circuit', match:/resistors.*series|series resistance|series circuit/i, concept:'Resistance', source:'Existing circuit-theory guides and toolkit', assumption:'Two ideal resistors in series at constant temperature.' },
  { id:'charge', title:'Connect current to transferred charge', match:/charge.*current|ampere|coulomb|quantify electricity/i, concept:'Charge', source:'Existing electrical foundations guides', assumption:'Constant current over the stated time.' },
  { id:'energy', title:'Distinguish power from energy', match:/power.*energy|units.*energy|kilowatt.hour|energy consumption/i, concept:'Power', source:'Existing energy toolkit', assumption:'Constant electrical input power over the stated operating period.' },
  { id:'drop', title:'Calculate voltage drop from supplied data', match:/voltage drop|volt drop/i, concept:'Voltage drop', source:'Electrical Installation Designs, chapter 19', assumption:'The fictional mV/A/m coefficient is already for this complete circuit configuration. Length is one-way route length; do not multiply by two again. It is not a standards table value.' },
  { id:'power', title:'Choose a power relationship', match:/calculate power|power formula|power in.*circuit/i, concept:'Power', source:'Existing power toolkit', assumption:'DC resistive load. P = VI; AC loads require the applicable power-factor relationship.' },
  { id:'lighting', title:'Estimate maintained illuminance', match:/lighting design|illuminance|lux|lumen/i, concept:'Lux', source:'Electrical Installation Designs, lighting case studies', assumption:'Simplified average lumen method using supplied utilisation and maintenance factors. Does not assess uniformity, glare or emergency-lighting compliance.' },
  { id:'battery', title:'Separate stored energy from runtime', match:/battery|batteries|storage|\bups\b/i, concept:'Inverter', source:'Supplemental idealised energy-balance exercise', assumption:'Usable energy is supplied, including the reserve. Assume 90% conversion efficiency and constant load; real runtime also depends on temperature, ageing and discharge rate.' },
  { id:'ohm', title:'Predict, calculate, explain', match:/ohm|voltage.*resistance|resistance.*current/i, concept:'Resistance', source:'Existing Ohm’s-law toolkit', assumption:'An ideal ohmic component at constant temperature in a low-voltage DC learning circuit.' },
];
export type CalculationProblem = { prompt: string; answer: number; unit: string; units: string[]; working: string; hint: string; transfer: string; wrong?: { value: number; feedback: string }[] };
export function calculationProblem(kind: CalculationKind, variant = 0): CalculationProblem {
  const k = Math.abs(Math.floor(variant)) % 4;
  switch (kind) {
    case 'ohm': { const voltage=[12,24,18,36][k], resistance=[24,8,6,12][k]; return { prompt:`A ${voltage} V source supplies a ${resistance} Ω resistor. What current flows?`,answer:voltage/resistance,unit:'A',units:['A','mA','V'],working:`I = V / R = ${voltage} / ${resistance} = ${voltage/resistance} A.`,hint:'Current is voltage divided by resistance. Keep both quantities in base units.',transfer:'At fixed voltage, doubling resistance halves current.',wrong:[{value:voltage*resistance,feedback:'You appear to have multiplied V by R. Rearrange V = IR by dividing both sides by R.'}] }; }
    case 'charge': {const current=[2,3,4,5][k],time=[30,20,15,12][k]; return {prompt:`A constant ${current} A flows for ${time} seconds. How much charge passes?`,answer:current*time,unit:'C',units:['C','A','J'],working:`Q = It = ${current} × ${time} = ${current*time} C.`,hint:'An ampere is one coulomb per second.',transfer:'Same charge in half the time means twice the current.'};}
    case 'power': {const voltage=[12,24,18,36][k],current=[4,3,2,2][k];return {prompt:`A DC load draws ${current} A at ${voltage} V. Find its input power.`,answer:voltage*current,unit:'W',units:['W','kW','Wh'],working:`P = VI = ${voltage} × ${current} = ${voltage*current} W.`,hint:'Multiply voltage by current for this DC load.',transfer:'Power is a rate; multiply by time to obtain energy.'};}
    case 'energy': {const watts=[150,200,300,400][k],hours=[2,3,2,4][k];return {prompt:`A ${watts} W load operates for ${hours} hours. Find its energy use in kWh.`,answer:watts*hours/1000,unit:'kWh',units:['kWh','Wh','kW'],working:`E = (${watts} / 1000) × ${hours} = ${watts*hours/1000} kWh.`,hint:'Convert W to kW, then multiply by hours.',transfer:'Two loads with different power ratings can use the same energy if their operating times differ.',wrong:[{value:watts*hours,feedback:'That number is watt-hours. Divide by 1000 to express it in kilowatt-hours.'}]};}
    case 'series': {const a=[10,12,15,20][k],b=[20,24,30,40][k];return {prompt:`${a} Ω and ${b} Ω resistors are in series. Find the total resistance.`,answer:a+b,unit:'Ω',units:['Ω','kΩ','A'],working:`Rtotal = R1 + R2 = ${a} + ${b} = ${a+b} Ω.`,hint:'The same current must travel through both resistors.',transfer:'Adding another series resistor increases total resistance.'};}
    case 'parallel': {const a=[12,18,24,30][k],b=a*2;return {prompt:`${a} Ω and ${b} Ω resistors are in parallel. Find the equivalent resistance.`,answer:a*b/(a+b),unit:'Ω',units:['Ω','kΩ','A'],working:`Rtotal = R1R2 / (R1 + R2) = ${a*b} / ${a+b} = ${a*b/(a+b)} Ω.`,hint:'The result must be less than the smaller branch resistance.',transfer:'Adding another conducting branch reduces equivalent resistance.',wrong:[{value:a+b,feedback:'Adding resistances applies to series. Parallel branches provide additional paths.'}]};}
    case 'loop': {const ze=[.3,.25,.4,.2][k],r=[.5,.65,.4,.7][k];return {prompt:`At the same stated temperature, Ze = ${ze.toFixed(2)} Ω and R1 + R2 = ${r.toFixed(2)} Ω. Estimate Zs.`,answer:ze+r,unit:'Ω',units:['Ω','mΩ','A'],working:`Zs ≈ Ze + (R1 + R2) = ${ze.toFixed(2)} + ${r.toFixed(2)} = ${(ze+r).toFixed(2)} Ω.`,hint:'Account for the external supply path and the circuit line/protective path.',transfer:'A higher loop impedance reduces prospective fault current at unchanged source voltage. Compliance still requires the actual device and conditions.',wrong:[{value:ze,feedback:'That is Ze, the external part. Include the circuit line and protective conductor resistances.'},{value:r,feedback:'That is only the circuit portion. Include the external supply loop.'}]};}
    case 'drop': {const length=[20,25,30,40][k],current=[10,12,8,6][k],coefficient=4.4;return {prompt:`Use the supplied coefficient 4.4 mV/A/m, ${current} A and a ${length} m one-way route. Find circuit voltage drop.`,answer:coefficient*current*length/1000,unit:'V',units:['V','mV','%'],working:`ΔV = 4.4 × ${current} × ${length} / 1000 = ${(coefficient*current*length/1000).toFixed(3)} V.`,hint:'mV to V requires division by 1000. This coefficient already includes the circuit configuration.',transfer:'At fixed current and coefficient, doubling route length doubles voltage drop.'};}
    case 'three-phase': {const current=[10,15,20,25][k],pf=[.8,.9,.75,.85][k],p=Math.sqrt(3)*400*current*pf/1000;return {prompt:`A balanced load draws ${current} A per line at 400 V line-to-line and power factor ${pf}. Find total real power in kW.`,answer:p,unit:'kW',units:['kW','W','kVA'],working:`P = √3 × VL × IL × PF / 1000 = √3 × 400 × ${current} × ${pf} / 1000 = ${p.toFixed(3)} kW.`,hint:'Use line values in √3 VL IL PF. Divide watts by 1000.',transfer:'At the same real power and voltage, a lower power factor requires a higher line current.',wrong:[{value:400*current*pf/1000,feedback:'This is the single-phase expression. Include √3 when using balanced three-phase line values.'},{value:Math.sqrt(3)*400*current/1000,feedback:'This is apparent power in kVA. Multiply by power factor for real power.'}]};}
    case 'motor': {const slip=[4,3,5,2][k],speed=1500*(1-slip/100);return {prompt:`A four-pole motor runs on 50 Hz with ${slip}% slip. Estimate rotor speed.`,answer:speed,unit:'rpm',units:['rpm','Hz','%'],working:`ns = 120 × 50 / 4 = 1500 rpm; nr = 1500 × (1 − ${slip}/100) = ${speed} rpm.`,hint:'First calculate field speed. Rotor speed is lower by the slip fraction.',transfer:'Changing supply frequency changes synchronous speed; changing a contactor does not.',wrong:[{value:1500,feedback:'1500 rpm is the synchronous field speed. Subtract the slip fraction to find rotor speed.'}]};}
    case 'transformer': {const primary=[1000,800,600,1200][k],secondary=[100,80,60,120][k];return {prompt:`An ideal transformer has ${primary} primary turns, ${secondary} secondary turns and 230 V across the primary. Find secondary voltage.`,answer:23,unit:'V',units:['V','A','VA'],working:`V2 = V1 × N2/N1 = 230 × ${secondary}/${primary} = 23 V.`,hint:'A smaller secondary turns count should give a smaller secondary voltage.',transfer:'In the ideal model, reducing voltage allows more current at the same apparent power.'};}
    case 'lighting': {const flux=[10000,12000,16000,20000][k],area=[20,30,40,50][k];return {prompt:`Total luminaire flux is ${flux} lm over ${area} m². Use utilisation factor 0.6 and maintenance factor 0.8. Estimate average maintained illuminance.`,answer:flux*.6*.8/area,unit:'lx',units:['lx','lm','W'],working:`E = flux × UF × MF / area = ${flux} × 0.6 × 0.8 / ${area} = ${flux*.6*.8/area} lx.`,hint:'Apply both factors before dividing by area.',transfer:'Average illuminance cannot establish uniformity or glare performance.'};}
    case 'battery': {const energy=[2,3,4,5][k],load=[.5,.6,.8,1][k];return {prompt:`A battery provides ${energy} kWh of usable DC energy. An inverter is 90% efficient and supplies a constant ${load} kW load. Estimate runtime.`,answer:energy*.9/load,unit:'h',units:['h','kWh','kW'],working:`t = usable energy × efficiency / load = ${energy} × 0.9 / ${load} = ${energy*.9/load} h.`,hint:'Reduce usable DC energy by conversion losses before dividing by load power.',transfer:'A kWh rating describes energy. A kW rating describes the rate at which it is used.'};}
  }
}
export function checkCalculation(problem: CalculationProblem, raw: string, unit: string) {
  if (!raw.trim() || !Number.isFinite(Number(raw)) || Number(raw) < 0) return { valid:false, correct:false, feedback:'Enter a finite, non-negative number before checking.' };
  const value=Number(raw), tolerance=Math.max(.005,Math.abs(problem.answer)*.01);
  if (unit !== problem.unit) return { valid:true, correct:false, feedback:`Check the requested unit: ${problem.unit}. The unit is part of the answer, not a label to add afterwards.`, misconception:'Unit selection' };
  if (Math.abs(value-problem.answer)<=tolerance) return {valid:true,correct:true,feedback:'Your value and unit agree with the model. Now explain why the result is plausible.'};
  const diagnostic=problem.wrong?.find(item=>Math.abs(value-item.value)<=Math.max(.005,Math.abs(item.value)*.01));
  return {valid:true,correct:false,feedback:diagnostic?.feedback ?? 'Check the quantities, formula and substitution. Use the hint, then explain each step before trying a new example.',misconception:diagnostic ? 'Formula or quantity confusion' : 'Calculation needs review'};
}
export function calculationChoices(problem: CalculationProblem, variant: number) {
  const format = (value: number) => Number(value.toPrecision(4)).toString();
  const alternatives = [...(problem.wrong?.map(item => item.value) ?? []), problem.answer * 2, problem.answer / 2, problem.answer + 1];
  const values = [...new Set(alternatives.map(format))].filter(value => value !== format(problem.answer)).slice(0, 2);
  const choices = values.map(value => ({value, unit: problem.unit}));
  choices.push({value: format(problem.answer), unit: problem.units.find(unit => unit !== problem.unit)!});
  const answer = Math.abs(variant) % 4;
  choices.splice(answer, 0, {value: format(problem.answer), unit: problem.unit});
  return { choices, answer };
}
export type CaseStep = { title: string; prompt: string; options: string[]; answer: number; feedback: string[] };
export type FaultCase = { id:string; title:string; match:RegExp; concept:string; observation:string; source:string; steps:CaseStep[] };
const safety: CaseStep={title:'Establish the safe condition',prompt:'Before the virtual investigation proceeds to a dead test, which condition must be established?',options:['Stop the appliance using its control switch.','Identify every supply, isolate and secure against reconnection, then prove dead using suitable proven equipment.','Assume the tripped protective device has isolated everything.'],answer:1,feedback:['A control switch may leave power conductors energised. Identify and isolate all relevant sources.','Correct. This scenario now assumes a qualified person has established safe isolation.','A trip is not proof of isolation and may not disconnect every source.']};
const step=(title:string,prompt:string,options:string[],answer:number,feedback:string[]):CaseStep=>({title,prompt,options,answer,feedback});
export const faultCases:FaultCase[]=[
  {id:'open-cpc',title:'A socket works, but its protective path does not',match:/loop impedance|\bcpc\b|continuity|earthing|fault.find|polarity/i,concept:'CPC',observation:'A fictional socket supplies a lamp normally. The inspection record raises a concern about CPC continuity. Successful operation is the only evidence you currently have.',source:'Modern Wiring Practice, chapter 16; IET safe verification guidance',steps:[safety,step('Choose an informative test','With safe isolation established, what should the qualified tester investigate first?',['Load current, with the circuit re-energised.','Insulation resistance only.','Continuity of the intended protective path with a suitable low-resistance instrument.'],2,['Load operation does not establish protective continuity.','Insulation condition and continuity answer different questions.','Correct. Inspect and test the intended CPC path under the appropriate dead-test arrangement.']),step('Interpret the evidence','The simulated low-resistance test reports an open path. What can you conclude?',['The protective path under test is not continuous; locate the discontinuity.','The supply Ze is definitely too high.','The lamp current is too low to operate the breaker.'],0,['Correct. The observation concerns the tested path; it does not identify the exact location yet.','This dead continuity test did not measure the external supply loop.','The lamp working does not explain an open protective path.']),step('Correct and verify','Inspection locates a disconnected CPC terminal. What completes the response?',['Reconnect it and return the circuit to service because the lamp works.','Have the defect corrected by an authorised competent person, then repeat relevant inspection and tests and record the results before return to service.','Increase the protective-device rating.'],1,['The correction needs verification, not just a functional check.','Correct. Evidence after repair is required; this simulation grants no work authorisation.','A larger breaker does not restore a protective conductor.'])]},
  {id:'rcd-trip',title:'The RCD trips when an appliance is connected',match:/\brcd\b|\brcbo\b|residual|insulation|fault.find/i,concept:'RCD',observation:'In this fictional installation, the RCD trips when one appliance is connected. Several explanations remain possible; an RCD trip alone does not identify the defect.',source:'Electrical Installation Designs, chapter 17; HSE GS38',steps:[safety,step('Select the next investigation','What is a useful next step under a suitable dead-test plan?',['Replace the RCD with a higher residual-current rating.','Separate the appliance from the fixed wiring and inspect/test each using methods suitable for its electronics.','Disconnect the CPC and see whether the trip disappears.'],1,['Changing a rating masks the symptom without establishing the cause.','Correct. Separate possible causes while preserving protective measures.','Removing a CPC can create a hazardous exposed-conductive-part condition.']),step('Interpret the result','The fixed wiring passes the specified tests; the isolated appliance shows insulation damage. What does this support?',['An appliance defect is a supported hypothesis requiring appropriate repair or replacement.','The RCD is definitely defective.','The fixed wiring can never have a fault.'],0,['Correct. The observations narrow the hypothesis; avoid conclusions beyond the evidence.','The result does not demonstrate a defective RCD.','Passing these tests under these conditions is not a permanent guarantee.']),step('Verify the remedy','What follows repair or replacement?',['Restore service immediately without records.','Bypass the RCD during the first week.','Perform the applicable verification of appliance/circuit protection and document the outcome.'],2,['The remedy must be verified.','Protection must not be bypassed as a diagnostic shortcut.','Correct. Check the repaired system under the appropriate conditions.'])]},
  {id:'motor-no-start',title:'The motor stops when Start is released',match:/contactor|\bdol\b|motor control|starter|holding contact/i,concept:'Contactor',observation:'A virtual DOL control circuit energises its contactor while Start is pressed, then drops out on release. Do not assume the motor itself is defective.',source:'Modern Wiring Practice, motor control diagrams; existing book motor simulation',steps:[safety,step('Choose the circuit to examine','Which part of the drawing best explains the symptom?',['The holding-contact branch around the momentary Start contact.','The lighting circuit.','Only the motor bearings.'],0,['Correct. The holding branch should maintain coil energisation after Start is released.','That circuit does not explain this control symptom.','Mechanical load issues cannot alone explain the stated control-contact behaviour.']),step('Interpret the drawing and test','The safely isolated holding branch is open when its auxiliary contact should be closed. What hypothesis fits?',['The supply frequency is too low.','A holding-contact or connection defect prevents the sustaining path.','The overload must be removed.'],1,['This observation is about continuity in the control branch.','Correct. Inspect the auxiliary contact and connections; do not bypass safety contacts.','Overload protection must remain part of the intended circuit.']),step('Verify the sequence','After authorised correction, which virtual functional sequence matters?',['Start latches, Stop drops out, overload action drops out, and supply restoration does not cause unintended restart.','The motor starts once.','The contactor always remains on.'],0,['Correct. Verify intended operation and protective/control responses.','A single start does not test stopping, overload response or restart prevention.','Remaining energised despite Stop or a protective action is a defect.'])]},
  {id:'cable-route',title:'The same cable, a different route',match:/cable|conduit|containment|trunking|overcurrent|breaker|design|demand|diversity/i,concept:'Iz',observation:'A circuit design was based on a cable route that could dissipate heat freely. The revised drawing places part of that route in thermal insulation.',source:'Modern Wiring Practice, chapter 4; Electrical Installation Designs, chapter 19',steps:[step('Identify the changed assumption','Which design assumption needs review?',['The conductor material must have changed.','The heat-dissipation and current-capacity conditions have changed.','Nothing changes if cross-section stays the same.'],1,['The route changed; conductor material was not stated to change.','Correct. The same cable can have a different usable current capacity in different conditions.','Cross-section alone is not a complete cable-selection method.']),step('Use the supplied design values','For this exercise only: Ib = 20 A, In = 25 A, and corrected Iz = 18 A. Which statement is supported?',['The overload coordination check fails because In exceeds Iz.','It passes because In exceeds Ib.','It passes if the cable is short.'],0,['Correct. Ib ≤ In ≤ Iz is not satisfied. These are fictional supplied values, not table values.','The cable-capacity side of the check also matters.','Length may affect other checks, but it does not repair this inequality.']),step('Choose the next design action','What should the designer do?',['Increase the breaker rating.','Ignore the insulated section.','Reassess route, conductor and protection using applicable current data, then check voltage drop and fault protection too.'],2,['That could worsen cable protection.','The limiting section must be considered.','Correct. Coordinate the complete circuit and document the revised assumptions.'])]},
  {id:'multi-source',title:'The main switch is off — is every source isolated?',match:/solar|\bpv\b|battery|inverter|generator|\bups\b|ev charg|backup/i,concept:'Inverter',observation:'A fictional building has grid supply, battery backup and rooftop PV. The grid main switch has been opened for maintenance.',source:'IET BS 7671 A4 scope and existing source-system lessons',steps:[step('Question the apparent isolation','What does opening the grid main switch establish?',['Every conductor is dead.','Only the stated switching action; other supplies and stored energy must still be considered.','PV modules stop generating.'],1,['Multiple sources may remain.','Correct. Trace every supply and operating mode before selecting isolation points.','Illuminated PV modules can still generate DC.']),safety,step('Check the operating modes','What evidence is needed before approving the revised system?',['Only a successful grid-connected trial.','A photograph of the inverter.','Verified isolation, changeover, earthing and protection in each intended operating mode, using the actual manufacturer design.'],2,['Island operation can change fault current and protective behaviour.','Appearance cannot establish coordination.','Correct. A calculation based on grid fault current alone cannot establish island-mode protection.'])]},
  {id:'professional-evidence',title:'An installation works — what is still missing?',match:/inspection|commission|professional|estimating|quotation|certificat|handover|lighting|socket|accessor|termination|wiring|building|pump|hvac|security|data|cctv|alarm/i,concept:'Polarity',observation:'A fictional completed installation operates as the client requested. The test schedule is incomplete and the applicable standards edition has not been recorded.',source:'Electrical Installation Designs, introduction and chapter 15; IEC 60364-6 scope',steps:[step('Assess the evidence','Which conclusion is justified?',['Function has been observed; safety and compliance are not established by that alone.','Client satisfaction is equivalent to certification.','The manufacturer logo proves installation quality.'],0,['Correct. Separate function, inspection, testing and formal documentation.','Client acceptance cannot replace required verification.','A compliant product can be installed incorrectly.']),step('Resolve missing requirements','Which information should be established?',['Only the installation date.','Applicable jurisdiction, current documents, project conditions, equipment requirements and authorised scope.','Whichever foreign video was easiest to follow.'],1,['The date alone does not identify requirements or responsibilities.','Correct. The applicable requirements and responsibilities must be explicit.','A video explains an example, not automatically the applicable law.']),step('Complete the professional record','What should happen before claiming verified completion?',['Estimate the missing test results.','Copy results from a similar building.','Obtain the required inspection/test evidence, resolve defects, record limitations and arrange authorised certification or handover as applicable.'],2,['Test results must be measured or otherwise established by an allowed method, never invented.','A different installation cannot supply this installation’s evidence.','Correct. A complete record connects requirements, observations, decisions and responsibility.'])]},
];
export function practiceForLesson(text:string) {
  return { calculation:calculations.find(item=>item.match.test(text)), cases:faultCases.filter(item=>item.match.test(text)).slice(0,2) };
}
