import type { Revision } from './question-revisions';

// Individually authored against the supplied transcript, not generated from guide sentences.
// p16-l07: GT_wTybt6Ao — site visit, mental method statement, lead times,
// realistic allowance, fixed quotation and agreed extras.
export const professionalQuestionRevisions: Record<string, Revision> = {
  'p16-l06-q-concept-1': {
    prompt: 'A terminal appears cooler after repair, but the second image was taken when production was running at a much lower load. What can the maintenance team conclude from these two images alone?',
    correct: 'The apparent temperature fell, but the changed load prevents the images alone from proving the repair succeeded.',
    wrong: ['The repair succeeded because any reduction in displayed temperature proves the defect was removed.', 'The repair failed because a sound terminal must have exactly the same temperature at every load.', 'The lower temperature proves that the terminal resistance increased after the repair.'],
    errors: ['A reduced load can reduce heating even if a defect remains.', 'A sound component’s temperature can change with operating conditions.', 'A temperature change under a different load does not establish that resistance increased.'],
    why: 'The instructor stresses before-and-after checks and the effect of load on heating. For a meaningful comparison, the operating conditions must be understood. An improved image is evidence to interpret, not a substitute for assessing whether the original problem has been resolved.',
    distinction: 'A cooler image and a verified repair are different conclusions.',
    practice: 'Record load conditions with repeat images and compare suitable operating conditions when assessing the repair.',
    followUp: { prompt: 'Why record the load during a thermal survey?', answer: 'Because the same component can generate different heating at different currents.', why: 'Load provides context for interpreting the temperature pattern and comparing later observations.' },
  },
  'p16-l06-q-concept-2': {
    prompt: 'A shiny connector looks hotter than nearby insulation in a thermal image. Before treating the displayed values as comparable actual temperatures, which issue needs attention?',
    correct: 'The surfaces have different emissivity and may reflect infrared energy differently.',
    wrong: ['The same camera automatically gives equally reliable temperatures for every surface.', 'The connector’s bright appearance proves that its internal resistance is higher.', 'Insulation and metal can be compared directly whenever both fit within the image.'],
    errors: ['Using one camera does not remove differences in the infrared behaviour of the surfaces.', 'Brightness is an apparent thermal indication, not a direct resistance measurement.', 'Being in the same frame does not establish comparable surface properties.'],
    why: 'In the questions after the webinar, the instructor warns that shiny metals reflect infrared energy and can produce large errors. The displayed temperature depends on the surface and the measurement assumptions. Identify those limitations before turning an apparent difference into a repair diagnosis.',
    distinction: 'Apparent temperature is not automatically the true surface temperature.',
    practice: 'Document the measurement surface and settings instead of comparing unlike surfaces solely by their colours.',
    followUp: { prompt: 'What does a thermal imager detect before converting the signal into a temperature display?', answer: 'Infrared radiation reaching the imager.', why: 'The conversion depends on assumptions about the surface and its surroundings, which is why reflections matter.' },
  },
  'p16-l06-q-concept-3': {
    prompt: 'A survey shows heating along a motor feeder rather than only at one terminal. Which next step best follows the instructor’s search for the root cause?',
    correct: 'Use appropriate electrical measurements to investigate loading, imbalance and harmonics alongside the thermal pattern.',
    wrong: ['Record a loose terminal as the confirmed cause because every hot cable has a bad connection.', 'Replace the motor immediately because cable heating proves its windings have failed.', 'Record harmonics as the confirmed cause because an image identifies the current waveform.'],
    errors: ['The instructor distinguishes a localised hot spot from more distributed heating with several possible causes.', 'A hot feeder alone does not identify a failed motor winding.', 'Thermal imaging does not measure the harmonic spectrum of the current.'],
    why: 'The webinar identifies imbalance, overload and harmonics as possible explanations for distributed heating. Complementary instruments provide the electrical evidence needed to distinguish them. The image locates a symptom; the diagnosis must account for the operating conditions and measurements.',
    distinction: 'A thermal signature narrows an investigation without proving every underlying cause.',
    practice: 'Plan corroborating measurements through the authorised inspection procedure; the image is not permission for an apprentice to access live parts.',
    followUp: { prompt: 'Why can a power-quality analyser add information that a thermal image cannot?', answer: 'It can characterise electrical quantities such as phase imbalance and harmonic content.', why: 'Those measurements help distinguish causes that can produce similar heating patterns.' },
  },
  'p16-l06-q-concept-4': {
    prompt: 'A maintenance report contains only a cropped thermal picture labelled “hot connection”. What addition would make it more useful for locating the problem and checking the subsequent repair?',
    correct: 'Identify the component and operating conditions, retain the visual and thermal evidence, and record the finding and follow-up action.',
    wrong: ['Remove all location information so the report can be reused for any similar panel.', 'Replace the image with its highest displayed temperature and omit the operating conditions.', 'Keep only the red areas because the remaining image cannot help interpret the finding.'],
    errors: ['A repair team needs to locate the actual component, not a generic example.', 'A temperature number without context weakens both diagnosis and later comparison.', 'The surrounding pattern and visible image help identify the component and interpret the anomaly.'],
    why: 'The instructor combines thermal and visible images for identification and emphasises analysis and reporting. Useful records support a real maintenance decision and a later comparison. A labelled hot spot should remain connected to the equipment and conditions in which it was observed.',
    distinction: 'A striking picture is not yet a traceable maintenance record.',
    practice: 'Keep enough identification and context for another competent person to understand the finding without relying on the surveyor’s memory.',
    followUp: { prompt: 'Why retain a visible image alongside the thermal image?', answer: 'It helps identify the actual equipment or connection represented by the thermal pattern.', why: 'Thermal colours show temperature patterns, while visible details make the affected location easier to recognise.' },
  },
  'p16-l06-q-term-1': {
    prompt: 'A connection carries twice the earlier current. If its resistance is treated as unchanged, what happens to the resistive power loss used to explain its heating?',
    correct: 'It becomes four times as large; this does not mean its Celsius temperature must quadruple.',
    wrong: ['It becomes twice as large because heating power is directly proportional to current.', 'It remains unchanged because the conductor resistance has not changed.', 'It becomes four times as large, so the displayed Celsius temperature must also quadruple.'],
    errors: ['Resistive power depends on current squared, not current alone.', 'Fixed resistance does not keep power fixed when current changes.', 'Power loss and absolute temperature are different quantities; cooling and ambient conditions also affect temperature.'],
    why: 'The electrical relationship is P = I²R. Doubling current at fixed resistance multiplies resistive power by four. The transcript’s loose temperature wording must not be read as a universal rule for multiplying a Celsius reading.',
    distinction: 'The square law applies to resistive power under the stated assumptions, not directly to the temperature display.',
    practice: 'Use the current change to interpret why heating may change, while retaining ambient and operating context in the survey.',
    workingTex: String.raw`\frac{P_2}{P_1}=\frac{(2I)^2R}{I^2R}=4`,
    followUp: { prompt: 'At fixed current, what happens to resistive power if a connection’s resistance doubles?', answer: 'The resistive power doubles.', why: 'In P = I²R, resistance is a direct multiplier when current is fixed.' },
  },
  'p16-l06-q-standard': {
    prompt: 'Three phase-current readings in a computer centre are nearly equal, but the shared neutral appears unusually hot. What should prevent the inspector from dismissing the finding as impossible?',
    correct: 'Nonlinear loads can produce triplen harmonic currents that add in the neutral despite similar phase-current readings.',
    wrong: ['Equal phase-current readings guarantee that every frequency component cancels in the neutral.', 'A neutral cannot carry current when the phase currents have matching RMS magnitudes.', 'The hottest image colour directly establishes which harmonic order is present.'],
    errors: ['Equal RMS magnitudes do not show that every waveform component cancels.', 'Neutral current depends on waveforms and their relationship, not only three displayed magnitudes.', 'Harmonic order requires electrical waveform information, not a thermal colour.'],
    why: 'The instructor uses a computer-centre example to explain third-harmonic and other triplen contributions. Those components can add in the shared neutral rather than cancelling like balanced fundamental currents. The observation calls for investigation, not a conclusion from the phase magnitudes alone.',
    distinction: 'Balanced fundamental currents do not guarantee zero neutral current with nonlinear loads.',
    practice: 'Investigate neutral loading and harmonic content with suitable authorised measurements; do not infer a cable size from this image or example alone.',
    followUp: { prompt: 'Which triplen orders does the instructor mention after the third harmonic?', answer: 'The ninth and fifteenth.', why: 'They belong to the triplen sequence discussed in the explanation of neutral-current addition.' },
  },
  'p16-l08-q-concept-1': {
    prompt: 'A client asks for “a standard four-bedroom rewire” but has not specified socket locations, lighting or future equipment. What is the most useful next step before preparing the detailed price?',
    correct: 'Agree a room-by-room plan of points, positions, finishes and any additional systems.',
    wrong: ['Use the bedroom count to fix the scope and leave accessory positions until first fix.', 'Assume the new installation should have exactly the same points as the old one.', 'Price a standard accessory package and treat any differences as extras after installation.'],
    errors: ['Bedroom count does not identify what will be installed or where.', 'The existing arrangement may not match the client’s requirements.', 'Known preferences should be clarified before quotation rather than becoming predictable surprises.'],
    why: 'The instructor obtains a floor plan and a list of points for each room, then agrees exact positions. His example also includes unusually extensive alarms and future EV provision. Those requirements affect materials and work even when the property sounds ordinary.',
    distinction: 'A property description is not a measurable installation scope.',
    practice: 'Record agreed positions and accessory types before first fix so the installation team and customer are working from the same information.',
    followUp: { prompt: 'Why ask whether the customer wants flat-plate accessories before pricing the work?', answer: 'The selected accessory can change both material cost and the back-box or chasing work needed.', why: 'The instructor links finish choices to installation effort, not just appearance.' },
  },
  'p16-l08-q-concept-2': {
    prompt: 'The occupants can leave a house for only one week, but plastering and later electrical stages normally span a longer period. What must the quotation planning address?',
    correct: 'The occupied-work sequence, access constraints and how the required stages fit the available programme.',
    wrong: ['The same programme as an empty house, because the number of points is unchanged.', 'Only the cost of extra cable, because occupancy does not change labour organisation.', 'Completion of all stages within the week simply because that is the client’s preferred deadline.'],
    errors: ['Occupancy changes access and sequencing even when the point count remains the same.', 'The transcript identifies time and sequencing constraints, not merely a materials change.', 'A requested deadline is a constraint to assess, not evidence that all required work fits within it.'],
    why: 'The instructor contrasts the usual first-fix, plastering, second-fix and testing sequence with this occupied rewire. The residents’ return created pressure that was not captured by counting points alone. The lesson is to plan the actual working conditions and allow realistic time.',
    distinction: 'Labour quantity and the calendar programme are related but not interchangeable.',
    practice: 'Agree access and sequencing before committing to a date; a timetable must not turn required completion checks into optional work.',
    followUp: { prompt: 'Why can two rewires with the same number of points need different labour allowances?', answer: 'Access, occupancy, construction, equipment and existing conditions can change how long the work takes.', why: 'The case demonstrates that point count alone does not describe the effort required.' },
  },
  'p16-l08-q-concept-3': {
    prompt: 'While pricing a rewire, the client asks to retain the wiring in one bedroom. Its integration into the proposed new circuits has not been assessed. How should the electrician treat this request?',
    correct: 'Investigate the retained wiring and its integration, and allow for that work before assuming a saving.',
    wrong: ['Deduct the room’s entire labour allowance because no new wiring will be installed there.', 'Assume the retained wiring is suitable because the customer reports that it still works.', 'Keep the original allowance unchanged and decide whether integration is possible at final testing.'],
    errors: ['Reusing wiring can require investigation and integration work rather than eliminating all labour.', 'Operation alone does not establish suitability for incorporation into the revised installation.', 'Deferring an identified uncertainty leaves the scope and programme unsupported.'],
    why: 'In the case study, figuring out how to retain a bedroom’s wiring added time. Reuse is therefore a design and investigation question before it is a cost deduction. Existing information should support the proposed scope rather than merely confirm the customer’s preference.',
    distinction: 'Keeping a component is not the same as having no work associated with it.',
    practice: 'Identify what must be established about retained work and communicate the effect on the quotation.',
    followUp: { prompt: 'Why does the instructor ask for an EICR before committing to a full rewire?', answer: 'To establish whether the condition justifies that extent of work rather than relying only on an assumption that a rewire is needed.', why: 'The instructor explains that some clients are told they need a rewire when that has not been established.' },
  },
  'p16-l08-q-concept-4': {
    prompt: 'A rewire costing includes cable, accessories and installation hours but leaves out a wall chaser, site lighting and waste removal. What does the instructor’s completed-job review show about this omission?',
    correct: 'These supporting resources still cost money and should be included in planning the job’s total cost.',
    wrong: ['They are automatically covered by the cable quantity, so no separate allowance is needed.', 'They do not affect the estimate because they are not left behind as installed equipment.', 'They should always be charged later regardless of what the customer agreed to pay.'],
    errors: ['Cable quantities do not account for hire, lighting or disposal expenditure.', 'Resources needed to deliver the work can cost money without becoming part of the finished installation.', 'The lesson is to anticipate the costs, not to justify unexplained additions to an agreed price.'],
    why: 'The instructor identifies hire and waste costs that contributed to the overrun. A materials list is useful, but the quotation also needs the resources used to carry out and finish the job. Omitting them can reduce the return on work even if all the accessories were priced correctly.',
    distinction: 'Installed materials are only part of the cost of delivering an installation.',
    practice: 'Check the work sequence for access equipment, hire, temporary site resources and disposal responsibilities before finalising the price.',
    followUp: { prompt: 'What should be clear about the rubbish produced by chasing and removing old wiring?', answer: 'Who is responsible for removal and how its cost is allowed for.', why: 'The instructor points out the conflict created if the customer unexpectedly receives a pile of waste to dispose of.' },
  },
  'p16-l08-q-term-1': {
    prompt: 'The rewire plan appears straightforward from the room layout, but the building survey identifies a material hazard in surfaces on the proposed route. Why does that information belong in quotation planning?',
    correct: 'It can change the permissible method, route, specialist input and time needed for the work.',
    wrong: ['It affects only decorating, so the electrical work can be priced as though the surfaces were clear.', 'It can be left until chasing starts because the number of sockets has already been agreed.', 'It proves that every part of the electrical installation needs replacement.'],
    errors: ['A surface hazard can affect how electrical routes and penetrations are carried out.', 'A known hazard should inform planning rather than becoming a discovery during intrusive work.', 'A building-material hazard and the electrical condition are different findings.'],
    why: 'The instructor’s survey identified asbestos-containing areas, including soffits that might otherwise have been drilled. The transferable lesson is that building information affects the method and price before intrusive work is planned. The video is not instruction or authorisation to disturb hazardous materials.',
    distinction: 'The electrical layout does not reveal every building constraint on installing it.',
    practice: 'Record relevant survey constraints and obtain the appropriate specialist input rather than treating a point schedule as permission to drill every planned location.',
    followUp: { prompt: 'Why should a relevant building survey be available before the quotation is finalised?', answer: 'So identified constraints can influence the proposed method and allowance from the start.', why: 'The instructor explains that learning the locations early allows the work to be planned accordingly.' },
  },
  'p16-l08-q-term-2': {
    prompt: 'The instructor estimated ten person-days for a rewire: two people for five eight-hour days. What labour quantity does that represent before applying an hourly charge?',
    correct: '80 person-hours, because both people’s time contributes to the labour quantity.',
    wrong: ['40 person-hours, because the site programme lasts only five days.', '160 person-hours, because the ten person-days must be multiplied by two people again.', '10 person-hours, because the estimate already states the number of days.'],
    errors: ['This counts only one person’s five days and omits the other person’s time.', 'The person-day figure already includes the number of people; multiplying by two again double-counts them.', 'A day must still be converted into the stated eight hours.'],
    why: 'Person-days count labour, whereas calendar days describe the programme. Ten eight-hour person-days equal eighty person-hours. The case later needed more labour than estimated, so an accurate unit conversion does not by itself make the original time allowance realistic.',
    distinction: 'Five days on the calendar can contain ten person-days of work.',
    practice: 'State the crew size and working-day assumption when converting a programme into a labour allowance.',
    workingTex: String.raw`2\times5\times8=80\;\text{person-hours}`,
    followUp: { prompt: 'How many eight-hour person-hours are represented by fifteen person-days?', answer: '120 person-hours.', why: 'Multiply the labour days by eight; the person-day total already accounts for the people involved.', workingTex: String.raw`15\times8=120\;\text{person-hours}` },
  },
  'p16-l08-q-standard': {
    prompt: 'An apprentice proposes omitting the allowance for second-fix testing because a rewire already has a detailed point schedule. What is the flaw in that quotation?',
    correct: 'The schedule defines what is wanted; it does not perform or resource the completion checks.',
    wrong: ['Testing is unnecessary whenever every cable in the agreed scope is new.', 'Testing time is needed only if the customer separately requests it after first fix.', 'The point schedule counts as evidence that the completed circuits operate as intended.'],
    errors: ['New materials do not demonstrate the condition or correctness of the completed installation.', 'Required completion work should be part of planning the installation, not an optional late request.', 'A schedule is a plan, not the result of inspecting or testing what was built.'],
    why: 'The instructor includes second fix and testing in the normal rewire sequence. Pricing the agreed points without the work needed to complete them understates the job. This applies the case’s planning lesson; the detailed inspection requirements belong to the relevant inspection lessons and applicable documents.',
    distinction: 'A plan describes the intended result; verification provides evidence about the completed work.',
    practice: 'Carry inspection and testing time into the work sequence and labour estimate rather than relying on leftover time at the end.',
    followUp: { prompt: 'Does a short customer deadline remove the need to plan the final stages of the installation?', answer: 'No. The programme must account for the work needed to complete and verify the installation.', why: 'A deadline changes the planning constraint, not what evidence the completed work needs.' },
  },
  'p16-l07-q-concept-1': {
    prompt: 'A bakery asks for a three-phase socket only a few metres from its distribution board. The visit reveals awkward conduit routing and no spare way. How should the electrician develop the labour allowance?',
    correct: 'Walk through the actual job step by step, including the board work, route and completion checks.',
    wrong: ['Base the allowance on the short cable length, since the socket is close to the board.', 'Use the time for a previous socket job, since the accessory rating is the same.', 'Allow for mounting the socket first and price the board work after installation starts.'],
    errors: ['A short distance does not remove the additional work revealed by the site visit.', 'A matching accessory does not establish matching access, routing or distribution-board work.', 'The known board constraint belongs in the planned scope rather than becoming a surprise after work starts.'],
    why: 'The instructor calls this a mental method statement: work through how the job will actually be completed and count the small steps. In his bakery example, routing and making space in the board matter despite the short distance. A realistic allowance supports the required standard of work without rushing.',
    distinction: 'Cable distance is one input to labour, not a complete description of the job.',
    practice: 'Use the survey notes to plan the work sequence and list resources before committing to a price. Completion checks are part of completing the installation, not spare time if the job finishes early.',
    followUp: { prompt: 'Why can photographs taken during the quotation visit improve the later estimate?', answer: 'They let the electrician revisit details that were missed or forgotten during the walk-through.', why: 'The instructor uses phone photographs as a record of the actual site, rather than relying entirely on memory.' },
  },
  'p16-l07-q-concept-2': {
    prompt: 'A customer wants the work next week. The electrician has a free day, but a required accessory has a two-week supplier lead time. What should the quotation communicate?',
    correct: 'A realistic earliest date based on both material availability and the electrician’s availability.',
    wrong: ['Next week as the firm start date, because the electrician has already reserved a day.', 'An immediate start date, with the missing accessory treated as an unexpected delay.', 'No delivery information, because the supplier rather than the electrician controls the lead time.'],
    errors: ['An available diary slot does not make the required equipment available.', 'The lead time is already known and should inform the programme before a date is promised.', 'The customer still needs to understand a known constraint on completing the work.'],
    why: 'The instructor checks delivery time as well as price when sourcing materials. A quotation should not promise a date that depends on equipment arriving sooner than the supplier indicates. Communicating the constraint before acceptance helps both parties plan.',
    distinction: 'Knowing the purchase price is not the same as confirming availability.',
    practice: 'For a specified accessory, confirm price and lead time together and identify any programme dependency in the quotation.',
    followUp: { prompt: 'At what stage should materials be listed in the instructor’s quotation process?', answer: 'As each material is identified during the step-by-step walk-through of the job.', why: 'Building the list alongside the method reduces the chance of overlooking small but necessary items.' },
  },
  'p16-l07-q-concept-3': {
    prompt: 'An electrician prices every stage using their fastest expected time. The property has existing accessories whose internal condition has not yet been seen. Why is this a weak labour estimate?',
    correct: 'It leaves no realistic allowance for the additional work that existing conditions may reveal.',
    wrong: ['It is sound because unfamiliar existing conditions cannot affect a fixed quotation.', 'It is sound because every unforeseen task can be added to the bill without discussion.', 'It is weak only if the electrician’s hourly rate is lower than a competitor’s rate.'],
    errors: ['A fixed price does not prevent unexpected conditions from taking time to address.', 'The instructor stresses communication about extras, not an unexplained addition to the final bill.', 'The issue is the amount of work allowed for, not simply how the hourly rate compares.'],
    why: 'The instructor describes opening accessories and finding problems that take additional time. An optimistic allowance creates pressure to rush when those conditions appear. A realistic buffer addresses uncertainty; a major change still needs discussion rather than an unlimited promise to absorb all work.',
    distinction: 'An allowance for uncertainty is different from ignoring an identified change of scope.',
    practice: 'Review likely snags while estimating the method, and make clear what the quoted work includes before it starts.',
    followUp: { prompt: 'How can an unrealistically short allowance affect workmanship even when the customer accepts the price?', answer: 'It creates pressure to rush once the allowed time runs out.', why: 'The instructor connects realistic estimating with sufficient time to complete work to the intended standard.' },
  },
  'p16-l07-q-concept-4': {
    prompt: 'During an agreed socket installation, the customer requests an additional light that is outside the written quotation. What response follows the instructor’s approach?',
    correct: 'Explain the additional work and price, and agree the extra with the customer before proceeding with it.',
    wrong: ['Install the light and add its cost to the final invoice without a separate discussion.', 'Treat the extra light as included because the original quotation was a fixed price.', 'Abandon the original quotation and charge all the work by the hour instead.'],
    errors: ['An unexplained final charge creates the surprise that the instructor aims to avoid.', 'A fixed quotation applies to its agreed work; it does not automatically include new requests.', 'An extra does not automatically require replacing the agreed basis for the original work.'],
    why: 'The instructor distinguishes the original quoted job from extras that arise during it. Clear communication establishes what the customer is asking for and what the change costs. Agreement at that point avoids relying on different expectations at invoicing.',
    distinction: 'A fixed price for defined work is not a price for every later addition.',
    practice: 'Record the agreed extra alongside the original scope so the job record and final charge describe the same work.',
    followUp: { prompt: 'Why give a written quotation even when a customer initially says they are not concerned about price?', answer: 'It establishes the expected work and price before either party relies on a different assumption.', why: 'The instructor still gives a quotation because an initially relaxed conversation does not prevent later surprise.' },
  },
  'p16-l07-q-term-1': {
    prompt: 'In this quotation lesson, the electrician offers one fixed total while keeping a detailed internal labour and materials calculation. What does that fixed-price quotation tell the customer?',
    correct: 'The price for the defined end result, with changes to that agreed work discussed separately.',
    wrong: ['The labour charge only, with every material added after the installation is finished.', 'A provisional starting figure that will automatically rise to match the actual hours.', 'An unlimited commitment to any electrical work requested while the electrician is on site.'],
    errors: ['The instructor’s total includes the priced job, not labour alone with undisclosed material additions.', 'This confuses his fixed quotation with an indicative estimate.', 'The quotation concerns a defined job, not unlimited subsequent requests.'],
    why: 'The instructor calculates labour and materials internally but normally presents a single total for the job. His emphasis is clarity about the result and its price, while discussing extras if the work changes. Presenting one total does not remove the need to calculate its components carefully.',
    distinction: 'The customer-facing total and the electrician’s detailed costing serve different purposes.',
    practice: 'Keep a detailed costing record even when the customer receives a concise quotation. This is the instructor’s presentation preference, not a universal rule about what every quotation must contain.',
    followUp: { prompt: 'Why does the instructor prepare the quotation soon after the site visit?', answer: 'The details remain fresh, reducing mistakes caused by forgetting what was seen.', why: 'Prompt preparation supports accuracy as well as a timely response to the customer.' },
  },
};
