export type StandardSource = { id:string; organisation:string; identifier:string; edition:string; verifiedAt:string; url:string; scope:string };
// Source URLs support editorial verification; learners receive in-app summaries.
export const standardSources:StandardSource[] = [
  {id:'bs7671',organisation:'IET / BSI',identifier:'BS 7671:2018+A4:2026',edition:'18th edition, Amendment 4',verifiedAt:'2026-09-05',url:'https://electrical.theiet.org/bs-7671-18th-edition-wiring-regulations/ensure-you-are-up-to-date-with-bs-7671/',scope:'Requirements for electrical installations. Amendment 4 was published on 15 April 2026; the preceding edition remains valid until 15 October 2026.'},
  {id:'part-m',organisation:'UK Government',identifier:'Approved Document M, Volume 1',edition:'2015 edition incorporating 2024 amendments',verifiedAt:'2026-09-05',url:'https://assets.publishing.service.gov.uk/media/6717d29438149ce9d09e3862/The_Merged_Approved_Documents_Oct24.pdf',scope:'Accessibility guidance for new dwellings in England, including reachable accessory positions. It is not a universal BS 7671 mounting-height rule.'},
  {id:'iet-faq',organisation:'IET',identifier:'BS 7671:2018 FAQs',edition:'Wiring Matters 77',verifiedAt:'2026-09-05',url:'https://electrical.theiet.org/wiring-matters/years/2019/77-september-2019/bs-76712018-frequently-asked-questions/',scope:'IET clarification on bathroom socket locations, bathroom ingress protection and guidance for socket positions near kitchen sinks.'},
  {id:'iet-cable',organisation:'IET',identifier:'BS 7671 Appendix 4 explainer',edition:'18th edition design guidance',verifiedAt:'2026-09-05',url:'https://electrical.theiet.org/media/1617/appendix-4-of-bs-7671.pdf',scope:'Current-carrying-capacity calculation and correction-factor method for cable selection.'},
  {id:'gs38',organisation:'HSE',identifier:'GS38',edition:'Fourth edition, 2015',verifiedAt:'2026-09-05',url:'https://www.hse.gov.uk/pubns/books/gs38.htm',scope:'Guidance on suitable electrical test equipment and safe testing.'},
  {id:'iet-loop',organisation:'IET',identifier:'Wiring Matters 105',edition:'May 2025',verifiedAt:'2026-09-05',url:'https://electrical.theiet.org/wiring-matters/years/2025/105-may-2025/minimizing-unnecessary-live-testing-for-initial-verification/',scope:'How dead-test evidence can reduce unnecessary live testing.'},
];
export type StandardsTopic = { id:string;title:string;reference:string;match:RegExp;principle:string;why:string;example:string;verify:string;mistake:string;sources:string[] };
export const standardsTopics:StandardsTopic[] = [
  {id:'bathroom-sockets',title:'Keep ordinary sockets outside the bathroom limit',reference:'BS 7671 · Section 701',match:/bathroom.{0,80}(socket|outlet)|shaver socket|shaver outlet/i,principle:'An ordinary 230 V 13 A socket-outlet may be installed only at least 3 m horizontally from the boundary of zone 1. A compliant shaver supply is a different, limited-purpose accessory.',why:'The rule keeps ordinary plug-in equipment and trailing leads away from the highest wet-location risk.',example:'Measure the 3 m horizontal distance from the boundary of zone 1, not from the bath centre or the nearest wall. Do not treat a shaver outlet as a general socket.',verify:'Equipment in zones 1 and 2 requires at least IPX4, or IPX5 where water jets are likely. Product instructions and every other Section 701 condition still apply.',mistake:'A cover or an RCD does not allow an ordinary socket inside the 3 m limit.',sources:['bs7671','iet-faq']},
  {id:'kitchen-placement',title:'Place kitchen accessories from the finished layout',reference:'IET guidance · BS 7671 has no fixed sink distance',match:/kitchen.{0,100}(socket|outlet|accessor|cooker.point|position|layout)|socket.{0,60}(sink|worktop)/i,principle:'BS 7671 gives no fixed distance between a socket and a kitchen sink. IET guidance recommends at least 300 mm from the sink edge, with the finished worktop, splash risk, heat and appliance leads also considered.',why:'The 300 mm figure reduces splash and lead damage risk, but the final position still requires a site-specific judgement.',example:'Set out from the finished sink edge shown on the coordinated kitchen elevation. A point 300 mm from the centreline may still be too close to the edge.',verify:'Confirm cabinet, worktop, sink, hob and appliance positions before first fix. Keep cooker controls and isolation accessible.',mistake:'Do not present 300 mm as a universal BS 7671 regulation.',sources:['iet-faq','bs7671']},
  {id:'accessory-height',title:'Use the applicable accessibility height',reference:'Approved Document M · new dwellings in England',match:/(socket|switch|accessor).{0,80}(height|level|position|set.out|placement)|first fix.{0,80}(box|socket|switch)/i,principle:'BS 7671 does not set one general mounting height. For new dwellings covered by Approved Document M in England, switches and socket-outlets for lighting and other equipment should be 450–1200 mm above finished floor level.',why:'The band keeps common controls and outlets within reach for a wider range of occupants.',example:'Measure from the final floor level, including the floor finish. A rough-floor measurement can put the completed accessory outside the intended band.',verify:'Use the project’s applicable building requirements and drawings. Some controls, such as consumer-unit switches used to satisfy accessibility guidance, use different guidance.',mistake:'Do not apply 450–1200 mm as a universal BS 7671 dimension for every building.',sources:['part-m','bs7671']},
  {id:'fault-protection',title:'Disconnect a dangerous earth fault',reference:'BS 7671 · Chapter 41',match:/earthing|bonding|loop impedance|\bzs\b|\bze\b|protective conductor|tn-s|tn-c-s|\btt\b/i,principle:'Accessible metal must not remain dangerously live after an insulation fault. The protective path and protective device must work together.',why:'A complete return path allows fault current to flow. The protective device must disconnect within the time required for that circuit.',example:'If a line conductor touches a metal appliance case, the CPC provides the intended protective path. If that path is broken, the appliance can still work while its case is hazardous.',verify:'For a Zs comparison, identify the circuit’s device type and rating, the matching maximum Zs and the temperature basis. Ze alone is only the external part of the loop.',mistake:'A working appliance does not prove its protective path is intact.',sources:['bs7671','iet-loop']},
  {id:'residual',title:'Know what an RCD detects',reference:'BS 7671 · Chapters 41 and 53',match:/\brcd\b|\brcbo\b|\brccb\b|residual/i,principle:'An RCD detects an imbalance between outgoing and returning current. It provides a different function from overload protection.',why:'Current returning outside the intended live conductors can indicate leakage. An RCCB detects residual current; an RCBO also includes overcurrent protection.',example:'An appliance can draw a normal load current while leaking current to its metal case. A residual-current device and an overcurrent device respond to different features of that fault.',verify:'The test button checks the device’s built-in test function. It does not test every connection or prove the installation is safe.',mistake:'An RCD does not make touching live conductors safe.',sources:['bs7671']},
  {id:'cable-design',title:'Calculate cable size from the installation',reference:'BS 7671 · Sections 433, 434, 525 and Appendix 4',match:/cable|trunking|conduit|voltage drop|design current|diversity|demand|overcurrent|breaker|fuse|\bmcb\b|\bmccb\b/i,principle:'BS 7671 does not assign one cable size from the load name alone. Establish Ib, select In, then choose a cable whose corrected capacity Iz satisfies Ib ≤ In ≤ Iz.',why:'Installation method, ambient temperature, grouping and thermal insulation change how much current a cable can carry safely.',example:'If the chosen device is 25 A but the cable’s corrected Iz is 18 A, overload coordination fails because In is greater than Iz.',verify:'When tabulated capacity is needed, use It ≥ In ÷ (Ca × Cg × Ci × Cc, where applicable). Then check voltage drop, fault disconnection, short-circuit withstand, terminals and mechanical duty.',mistake:'A familiar size such as 1.5 mm² or 2.5 mm² is not automatically correct for a circuit type.',sources:['bs7671','iet-cable']},
  {id:'safe-testing',title:'Isolate before a dead test',reference:'BS 7671 · Isolation and switching; HSE GS38',match:/test|isolation|instrument|multimeter|measure|fault.find|diagnos|commission|motor control/i,principle:'A control switch stopping equipment is not proof that its conductors are dead.',why:'Another supply, a wiring fault or stored energy may still be present.',example:'A resistance test belongs on a safely isolated circuit. Applying a resistance range to a live circuit can damage the instrument and expose the operator to danger.',verify:'The safe-isolation sequence identifies all supplies, isolates and secures them, then verifies absence of voltage with suitable equipment proved before and after use.',mistake:'A non-contact detector alone is not proof of safe isolation.',sources:['bs7671','gs38']},
  {id:'verification',title:'Check safety as well as operation',reference:'BS 7671 · Part 6: Inspection and testing',match:/inspection|certificat|commission|handover|periodic|test result|polarity|insulation/i,principle:'Inspection, testing and records establish different parts of the installation’s condition.',why:'An appliance may operate with incorrect polarity or a missing protective conductor.',example:'A lamp lighting proves it receives power. It does not prove that a single-pole switch is in the line conductor or that exposed metal has a continuous protective path.',verify:'After correcting a defect, repeat the relevant checks and record the actual results. Never replace missing measurements with estimates.',mistake:'“It works” is not the same as “it has been verified”.',sources:['bs7671','iet-loop']},
  {id:'multiple-sources',title:'Check every source of energy',reference:'BS 7671 · Generating sets and prosumer installations',match:/solar|\bpv\b|battery|batteries|inverter|generator|\bups\b|storage|ev charg/i,principle:'Opening the grid main switch may leave a battery, generator or PV source connected.',why:'The supply arrangement and available fault current can change when the system changes operating mode.',example:'Illuminated PV modules can produce DC even after their AC connection has been isolated.',verify:'The design must establish isolation, earthing and protective operation for each intended mode, including island operation.',mistake:'A grid-mode protection calculation does not automatically describe inverter island mode.',sources:['bs7671','gs38']},
];
const foundation:StandardsTopic={id:'basic-protection',title:'Keep live parts out of reach',reference:'BS 7671 · Chapter 41: Protection against electric shock',match:/.*/,principle:'Basic protection prevents contact with live parts during normal use. Insulation and suitable barriers or enclosures provide this protection.',why:'Current can pass through a person who becomes part of a circuit. Keeping live conductors inaccessible prevents that contact.',example:'The plastic insulation around a conductor separates the live metal from fingers and nearby metalwork. Damaged insulation removes that barrier.',verify:'This is a useful installation connection for the theory in this lesson. It is not a separate rule about the mathematical or scientific model.',mistake:'A conductor looking clean or an appliance working does not establish that its insulation is sound.',sources:['bs7671']};
export const topicsForLesson=(text:string)=>{const matched=standardsTopics.filter(topic=>topic.match.test(text));return matched.length?matched.slice(0,2):[foundation];};
