import { Q, S, type SuppliedTeaching } from './supplied-content-types';

export const resistanceContent: Record<string, SuppliedTeaching> = {
  mppNEL8thcM: S(
    'A conductor has resistance even when it is intended to carry current. For the same material and temperature, resistance rises with length and falls as cross-sectional area increases.',
    ['Length and resistance are directly proportional when area and material stay fixed.', 'Two equal conductors in parallel provide twice the conducting area and half the resistance.', 'Compare readings only after accounting for lead resistance and the actual conducting path.'],
    'Predict the resistance of an isolated cable before comparing it with a low-resistance test. Trace whether the test includes one conductor, an outgoing-and-return pair, or parallel paths.',
    'One 100 m conductor measures 1.78 Ω. What should two identical conductors measure when joined in series?', '3.56 Ω. Rtotal = 1.78 + 1.78 = 3.56 Ω.', 'The current path is now 200 m long with the original area. Both conductor resistances contribute in series.', [
      Q('A 20 m conductor measures 0.40 Ω. What resistance should 60 m of the same conductor have at the same temperature?', '1.20 Ω|0.13 Ω|0.40 Ω|3.60 Ω', 'Dividing by three reverses the length relationship.|Unchanged material does not mean unchanged resistance when length changes.|Squaring the length ratio confuses length with an area effect.', 'R is proportional to length: 0.40 × 60/20 = 1.20 Ω. The longer path presents more resistance.', 'What happens to conductor resistance when its length is halved, with all other factors fixed?', 'It halves because R is directly proportional to length.'),
      Q('Two identical 1.8 Ω conductors are connected in parallel at both ends. What is their combined resistance?', '0.9 Ω|3.6 Ω|1.8 Ω|0.45 Ω', 'Adding the resistances describes series wiring, not parallel paths.|Both paths carry current, so the original resistance cannot remain unchanged.|The area doubles; it does not increase by a factor of four.', 'Equal parallel paths share current. Their combined conducting area doubles, so the equivalent resistance halves.', 'How does joining equal conductors in parallel differ from joining them end to end?', 'Parallel joining doubles the effective area and halves resistance; end-to-end joining doubles length and resistance.'),
      Q('A cable route is 30 m long. Its equal line and neutral conductors are linked at the far end for a dead resistance check. What conductor length is measured?', '60 m|30 m|15 m|90 m', 'The reading includes the return conductor as well as the outward conductor.|The paths are in series, so their lengths do not halve.|Only two 30 m conductors form the stated path.', 'The test signal travels to the far-end link and returns through the second conductor. The measured series path is 30 + 30 = 60 m.', 'Why can a loop resistance be about twice the resistance of one conductor?', 'The loop includes an outward and a return conductor of equal resistance.'),
      Q('A conductor is expected to measure 0.10 Ω, but the shorted test leads measure 0.03 Ω. What must the comparison account for?', 'The lead contribution to the measured resistance|A 30% change in the conductor length|A change in conductor resistivity caused by the meter|A parallel path through the open test leads', 'Lead resistance does not establish any change in conductor length.|The meter reading includes leads without changing the material property being measured.|The connected leads contribute in series, not as an open parallel path.', 'At low resistances, lead and contact contributions can be a substantial part of the reading. Null suitable leads or account for their measured contribution.', 'Why recheck lead zero after changing probes?', 'Changing probes changes the test path and may change the resistance contributed by the leads and contacts.'),
      Q('Two copper conductors have equal length and temperature, but one has twice the cross-sectional area. Which comparison is valid?', 'The thicker conductor has half the resistance|The thicker conductor has twice the resistance|Both have the same resistance because both are copper|The thicker conductor has half the resistivity', 'Increasing area provides more parallel conducting paths, reducing resistance.|Material is only one factor; conductor geometry also matters.|Changing geometry changes resistance, not the material resistivity.', 'For fixed resistivity and length, R = ρL/A. Doubling A divides R by two without changing ρ.', 'Which is a material property: resistance of a cable or resistivity at a stated temperature?', 'Resistivity is the material property; cable resistance also depends on length and area.'),
    ]),
  aT24eK3aniU: S(
    'Copper resistance increases as the conductor warms. A resistance reading must be interpreted at the conductor temperature, which need not equal the surrounding air temperature.',
    ['Cooling copper lowers resistance; warming it raises resistance over the range demonstrated.', 'Length and area comparisons still apply when conductors are at the same temperature.', 'A rising temperature trend is not proof that resistance is directly proportional to Celsius temperature.'],
    'A cold continuity reading and the resistance of a loaded warm cable need not match. Use the stated temperature basis when comparing calculations, measurements and conductor data.',
    'The same copper conductor reads 1.78 Ω when cool and 2.04 Ω when warm. Must it have become longer?', 'No. Its resistance can rise because its temperature rises.', 'The material resistivity changes with temperature even when the conductor geometry is effectively unchanged.', [
      Q('An isolated copper conductor warms from 20 °C to 40 °C while its geometry stays effectively fixed. Which prediction is justified?', 'Its resistance increases, but need not double|Its resistance decreases because warmer electrons move faster|Its resistance stays fixed because its area is unchanged|Its resistance doubles because the Celsius temperature doubles', 'Faster thermal motion does not establish lower conductor resistance.|Geometry is not the only factor: resistivity also depends on temperature.|A doubling on the Celsius scale does not imply a doubling of resistance.', 'Warming copper increases resistivity over ordinary operating temperatures. The same geometry therefore has a higher resistance.', 'Why can the same cable give different resistance readings on a cold and a warm day?', 'Its conductor temperature can change the copper resistivity and hence its resistance.'),
      Q('A copper conductor measures 2.04 Ω when warm. What should two equal lengths in series measure at that same temperature?', '4.08 Ω|1.02 Ω|2.04 Ω|3.56 Ω', 'Halving describes two equal parallel paths, not a series path.|The series path contains twice the length.|3.56 Ω uses the earlier cold reading instead of the stated warm reading.', 'Each warm conductor contributes 2.04 Ω. Series resistance is 2.04 + 2.04 = 4.08 Ω.', 'Does warming a conductor remove the relationship between length and resistance?', 'No. At a common temperature, doubling length still doubles resistance.'),
      Q('Why should a warm cable reading not be compared directly with a reference value specified at 20 °C?', 'The reference and measurement use different temperature conditions|Resistance is determined only by ambient air temperature|Copper changes into a different metal when heated|A warm reading measures inductance instead of resistance', 'Conductor temperature can differ from ambient, especially under load.|The material remains copper; its resistivity changes with temperature.|The selected resistance test still measures resistance.', 'A comparison needs a common temperature basis. Heating can raise the measured resistance without indicating a change of length or conductor size.', 'Which temperature matters directly to conductor resistivity?', 'The conductor temperature, not simply the temperature of the surrounding air.'),
      Q('A demonstration shows copper resistance rising as it warms. Which conclusion is justified?', 'Copper resistance rises over the demonstrated temperature range|Doubling Celsius temperature must double resistance|Every material has the same temperature response as copper|Temperature determines resistance independently of length and area', 'Celsius has an arbitrary zero, so this is not a direct-proportion claim.|Different materials can have different temperature coefficients.|Geometry still contributes through R = ρL/A.', 'The observation establishes a trend for copper. It does not establish a universal material law or a doubling rule on the Celsius scale.', 'Why is a rising graph not enough to claim direct proportionality?', 'Direct proportionality requires a constant ratio and a line through the relevant origin, not merely an increase.'),
      Q('Two copper samples have the same geometry but different resistance readings. What condition should be checked before inferring a material defect?', 'Whether both samples are at the same temperature|Whether the readings use different time units|Whether copper has lost all mobile electrons|Whether resistance should be measured in farads', 'Time units do not explain a difference between two resistance readings.|Normal temperature changes do not remove all conduction electrons.|Farads measure capacitance, not resistance.', 'A temperature difference is a plausible cause of a resistance difference. Measurement leads and contacts also need to be comparable before attributing it to the sample.', 'What should remain matched when comparing the resistance of equal copper samples?', 'Length, area, conductor temperature and the measurement setup.'),
    ], 'Corrects the transcript’s loose use of “directly proportional” for temperature. The heated-cable demonstration is observational, not a suggested home experiment.'),
  oYL9DVdWBpA: S(
    'A known material and cross-sectional area let resistance estimate conductor length. Rearrange R = ρL/A to L = RA/ρ, and keep the area and resistivity units compatible.',
    ['Length is the unknown; resistance is the measured input.', 'Convert 1.5 mm² to 1.5 × 10⁻⁶ m² when resistivity is in Ω·m.', 'Lead resistance, temperature and conductor tolerances limit the precision of the estimate.'],
    'Estimate the remaining length of a known isolated cable using its resistance, then compare it with a physical measurement. Treat the result as an estimate with stated assumptions.',
    'For R = 0.19 Ω, A = 1.5 × 10⁻⁶ m² and ρ = 17.2 × 10⁻⁹ Ω·m, what length is estimated?', 'L = RA/ρ = (0.19 × 1.5 × 10⁻⁶)/(17.2 × 10⁻⁹) = 16.57 m, approximately.', 'Multiplying R by A and dividing by the material resistivity isolates length. Precision is limited by the measured inputs.', [
      Q('Which rearrangement of R = ρL/A gives conductor length?', 'L = RA/ρ|L = Rρ/A|L = ρA/R|L = R/(ρA)', 'This reverses the roles of area and resistivity.|Resistance belongs in the numerator when finding length.|Area must multiply resistance, not divide it.', 'Multiply both sides by A, then divide by ρ: RA = ρL, so L = RA/ρ.', 'Which operation first removes the division by area in R = ρL/A?', 'Multiply both sides by A, giving RA = ρL.'),
      Q('A length calculation uses resistivity in Ω·m. How should 1.5 mm² be entered?', '1.5 × 10⁻⁶ m²|1.5 × 10⁻³ m²|1.5 m²|1.5 × 10⁶ m²', 'The length conversion factor must also be squared for area.|This treats a small cable area as a square-metre area.|The conversion must make the numerical area smaller, not larger.', 'One millimetre is 10⁻³ m. Squaring both dimensions gives 1 mm² = 10⁻⁶ m².', 'Why does converting square millimetres require a factor of 10⁻⁶?', 'Area has two length dimensions, so (10⁻³)² = 10⁻⁶.'),
      Q('The resistance of a uniform isolated conductor doubles while the assumed area, material and temperature stay fixed. What length does the formula infer?', 'Twice the original length|Half the original length|The original length|Four times the original length', 'L = RA/ρ increases with R; it does not vary inversely.|A change in resistance changes the inferred length under the stated assumptions.|Resistance is not squared in the length relationship.', 'With A and ρ fixed, L is directly proportional to the measured R. Doubling R therefore doubles the estimated length.', 'For the same measured resistance, what does a larger known area imply about length?', 'A longer conductor, because more length is needed to give the same resistance with a larger area.'),
      Q('Unaccounted test-lead resistance is included in a cable-length estimate. How is the result affected?', 'The estimated length is too long|The estimated length is too short|Only the area estimate changes|The extra resistance cancels automatically', 'An excessive R increases RA/ρ rather than reducing it.|Area is a supplied input in this calculation, not the unknown.|The formula does not distinguish lead resistance from cable resistance.', 'Extra series resistance is mistaken for extra conductor length. Account for the measuring path before using R in the estimate.', 'Why can poor probe contact make a cable appear longer electrically?', 'Contact resistance adds to the measured R and is then wrongly converted into cable length.'),
      Q('An electrical estimate gives 16.57 m and a physical measurement gives about 16 m. What is the best interpretation?', 'Check input tolerances and measurement uncertainty|The formula is disproved by any difference|Round every future result down to 16 m|The cable must have changed its material', 'An approximate experiment cannot establish an exact contradiction from this difference alone.|Rounding is not a correction for unknown measurement error.|The difference does not establish a change of material.', 'The estimate depends on resistivity, nominal area, temperature and resistance measurement. A small difference calls for checking those inputs, not inventing a new cable length rule.', 'Why should a calculated length not be reported as exact to many decimal places?', 'The measured resistance and assumed material and area are not exact to that precision.'),
    ]),
  Gy2u6W8IyCg: S(
    'Resistivity separates a material’s behaviour from sample geometry. Measure resistance and use ρ = RA/L; the result belongs to the sample and its temperature, not every alloy with a similar name.',
    ['Resistance is measured in Ω; resistivity is measured in Ω·m.', 'Convert length and area separately before substituting.', 'Contact and lead resistance can bias a two-terminal estimate upward.'],
    'Compare resistance-wire samples on a common unit and temperature basis before reasoning about a heating element. A measured resistivity is evidence, not a complete material specification.',
    'A 0.5 m sample has area 0.21 mm² and resistance 3.6 Ω. What resistivity follows?', 'ρ = RA/L = 3.6 × 0.21 × 10⁻⁶ / 0.5 = 1.512 × 10⁻⁶ Ω·m = 1.512 μΩ·m.', 'Area must be expressed in square metres. The result is a material estimate inferred from this particular sample.', [
      Q('Which additional information is needed to infer resistivity from a resistance measurement?', 'Sample length and cross-sectional area|Sample length and test voltage only|Sample cross-sectional area and test current only|Test voltage and test current only', 'Length is needed, but test voltage cannot replace cross-sectional area.|Area is needed, but test current cannot replace sample length.|These may establish resistance, which is already given; geometry is still missing.', 'Resistance alone mixes material and geometry. Multiplying it by area and dividing by length separates the geometry from the inferred material property.', 'Can two wires with equal resistance have different resistivities?', 'Yes. Different lengths and areas can give equal resistance despite different material resistivities.'),
      Q('What is the SI unit of resistivity?', 'Ω·m|Ω/m|Ω|Ω·m²', 'Ohms per metre describes resistance per length, not resistivity.|Ohms measure the resistance of the complete sample.|Dividing area by length leaves one power of metres, not two.', 'From ρ = RA/L, the units are Ω × m² / m = Ω·m.', 'How do the units in RA/L reduce?', 'Ω × m² divided by m gives Ω·m.'),
      Q('A 500 mm sample is used in a calculation with SI base units. What length is entered?', '0.5 m|500 m|0.0005 m|5 m', 'The original number is in millimetres, not metres.|This divides by a million rather than one thousand.|500 mm is half a metre, not five metres.', 'Divide millimetres by 1000 to obtain metres: 500/1000 = 0.5 m. Length and area use different conversion powers.', 'How does the millimetre conversion differ from the square-millimetre conversion?', 'mm to m uses 10⁻³; mm² to m² uses 10⁻⁶.'),
      Q('A sample is measured with leads contributing 0.2 Ω. The calculation uses the whole reading in ρ = RA/L. What error results?', 'The inferred resistivity is too high|The inferred resistivity is too low|The inferred resistivity is unchanged because leads are outside the sample|The sample area is automatically corrected by the resistance reading', 'Extra R multiplies the result upward, not downward.|The meter includes the external series resistance even though it is not part of the sample.|Area is an independent input; the formula cannot correct it from the resistance reading.', 'Any extra measured series resistance is attributed to the sample. The resulting material estimate is therefore biased upward.', 'What must be excluded when the aim is to estimate the sample’s resistivity?', 'Resistance from measuring leads and contacts, as far as the measurement method allows.'),
      Q('A nichrome sample gives 1.512 μΩ·m. What can be concluded?', 'This is the estimate for that sample under the measurement conditions|Every nichrome alloy has exactly this value|The sample resistance is 1.512 μΩ|The sample has no temperature dependence', 'Alloy composition and measurement conditions can vary.|The result is resistivity, not the resistance of the sample.|One measurement does not establish a temperature coefficient.', 'A sample-derived value should retain its units and conditions. It is not a universal exact constant for all products called nichrome.', 'Why retain the material and temperature context with a resistivity result?', 'Composition and temperature affect the property, so the numerical value alone is incomplete.'),
    ]),
  Zt1tL5wJoPU: S(
    'Compare materials using resistivity in matching units, not the raw resistance of differently sized samples. A thinner constantan sample can have higher resistance than a thicker nichrome sample despite lower resistivity.',
    ['The constantan calculation uses ρ = RA/L with A = 0.075 mm² and L = 0.5 m.', '604.5 nΩ·m and 0.6045 μΩ·m describe the same resistivity.', 'Different sample geometries prevent a direct ranking of materials by resistance alone.'],
    'When comparing resistance-wire samples, record dimensions with each resistance reading. Otherwise a thin wire can be mistaken for a material with intrinsically higher resistivity.',
    'For R = 4.03 Ω, A = 0.075 mm² and L = 0.5 m, what is the inferred resistivity?', 'ρ = 4.03 × 0.075 × 10⁻⁶ / 0.5 = 6.045 × 10⁻⁷ Ω·m = 0.6045 μΩ·m.', 'The square-millimetre conversion belongs in the numerator. This is an estimate from the demonstrated sample and includes measurement limitations.', [
      Q('A thin constantan sample has higher resistance than a thicker nichrome sample of equal length. Does this establish higher constantan resistivity?', 'No; the areas must be included in the comparison|Yes; higher resistance always means higher resistivity|Yes; equal length removes every geometric effect|No; all metal alloys have identical resistivity', 'Resistance also depends inversely on sample area.|Equal length does not remove the area difference.|Different alloys can have different material resistivities.', 'Compute RA/L for each sample. Raw resistance cannot isolate material behaviour when the sample areas differ.', 'Why normalize by sample dimensions when comparing materials?', 'It separates geometry from the material resistivity.'),
      Q('Which value equals 604.5 nΩ·m?', '0.6045 μΩ·m|604.5 μΩ·m|604500 μΩ·m|0.0006045 μΩ·m', 'A micro-unit is 1000 nano-units, so the numerical value must shrink.|This converts in the wrong direction.|This divides by a million instead of one thousand.', '1 μΩ·m equals 1000 nΩ·m. Therefore 604.5/1000 = 0.6045 μΩ·m.', 'Is 0.6 μΩ·m larger or smaller than 1.5 μΩ·m?', 'Smaller; both use the same prefix and can be compared directly.'),
      Q('Which area in square metres corresponds to 0.075 mm²?', '7.5 × 10⁻⁸ m²|7.5 × 10⁻⁵ m²|7.5 × 10⁻² m²|7.5 × 10⁸ m²', 'This uses a linear millimetre conversion for an area.|The original 0.075 is not already in square metres.|Converting a small area to square metres cannot create a huge positive exponent.', '0.075 × 10⁻⁶ = 7.5 × 10⁻⁸ m². Keeping the area units correct prevents a thousandfold error.', 'How can you check an area conversion before calculating?', 'A small wire area must be a very small fraction of one square metre.'),
      Q('A resistivity estimate is above a reference value. Which investigation is justified first?', 'Check leads, contacts, temperature and sample dimensions|Replace the measured value with the reference without checking|Assume the sample has become a perfect insulator|Conclude that ρ = RA/L applies only to copper', 'Replacing the value hides the measurement discrepancy rather than explaining it.|A finite resistance estimate does not establish insulation behaviour.|The uniform-conductor relationship is not restricted to copper.', 'The calculation is only as good as its inputs. Additional series resistance and uncertain geometry can explain a high estimate.', 'Does agreement to many displayed digits prove a resistivity measurement is accurate?', 'No. Displayed digits do not remove input uncertainty or systematic measurement error.'),
      Q('Two materials are compared at the same temperature using equal lengths and areas. What does the higher resistance then indicate?', 'Higher resistivity under those conditions|Lower resistivity under those conditions|A longer path despite equal lengths|A larger area despite equal areas', 'With L/A fixed, resistance increases with resistivity.|The question fixes length, so that cannot explain the difference.|The question fixes area, so that cannot explain the difference.', 'R = ρL/A leaves resistivity as the differing factor when geometry and temperature are controlled.', 'When can resistance readings directly rank sample resistivities?', 'When length, cross-sectional area, temperature and measurement conditions are matched.'),
    ]),
};
