import type { Calculation, FormulaMode } from './toolkit-math';
import { formatNumber } from './toolkit-math';

export default function ToolkitVisual({ mode, result }: { mode: FormulaMode; result: Calculation }) {
  const { numbers: n } = result;
  if (mode === 'series') return <figure className="formula-visual"><figcaption>One path. Resistance adds up.</figcaption><svg viewBox="0 0 520 180" role="img" aria-label={`Three series resistors: ${n.r1}, ${n.r2}, and ${n.r3} ohms. Total ${result.value} ohms.`}><path d="M35 92H85M155 92H220M290 92H355M425 92H485" className="diagram-wire" />{[n.r1, n.r2, n.r3].map((r, i) => <g key={i}><rect x={85 + i * 135} y="72" width="70" height="40" rx="3" className="diagram-load" /><text x={120 + i * 135} y="54" textAnchor="middle">R{i + 1}</text><text x={120 + i * 135} y="142" textAnchor="middle">{formatNumber(r)} Ω</text></g>)}</svg><div className="resistance-stack" aria-hidden="true">{[n.r1, n.r2, n.r3].map((r, i) => <span key={i} style={{ flexGrow: r || 0.01 }} />)}</div><p>The coloured lengths show each resistor’s share of the total.</p></figure>;
  if (mode === 'energy') {
    const end = 80 + (n.time / Math.max(6, n.time)) * 370;
    const height = n.power / Math.max(200, n.power) * 120;
    const top = 175 - height;
    return <figure className="formula-visual"><figcaption>Energy is the area under power × time.</figcaption><svg viewBox="0 0 520 220" role="img" aria-label={`Constant ${n.power} watts for ${n.time} hours gives ${formatNumber(result.value)} kilowatt-hours.`}><path d="M65 25V175H490" className="diagram-axis" /><rect x="80" y={top} width={end - 80} height={height} className="energy-area" /><path d={`M80 ${top}H${end}`} className="diagram-wire" /><text x="80" y={top - 12}>{formatNumber(n.power)} W</text><text x="80" y="200">0 h</text><text x={end} y="200" textAnchor="end">{formatNumber(n.time)} h</text>{end - 80 > 100 && height > 55 && <text x={(80 + end) / 2} y={top + height / 2 + 8} textAnchor="middle" className="diagram-answer">E</text>}</svg><p>Area model; axes rescale to your values.</p></figure>;
  }
  if (mode === 'three-phase') {
    const curves = [0, 1, 2].map((phase) => Array.from({ length: 121 }, (_, i) => `${i ? 'L' : 'M'}${35 + i * 3.75},${95 - 44 * Math.sin(i / 120 * Math.PI * 4 - phase * Math.PI * 2 / 3)}`).join(' '));
    const apparent = Math.sqrt(3) * n.voltage * n.current / 1000;
    return <figure className="formula-visual"><figcaption>Three phases, 120° apart</figcaption><svg viewBox="0 0 520 190" role="img" aria-label="Three sinusoidal phases with equal amplitude, separated by 120 degrees. Normalised illustration."><path d="M35 95H485" className="diagram-axis" />{curves.map((d, i) => <path key={i} d={d} fill="none" stroke={['#43d3e2', '#ff914d', '#b7a4ff'][i]} strokeWidth="3" />)}{['L1', 'L2', 'L3'].map((label, i) => <text key={label} x={170 + i * 90} y="170" style={{ fill: ['#43d3e2', '#ff914d', '#b7a4ff'][i] }}>{label}</text>)}</svg><div className="power-factor-track" role="meter" aria-label="Real power as a share of apparent power" aria-valuenow={Math.round(n.pf * 100)} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${n.pf * 100}%` }} /></div><p>{formatNumber(result.value)} kW real / {formatNumber(apparent)} kVA apparent · PF {n.pf}. Waveforms show phase spacing only.</p></figure>;
  }
  const isOhm = mode === 'ohm';
  return <figure className="formula-visual"><figcaption>{isOhm ? 'A simple DC circuit' : 'Electrical power at the load'}</figcaption><svg viewBox="0 0 520 250" role="img" aria-label={`${n.voltage} volt source supplies ${n.current} amperes to a ${isOhm ? `${formatNumber(n.resistance)} ohm resistor` : 'load'}.`}><path d="M95 113V60H390V92M390 144V200H95V138" className="diagram-wire" /><path d="M64 113H126M76 138H114" className="diagram-source" /><text x="60" y="105">+</text><text x="62" y="165">−</text><rect x="368" y="92" width="44" height="52" rx="3" className="diagram-load" /><path d="M235 60H272L260 51M272 60L260 69" className="diagram-flow" /><text x="250" y="39" textAnchor="middle">I = {formatNumber(n.current)} A →</text><text x="130" y="132">{formatNumber(n.voltage)} V</text><text x="360" y="172" textAnchor="middle">{isOhm ? `R = ${formatNumber(n.resistance)} Ω` : `P = ${formatNumber(result.value)} W`}</text></svg><p>{isOhm ? 'Raise voltage at fixed resistance: current rises.' : 'Each watt is one joule of energy transferred per second.'}</p></figure>;
}
