import { G, L, M } from './builders';

export const module11 = M(
  11,
  'Residential First-Fix, Accessories and Client Specification',
  'Turn a room layout into coordinated masonry first-fix work, then select and explain the socket-outlets, isolators and accessories a modern client may need.',
  'PRODUCE a marked-up room and kitchen accessory schedule showing box positions, circuit purpose, accessory type, load, isolation, IP or impact rating, mounting depth and the checks required before handover.',
  'Complete the existing safety, cable-routing, circuit-protection and testing modules before using these lessons for supervised practical work.',
  'The videos demonstrate UK trade practice. Apply the methods in Kenya only after checking current Kenyan law, EPRA and Kenya Power requirements, applicable KS/IEC standards, project specifications, product instructions and competent inspection and testing.',
  [
    L(
      'p11-l01',
      'Chasing Masonry Walls and Installing Flush Boxes',
      '0D_EGvEqElE',
      'Champions of the Trade',
      792,
      'Masonry chasing, set-out and flush boxes',
      'FIRST-FIX PRACTICE',
      'UK educator',
      G(
        'A practical wall-chasing sequence shows how careful set-out, controlled cutting and accurate back-box alignment create a clean first fix. Translate the method to Kenyan stone, fired-brick and block walls without assuming that every wall may safely be chased.',
        [
          'Establish a level datum and mark recognised cable routes before cutting.',
          'Choose box depth for the accessory, conductor space and final plaster or tile finish.',
          'Scan for hidden services and control silica dust with extraction, PPE and an exclusion area.',
          'Keep chases straight and shallow enough to protect the wall, lintels and structural elements.',
        ],
        'A neat chase is not automatically a safe chase: never cut structural concrete, columns, beams or lintels without authorised structural guidance.',
        'On a sample room drawing, mark switch and socket positions, vertical routes, box depths and the finished-surface allowance before preparing a supervised practice panel.',
        'What four checks must be complete before the wall chaser or SDS tool touches the masonry?',
      ),
      {
        regulationStatus: 'Verify wall construction, permitted chase depth, concealed-wiring zones, dust controls and project approval before cutting; UK chase guidance is context rather than Kenyan legal authority.',
      },
    ),
    L(
      'p11-v2-l02',
      'Recognising Common Switches, Sockets and Consumer Units',
      'JhD5nOq21bo',
      'GSH Electrical',
      834,
      'Accessory identification and functional selection',
      'IDENTIFY + SPECIFY',
      'UK educator',
      G(
        'This visual survey distinguishes common BS-style switches, socket-outlets and distribution accessories by what they do, not merely by appearance. It builds the vocabulary needed to discuss options clearly with a client and to read a schedule correctly.',
        [
          'Distinguish one-way, two-way and intermediate switching by intended control points and terminals.',
          'Separate socket-outlets, connection units, isolators and consumer units by function and rating.',
          'Read terminal markings, pole arrangement and manufacturer data before making any connection.',
          'Select an accessory from circuit duty, load, environment, user needs and available box depth.',
        ],
        'Similar-looking accessories are not interchangeable; the front plate is never a substitute for reading ratings, terminal markings and instructions.',
        'Create a client-facing accessory board or photo schedule naming each item, where it would be used and one reason it may be unsuitable elsewhere.',
        'How would you explain the difference between two-way switching, an isolator and a fused connection unit without referring only to their appearance?',
      ),
      {
        regulationStatus: 'Confirm Kenyan market approval, voltage and current ratings, earthing provision, box compatibility and the applicable product standard before specification.',
      },
    ),
    L(
      'p11-v2-l03',
      'Changing Socket-Outlets: Five Mistakes to Avoid',
      '8wSYX2wtADM',
      'Artisan Electrics',
      704,
      'Safe socket replacement and workmanship',
      'AVOID + VERIFY',
      'UK educator',
      G(
        'A fault-focused socket replacement demonstrates how apparently small workmanship errors can create loose connections, damaged conductors or lost earthing. Treat it as a quality-control lesson, not permission to work live or bypass testing.',
        [
          'Safely isolate, lock off and prove dead with an approved method before disturbing conductors.',
          'Record conductor identity and inspect insulation, copper condition and circuit arrangement.',
          'Terminate to the correct length and torque without trapping insulation or leaving exposed copper.',
          'Restore box earthing, mechanical security and the inspection and tests appropriate to the work.',
        ],
        'A socket that powers a load can still be dangerous; energisation is not proof of polarity, earth continuity, terminal tightness or protective-device operation.',
        'Build a replacement checklist covering isolation, photographs, conductor inspection, terminal preparation, torque, faceplate fit and post-work verification.',
        'Which defects could remain hidden even when a newly replaced socket appears to work normally?',
      ),
      {
        regulationStatus: 'Socket replacement must follow Kenyan competence, isolation, inspection, testing and certification requirements; UK conductor colours and ring-circuit assumptions may not describe the local circuit.',
      },
    ),
    L(
      'p11-v2-l04',
      'Switched Fused Connection Units: Terminals and Uses',
      'weQVIwEpYww',
      'GSH Electrical',
      402,
      'Fused connection units and fixed-appliance supplies',
      'CONNECT + EXPLAIN',
      'UK educator',
      G(
        'Three fused connection unit layouts make supply, load, earth and flex-outlet arrangements visible. The lesson supports safer specification of local control for fixed appliances while showing why terminal layout must be checked on the actual product.',
        [
          'Separate incoming supply terminals from outgoing load or flex terminals.',
          'Understand how the replaceable fuse can protect a smaller appliance flex when correctly selected.',
          'Distinguish switching, isolation and overcurrent protection instead of treating them as one function.',
          'Allow for heat, conductor space, strain relief, labelling and future maintenance access.',
        ],
        'Never copy a terminal position from another brand: use the markings and diagram supplied with the exact connection unit.',
        'For a water heater, hood or pump control, draw the upstream circuit, local connection unit, flex and load, then label what each protective or control element does.',
        'Why can the fuse in a connection unit protect the appliance flex without replacing the protective device for the fixed circuit?',
      ),
      {
        regulationStatus: 'Use only where the accessory rating, fuse system and product standard are accepted for the Kenyan installation; verify isolation duties and appliance instructions.',
      },
    ),
    L(
      'p11-v2-l05',
      'USB Charging Sockets: Load, Depth and Upgrade Planning',
      'A31cs1ukm_k',
      'eFIXX',
      326,
      'Integrated USB socket selection',
      'SELECT + FUTURE-PROOF',
      'UK manufacturer or trade specialist',
      G(
        'A trade product demonstration introduces integrated USB charging outlets as an accessory option. Use it to ask better specification questions about charging power, back-box space, heat, replacement and client expectations rather than treating one model as a universal recommendation.',
        [
          'Compare total USB output, port type and power-sharing behaviour with the client devices.',
          'Check back-box depth, conductor bending space and thermal clearance before promising a retrofit.',
          'Confirm the mains socket rating, earthing and protective arrangement remain suitable.',
          'Plan for electronic-component ageing, standby consumption and straightforward future replacement.',
        ],
        'USB labels such as fast or high power are incomplete specifications; verify the supported charging protocol and shared maximum output.',
        'Add optional USB outlets to a bedroom or home-office schedule and record device demand, mounting depth, expected replacement path and a standard-socket alternative.',
        'What information must you collect before recommending an integrated USB outlet to a client?',
      ),
      {
        regulationStatus: 'This is a UK trade/product example, not a Kenyan approval. Verify local product certification, supply rating, back-box compatibility and manufacturer installation limits.',
      },
    ),
    L(
      'p11-v2-l06',
      'Planning Kitchen Socket and Cooker-Point Positions',
      'bOSMYzXY_Uk',
      'LEARN ELECTRICS',
      789,
      'Kitchen accessory layout and service coordination',
      'PLAN + COORDINATE',
      'UK educator',
      G(
        'The kitchen layout discussion links socket and cooker-point positions to cabinets, worktops and appliance access. Its durable value is coordination: electrical points must be agreed before masonry, plumbing, joinery, tiling and finishes remove safe or usable locations.',
        [
          'Place general-use outlets where appliance leads can reach without crossing heat or wet work areas.',
          'Keep appliance isolation accessible rather than hidden behind equipment that cannot be moved safely.',
          'Coordinate cooker controls, connection points and cable routes with the final appliance data.',
          'Record finished levels, cabinet dimensions, sinks, hobs, splashbacks and service conflicts before first fix.',
        ],
        'The video includes UK and Welsh layout context; use its coordination method, not its regional dimensions as automatic Kenyan rules.',
        'Overlay the electrical schedule on an actual kitchen elevation and resolve every outlet, isolator and cooker point with the cabinetmaker and plumber before chasing.',
        'Which kitchen dimensions and appliance details must be frozen before the electrician can set out boxes confidently?',
      ),
      {
        regulationStatus: 'Verify Kenyan building, wet-area, accessibility and appliance requirements; project drawings and manufacturer clearances govern the final positions.',
      },
    ),
    L(
      'p11-v2-l07',
      'Cooker-Circuit Diversity and Realistic Load Assessment',
      'QQduU8RkjD8',
      'John Ward',
      1348,
      'Cooking appliance demand and circuit design',
      'CALCULATE + CHALLENGE',
      'UK educator',
      G(
        'A worked 15 kW cooker example explains why connected load and expected maximum demand are different quantities. It also shows why diversity is a design judgement that must be combined with cable, protection, installation method and appliance information.',
        [
          'Convert nameplate power into current using the correct supply voltage and phase arrangement.',
          'Apply only a diversity method accepted for the installation type and document the assumption.',
          'Check cable capacity, voltage drop, fault protection, terminal ratings and installation conditions separately.',
          'Allow for future cooking equipment and challenge unrealistic simultaneous-load assumptions with the client.',
        ],
        'Diversity does not reduce the appliance rating or excuse an undersized connection; it estimates design demand under a stated usage model.',
        'Prepare two cooker-circuit proposals for a client: current equipment and a future induction upgrade, with every diversity and installation assumption shown.',
        'Why can a high connected cooking load sometimes use a lower design current, and what checks must still remain unchanged?',
      ),
      {
        regulationStatus: 'The worked diversity rule is UK guidance. Use a demand method accepted by the Kenyan designer, utility and applicable standard, and verify it against actual appliance data.',
      },
    ),
    L(
      'p11-v2-l08',
      'Electric-Shower Isolation: When and How to Specify It',
      'R1sDSQJjmsE',
      'eFIXX',
      345,
      'High-load bathroom appliance isolation',
      'DECIDE + ISOLATE',
      'UK manufacturer or trade specialist',
      G(
        'The shower-isolator discussion separates habit from a reasoned design decision. It prompts the learner to examine appliance instructions, switching duties, bathroom location, current rating and maintenance needs before specifying an isolator.',
        [
          'Identify the required means of isolation from the equipment instructions and applicable rules.',
          'Select poles, current rating and duty for the actual shower circuit rather than the nominal label alone.',
          'Position the control outside restricted wet zones and make its state clear to the user.',
          'Coordinate cable size, terminals, enclosure temperature, protective devices and post-installation tests.',
        ],
        'An isolator is not overload or shock protection, and a large printed current rating does not guarantee suitable terminals or installation conditions.',
        'For a proposed instant shower, build a one-line diagram and location sketch showing the local control, circuit protection, cable route, earthing and access for service.',
        'What evidence would justify adding, omitting or relocating a shower isolator on a real project?',
      ),
      {
        regulationStatus: 'UK bathroom and isolation conclusions do not transfer automatically. Verify Kenyan wet-area rules, supply capacity, manufacturer instructions and competent design for the selected shower.',
      },
    ),
    L(
      'p11-v2-l09',
      'Bathroom Shaver Sockets and Isolation Transformers',
      'hyaaPt6UuEU',
      'John Ward',
      907,
      'Isolated shaver supplies in bathrooms',
      'UNDERSTAND + LOCATE',
      'UK educator',
      G(
        'A detailed look inside UK shaver outlets explains why their isolating transformer and limited output make them different from ordinary socket-outlets. The lesson supports informed bathroom specification while exposing strict load and location limitations.',
        [
          'Understand how the internal isolating transformer separates the output from the normal mains supply.',
          'Read voltage options, output limits and continuous-use restrictions on the exact product.',
          'Choose a location that respects wet zones, splashing, access and the user appliance lead.',
          'Provide the correct supply, earthing where required, enclosure depth and verification.',
        ],
        'A shaver outlet is a limited isolated supply, not a convenient general-purpose bathroom socket for hair dryers, heaters or other high-power loads.',
        'Compare a proposed shaver outlet with a standard socket and USB charger, then document which bathroom uses each can and cannot serve.',
        'What electrical feature makes a shaver outlet suitable for its narrow purpose, and why does that not make every connected appliance acceptable?',
      ),
      {
        regulationStatus: 'Confirm that the selected isolated outlet and its location comply with Kenyan wet-area requirements and the applicable product standard; UK bathroom zones are reference context only.',
      },
    ),
    L(
      'p11-v2-l10',
      'Weatherproof Outdoor Sockets: Selection and Installation',
      'QOLsQtHZbYk',
      'eFIXX',
      464,
      'Outdoor socket-outlets and environmental protection',
      'WEATHERPROOF + TEST',
      'UK manufacturer or trade specialist',
      G(
        'An outdoor socket installation demonstrates that an IP label is only one part of weather resistance. Correct entries, seals, drainage, mounting and circuit protection must preserve the enclosure performance throughout Kenyan rain, dust, heat and ultraviolet exposure.',
        [
          'Select IP, impact and ultraviolet resistance for the actual exposed location and likely use.',
          'Use suitable glands, seals, cable entries and mounting surfaces without creating water paths.',
          'Provide earthing, residual-current protection and mechanical cable protection appropriate to the circuit.',
          'Inspect the lid, gasket, terminals and enclosure periodically because weathering degrades protection.',
        ],
        'The advertised IP rating applies only when the enclosure is installed, closed and maintained exactly as tested by the manufacturer.',
        'Survey one compound location and specify socket position, enclosure rating, cable route, gland direction, protective devices and an inspection interval.',
        'Which installation details can defeat a high IP rating even when the enclosure itself is genuine?',
      ),
      {
        regulationStatus: 'Verify Kenyan outdoor-supply, RCD, earthing and equipment-approval requirements plus the manufacturer IP conditions; do not infer local compliance from a UK product demonstration.',
      },
    ),
    L(
      'p11-v2-l11',
      'Industrial Plugs and Sockets: IP, IK and Duty Selection',
      'PNWdC47daYM',
      'eFIXX',
      346,
      'Heavy-duty industrial connection systems',
      'SELECT + PROTECT',
      'UK manufacturer or trade specialist',
      G(
        'A heavy-duty product example introduces robust industrial plugs and socket-outlets for harsh service. Use the construction details to build a general selection method based on voltage, current, poles, environment, impact and safe disconnection.',
        [
          'Match voltage, frequency, current, pole arrangement and keying to the connected equipment.',
          'Select IP and IK performance for water, dust, cleaning, impact and corrosive exposure.',
          'Consider interlocking or switch-disconnection so contacts are not made or broken unsafely under load.',
          'Coordinate cable type, glands, strain relief, protective devices, earthing and maintenance access.',
        ],
        'Industrial appearance does not prove compatibility: colour, key position, pins, rating and product standard must all agree with the supply and load.',
        'Specify a connection for a workshop machine or outdoor pump and justify every electrical, mechanical and environmental rating in a client schedule.',
        'What must match before an industrial plug and socket can be considered electrically and mechanically compatible?',
      ),
      {
        regulationStatus: 'The featured product is a UK trade example. Verify the applicable IEC/KS product standard, Kenyan approval, short-circuit duty, earthing and isolation requirements for the actual installation.',
      },
    ),
  ],
);
