import { G, L, M } from './builders';

const kenyaLightingStatus =
  'Use the UK lesson for design principles, product literacy and workmanship. For Kenyan work, verify the current Kenyan Building Code, applicable KS/IEC standards, EPRA requirements, fire-authority and project requirements, and manufacturer instructions; a cited UK rule is not automatically Kenyan law.';

export const module12 = M(
  12,
  'Lighting Specification, Fittings and Controls',
  'Move from simply wiring a light to specifying a complete lighting result. The sequence covers lamp and fitting selection, human-centred design, gypsum and fire-rated ceiling coordination, LED strips and drivers, dimming, outdoor and industrial lighting, sensors, DALI, smart controls and emergency lighting. UK teaching is translated into practical decisions for Kenyan masonry, stone and brick homes with gypsum ceilings, strong daylight, dust, rain, voltage variation and backup-power systems.',
  'Prepare a room-by-room lighting schedule for a Kenyan masonry-and-gypsum home. For every space, justify the visual task, fitting type, lumen target, colour quality, beam or distribution, glare control, IP/IK needs, mounting and maintenance access, driver location, switching or control method, and coordination with ceiling services. Identify every point where Kenyan requirements or manufacturer evidence must be checked.',
  'Complete the core lighting-circuit, protective-device, safe-isolation and testing lessons before specifying fittings or controls.',
  kenyaLightingStatus,
  [
    L(
      'p12-v2-l01',
      'Lamp Technologies, Caps and Practical LED Selection',
      'AF4RsoveL1Y',
      'GSH Electrical',
      625,
      'Lamp technologies and cap identification',
      'FOUNDATION',
      'UK educator',
      G(
        'The lesson compares incandescent, halogen, compact-fluorescent and LED light sources, then identifies common bayonet and Edison-screw cap arrangements. Use those comparisons to separate heat, energy use, expected life and light quality from the physical cap that connects a lamp to its holder. On Kenyan projects, also confirm the actual supply rating, lamp-holder temperature rating, locally available replacement type and the quality of imported LED electronics before promising a client long service life.',
        [
          'Lamp technology changes efficiency, heat output and service life.',
          'The lamp cap must mechanically and electrically match the holder.',
          'Brightness and appearance cannot be selected from watts alone.',
          'Replacement availability and product quality affect maintainability.',
        ],
        'A lamp that fits physically is not automatically electrically suitable or visually appropriate.',
        'Audit the lamps in one home: record technology, cap, wattage, lumen output, colour temperature and any mismatched replacements.',
        'Could you recommend a replacement lamp without relying on the old lamp wattage alone?',
      ),
    ),
    L(
      'p12-v2-l02',
      'Lighting Design: From Visual Task to Specification',
      'qWoWcA_3zfU',
      'eFIXX',
      1434,
      'Lighting-design fundamentals',
      'DESIGN FOUNDATION',
      'UK educator',
      G(
        'Lighting design starts with people, activities and surfaces rather than a symmetrical pattern of ceiling points. The lesson introduces the linked choices behind useful illumination: quantity of light, distribution, colour, glare, contrast, fitting position and control. Apply the method to Kenyan rooms by accounting for strong daytime light, dark stone or timber finishes, reflective tiles, gypsum details, ceiling fans and the locations of HVAC, sprinklers and detectors.',
        [
          'Define the visual task before choosing a fitting.',
          'Light distribution and surface reflectance shape the result.',
          'Glare, shadows and contrast matter as much as brightness.',
          'Controls and ceiling coordination belong in the first design conversation.',
        ],
        'A neat ceiling grid is not evidence of a good lighting design.',
        'Choose one kitchen or sitting room and mark its ambient, task, accent and decorative needs before drawing any light points.',
        'Can you explain what job every proposed fitting performs and who benefits from it?',
      ),
    ),
    L(
      'p12-v2-l03',
      'Thirty Rules of Lighting — Part 1: Observe Before You Specify',
      'IzqbaE_KJXU',
      'eFIXX',
      671,
      'Professional lighting rules of thumb',
      'CLIENT DESIGN',
      'UK educator',
      G(
        'The first part of Ray Molony\'s series turns professional lighting experience into questions an electrician can use during a client survey. Treat each rule as a design prompt rather than a fixed recipe: observe the task, daylight, surfaces, sightlines and desired atmosphere, then decide where light should come from. In a Kenyan home, survey both daytime and night-time use because deep verandas, small openings, dark finishes and load-shedding can change the brief.',
        [
          'Survey how the space is used before discussing products.',
          'Daylight and electric light must be considered together.',
          'Light surfaces and objects, not empty floor plans.',
          'Rules of thumb guide judgment but do not replace calculation.',
        ],
        'Begin with the client\'s activity and experience, not the catalogue.',
        'Write five survey questions for a client planning a new lounge, kitchen or shop lighting layout.',
        'What information must you collect before quoting the number and type of fittings?',
      ),
    ),
    L(
      'p12-v2-l04',
      'Thirty Rules of Lighting — Part 2: Shape, Contrast and Fitting Choice',
      'lJPnpzv0UMc',
      'eFIXX',
      652,
      'Applying lighting rules to fitting selection',
      'CLIENT DESIGN',
      'UK educator',
      G(
        'Part two continues the rule-based review and helps turn a broad brief into fitting and placement decisions. Use it to compare general illumination with light aimed at worktops, walls, artwork, circulation routes or architectural features, and to judge whether contrast is intentional or accidental. For gypsum ceilings and stone or brick walls, coordinate recess depth, surface texture, grazing effects, access panels and the shadow lines created by coves and bulkheads before first-fix.',
        [
          'Different visual jobs need different distributions of light.',
          'Contrast should be designed rather than left to chance.',
          'Beam direction and mounting position change surface appearance.',
          'Architectural details must be coordinated before conduit and boxes are fixed.',
        ],
        'Choose a fitting for the light it delivers, not merely for how it looks when switched off.',
        'Sketch two schemes for one feature wall: uniform wall lighting and a more dramatic accent treatment.',
        'How would a textured stone wall change your choice of beam angle and fitting position?',
      ),
    ),
    L(
      'p12-v2-l05',
      'Thirty Rules of Lighting — Part 3: Controls, Maintenance and Review',
      'ndbEo2YpRN8',
      'eFIXX',
      860,
      'Completing and reviewing a lighting proposal',
      'CLIENT DESIGN',
      'UK educator',
      G(
        'The final part completes the professional checklist and is best used as a review before a scheme is priced or installed. Check that control groups make sense to the user, fittings and drivers remain maintainable, the scheme can adapt to different activities, and the visual result has not been sacrificed to ceiling symmetry. Add Kenyan realities to the review: locally serviceable parts, surge exposure, generator or inverter operation, cleaning access and a clear manual override for smart controls.',
        [
          'Group controls around activities and understandable scenes.',
          'Drivers, lamps and fittings require realistic maintenance access.',
          'A design should work in normal and backup-power conditions.',
          'Review the whole room before releasing the first-fix drawing.',
        ],
        'A premium system that the client cannot understand or maintain is not a successful design.',
        'Review a proposed lighting plan and mark confusing switch groups, inaccessible components and circuits that should or should not be on backup power.',
        'Can another electrician maintain your design from the drawings and labels you intend to hand over?',
      ),
    ),
    L(
      'p12-v2-l06',
      'SLL Lighting Handbook: Professional Design Framework',
      'qZnvS3bcnA0',
      'CIBSE',
      2991,
      'Professional lighting-design reference framework',
      'ADVANCED DESIGN',
      'UK professional body',
      G(
        'CIBSE presents the Society of Light and Lighting handbook as a structured professional reference covering both the measurable and human sides of lighting. Use the webinar to understand how illuminance, uniformity, glare, colour, daylight, controls, energy, maintenance and application guidance fit into one design process. The handbook is a UK reference, so its figures are valuable study material but must be checked against the Kenyan project brief, applicable local standards and the authority having jurisdiction.',
        [
          'Professional design combines quantitative and qualitative criteria.',
          'Application guidance depends on the task and occupants.',
          'Maintenance and controls influence delivered performance over time.',
          'Reference values must be verified for the project jurisdiction.',
        ],
        'Use a handbook to justify decisions, not to copy a number without its context and assumptions.',
        'Create a one-page specification template with fields for illuminance, uniformity, glare, colour, controls, maintenance and verification source.',
        'Which parts of a UK lighting recommendation transfer as principles, and which require Kenyan verification?',
      ),
    ),
    L(
      'p12-v2-l07',
      'Selecting LED Downlights Without Expensive Mistakes',
      'X1WXYt-rStM',
      'eFIXX',
      1228,
      'LED downlight specification',
      'FITTING SELECTION',
      'UK educator',
      G(
        'This lesson evaluates the decisions hidden behind a simple downlight: light output and beam, glare, colour, dimming, cut-out, connector, driver, insulation contact and evidence for the ceiling application. For Kenyan gypsum work, agree the fitting and access strategy before the ceiling is closed; leave the required clearance, support cables independently, keep drivers retrievable and coordinate with brandering, HVAC and fire or acoustic barriers. A fire-rated product claim must be matched to the actual tested ceiling construction rather than treated as a universal label.',
        [
          'Beam, lumen output and glare determine visual performance.',
          'Cut-out, recess depth and insulation conditions determine physical suitability.',
          'Driver and dimmer compatibility determine electrical performance.',
          'Ceiling-system evidence must match the construction being used.',
        ],
        'Do not let the gypsum installer cut holes until the fitting schedule and setting-out drawing are approved.',
        'Compare three downlight data sheets and reject any option lacking the evidence needed for its proposed ceiling and control method.',
        'What must you know about both the room and the ceiling before ordering a downlight?',
      ),
    ),
    L(
      'p12-v2-l08',
      'LED Downlights in Fire-Rated Ceiling Assemblies',
      'tcvFPnYUHcU',
      'eFIXX',
      737,
      'Fire performance of recessed lighting',
      'FITTING SELECTION',
      'UK educator',
      G(
        'Recessing a luminaire can interrupt a ceiling that is intended to resist fire, so product testing and the complete ceiling build-up matter. The lesson explains why a fire-rated downlight is part of an assembly decision involving board type, layers, joists, insulation and test evidence. Many Kenyan gypsum ceilings are decorative rather than certified fire-resisting constructions; first establish the required performance, then obtain evidence applicable to the actual system instead of borrowing a UK installation detail blindly.',
        [
          'A downlight opening can compromise a fire-separating ceiling.',
          'Fire performance belongs to the tested assembly, not the fitting alone.',
          'Board, structure, insulation and installation detail all matter.',
          'Decorative gypsum and certified fire-rated ceilings are not equivalent.',
        ],
        'The words “fire rated” on a box do not prove suitability for every ceiling.',
        'Ask the architect or gypsum contractor for the ceiling build-up, required rating and penetration detail before approving a recessed fitting.',
        'What evidence links the proposed downlight to the exact ceiling construction on site?',
      ),
    ),
    L(
      'p12-v2-l09',
      'Choosing the Right LED Strip System',
      '4z35ku0BWy8',
      'eFIXX',
      430,
      'LED strip specification',
      'FITTING SELECTION',
      'UK educator',
      G(
        'LED tape must be specified as a system rather than as a decorative roll. Match voltage, watts per metre, lumen output, colour temperature, colour quality, LED density, ingress protection, dimming method, profile and driver to the required effect and installed length. In Kenyan gypsum coves, kitchens and joinery, document feed points and accessible driver locations before closing finishes, and allow for heat, dust, cleaning and the voltage drop of long concealed runs.',
        [
          'Voltage and watts per metre determine driver and cable requirements.',
          'LED density and profile affect dotting, diffusion and heat removal.',
          'Colour quality and output must suit the visual task.',
          'Long runs require planned feeds and voltage-drop control.',
        ],
        'The strip, cable, connections, profile, diffuser, driver and control are one lighting system.',
        'Specify a five-metre gypsum-cove run with strip data, driver headroom, profile, feed arrangement and an accessible maintenance point.',
        'How would you prevent a long strip from being bright near the driver and dim at the far end?',
      ),
    ),
    L(
      'p12-v2-l10',
      'LED Strip Heat, Profiles and Service Life',
      'Yps6hlw3j8s',
      'eFIXX',
      704,
      'Thermal management for LED strip',
      'FITTING SELECTION',
      'UK educator',
      G(
        'Even efficient LEDs convert part of their input power into heat, and excessive junction temperature shortens life and shifts performance. The lesson shows why an aluminium profile is more than a decorative channel: it spreads heat, protects the tape and supports a diffuser for a cleaner result. In gypsum coves or timber joinery, do not stick tape directly to dusty, insulating or inaccessible surfaces; prepare the substrate, provide ventilation where required and leave the strip, joints and driver serviceable.',
        [
          'LED efficiency does not eliminate heat.',
          'Thermal management strongly affects output and life.',
          'Profiles improve heat spreading, protection and optical finish.',
          'Mounting surfaces and access must be designed before installation.',
        ],
        'A strip that lights during handover may still fail early if its heat has nowhere to go.',
        'Inspect a proposed cove detail and mark the metal profile, airflow, cable entry, removable diffuser and driver-access route.',
        'Which installation details would make an LED strip run both cooler and easier to repair?',
      ),
    ),
    L(
      'p12-v2-l11',
      'Reading LED Driver Symbols and Ratings',
      '3UesLmjG2VQ',
      'eFIXX',
      542,
      'LED driver data and markings',
      'DRIVER SELECTION',
      'UK educator',
      G(
        'Driver markings communicate the electrical and environmental limits that protect both the LED load and the installation. Learn to distinguish constant-voltage from constant-current output and to read power, input, output, temperature, insulation, SELV, ingress and dimming information before connecting a product. For Kenyan projects, also check supply tolerance, surge strategy, generator or inverter compatibility, ambient temperature and whether the selected replacement will remain obtainable.',
        [
          'Constant-voltage and constant-current drivers are not interchangeable.',
          'Input, output and maximum power must all suit the load.',
          'Temperature and enclosure markings constrain driver location.',
          'Dimming, surge and backup-supply compatibility require evidence.',
        ],
        'Never identify an LED driver from its connector shape or nominal wattage alone.',
        'Photograph one installed driver label and translate every symbol and rating into a plain-language installation constraint.',
        'Could you prove that a proposed driver matches the LED load, environment and control system?',
      ),
    ),
    L(
      'p12-v2-l12',
      'A Practical Guide to Reliable LED Dimming',
      'tRGfppBahgY',
      'eFIXX',
      599,
      'LED dimmer compatibility',
      'CONTROLS',
      'UK educator',
      G(
        'Reliable dimming depends on the combined behaviour of the control, driver or lamp, connected load and wiring. The lesson explains why LED loads can flicker, buzz, jump, refuse to start or have a poor low end when a dimmer is selected by current rating alone. Build compatibility from manufacturer data and testing, and re-check behaviour on the generator, UPS or inverter supply that may operate a Kenyan home during an outage.',
        [
          'The lamp or driver and dimmer must be tested as a combination.',
          'Minimum load and control method affect the dimming range.',
          'Flicker and buzzing are system symptoms, not one-component diagnoses.',
          'Backup-supply waveforms can change otherwise acceptable behaviour.',
        ],
        '“Dimmable” on two separate products does not guarantee that they work well together.',
        'Create a commissioning sheet that records product codes, connected load, low-end setting, flicker, noise and operation on every available supply source.',
        'What evidence would let you approve a dimmer-and-lamp combination before installing twenty of them?',
      ),
    ),
    L(
      'p12-v2-l13',
      'Low-Level LED Dimming, Flicker and Fault Diagnosis',
      'ii_dyfigDtA',
      'eFIXX',
      999,
      'Advanced LED dimming behaviour',
      'DIAGNOSE',
      'UK educator',
      G(
        'This deeper lesson examines what happens inside common dimming arrangements and why LED lamps may behave badly as the requested output approaches the lower limit. Use it to separate control-type, minimum-load, driver, lamp, supply and connection problems instead of replacing components at random. Phone-camera banding can reveal modulation, but a professional conclusion still needs product data, repeatable tests and suitable measuring equipment.',
        [
          'Low-end dimming exposes driver and control limitations.',
          'Leading-edge and trailing-edge controls present different loads.',
          'Mixed lamp types and small loads can destabilise operation.',
          'Diagnosis should isolate control, load, supply and connection variables.',
        ],
        'Treat flicker as evidence to investigate, not as permission to guess which component is faulty.',
        'Write a safe fault tree for a dimmed circuit that flickers only at low output and behaves differently on inverter power.',
        'Which controlled substitution would distinguish a dimmer problem from a driver or supply problem?',
      ),
    ),
    L(
      'p12-v2-l14',
      'IP and IK Ratings for Dust, Water and Impact',
      'bvUZ2L7eHSE',
      'eFIXX',
      1336,
      'Ingress and impact protection',
      'FITTING SELECTION',
      'UK educator',
      G(
        'IP and IK codes describe different kinds of protection: ingress of solids and water versus mechanical impact. The lesson explains how to read the digits and why the completed installation, including glands, seals, orientation and opening method, must preserve the claimed performance. Kenyan outdoor fittings may face wind-blown dust, insects, intense rain, irrigation, cleaning jets, sunlight and casual impact, so choose from the real exposure rather than using “waterproof” as a vague sales term.',
        [
          'IP addresses solid and water ingress; IK addresses impact.',
          'Each IP digit has a separate meaning.',
          'Installation details can invalidate an enclosure rating.',
          'Location risk determines the required protection level.',
        ],
        'A high printed rating is useless if the cable entry, seal or mounting orientation defeats it.',
        'Survey an exterior wall, gate and garden and assign the dust, rain, jet, impact, UV and maintenance risks at each proposed fitting position.',
        'Why might two fittings on the same compound require different IP or IK performance?',
      ),
    ),
    L(
      'p12-v2-l15',
      'Garden Lighting: Six Design Ideas That Deliver',
      '9oeEzecYINA',
      'eFIXX',
      464,
      'Outdoor lighting concepts',
      'OUTDOOR DESIGN',
      'UK educator',
      G(
        'The lesson demonstrates how several outdoor-lighting approaches create different effects instead of flooding a whole garden with one harsh source. Translate the ideas into layers for paths, steps, planting, walls, entrances, work areas and security while controlling glare into bedrooms and neighbouring property. For Kenyan compounds, coordinate lighting with gates, electric-fence zones, CCTV, drainage, irrigation and future landscaping, and keep buried joints and drivers accessible and appropriately protected.',
        [
          'Outdoor lighting works best as purposeful layers.',
          'Beam direction controls drama, visibility and glare.',
          'Security lighting should support cameras without blinding users.',
          'Cable routes, drainage and maintenance shape the design.',
        ],
        'More outdoor lumens can produce less useful visibility when glare destroys contrast.',
        'Draw a compound plan and assign separate purposes to entrance, path, steps, planting, wall texture and CCTV-support lighting.',
        'Can you explain how each exterior fitting improves safety, orientation, security or atmosphere?',
      ),
    ),
    L(
      'p12-v2-l16',
      'Garden Lighting Case Study: From Brief to Installation',
      '7fr4SlMjmxQ',
      'Artisan Electrics',
      1759,
      'Premium garden-lighting installation',
      'CASE STUDY',
      'UK educator',
      G(
        'This extended site case study shows the coordination and workmanship behind a high-end garden-lighting result. Observe how a visual concept becomes fitting positions, cable routes, connections, controls, testing and a finished client experience, while distinguishing transferable method from project-specific products. On a Kenyan compound, adapt the workflow for masonry walls, garden trenches, heavy rain, termites or soil disturbance, gate services, electric-fence separation and the availability of replacement fittings.',
        [
          'A site survey connects the visual brief to buildable routes.',
          'Outdoor joints and supports require durable workmanship.',
          'Controls should support daily use, security and maintenance.',
          'Commissioning includes the night-time visual result.',
        ],
        'Outdoor lighting should be inspected after dark; daylight completion alone cannot prove the design.',
        'Create a method statement for one Kenyan garden zone covering route, protection, drainage, joints, control, testing and night-time aiming.',
        'Which details in the case study transfer directly, and which must change for local construction and environment?',
      ),
    ),
    L(
      'p12-v2-l17',
      'High-Bay, Emergency and Control Integration',
      'tWnxI5yq4tg',
      'eFIXX',
      649,
      'Industrial high-bay lighting',
      'COMMERCIAL FITTINGS',
      'UK educator',
      G(
        'A warehouse fitting is a package of optical distribution, mounting, output, control and emergency options rather than simply a powerful lamp. The lesson uses a high-bay product to expose questions about mounting height, aisle or open-area distribution, sensors, emergency provision, installation speed and maintenance access. Apply the questions to Kenyan warehouses and workshops while verifying local emergency, occupational-safety and fire requirements and checking high ambient temperature, dust and supply quality.',
        [
          'Mounting height and distribution determine useful floor-level light.',
          'High output still requires glare and uniformity control.',
          'Sensors and emergency functions must be coordinated with the fitting.',
          'Access, heat, dust and maintenance influence lifecycle cost.',
        ],
        'Selecting a high bay by wattage alone ignores the space, optics and operating conditions.',
        'Compare two high-bay data sheets for a workshop and justify distribution, output, controls, emergency option, IP rating and maintenance strategy.',
        'What site information must be measured before selecting an industrial luminaire?',
      ),
    ),
    L(
      'p12-v2-l18',
      'PIR Lighting Control with Manual Override',
      's0G2DnI6spA',
      'John Ward (jwflame)',
      1413,
      'Sensor control and override wiring',
      'CONTROLS',
      'UK educator',
      G(
        'The lesson develops a sensor-controlled lighting arrangement with an override facility and explains the function of permanent supply, switched output, neutral and manual control. Use the circuit logic to design predictable operation rather than copying conductor colours or a UK accessory layout. PIR control suits Kenyan entrances, stairs, corridors, washrooms and security areas, but the sensor position, load type, weather exposure, client expectation and safe override state must be agreed first.',
        [
          'A sensor needs the correct supply and switched-load connections.',
          'Override logic must be intentional and clearly documented.',
          'Sensor position controls coverage and nuisance operation.',
          'LED load and environmental ratings must suit the device.',
        ],
        'If nobody can explain the override state, the control is not ready for handover.',
        'Draw and label a sensor-plus-override circuit for an entrance, then write the expected behaviour in every switch and sensor condition.',
        'How will the client force the lights on, return them to automatic mode and identify the current state?',
      ),
    ),
    L(
      'p12-v2-l19',
      'A Beginner’s Guide to DALI Lighting Controls',
      'FGPkVOycyP8',
      'eFIXX',
      552,
      'DALI control fundamentals',
      'SMART CONTROLS',
      'UK educator',
      G(
        'DALI allows compatible lighting devices to receive digital commands, be addressed and arranged into groups and scenes without reproducing every control relationship in mains switch wiring. The lesson introduces the bus, control gear and commissioning concept so an electrician can understand the difference between supplying a fitting and controlling it. In Kenya, DALI is most useful where project scale, scene changes, monitoring or energy management justify the added design, programming, documentation and spare-parts burden.',
        [
          'DALI separates digital control relationships from mains power paths.',
          'Addressing enables flexible groups and scenes.',
          'Every luminaire or driver must be DALI compatible.',
          'Commissioning records are essential for future maintenance.',
        ],
        'A DALI cable and compatible driver do not create a working system until the devices are commissioned.',
        'Sketch a four-zone office or large home and show which fittings should be grouped, dimmed or recalled as scenes.',
        'What project benefit would justify DALI instead of conventional switching?',
      ),
    ),
    L(
      'p12-v2-l20',
      'DALI Wiring and Installation Strategy',
      'XmucYqxYEH4',
      'eFIXX',
      434,
      'DALI bus wiring',
      'SMART CONTROLS',
      'UK educator',
      G(
        'This follow-on lesson focuses on the physical DALI control bus and shows why its topology and function differ from a conventional switched-live circuit. Plan the bus, compatible cable, control power and device locations as an engineered system, then leave addressing and group information in the commissioning record. Cable rating, containment, segregation and identification must follow the applicable Kenyan installation requirements and the selected DALI equipment instructions rather than an assumed UK detail.',
        [
          'DALI power and DALI control are related but distinct functions.',
          'Bus topology offers flexibility within documented limits.',
          'Cable rating, identification and segregation require deliberate design.',
          'Addresses and groups belong in the as-built record.',
        ],
        'Do not improvise DALI wiring from an Ethernet or two-way-lighting mental model.',
        'Add a DALI bus, control devices, drivers and commissioning labels to the zoning sketch from the previous lesson.',
        'Could a future technician trace both the power circuit and the digital control path from your drawing?',
      ),
    ),
    L(
      'p12-v2-l21',
      'UK Smart Dimmer Case Study: Two-Way, Matter and No-Neutral Design',
      'nEpOpzAzgFs',
      'My Project Box',
      1336,
      'Retrofit smart dimming',
      'SMART CONTROLS',
      'UK educator',
      G(
        'This practical case study explores a smart-dimmer retrofit that must work with UK-style switch wiring, multi-way control, Matter integration and locations where no neutral is available at the switch. Those constraints closely resemble many Kenyan homes, but product suitability still depends on the exact load, conductor arrangement, box depth, wireless environment and supply. For new masonry work, provide neutrals, deep boxes and spare conduit where practical so future smart controls do not depend on compromises.',
        [
          'No-neutral controls power themselves through the connected load.',
          'Multi-way switching and smart control need a defined architecture.',
          'Load type and minimum load affect dimming performance.',
          'Deep boxes, neutrals and spare routes improve future flexibility.',
        ],
        'Design new switch points for future controls even if the first installation uses ordinary switches.',
        'Inspect a switch box and record neutral availability, depth, conductor arrangement, load type, wireless coverage and manual-override requirement.',
        'Would this smart dimmer remain safe and usable if the network, hub or internet connection failed?',
      ),
    ),
    L(
      'p12-v2-l22',
      'Lighting Controls: Choosing the Right Architecture',
      'n1j1lxGEnbk',
      'eFIXX',
      5112,
      'Lighting-control system design',
      'ADVANCED CONTROLS',
      'UK educator',
      G(
        'This extended discussion compares the purposes and trade-offs behind modern lighting controls rather than treating “smart” as a single product category. Use it to organise manual switching, dimming, occupancy and daylight sensors, scenes, scheduling, connected systems, commissioning and user interfaces around the building brief. For Kenyan projects, include offline operation, manual fallback, surge protection, backup-power behaviour, local technical support, cybersecurity and an exit plan if a cloud service or proprietary component disappears.',
        [
          'Control architecture begins with user and energy objectives.',
          'Sensors, scenes and schedules solve different problems.',
          'Commissioning and user training determine real-world performance.',
          'Resilience and supportability matter as much as features.',
        ],
        'The best control system is the simplest one that reliably delivers the required outcomes.',
        'Write a controls brief for a home, office or shop covering normal use, visitors, cleaning, outage operation, manual fallback and future maintenance.',
        'Which features still work when the internet, controller or preferred installer is unavailable?',
      ),
    ),
    L(
      'p12-v2-l23',
      'Principles of Good Emergency Lighting',
      'c8GpxY6ANSU',
      'Rexel UK with Eaton',
      3648,
      'Emergency-lighting design',
      'LIFE SAFETY',
      'UK manufacturer or trade specialist',
      G(
        'The webinar develops emergency lighting as a life-safety system that begins with risk, escape strategy and the loss of normal supply—not with placing a few battery fittings. It covers maintained and non-maintained operation, escape routes, open and high-risk areas, signs, duration, central or self-contained arrangements, commissioning and records. These UK design principles are valuable, but a Kenyan installation must follow the project fire strategy, current local legal and standards requirements, the approving authorities and the specified product evidence.',
        [
          'Emergency coverage follows risk and escape strategy.',
          'Maintained and non-maintained modes serve different needs.',
          'Duration and supply architecture are design decisions.',
          'Commissioning, records and maintenance complete the system.',
        ],
        'A glowing emergency fitting does not prove that people can escape safely during a power failure.',
        'Mark exits, route changes, stairs, fire points, open areas and high-risk tasks on a small public-building plan before selecting fittings.',
        'What approved fire-strategy information must exist before you can finalise emergency-light positions?',
      ),
    ),
    L(
      'p12-v2-l24',
      'Emergency-Lighting Inspection and Test Intervals',
      '0HrACbmECnI',
      'eFIXX',
      628,
      'Emergency-lighting testing and records',
      'LIFE SAFETY',
      'UK educator',
      G(
        'Emergency lighting needs routine functional checks, periodic duration testing, defect correction and records that show the system remains ready after handover. The lesson explains the UK testing pattern and the practical difference between confirming operation and proving rated endurance. Treat those intervals as UK teaching, not Kenyan law: establish the schedule from current Kenyan requirements, the fire strategy, the responsible authority and manufacturer instructions, and arrange tests so battery discharge does not leave the building unprotected.',
        [
          'A functional test and a full-duration test prove different things.',
          'Test timing must consider recharge and continued building safety.',
          'Failures require repair and documented re-test.',
          'The Kenyan maintenance schedule must be formally verified.',
        ],
        'Testing without a log, defect process and responsible person is not a maintenance system.',
        'Draft an emergency-lighting logbook page with asset ID, location, test type, result, defect, action, re-test and responsible person.',
        'How would you schedule a duration test without leaving an occupied building vulnerable afterward?',
      ),
    ),
    L(
      'p12-l04',
      'Lighting Design Mistakes: Position, Layers and Controls',
      'C1r4rgdtSKg',
      'eFIXX',
      6812,
      'Whole-scheme lighting design review',
      'CAPSTONE',
      'UK educator',
      G(
        'Good lighting begins with what people do in the room. This practitioner-led capstone critiques common mistakes in fitting position, glare, task lighting, ceiling-grid thinking and control grouping. Bring the complete module together by layering ambient, task, accent and decorative light; coordinating furniture, daylight, showers, joinery, fans, HVAC, detectors and gypsum details; and making drivers, fittings and controls maintainable in Kenyan construction conditions.',
        [
          'Start with activities, surfaces and visual tasks.',
          'Layer light instead of relying on one uniform ceiling grid.',
          'Position fittings to control glare, shadows and reflections.',
          'Plan simple controls and coordinate all ceiling services early.',
        ],
        'A symmetrical ceiling is not the same as a well-lit room.',
        'Review one complete room at night, photograph the result, and annotate useful layers, glare, shadows, dead zones, control problems and inaccessible components.',
        'Can you defend every fitting and control in your final scheme using the client brief, product evidence and a maintainable installation detail?',
      ),
    ),
  ],
);
