import { G, L, M } from './builders';

export const module14 = M(
  14,
  'Solar, Storage, Backup Power and EV Readiness',
  'Progress from survey and prosumer architecture through PV, batteries, inverters, source transfer and UPS systems to a complete three-part EV-charger installation and fault-finding sequence.',
  'PRODUCE a project-specific single-line diagram and commissioning plan showing utility supply, PV strings, inverter, battery, essential-load board, isolation, earthing, SPDs, source transfer or UPS, monitoring and a load-managed EV circuit.',
  'Complete the existing modules on AC/DC principles, distribution, earthing, protection, safe isolation, testing and three-phase systems before entering this advanced module.',
  'These lessons use UK practice plus explicitly labelled international manufacturer explanations. For Kenya, verify every design against current EPRA and Kenya Power requirements, applicable KS/IEC standards, the supply earthing arrangement, product manuals, fire/building rules and competent commissioning.',
  [
    L(
      'p14-l01',
      'Planning a Solar Installation: Professional Site Survey',
      'a3iiTnA03Lk',
      'Spirit Energy with GaryDoesSolar',
      912,
      'Solar PV site survey and client brief',
      'SURVEY + DEFINE',
      'UK manufacturer or trade specialist',
      G(
        'A professional survey begins solar design with evidence rather than equipment shopping. It connects the client goal, energy use, roof and shading, cable routes, distribution equipment and plant space before an array or inverter is selected.',
        [
          'Record consumption, peak loads, operating times and the client priority: saving, backup or both.',
          'Assess usable roof or ground area, orientation, shading, structure, access and future maintenance.',
          'Inspect the supply, meter, earthing, distribution-board capacity and feasible AC and DC routes.',
          'Reserve safe, ventilated and serviceable positions for inverter, battery, isolation and monitoring equipment.',
        ],
        'A panel count is not a design; the survey must connect the resource, building, electrical installation and client operating objective.',
        'Carry out a paper survey of a Kenyan home and produce a photo list, load questions, shading sketch, proposed equipment zones and unresolved risks.',
        'Which survey finding could change the entire system architecture even if the roof has ample space?',
      ),
      {
        regulationStatus: 'Replace UK network-notification assumptions with current Kenya Power, EPRA, county/building and applicable KS/IEC requirements; obtain structural advice where the mounting surface is uncertain.',
      },
    ),
    L(
      'p14-v2-l02',
      'Touring a Prosumer Solar-and-Battery Installation',
      'CRYnracqRjM',
      'eFIXX ENERGY',
      1125,
      'Prosumer architecture and energy flow',
      'SEE THE SYSTEM',
      'UK manufacturer or trade specialist',
      G(
        'A technical tour follows a property that both consumes and produces energy, making the relationships between PV, storage, distribution, metering and household loads visible. Study the architecture and decisions rather than copying its UK equipment schedule.',
        [
          'Trace power from the array through DC equipment, inverter, AC distribution, loads, battery and grid.',
          'Distinguish self-consumption, battery charging, export, import and backup operating states.',
          'Locate isolation, protective devices, metering and monitoring at each system boundary.',
          'Explain to a client how control settings and daily load timing affect savings and resilience.',
        ],
        'A prosumer system changes direction and source; every drawing and isolation procedure must remain clear in all operating modes.',
        'Redraw the tour as a source-and-load block diagram, then adapt it for a Kenyan home with an essential-load board and intermittent utility supply.',
        'When the sun, battery and utility are all available, how would you determine which source is feeding each load and where excess energy goes?',
      ),
      {
        regulationStatus: 'The installation is a UK case study. Recalculate ratings and replace UK metering, export and DNO arrangements with current Kenyan utility and approval requirements.',
      },
    ),
    L(
      'p14-v2-l03',
      'Electrical Preparation Before Installing Solar',
      'fMM-EPRKNhw',
      'eFIXX',
      1174,
      'Pre-installation condition and capacity checks',
      'INSPECT + PREPARE',
      'UK manufacturer or trade specialist',
      G(
        'This lesson puts the existing electrical installation under scrutiny before generation is added. It reinforces that a new inverter can expose weaknesses in earthing, protection, distribution capacity, labelling and isolation that a panel-only survey would miss.',
        [
          'Confirm supply characteristics, earthing arrangement, polarity and the condition of existing conductors and bonding.',
          'Assess distribution-board capacity, protective-device suitability, spare ways and bidirectional current paths.',
          'Plan dedicated AC and DC routes, isolation points, labels and space for coordinated surge protection.',
          'Record defects and remedial work that must be completed before the PV system is connected.',
        ],
        'Adding generation does not repair an unsafe installation; outstanding defects must be assessed and resolved before connection.',
        'Create a pre-solar inspection sheet for an older masonry home, including supply data, board condition, earthing, cable routes and required upgrades.',
        'Which existing-installation defects could make an otherwise correctly sized solar system unsafe?',
      ),
      {
        regulationStatus: 'Use inspection and test methods accepted in Kenya and confirm utility connection, export, protection and metering requirements before equipment procurement.',
      },
    ),
    L(
      'p14-v2-l04',
      'Battery Storage Location and Fire-Risk Planning',
      'YHZqAGpDwxo',
      'eFIXX',
      626,
      'Stationary battery siting and PAS 63100 context',
      'LOCATE + MANAGE RISK',
      'UK manufacturer or trade specialist',
      G(
        'A discussion of UK PAS 63100:2024 shows why battery location is a fire, access and emergency-planning decision rather than a spare-space decision. Its risk principles are valuable in Kenya even though the cited UK document is not Kenyan law.',
        [
          'Keep storage away from escape routes, vulnerable occupants and locations where a fire would trap people.',
          'Evaluate temperature, ventilation, moisture, direct sun, flooding and combustible surroundings.',
          'Maintain manufacturer clearances, impact protection, secure mounting and access for isolation and service.',
          'Coordinate detection, warning, emergency information and the response of occupants and firefighters.',
        ],
        'Do not interpret a permitted product temperature range as permission to install a battery in any hot, confined or occupied space.',
        'Score three possible battery locations in a Kenyan house against fire spread, escape, heat, moisture, security, cable length and maintenance access.',
        'Why can the electrically shortest battery location still be the wrong overall location?',
      ),
      {
        regulationStatus: 'PAS 63100:2024 is UK guidance, not Kenyan law. Verify Kenyan fire/building requirements, insurer conditions, manufacturer limits and a project-specific risk assessment.',
      },
    ),
    L(
      'p14-v2-l05',
      'Selecting a Safe Location for a Solar Inverter',
      '46c1BXEloR8',
      'eFIXX',
      814,
      'Inverter siting, environment and service access',
      'SELECT + COORDINATE',
      'UK manufacturer or trade specialist',
      G(
        'The inverter-location lesson exposes the thermal, environmental and maintenance consequences of treating a power-electronics unit like a decorative wall box. Good siting protects output, lifespan, safe operation and the technician who must service it.',
        [
          'Provide ventilation and manufacturer clearances so heat can escape without recirculation.',
          'Check ingress, ultraviolet, corrosion, dust, flooding and ambient-temperature exposure.',
          'Use a sound, non-combustible mounting surface with realistic weight and fixing capacity.',
          'Preserve access to isolators, labels, displays, cable entries and safe maintenance space.',
        ],
        'An inverter may derate or fail long before an enclosure looks damaged; thermal and environmental design must be deliberate.',
        'Compare indoor utility-room, garage and shaded outdoor positions for one project and document why the selected position best balances safety, route length and serviceability.',
        'Which site conditions affect inverter performance even when its electrical ratings are correct?',
      ),
      {
        regulationStatus: 'Follow the exact inverter environmental category, mounting and clearance instructions plus Kenyan fire, access and electrical requirements; never infer suitability from another model.',
      },
    ),
    L(
      'p14-v2-l06',
      'PV Installation Checks and Safe Test Sequencing',
      'yiuZkfuwzPs',
      'eFIXX',
      607,
      'PV inspection, testing and commissioning discipline',
      'TEST + RECORD',
      'UK manufacturer or trade specialist',
      G(
        'A mistake-led PV testing lesson shows why the order of inspection, polarity, voltage and insulation checks matters. Solar DC remains present in daylight, so instruments, connectors and the commissioning sequence must be selected for the real array voltage and energy.',
        [
          'Inspect module, connector, cable support, labels, isolation and protective bonding before energisation.',
          'Confirm string polarity and compare open-circuit voltage with the design and environmental conditions.',
          'Use a PV-suitable insulation-test method that will not damage connected electronics or SPDs.',
          'Document results, inverter settings, functional checks and as-built string information at handover.',
        ],
        'Opening an AC isolator does not make illuminated PV conductors dead; test equipment and safe procedures must address every DC source.',
        'Write a commissioning sequence that states what is disconnected, which instrument is used, its category and range, the expected result and the stop condition for each test.',
        'Why must polarity and expected string voltage be checked before connecting a string to the inverter?',
      ),
      {
        regulationStatus: 'Use current Kenyan/IEC PV verification requirements, calibrated PV-rated instruments and the exact inverter, module and SPD test instructions; advanced testing requires competent persons.',
      },
    ),
    L(
      'p14-v2-l07',
      'Installing a 5 kW Hybrid Inverter and Battery System',
      'LLfU47Zs3Qc',
      'Mark The Sparky Allison',
      1561,
      'Hybrid inverter and battery installation case study',
      'BUILD + COMMISSION',
      'UK educator',
      G(
        'A complete UK installation case study brings mounting, DC and AC wiring, battery communication and startup into one visible sequence. Observe it as a coordination and workmanship example, not a generic connection diagram for other brands.',
        [
          'Set out equipment, cable routes, clearances and lifting operations before drilling or termination.',
          'Coordinate PV strings, DC isolation, battery conductors, overcurrent protection and polarity.',
          'Provide the correct AC supply, backup-load arrangement, earthing, SPDs and labels.',
          'Pair the battery management system, enter approved settings and complete functional commissioning records.',
        ],
        'Hybrid terminals and backup outputs differ between models; one successful installation must never be copied without the exact manuals and approved design.',
        'Pause the case study at each connection stage and add that boundary to your own single-line diagram, including the protection and verification required before proceeding.',
        'Which settings and connections are specific to the selected inverter and battery combination rather than transferable installation principles?',
      ),
      {
        regulationStatus: 'The case follows UK equipment and practice. Re-engineer protection, earthing, anti-islanding, settings and utility interfaces for the exact Kenyan supply and approved product combination.',
      },
    ),
    L(
      'p14-l02',
      'Inside an Inverter-Charger: How the Victron MultiPlus Works',
      'UPfUn5ki7OM',
      'Victron Energy',
      1153,
      'Inverter-charger internal functions',
      'WHY + SYSTEM',
      'Official international manufacturer exception',
      G(
        'This official international manufacturer cutaway is retained as a clearly labelled exception because it gives an unusually clear explanation of conversion, charging and transfer inside an inverter-charger. The architecture is educational; product selection still requires model-specific engineering.',
        [
          'Follow DC energy through the inverter stage to a controlled AC waveform.',
          'Trace AC input through charging, pass-through and transfer functions.',
          'Understand how load support or power-assist features combine source and battery limits.',
          'Recognise battery-current, heat, fault-energy and bypass paths that external diagrams can hide.',
        ],
        'An inverter-charger is several power functions in one enclosure; isolation must account for AC input, AC output, battery and any generation source.',
        'Draw the unit as functional blocks and identify which path supplies the load during normal supply, charging, outage and overload conditions.',
        'What changes inside the unit when utility power fails but the protected loads remain energised?',
      ),
      {
        regulationStatus: 'Official Victron training is an international manufacturer exception. Apply only the transferable principles and use the exact model manual plus Kenyan protection, earthing and approval requirements.',
      },
    ),
    L(
      'p14-v2-l09',
      'Solar Inverters, Multiple Sources and Safe Isolation',
      'ef2TQvu76jg',
      'eFIXX',
      1061,
      'Inverter backfeed and isolation hazards',
      'QUESTION + ISOLATE',
      'UK manufacturer or trade specialist',
      G(
        'Using an IET warning as its starting point, this electrical-news lesson challenges any assumption that an inverter control or one isolator removes every source. Its core value is a multiple-source isolation mindset for PV, batteries and prosumer circuits.',
        [
          'Identify utility, inverter, battery and PV sources that can energise the point of work.',
          'Distinguish an operational control from a recognised, lockable means of isolation.',
          'Allow for stored energy, discharge time, backfeed and conductors that remain live in daylight.',
          'Use diagrams, warning labels, proving-dead procedures and source-specific lock-off points.',
        ],
        'Never rely on a dark display, app command or inverter shutdown button as proof that every conductor is dead.',
        'Write an isolation schedule for a hybrid system that states the isolation point, lock-off method, proving point and remaining live parts for each source.',
        'After opening the main AC switch, which parts of a solar-and-storage installation may still be energised and why?',
      ),
      {
        regulationStatus: 'The programme reports UK/IET concerns rather than replacing a standard. Use current Kenyan rules, manufacturer isolation instructions and a system-specific safe-isolation procedure.',
      },
    ),
    L(
      'p14-v2-l10',
      'Automatic Transfer Switch Fundamentals',
      'yjphp4SBkSA',
      'Eaton',
      902,
      'Automatic source transfer architecture',
      'TRANSFER + INTERLOCK',
      'Official international manufacturer exception',
      G(
        'This official Eaton lesson is retained as an international manufacturer exception for its clear mechanical and operating explanation of transfer switches. Its US UL examples must be separated from the transferable concepts used in Kenyan 230/400 V, 50 Hz systems.',
        [
          'Distinguish manual, non-automatic and automatic transfer operation.',
          'Compare open, delayed and closed transition without allowing unintended source paralleling.',
          'Relate three-pole or four-pole switching to neutral and earthing design.',
          'Check source sensing, interlocking, fault withstand, bypass and maintenance arrangements.',
        ],
        'An ATS changes sources; it does not provide uninterrupted power, and its pole arrangement can change the safety of the neutral and earth reference.',
        'Develop a utility-to-generator transfer sequence showing start delay, source validation, break-before-make operation, retransfer and generator cooldown.',
        'When would the neutral need to be switched, and what supply and earthing information is required before deciding?',
      ),
      {
        regulationStatus: 'Official Eaton US training is an international exception. Ignore UL/NEC conclusions unless independently applicable; verify IEC product duty, Kenyan source-changeover rules, poles switched, earthing and backfeed prevention.',
      },
    ),
    L(
      'p14-v2-l11',
      'UPS Topologies, Bypass and Critical Loads',
      'ZhGQAaen59E',
      'Eaton',
      753,
      'Uninterruptible power supply operation',
      'CONTINUE + PROTECT',
      'Official international manufacturer exception',
      G(
        'This official international manufacturer explanation introduces the functional blocks and operating states of an uninterruptible power supply. It helps distinguish momentary source transfer from conditioned, battery-backed continuity for genuinely critical loads.',
        [
          'Compare standby, line-interactive and online double-conversion behaviour and transfer time.',
          'Trace rectifier, charger, battery, inverter, static bypass and maintenance-bypass paths.',
          'Size power, runtime and battery energy from the critical load profile and growth allowance.',
          'Plan ventilation, fault protection, maintenance access, alarms and safe battery replacement.',
        ],
        'UPS power rating and battery runtime are different specifications; both must be checked at the real load, temperature, age and required autonomy.',
        'Classify a home office, CCTV/NVR, network rack and life-safety load, then choose which require UPS continuity and estimate their separate runtime needs.',
        'Why might a correctly rated UPS still provide less runtime than the client expects?',
      ),
      {
        regulationStatus: 'Official Eaton training is an international manufacturer exception. Verify 230/400 V, 50 Hz compatibility, Kenyan protection and earthing, battery/fire provisions and the exact bypass design.',
      },
    ),
    L(
      'p14-l07',
      'Three-Phase Battery Backup: Advanced Case Study',
      'sLyawfMcki4',
      'Artisan Electrics',
      1605,
      'Three-phase battery storage and whole-property backup',
      'SYNTHESISE + REVIEW',
      'UK educator',
      G(
        'A large UK battery installation reveals the physical and system-level decisions hidden by small diagrams: three-phase distribution, gateway position, battery stacking, cable containment, lifting, commissioning and client monitoring.',
        [
          'Map utility, gateway, inverter phases, battery modules and backed-up distribution boundaries.',
          'Check phase loading, total power, surge demand and the distinction between whole-site and essential-load backup.',
          'Plan equipment weight, access, clearances, containment, fire considerations and future service.',
          'Commission operating modes, loss-of-grid behaviour, monitoring, alarms and client handover.',
        ],
        'A polished product installation is a case study, not a design certificate; whole-property backup greatly increases fault, load and operating-mode complexity.',
        'Review the case using a design checklist and identify which decisions require structural, fire, utility, manufacturer or electrical-engineering approval in Kenya.',
        'What new risks appear when backup expands from a few essential circuits to an entire three-phase property?',
      ),
      {
        regulationStatus: 'This UK, product-led case study must be re-engineered for Kenyan supply conditions, utility permissions, fault levels, earthing, fire strategy and approved equipment.',
      },
    ),
    L(
      'p14-v2-l13',
      'Installing an EV Charger: Survey, Mounting and Protection',
      'QCmZKEJNa5E',
      'eFIXX',
      894,
      'EV charging installation workflow',
      'PLAN + INSTALL',
      'UK manufacturer or trade specialist',
      G(
        'The first EV lesson follows a professional charger installation from site decisions into mounting and electrical preparation. Use the workflow to connect client charging needs with supply capacity, cable routes, protective functions and maintainable positioning.',
        [
          'Establish vehicle, connector, charging-power, parking and daily-energy requirements.',
          'Assess supply capacity, maximum demand, phase arrangement and the need for load management.',
          'Select a protected cable route and mounting position for weather, impact, reach and accessibility.',
          'Coordinate dedicated protection, isolation, earthing features, labels and commissioning access.',
        ],
        'A charger is a sustained high-power load in an outdoor user environment; spare physical space in a board does not prove spare electrical capacity.',
        'Complete an EV site-survey form for a driveway, including cable length, parking positions, Wi-Fi or data, supply headroom, future solar and client charging routine.',
        'Which client and supply data determine whether load management is required?',
      ),
      {
        regulationStatus: 'The installation uses UK equipment and rules. Verify Kenyan EVSE approval, supply capacity, RCD/DC protection, earthing, outdoor equipment and utility requirements.',
      },
    ),
    L(
      'p14-v2-l14',
      'EV Charger Earthing and Open-Conductor Protection',
      'o7heO1ENqKw',
      'eFIXX',
      1279,
      'EV charging earthing and shock protection',
      'EARTH + PROTECT',
      'UK manufacturer or trade specialist',
      G(
        'A charger-specific earthing lesson explains why vehicle charging creates a special touch-voltage problem and how one UK product addresses supply-conductor faults. The reasoning is useful, but the exact UK PME and open-PEN solution must not be copied into an unverified Kenyan earthing system.',
        [
          'Identify the actual supply earthing arrangement and every exposed or extraneous conductive part.',
          'Understand how a lost neutral/PEN-type fault can raise vehicle body voltage in relevant systems.',
          'Verify whether protection is built into the charger or requires external RCD, DC detection or electrodes.',
          'Test protective functions and earth-fault paths under the exact manufacturer commissioning procedure.',
        ],
        'Earthing labels such as TN-C-S, TN-S or TT describe system conditions, not a menu from which the installer may choose without supply evidence.',
        'Draw the vehicle, charger, CPC, supply neutral and earth paths for the actual property, then mark the protective response to each credible conductor fault.',
        'Why can a UK charger with built-in open-PEN protection still require a different earthing decision on a Kenyan supply?',
      ),
      {
        regulationStatus: 'UK PME/open-PEN requirements are contextual only. Determine the Kenyan supply earthing arrangement and apply current local/IEC EV charging and manufacturer protection requirements.',
      },
    ),
    L(
      'p14-l08',
      'EV Charger Connections, CT Load Sensing and Commissioning',
      'x8eCM6Ngp9Q',
      'eFIXX and Indra',
      1211,
      'EV charger final connection and load management',
      'CONNECT + COMMISSION',
      'UK manufacturer or trade specialist',
      G(
        'The connection stage makes current-transformer load sensing, final terminations and commissioning visible. It links the earlier supply survey to a charger that can limit demand instead of overloading the property supply.',
        [
          'Terminate supply, CPC and communication conductors to the exact diagram and specified torque.',
          'Fit the current transformer in the correct position, conductor and orientation for valid readings.',
          'Configure supply limit, charger rating, network connection and user access without defeating safety settings.',
          'Verify polarity, earthing, RCD functions, load limiting, charging operation and handover records.',
        ],
        'A reversed or misplaced CT can make a load-management system increase demand when it should reduce it.',
        'Write a commissioning test that deliberately adds a large household load and confirms the charger reduces current while the measured supply stays within its limit.',
        'How can you prove that dynamic load management is measuring the correct conductor and responding in the safe direction?',
      ),
      {
        regulationStatus: 'Follow the exact charger, CT and protective-device manuals and Kenyan verification requirements; UK notification and PME details do not automatically apply.',
      },
    ),
    L(
      'p14-v2-l16',
      'EV Charger Troubleshooting and Client Handover',
      '7unMAv89nwU',
      'eFIXX',
      719,
      'EV charger diagnosis and support',
      'DIAGNOSE + HAND OVER',
      'UK manufacturer or trade specialist',
      G(
        'The final EV lesson turns common installation questions into a structured diagnostic approach. It separates supply, protection, CT sensing, communications, vehicle and cloud-service faults so that troubleshooting does not become random part replacement.',
        [
          'Confirm supply voltage, protective devices, earthing and charger status before investigating software.',
          'Validate CT direction, current limits and measured load against an independent instrument.',
          'Separate local charger, vehicle, Wi-Fi, account and remote-platform problems using evidence.',
          'Record settings, error codes, corrective action, functional retest and client operating instructions.',
        ],
        'Repeated resets can erase evidence and conceal a protection fault; capture status and measurements before changing settings.',
        'Build a fault tree for no charge, slow charge and nuisance trip, with a safe stop point that triggers manufacturer or specialist support.',
        'What first checks distinguish an electrical-supply problem from a communications or vehicle problem?',
      ),
      {
        regulationStatus: 'Use manufacturer-approved diagnostic steps and Kenyan electrical safety procedures; do not bypass protection or energise exposed equipment to chase a software fault.',
      },
    ),
  ],
);
