import { G, L, M } from './builders';

export const module16 = M(
  16,
  'Professional Tools, Estimating and Handover',
  'Build the professional habits that turn technical ability into reliable paid work. The module covers purposeful tool selection, dependable terminations, cable detection, thermal inspection, job pricing, rewire surveys and defensible installation documentation, with a strong emphasis on traceability and client communication.',
  'Prepare a complete proposal and handover pack for a sample house rewire. Include a task-based tool and test-equipment plan, termination schedule for flexible conductors and larger cable lugs, pre-drilling cable-detection method, optional thermal-survey scope, measured quantities, labour and overhead build-up, exclusions, variation procedure, inspection and test plan, labelled drawings, certificate information and a short client demonstration. State clearly where UK examples have been adapted to Kenyan prices, contracts, EPRA practice and supply conditions.',
  'Complete the practical wiring and inspection-and-testing modules so the tools, quotation and certificate can be related to a complete installation rather than isolated exercises.',
  'Tool techniques are broadly transferable, but safe systems of work, calibration, certificates, commercial terms and regulatory duties must be checked against current manufacturer guidance and Kenyan requirements.',
  [
    L(
      'p16-l01',
      'Essential Tools for Apprentice Electricians',
      'yzELC1QYSog',
      'eFIXX',
      3299,
      'Task-based electrician tool selection and care',
      'Professional toolkit',
      'UK educator',
      G(
        'This extended eFIXX lesson explains the purpose behind an apprentice electrician\'s core hand tools rather than encouraging an expensive collection. It connects insulated screwdrivers, correct terminal profiles, torque control, cable preparation, fastening and test equipment to safer work, repeatable terminations and fewer damaged accessories.',
        [
          'Choose a tool for the conductor, terminal, enclosure and task; apparent fit is not the same as correct fit.',
          'Insulated hand tools, proving equipment and lock-off items support a safe system but never replace safe-isolation procedure.',
          'Specified torque and the correct screwdriver profile reduce loose connections, damaged heads and misleading tightness.',
          'Inspection, cleaning, calibration where applicable and secure storage keep tools dependable and make defects visible before use.',
        ],
        'Buy capability in a deliberate order: safe isolation and accurate basic hand tools come before specialist gadgets, duplicate sets or cosmetic upgrades.',
        'Create a three-stage toolkit plan for first fix, second fix and inspection/testing. For every item, name the task it performs, its inspection requirement and whether it needs calibration or a proving check.',
        'Which tools are essential before you can safely begin electrical work, and which apparently useful tools can wait until a specific job justifies them?',
      ),
      {
        regulationSensitive: false,
        regulationStatus: 'Technique-focused UK training. Follow current safe-isolation rules, tool standards, calibration intervals, manufacturer instructions and the employer or site safe system of work.',
      },
    ),
    L(
      'p16-l02',
      'The Truth About Ferrules: Overkill or Essential?',
      'VE1THS428gM',
      'eFIXX',
      1189,
      'Ferrule selection and flexible-conductor termination',
      'Cable preparation',
      'UK educator',
      G(
        'This lesson examines when cable-end sleeves improve a flexible-conductor termination and when their use is optional or unsuitable. It covers conductor preparation, ferrule length and cross-section, insulated and uninsulated types, crimp profiles and the need to confirm that the receiving terminal is designed to accept the finished end.',
        [
          'A ferrule contains fine strands and creates a consistent end for compatible screw or spring terminals; it is not a universal repair for poor stripping.',
          'Ferrule size, sleeve length and conductor fill must match the conductor and the depth of the receiving terminal.',
          'A controlled full-cycle crimp with the correct die is different from squeezing the sleeve with ordinary pliers.',
          'Terminal manufacturer instructions decide whether a ferrule, bare flexible conductor or another termination is acceptable.',
        ],
        'Never double the conductor back, fit an oversized ferrule or include insulation in the metal crimp simply to make a loose termination feel tight.',
        'Prepare sample flexible conductors with several ferrule sizes. Inspect strand capture, sleeve position, crimp symmetry, pull security and full insertion into a compatible isolated terminal.',
        'What evidence tells you the ferrule size, crimp tool and terminal combination are compatible, and what defects would make you cut it off and start again?',
      ),
      {
        regulationStatus: 'Confirm the conductor class, terminal instructions, ferrule standard and crimp-tool compatibility for the actual equipment; practices differ between devices and markets.',
      },
    ),
    L(
      'p16-l03',
      'Cable Lugs: They Look Right. They Are Not.',
      'rxOEQD9KaE8',
      'eFIXX',
      1053,
      'Power-cable lug selection and crimp integrity',
      'High-current terminations',
      'UK educator',
      G(
        'Cable lugs carry high current in distribution equipment, switchgear, transformers and motor systems, so a visually neat crimp can still be dangerously wrong. The lesson compares lug families and crimp methods and explains how conductor construction, lug standard, die system, preparation and inspection combine to produce a low-resistance mechanical and electrical joint.',
        [
          'The conductor material, class and cross-sectional area must match the lug barrel, palm, stud size and equipment terminal.',
          'DIN-style and tubular lugs may require different dies and crimp sequences; similar dimensions do not prove interchangeability.',
          'Hexagonal and indent crimps behave differently and must be made with the tool-die-lug system specified by the manufacturer.',
          'Correct stripping, full insertion, crimp position, palm alignment, heat-shrink or insulation and final torque all affect long-term reliability.',
        ],
        'Do not judge a power termination by appearance alone. Record the lug, die, tool, crimp sequence and tightening torque so the connection is reproducible and auditable.',
        'Build a termination schedule for an inverter, pump panel or distribution feeder. Include cable type and size, lug reference, stud size, die/profile, number and position of crimps, insulation finish and terminal torque.',
        'If a lug fits over the conductor and its palm fits the bolt, what additional compatibility evidence is still required before it is safe to crimp and install?',
      ),
      {
        regulationStatus: 'Use the exact cable, lug, die, crimp-tool and equipment manufacturer data. High-current terminations require competent installation, controlled torque and project-specific inspection.',
      },
    ),
    L(
      'p16-l04',
      'How to Use a Pipe and Cable Detector',
      'JMAjWk1t6AA',
      'Gosforth Handyman',
      916,
      'Scanning walls before drilling or chasing',
      'Hidden-service detection',
      'UK educator',
      G(
        'This practical demonstration shows how a multi-detector can help locate concealed metal, timber and energised cables before drilling or chasing. It also exposes the limitations that create false confidence: calibration, grip, wall moisture, foil, mesh, depth, cable loading and scanning direction can all change what the instrument reports.',
        [
          'Start with a visual and documentary survey, then scan a known clear area and approach the suspected service from more than one direction.',
          'Live-wire detection depends on electric-field conditions and may miss isolated, screened, deeply buried or lightly loaded conductors.',
          'Metal modes can detect pipes, reinforcement and accessories but cannot identify which object produced the indication.',
          'Repeated scans, expected wiring zones and cautious trial methods are stronger than a single pass or one instrument mode.',
        ],
        'A detector reduces uncertainty; it never proves that a wall is safe to drill. Stop when indications conflict and use drawings, isolation, inspection or another detection method.',
        'Before positioning a back box in a masonry wall, record the expected service zones, scan pattern, detector modes, findings and any area that requires opening or further investigation.',
        'Why might a detector fail to indicate a real cable, and what independent checks should be made before drilling at that location?',
      ),
      {
        regulationSensitive: false,
        regulationStatus: 'Technique-focused guidance. Follow the detector instructions and the site permit, service-detection, isolation and drilling controls; never interpret a clear display as proof of no service.',
      },
    ),
    L(
      'p16-l05',
      'CAT and Genny Training: Signal Application',
      'ghlb9u8YTIk',
      'Sygma Solutions Training',
      4339,
      'Locating buried utilities with a cable avoidance tool and signal generator',
      'Underground services',
      'UK educator',
      G(
        'This detailed training webinar explains how applying a known signal with a Genny improves underground service location compared with passive scanning alone. It explores direct connection, signal clamping and induction, then shows how coupling, return paths, frequency choice and depth/current interpretation affect the apparent route on the locator.',
        [
          'Passive power and radio modes are an initial sweep, not a complete search for all buried services.',
          'Direct connection usually gives the most controlled signal; clamping and induction are useful alternatives with different coupling risks.',
          'The signal needs a suitable circuit and return path, and poor earthing or parallel services can move the strongest response away from the target.',
          'A systematic grid scan, peak confirmation, route tracing and marked results are required before excavation or driving earth electrodes.',
        ],
        'Locate, mark and prove; never assume. A CAT and Genny does not identify every non-conductive pipe, abandoned cable or poorly coupled service.',
        'Plan the service search before installing a gate duct, external light, earth electrode or solar structure. Mark the search area, modes and signal-application method, trace each response and escalate uncertain crossings.',
        'Why can induction place a signal on the wrong utility, and how would direct connection, current measurement or route tracing help confirm the intended service?',
      ),
      {
        regulationSensitive: false,
        regulationStatus: 'Formal equipment training and local excavation controls may be required. Use current site plans, permits, safe digging practice and complementary detection methods.',
      },
    ),
    L(
      'p16-l06',
      'Detecting Electrical Energy Loss with Thermal Imaging',
      'KceE8zdk35g',
      'VoltimumUK/Fluke',
      3060,
      'Electrical thermography and condition assessment',
      'Diagnostic inspection',
      'UK manufacturer or trade specialist',
      G(
        'This Fluke webinar explains how thermal imagers reveal abnormal heat patterns in cables, connections, fuses, breakers, transformers and motors. It moves beyond colourful pictures by considering load, comparison points, emissivity, reflections, environmental effects and temperature trend, enabling thermography to guide investigation without pretending it identifies the underlying fault by itself.',
        [
          'Electrical thermal surveys are most informative under representative stable load and with comparable phases or components.',
          'Emissivity, reflected temperature, viewing angle, distance and shiny surfaces can make the displayed temperature misleading.',
          'An anomaly indicates a thermal symptom; current measurement, inspection, torque records and electrical tests are needed to find the cause.',
          'A useful report preserves a visible image, thermal image, load condition, settings, location, temperature data, severity basis and recommended action.',
        ],
        'Thermography often requires equipment to be energised and covers removed; only competent people using an approved risk assessment, PPE and safe approach should perform it.',
        'Create a thermal-survey sheet for a distribution board, inverter and pump starter. Include load, ambient conditions, component identification, comparative temperatures, image references and the follow-up test or action.',
        'Why is the hottest-looking point not automatically the most serious fault, and which measurement and context checks are needed before recommending repair?',
      ),
      {
        regulationStatus: 'Follow current electrical-safety, live-working and thermography procedures, equipment instructions and site rules. Thermal imaging supplements rather than replaces prescribed inspection and testing.',
      },
    ),
    L(
      'p16-l07',
      'How to Price Jobs and Quote as an Electrician',
      'GT_wTybt6Ao',
      'Artisan Electrics',
      798,
      'Building a sustainable electrical quotation',
      'Commercial practice',
      'UK educator',
      G(
        'This lesson explains why a professional quotation must recover more than visible labour and materials. It introduces the cost of productive and non-productive time, overheads, travel, consumables, risk and profit, then connects accurate pricing to a clearly defined scope that lets the client compare value rather than a vague total.',
        [
          'Chargeable labour must recover time spent surveying, sourcing, travelling, documenting, correcting defects and providing warranty support.',
          'Materials need current supplier prices, realistic waste and consumable allowances, delivery costs and a controlled validity period.',
          'Overheads and profit are distinct from wages; omitting either makes a busy business financially fragile.',
          'Scope, assumptions, exclusions, programme, payment stages and a written variation process protect both electrician and client.',
        ],
        'A low total with an undefined scope is not a competitive quote; it is an unpriced dispute waiting for the work to begin.',
        'Build a simple rate from annual labour cost, realistic billable days, transport, insurance, tools, administration and target profit. Compare it with a rate based only on daily wages.',
        'Which costs continue when you are not physically installing, and where are they recovered in your labour rate or quotation?',
      ),
      {
        regulationStatus: 'The commercial examples are UK based. Recalculate with current Kenyan labour, tax, transport, insurance, supplier and contract conditions; use clear lawful terms appropriate to the client.',
      },
    ),
    L(
      'p16-l08',
      'How to Quote for a House Rewire',
      'ntAHKvT5pFg',
      'Artisan Electrics',
      1188,
      'Rewire surveying, quantities and risk allowances',
      'Estimating workflow',
      'UK educator',
      G(
        'This house-rewire lesson turns pricing principles into a site-survey workflow. It shows why the estimator must count points and circuits while also understanding occupation, access, construction, finishes, distribution equipment, earthing, temporary supplies, testing, making good and client expectations that can transform the labour required.',
        [
          'A room-by-room schedule of outlets, lighting points, controls, fixed loads, data and special systems forms the measurable scope.',
          'Masonry chasing, concrete slabs, gypsum ceilings, existing finishes, furniture and occupancy strongly affect access and reinstatement effort.',
          'Unknown existing conditions should be investigated where possible and otherwise covered by explicit assumptions, provisional sums or exclusions.',
          'The quotation should define containment, accessories, equipment quality, testing, certification, drawings, waste removal and making-good responsibility.',
        ],
        'Survey the route as carefully as the point count. Ten outlets in open new construction are not the same job as ten outlets in an occupied, finished stone house.',
        'Survey a sample Kenyan home room by room. Mark chases, slab or ceiling routes, distribution-board work, essential/backup circuits, data and security points, finish coordination, testing and every unresolved client decision.',
        'Which five site conditions can change rewire labour most, and how would each appear in the quotation so it cannot become an undocumented variation?',
      ),
      {
        regulationStatus: 'Adapt the UK workflow to Kenyan construction, supply arrangements, EPRA practice, Kenya Power interfaces, taxes, contracts and client expectations. Verify all prices at quotation time.',
      },
    ),
    L(
      'p16-l09',
      'Electrical Certificates Part 2: Installation Certificate',
      'cB35hzk4tDw',
      'John Ward',
      2563,
      'Installation certification and client handover evidence',
      'Handover documentation',
      'UK educator',
      G(
        'John Ward works through the purpose and completion of an electrical installation certificate, connecting its declarations, supply data, circuit schedules and test results to the work actually designed, constructed, inspected and tested. The enduring lesson is evidence: entries must be traceable to measured conditions and responsible people, never copied from a previous form or guessed after leaving site.',
        [
          'The extent of work, limitations and responsibility declarations define exactly what the certificate does and does not cover.',
          'Supply characteristics, earthing, protective devices and circuit details must agree with the installation, labels, drawings and measured results.',
          'Schedules of inspections and test results are part of the certificate, not optional attachments to be completed from memory.',
          'A complete handover also includes as-fitted information, equipment instructions, settings, warranties, demonstrations and any required notifications.',
        ],
        'Never invent, transpose or reuse a test value. If a result was not obtained correctly, the solution is to investigate and retest, not to complete the form convincingly.',
        'Assemble a mock handover pack for a new circuit: defined scope, single-line or circuit drawing, labels, inspection record, raw test notes, completed schedule, equipment data, settings and client operating instructions.',
        'How can a reviewer trace each certificate entry back to the circuit, instrument reading, design decision or responsible person who produced it?',
      ),
      {
        regulationStatus: 'The form and terminology shown are UK specific. Apply the evidence and traceability principles, then use the current certificates, signatures and submission process required in Kenya.',
      },
    ),
  ],
);
