import { G, L, M } from './builders';

export const module13 = M(
  13,
  'Smart Buildings, Data, Security and Life Safety',
  'Plan a modern connected building as one coordinated system: KNX automation, structured cabling, Wi-Fi, CCTV, access control, automated gates, domestic alarms and non-domestic fire detection. The sequence moves from system architecture to commissioning and life-safety decisions, while keeping power, data and future expansion coordinated from first fix.',
  'Produce a coordinated services plan for a three-bedroom masonry home with gypsum ceilings. Show the KNX or smart-control zones, data cabinet, Wi-Fi access points, CCTV coverage, access-controlled entrance, automated gate, domestic alarms, fire-alarm interface where applicable, backup-power needs and test records. Include segregation, accessible equipment, cyber-safe commissioning and spare labelled ducts to the boundary for future gate, intercom, CCTV or professionally designed electric-fence infrastructure. No electric-fence video is included because no substantial, UK-quality, directly embeddable lesson passed the course filter.',
  'Complete the core lighting, final-circuit, inspection and testing lessons so that power wiring, protective measures and commissioning terminology are already familiar.',
  'Use the UK and international material as a technical learning reference. Confirm current BS 7671, relevant BS/EN/ISO standards, manufacturer instructions, Kenyan law, EPRA requirements and the client brief before design or installation.',
  [
    L(
      'p13-v2-l01',
      'Introduction to KNX',
      'viBEZegNScU',
      'Ivory Egg',
      1308,
      'KNX architecture and smart-building fundamentals',
      'Systems overview',
      'UK manufacturer or trade specialist',
      G(
        'This lesson introduces KNX as an open building-automation platform rather than a collection of unrelated smart gadgets. It explains how sensors, user controls and actuators share a dedicated bus so lighting, blinds, heating and other services can work together, and it frames the design benefits of interoperability, distributed intelligence and future expansion.',
        [
          'KNX separates control messages on the bus from the mains power that feeds the controlled loads.',
          'Sensors issue commands, actuators switch or regulate loads, and system devices support the network infrastructure.',
          'A multi-manufacturer open standard reduces dependence on a single proprietary product ecosystem.',
          'Good smart-home outcomes begin with room functions, scenes and manual overrides, not with a shopping list of devices.',
        ],
        'Automation must fail safely and remain understandable: essential lighting and services need sensible local control even when an app, router or visualisation server is unavailable.',
        'For a Kenyan masonry home, decide the automation topology before chasing walls. Reserve deep boxes, accessible control locations, a suitable panel, neutral conductors where required and spare conduits between floors, ceilings and the communications cabinet.',
        'Can you describe the roles of a KNX sensor, actuator, bus power supply and programming interface, then identify which loads in a house should retain a manual fallback?',
      ),
      {
        regulationStatus: 'KNX architecture is transferable, but equipment selection, SELV segregation, mains wiring and commissioning must follow current product documentation, BS 7671 principles and Kenyan requirements.',
      },
    ),
    L(
      'p13-v2-l02',
      'How to Program KNX: ETS5 Introduction Part 1',
      'p-8FhDrLkxE',
      'Ivory Egg',
      757,
      'ETS project structure, products and backups',
      'Configuration foundations',
      'UK manufacturer or trade specialist',
      G(
        'The first ETS lesson tours the software used to engineer a KNX installation. It shows how a project is organised, how product data is obtained from the catalogue and why a recoverable project backup is part of the installation deliverable rather than an optional computer file.',
        [
          'The ETS project should mirror the real building through a clear building structure, topology and device naming convention.',
          'Manufacturer product applications define the parameters and communication objects available for each device.',
          'Addresses, panel labels, drawings and physical device locations should use one consistent identification scheme.',
          'Regular project exports and versioned backups protect the client from losing the only usable configuration record.',
        ],
        'A smart system is not professionally handed over until another competent person can identify the devices, understand the naming and recover the programmed project.',
        'Create a sample project structure for ground floor, first floor and external services. Name rooms and circuits in the same way you would label the distribution board, drawings and site test sheets.',
        'What information must be recorded before importing a product, adding it to the building structure and saving a recoverable project version?',
      ),
      {
        regulationStatus: 'The video demonstrates ETS5. Use it for enduring project-organisation concepts, then follow the current ETS release, KNX Association guidance and current device application programs.',
      },
    ),
    L(
      'p13-v2-l03',
      'How to Program KNX: ETS5 Introduction Part 2',
      '_rnYtUkV4eI',
      'Ivory Egg',
      1763,
      'KNX parameters, group addresses and commissioning',
      'Configuration workflow',
      'UK manufacturer or trade specialist',
      G(
        'Part two moves from project setup into programming. It demonstrates device parameterisation, group-address creation and the linking of communication objects so a physical input can command one or several outputs, providing the mental model needed to build scenes, central functions and coordinated room control.',
        [
          'Parameters determine how an individual KNX device behaves before it communicates with the rest of the system.',
          'Group addresses represent functions such as switching, dimming, status or scenes rather than physical cable routes.',
          'Compatible communication objects and datapoint types must be linked for commands and feedback to be interpreted correctly.',
          'Commissioning should proceed in small tested stages with documented changes, not by downloading an unverified whole-building project at once.',
        ],
        'A command path is only complete when operation and feedback have both been proved; a button that switches a light without reliable status can create confusing visualisations and fault finding.',
        'Model one bedroom with a door switch, bedside control, dimming actuator and an all-off scene. Define clear group addresses for command and status, then record the intended behaviour after a power interruption.',
        'How would you diagnose a light that can be operated from ETS but does not respond to its wall sensor: parameters, group-address links, datapoint compatibility or the physical bus?',
      ),
      {
        regulationStatus: 'The video demonstrates ETS5. Confirm current ETS workflows, firmware and application-program behaviour before commissioning a live project.',
      },
    ),
    L(
      'p13-v2-l04',
      'An Introduction to Cabling and Network Cable Testing',
      'a8vQQGuJjbg',
      'Fluke Networks',
      3184,
      'Structured cabling performance and test categories',
      'Data infrastructure',
      'Official international manufacturer exception',
      G(
        'This webinar establishes the difference between simply obtaining continuity and proving that a copper or fibre link can support its intended network application. It connects cable construction and installation quality to measurements such as wire map, length, attenuation, return loss, resistance and crosstalk, then distinguishes verification, qualification and standards-based certification.',
        [
          'A correct wire map does not prove bandwidth: split pairs and poor termination can pass basic continuity yet fail network performance.',
          'Insertion loss, return loss and near-end crosstalk reveal different installation and termination defects.',
          'Verification finds connection faults, qualification assesses application capability, and certification compares results with a defined cabling limit.',
          'Permanent-link test results and cable identifiers form part of a professional data-cabling handover pack.',
        ],
        'Choose the tester and pass/fail limit from the client requirement before testing; a green light from an unspecified test is not evidence that the installed link meets the design.',
        'Plan home runs from a ventilated communications cabinet to Wi-Fi access points, televisions, work areas, CCTV and gate/intercom positions. Keep data routes separated from mains wiring and label both ends before termination.',
        'Why can a cable with eight connected conductors still perform badly, and which test result would you inspect for a pair-termination or crosstalk problem?',
      ),
      {
        regulationStatus: 'Fluke provides authoritative test-method training. Select current ISO/IEC, BS/EN or client-specified cabling limits and apply Kenyan communications, fire-stopping and segregation requirements.',
      },
    ),
    L(
      'p13-v2-l05',
      'DSX and CertiFiber Test Setup: Options, Tips and Tricks',
      'fmzxSC_2SD8',
      'Fluke Networks',
      2848,
      'Configuring copper and fibre certification tests',
      'Data commissioning',
      'Official international manufacturer exception',
      G(
        'The lesson turns cabling theory into a repeatable commissioning setup for DSX twisted-pair and CertiFiber optical-loss testing. It covers unit configuration, project and cable identifiers, test limits, reference procedures and application-specific settings so results are traceable and comparable rather than a collection of unnamed passes.',
        [
          'The selected cable type, test limit and link model must match what was installed and what the contract requires.',
          'Correct adapters, reference setting and clean fibre interfaces are prerequisites for meaningful measurements.',
          'Structured cable-ID lists prevent duplicate names and link each electronic result to the correct outlet and patch-panel port.',
          'Unexpected failures should trigger inspection of setup and reference conditions before unnecessary retermination begins.',
        ],
        'A certification report is only as trustworthy as its setup. Record the tester, adapters, calibration status, selected limit and reference method with the results.',
        'Prepare an identifier schedule such as GF-LIV-AP01 or FF-BED2-D01 before site testing. Use it on the outlet, patch panel, drawing and electronic result file.',
        'Before accepting a failed fibre or copper result, which setup choices and reference checks would you verify first?',
      ),
      {
        regulationStatus: 'Use the current tester firmware, adapters, calibration requirements and the project-specified edition of the applicable cabling standard.',
      },
    ),
    L(
      'p13-v2-l06',
      'Cabling for Wi-Fi: Field-Terminated Plugs and MPTL Testing',
      'xBedi46dLco',
      'Fluke Networks',
      1764,
      'Wi-Fi access-point cabling and MPTL certification',
      'Wireless infrastructure',
      'Official international manufacturer exception',
      G(
        'This focused webinar explains the modular plug terminated link used to connect fixed horizontal cable directly to a wireless access point or similar device. It shows why higher-speed Wi-Fi and PoE increase demands on the cable, connector and test method, and how a purpose-made adapter enables an MPTL to be assessed correctly.',
        [
          'An MPTL terminates fixed cable in a field-installed plug at the device end instead of a conventional outlet and patch cord.',
          'The test configuration and adapters must match the MPTL topology; treating it as an ordinary channel can produce the wrong conclusion.',
          'Higher data rates and PoE make pair geometry, connector quality, heat and bundle planning increasingly important.',
          'Access-point placement must coordinate radio coverage, ceiling access, cable support and a serviceable route back to the cabinet.',
        ],
        'Do not hide an improvised plug above a finished gypsum ceiling. Use a rated field-termination solution, provide access and leave enough supported cable for safe replacement of the access point.',
        'On a residential plan, position ceiling access points from a coverage survey, then show the cable path, PoE source, accessible termination and unique test identifier for each link.',
        'What makes an MPTL different from a permanent link, and what must change in the certification setup to test it correctly?',
      ),
      {
        regulationStatus: 'Follow current cabling, PoE and product requirements; coordinate penetrations, fire stopping, ceiling access and separation with the Kenyan building design.',
      },
    ),
    L(
      'p13-v2-l07',
      'Hikvision I-Series NVR Overview',
      '0qjfR2Nqmdo',
      'DVS LTD',
      3114,
      'Network video recorder design and commissioning',
      'Video security',
      'UK manufacturer or trade specialist',
      G(
        'This technical overview uses an I-Series network video recorder to explain the centre of an IP CCTV system: camera channels, storage, recording, network configuration, event handling and remote access. The product-specific interface is useful as a worked example, but the more important lesson is how recording objectives drive bandwidth, disk capacity and commissioning choices.',
        [
          'Camera count, resolution, frame rate, codec and retention period determine recorder throughput and storage capacity.',
          'PoE topology, IP addressing and network isolation should be designed before cameras are added to the recorder.',
          'Continuous, scheduled and event recording serve different risks and produce different storage demands.',
          'Secure commissioning includes strong unique credentials, controlled remote access, firmware management, time synchronisation and an exported configuration record.',
        ],
        'A camera image on a monitor is not a commissioned CCTV system; prove recording, search, export, time accuracy, power-failure recovery and the client-approved retention period.',
        'Prepare a camera schedule for entrances, vehicle access and vulnerable external areas. State the purpose and scene for each camera, then calculate a storage allowance and identify which network equipment needs backup power.',
        'Which five design inputs would you collect before selecting an NVR and hard-drive capacity for a client?',
      ),
      {
        regulationStatus: 'The interface and firmware will age. Follow current manufacturer guidance and Kenyan privacy, cybersecurity, signage and data-retention requirements.',
      },
    ),
    L(
      'p13-v2-l08',
      'How to Install a Paxton Access Control System',
      'YtraXVxGdlg',
      'Gayle Electrical',
      1091,
      'Door access-control installation',
      'Access control',
      'UK educator',
      G(
        'A practical site lesson follows the installation of a Paxton access-control system and connects the logical access decision to the physical door hardware. It highlights neat controller placement, reader and lock wiring, power arrangements and the importance of commissioning the complete door rather than treating the electrical connections in isolation.',
        [
          'The controller, reader, locking device, request-to-exit input and door contact form one coordinated door system.',
          'Lock type and fail-safe or fail-secure behaviour must be chosen from security, escape and fire-strategy requirements.',
          'Voltage drop, lock current, cable type and backup time determine the power-supply and battery design.',
          'Commissioning must test authorised entry, denied entry, exit, forced-door and power-loss behaviour.',
        ],
        'Never let an access-control installation obstruct emergency escape. The door must behave correctly during fire alarm, power failure and controller fault conditions.',
        'Draw a single-door schematic for a pedestrian gate or office entrance, including containment, PSU and battery, reader, lock, exit device, door contact and any fire-alarm interface.',
        'For a selected door, should the lock fail safe or fail secure, and what evidence from the escape and security strategy supports that decision?',
      ),
      {
        regulationStatus: 'This is a product-based UK installation example. Confirm current manufacturer instructions, fire/escape coordination, security grades and Kenyan authority requirements.',
      },
    ),
    L(
      'p13-v2-l09',
      'ZLX: A Gate Control Panel Designed for Installers',
      'XZJADCuBno4',
      'CAME UK',
      422,
      'Automated-gate controller functions',
      'Gate automation',
      'UK manufacturer or trade specialist',
      G(
        'This lesson introduces a modern automated-gate control panel from an installer perspective. It provides a compact view of power, motor outputs, command inputs, safety devices and configuration features, making it a useful bridge between ordinary control wiring and the more demanding safety logic of a moving gate.',
        [
          'The controller coordinates motor movement, limits, user commands and safety inputs rather than merely switching a motor on and off.',
          'Photocells, safety edges and emergency controls must be positioned and configured for the actual crushing, shearing and trapping hazards.',
          'Weatherproof enclosure, earthing, isolation, surge exposure and cable routing are part of the electrical design.',
          'Every programmed function needs a documented test, including obstruction response and recovery after power loss.',
        ],
        'An automated gate is machinery. Electrical operation is not proof of safety, and no protective input should be bypassed merely to make commissioning easier.',
        'Plan separate, labelled ducts from the house or gate cabinet for mains power, controls, intercom/data and spare future services. Provide draw cords, drainage considerations and accessible isolation.',
        'Which gate hazards require a safety device, and how would you prove that each device stops or reverses movement as intended?',
      ),
      {
        regulationStatus: 'Use the lesson as a product example only. Apply current machinery, automated-gate, electrical and workplace-safety requirements plus the exact controller instructions used on the project.',
      },
    ),
    L(
      'p13-v2-l10',
      'Automated-Gate Safety Devices',
      'FSOzR7a1e1M',
      'FAAC UK',
      1153,
      'Gate risk reduction and protective devices',
      'Gate safety',
      'UK manufacturer or trade specialist',
      G(
        'The FAAC safety webinar expands gate automation beyond wiring by examining devices used to reduce impact, crushing and entrapment risks. It encourages a hazard-led design in which photocells, monitored edges, force control, guarding and emergency arrangements are selected for the real geometry and users of the gate.',
        [
          'A site-specific risk assessment identifies hazards at the leading edge, hinges, posts, guides and travel area.',
          'Photocells detect presence across a beam, while pressure-sensitive edges protect contact zones; neither is a universal substitute for the other.',
          'Safety devices and circuits may need monitoring so a broken wire or failed component cannot remain undetected.',
          'Final validation includes force, stopping, reversal and repeated functional tests across all operating modes.',
        ],
        'Select protection from the hazard, not from the accessories already in the van. Children, vehicles, public access and gate construction all change the risk.',
        'Mark every crush, shear and draw-in point on a gate sketch. Assign a control measure and a commissioning test to each marked hazard before approving the design.',
        'Why might photocells alone be insufficient on a swing or sliding gate, and what additional hazards must be controlled?',
      ),
      {
        regulationStatus: 'Confirm the current editions of applicable automated-gate and machinery safety standards, local enforcement requirements and the complete manufacturer validation procedure.',
      },
    ),
    L(
      'p13-v2-l11',
      'Smoke Alarm Essentials: Where to Use Each Type',
      'n3wRQTaa9w0',
      'eFIXX',
      712,
      'Domestic smoke, heat and multi-sensor alarm selection',
      'Domestic life safety',
      'UK educator',
      G(
        'This lesson explains why alarm technology should match the fire risk and the normal environment of each room. It compares common smoke, heat and multi-sensor choices, connects selection to siting and interconnection, and helps prevent both dangerous under-protection and nuisance alarms that occupants may disable.',
        [
          'Optical smoke, heat and multi-sensor alarms respond differently and suit different room risks.',
          'Kitchens, circulation spaces, bedrooms and garages require technology selected for likely fire signatures and normal contaminants.',
          'Interconnection makes one detector warning available throughout the dwelling and should be proved during commissioning.',
          'Siting, dead-air spaces, ceiling geometry, maintenance access and backup supply affect real-world protection.',
        ],
        'A technically sensitive alarm in the wrong location can create repeated false alarms and become less safe when the occupant removes or isolates it.',
        'Create an alarm schedule for a two-storey home with a kitchen and attached garage. Name the alarm type and siting reason for every protected space, and include an interconnection test.',
        'Which alarm technology would you propose for the kitchen, escape route and garage, and what nuisance source or fire risk drives each choice?',
      ),
      {
        regulationStatus: 'The lesson is based on UK practice. Confirm the current domestic fire-alarm standard, Kenyan building/fire requirements and the selected manufacturer siting instructions.',
      },
    ),
    L(
      'p13-l10',
      'Electricians Introduction to Fire Alarms and BS 5839 Part 1',
      'OLjxJ2h0vDM',
      'Dans the Engineer/Schneider',
      4472,
      'Non-domestic fire-alarm fundamentals',
      'Fire-alarm foundations',
      'UK educator',
      G(
        'This substantial introduction gives electricians a structured route into non-domestic fire detection and alarm work. It covers system purpose and categories, common control and indicating equipment, initiating and alarm devices, circuit integrity and the design-install-commission-handover chain required for a life-safety system.',
        [
          'System categories express the agreed life-safety or property-protection objective and must come from the fire strategy or responsible designer.',
          'Manual call points, automatic detectors, sounders, interfaces, power supplies and control equipment have distinct functions and supervision needs.',
          'Zone plans, cable integrity, fault monitoring and standby power support safe operation during abnormal conditions.',
          'Design, installation, commissioning, acceptance and maintenance are separate responsibilities that require records and competent sign-off.',
        ],
        'Do not invent a category or detector layout at the installation stage. Obtain the fire strategy and clearly identify who is responsible for design decisions.',
        'Sketch a small office system with zones, call points, detectors, alarm devices, interfaces, cable routes, standby supply and a control-panel location accessible to responders.',
        'What is the difference between the system category, a detection zone and an alarm circuit, and where is each documented?',
      ),
      {
        regulationStatus: 'The lesson references BS 5839-1 as current when recorded. Verify the latest standard, Kenyan fire authority requirements, product approvals and the project fire strategy.',
      },
    ),
    L(
      'p13-v2-l13',
      'Fire Detection and Alarm Systems: Key Changes to BS 5839-1',
      'oPh3ORgowSk',
      'ECA/FSA',
      3314,
      'Fire-alarm standards and professional responsibilities',
      'Life-safety standards',
      'UK professional body',
      G(
        'The ECA and Fire & Security Association webinar examines important changes to BS 5839-1 and, more broadly, shows how detailed standards shape system design, installation, commissioning and documentation. Studying the reasoning behind changes helps an electrician recognise when a familiar rule or inherited site practice may no longer be adequate.',
        [
          'Standards evolve in response to incidents, technology and ambiguities, so edition control matters on every life-safety project.',
          'Variations from recommendations must be deliberate, risk-assessed, agreed and recorded rather than hidden during handover.',
          'Interfaces, false-alarm management, device selection and cable/support arrangements require coordination beyond the electrical drawing.',
          'Certificates, zone information, cause-and-effect records, user training and maintenance arrangements complete the system handover.',
        ],
        'Use older standards training to understand principles, never as proof that a quoted clause remains current. Record the exact standard edition and project specification used.',
        'Audit a sample fire-alarm handover pack for design responsibility, variations, test results, cause-and-effect, zone plan, as-fitted drawings, user instruction and maintenance information.',
        'If a site condition requires departure from the specified fire-alarm design, who must agree it, how should it be assessed and where must it be recorded?',
      ),
      {
        regulationStatus: 'This webinar discusses BS 5839-1:2017. Treat it as standards-development and responsibility training, then verify the latest edition and all Kenyan fire-safety requirements.',
      },
    ),
  ],
);
